/* ============================================================
   Anlam yıldızları — dönüştürücü girdisi (site bu dosyayı YÜKLEMEZ)

   Çok anlamlı kelimelerde her anlamın YDS önemi: 4 = sınavda asıl
   sorulan anlam, 1 = nadir/ikincil. Her kelimenin en yüksek yıldızı
   en az 3'tür. listeyi-aktar.py bunu okuyup anlamlara "yz" alanı
   olarak yazar ve anlamları yıldıza göre büyükten küçüğe sıralar.

   Yıldız anlam METNİNE bağlıdır; kaynak listedeki sıra değişse bile
   eşleşme bozulmaz. Metin değişirse o anlam yıldızsız kalır.
   Üretim: tools/test-uretim (agent + yildiz-dogrula.py) · 1173 kelime
   ============================================================ */

window.ANLAM_YILDIZ = {
"above": [{tr:"e. üstünde, üzerinde",yz:4}, {tr:"s. yukarıda adı geçen",yz:2}],
"abstract": [{tr:"s. soyut",yz:4}, {tr:"i. özet",yz:3}],
"abuse": [{tr:"i. istismar, kötüye kullanma",yz:4}, {tr:"f. kötüye kullanmak; kötü davranmak",yz:4}],
"academic": [{tr:"s. akademik",yz:4}, {tr:"i. akademisyen",yz:3}],
"accent": [{tr:"i. aksan, şive",yz:4}, {tr:"i. vurgu",yz:3}],
"accident": [{tr:"i. kaza",yz:4}, {tr:"i. rastlantı, tesadüf",yz:2}],
"account": [{tr:"f. (for) oluşturmak, açıklamak",yz:4}, {tr:"i. hesap",yz:2}],
"acid": [{tr:"i. asit",yz:4}, {tr:"s. asitli, ekşi",yz:2}],
"acquisition": [{tr:"i. edinim, kazanım",yz:4}, {tr:"i. (şirket) satın alma",yz:3}],
"acute": [{tr:"s. akut, şiddetli",yz:4}, {tr:"s. dar (açı)",yz:1}],
"adapt": [{tr:"f. uyum sağlamak",yz:4}, {tr:"f. uyarlamak",yz:2}],
"adaptation": [{tr:"i. uyum, adaptasyon",yz:4}, {tr:"i. uyarlama (eser)",yz:2}],
"address": [{tr:"f. ele almak, hitap etmek",yz:4}, {tr:"i. adres",yz:4}],
"administration": [{tr:"i. yönetim, idare",yz:4}, {tr:"i. (başkanlık) dönemi",yz:2}],
"admit": [{tr:"f. kabul etmek, itiraf etmek",yz:4}, {tr:"f. içeri almak",yz:2}],
"adolescent": [{tr:"i. ergen, genç",yz:4}, {tr:"s. ergenlikle ilgili, ergenlik çağına ait",yz:3}],
"adopt": [{tr:"f. benimsemek, kabul etmek",yz:4}, {tr:"f. evlat edinmek",yz:2}],
"advise": [{tr:"f. tavsiye etmek, öğütlemek",yz:4}, {tr:"f. bildirmek, haber vermek",yz:1}],
"advocate": [{tr:"f. savunmak, desteklemek",yz:4}, {tr:"i. savunucu",yz:3}],
"aesthetic": [{tr:"s. estetik",yz:4}, {tr:"i. estetik anlayış, estetik (bir tarzın görünümü)",yz:2}],
"affair": [{tr:"i. mesele, iş, konu",yz:3}, {tr:"i. (foreign affairs) dış ilişkiler, işler",yz:3}],
"afford": [{tr:"f. gücü yetmek, karşılayabilmek",yz:4}, {tr:"f. sağlamak",yz:2}],
"ageing": [{tr:"i. yaşlanma",yz:4}, {tr:"s. yaşlanan, yaşlı",yz:4}],
"agent": [{tr:"i. etken, madde",yz:4}, {tr:"i. temsilci, aracı",yz:3}],
"aggregate": [{tr:"s. toplam, birleşik",yz:3}, {tr:"f. bir araya toplamak, biriktirmek",yz:3}],
"aggressive": [{tr:"s. agresif, hızlı yayılan (hastalık için)",yz:3}, {tr:"s. saldırgan, kavgacı",yz:4}],
"aid": [{tr:"i. yardım",yz:4}, {tr:"f. yardım etmek",yz:3}],
"aim": [{tr:"f. amaçlamak",yz:4}, {tr:"i. amaç, hedef",yz:3}],
"alien": [{tr:"s. yabancı; aykırı",yz:4}, {tr:"i. uzaylı",yz:2}],
"ally": [{tr:"i. müttefik",yz:4}, {tr:"f. ittifak kurmak, yanında yer almak",yz:2}],
"amino": [{tr:"s. amino (–NH2 grubuna ait)",yz:4}, {tr:"i. (günl.) amino asit",yz:1}],
"anger": [{tr:"i. öfke, kızgınlık",yz:4}, {tr:"f. öfkelendirmek, kızdırmak",yz:3}],
"annual": [{tr:"s. yıllık",yz:4}, {tr:"i. yıllık bitki (bir yılda yaşam döngüsünü tamamlayan bitki)",yz:1}],
"antibiotic": [{tr:"i. antibiyotik",yz:4}, {tr:"s. antibiyotik özellikli",yz:2}],
"antiquity": [{tr:"i. antik çağ",yz:3}, {tr:"i. antik eser, kalıntı",yz:2}],
"anxious": [{tr:"s. kaygılı, endişeli",yz:4}, {tr:"s. istekli, can atan",yz:2}],
"apart": [{tr:"z. ayrı, birbirinden ayrı",yz:4}, {tr:"s. parçalara ayrılmış",yz:2}],
"appeal": [{tr:"f. cazip gelmek, başvurmak",yz:4}, {tr:"i. temyiz",yz:2}],
"appearance": [{tr:"i. ortaya çıkış",yz:3}, {tr:"i. görünüş, görünüm",yz:4}],
"application": [{tr:"i. uygulama",yz:4}, {tr:"i. başvuru",yz:3}],
"apply": [{tr:"f. uygulamak",yz:4}, {tr:"f. başvurmak",yz:3}],
"approach": [{tr:"i. yaklaşım",yz:4}, {tr:"f. yaklaşmak",yz:3}],
"appropriate": [{tr:"s. uygun",yz:4}, {tr:"f. ayırmak, tahsis etmek",yz:1}],
"approximate": [{tr:"s. yaklaşık",yz:4}, {tr:"f. yaklaşmak, benzemek",yz:2}],
"architect": [{tr:"i. mimar",yz:4}, {tr:"i. kurucu, yaratıcı",yz:2}],
"argue": [{tr:"f. iddia etmek, savunmak",yz:4}, {tr:"f. tartışmak, atışmak",yz:2}],
"argument": [{tr:"i. sav, iddia, tez",yz:4}, {tr:"i. tartışma, çekişme, kavga",yz:2}],
"arm": [{tr:"f. silahlandırmak, donatmak",yz:2}, {tr:"i. kol",yz:4}],
"army": [{tr:"i. ordu",yz:4}, {tr:"(mecazi) büyük grup, yığın",yz:1}],
"array": [{tr:"i. dizi, geniş çeşitlilik",yz:4}, {tr:"f. dizmek, sıralamak, tertiplemek",yz:1}],
"article": [{tr:"i. makale",yz:4}, {tr:"i. madde",yz:2}],
"articulate": [{tr:"f. açıkça ifade etmek",yz:4}, {tr:"s. ifadesi düzgün, konuşkan, düşüncelerini iyi anlatabilen",yz:2}],
"arts": [{tr:"i. güzel sanatlar",yz:3}, {tr:"i. (the arts) sosyal/beşeri bilimler",yz:3}],
"aside": [{tr:"z. bir kenara, yana",yz:4}, {tr:"i. parantez sözü, ara söz",yz:1}],
"assemble": [{tr:"f. monte etmek",yz:3}, {tr:"f. toplamak, bir araya gelmek",yz:4}],
"assembly": [{tr:"i. montaj, birleştirme",yz:3}, {tr:"i. meclis, kurul",yz:3}],
"assert": [{tr:"f. ileri sürmek, iddia etmek",yz:4}, {tr:"f. (hakkını) savunmak",yz:2}],
"assist": [{tr:"f. yardım etmek, desteklemek",yz:4}, {tr:"i. yardım, asist",yz:1}],
"association": [{tr:"i. dernek, birlik",yz:3}, {tr:"i. ilişki, bağlantı",yz:4}],
"assume": [{tr:"f. varsaymak",yz:4}, {tr:"f. üstlenmek",yz:2}],
"atmosphere": [{tr:"i. atmosfer",yz:4}, {tr:"i. hava, ortam (ambiyans)",yz:3}],
"attached": [{tr:"s. bağlı, düşkün",yz:3}, {tr:"s. ekli, ilişikte",yz:2}],
"attack": [{tr:"f. saldırmak",yz:3}, {tr:"i. saldırı",yz:4}],
"attend": [{tr:"f. katılmak, devam etmek",yz:4}, {tr:"f. ilgilenmek",yz:2}],
"attraction": [{tr:"i. (tourist attraction) turistik cazibe merkezi",yz:2}, {tr:"i. çekim, cazibe",yz:4}],
"attribute": [{tr:"f. atfetmek, bağlamak",yz:4}, {tr:"i. nitelik, özellik",yz:3}],
"auction": [{tr:"f. açık artırmayla satmak",yz:2}, {tr:"i. açık artırma, mezat",yz:4}],
"audience": [{tr:"i. izleyici kitlesi, dinleyiciler",yz:4}, {tr:"i. resmi görüşme",yz:1}],
"average": [{tr:"s./i. ortalama",yz:4}, {tr:"s. sıradan, vasat",yz:2}],
"award": [{tr:"i. ödül",yz:4}, {tr:"f. ödül vermek, bahşetmek",yz:3}],
"baby": [{tr:"i. bebek",yz:4}, {tr:"f. şımartmak",yz:1}],
"background": [{tr:"i. arka plan, geçmiş, altyapı",yz:4}, {tr:"f. arka planda tutmak, arka planda çalıştırmak",yz:1}],
"balance": [{tr:"i. denge",yz:4}, {tr:"f. dengelemek",yz:2}],
"ball": [{tr:"i. top",yz:3}, {tr:"i. balo, dans partisi",yz:1}],
"ban": [{tr:"i. yasak",yz:4}, {tr:"f. yasaklamak",yz:4}],
"bang": [{tr:"i. gürültülü ses, patlama sesi",yz:3}, {tr:"f. şiddetle vurmak, çarpmak",yz:2}],
"bank": [{tr:"i. banka",yz:4}, {tr:"i. nehir kıyısı",yz:2}],
"bar": [{tr:"f. engellemek, yasaklamak",yz:4}, {tr:"i. bar (mekân)",yz:1}],
"bat": [{tr:"i. yarasa",yz:3}, {tr:"i. sopa",yz:1}],
"bath": [{tr:"i. banyo, yıkanma",yz:3}, {tr:"i. (public bath) hamam",yz:1}],
"battery": [{tr:"i. pil, batarya",yz:4}, {tr:"i. dizi, seri, takım",yz:2}],
"battle": [{tr:"i. savaş, muharebe",yz:4}, {tr:"f. mücadele etmek",yz:3}],
"beam": [{tr:"i. ışın, huzme",yz:4}, {tr:"i. kiriş",yz:2}],
"bear": [{tr:"f. taşımak, katlanmak",yz:4}, {tr:"i. ayı",yz:2}],
"beat": [{tr:"i. vuruş, ritim, atım",yz:3}, {tr:"f. yenmek, vurmak",yz:3}],
"beauty": [{tr:"i. güzellik",yz:4}, {tr:"i. eşsiz/harika örnek",yz:1}],
"bed": [{tr:"i. yatak; (nehir/deniz) taban",yz:4}, {tr:"f. yerleştirmek, oturtmak",yz:1}],
"beginning": [{tr:"i. başlangıç, başlama",yz:4}, {tr:"s. başlangıç düzeyinde, yeni başlayan",yz:1}],
"behave": [{tr:"f. davranmak",yz:4}, {tr:"f. terbiyeli davranmak, uslu durmak",yz:1}],
"behind": [{tr:"e. arkasında, gerisinde",yz:4}, {tr:"z. geride",yz:2}],
"beneath": [{tr:"e. altında, altına",yz:4}, {tr:"z. altta, aşağıda",yz:2}],
"besides": [{tr:"e. -den başka, yanı sıra",yz:3}, {tr:"z. ayrıca, üstelik",yz:4}],
"bet": [{tr:"i. bahis, iddia",yz:3}, {tr:"f. bahse girmek, iddiaya girmek",yz:2}],
"bias": [{tr:"i. önyargı, yanlılık",yz:4}, {tr:"f. yanlı hâle getirmek",yz:1}],
"bill": [{tr:"i. kanun tasarısı",yz:4}, {tr:"i. fatura, hesap",yz:2}],
"birth": [{tr:"i. doğum",yz:4}, {tr:"f. doğurmak",yz:1}],
"bite": [{tr:"f. ısırmak, sokmak",yz:3}, {tr:"i. ısırık",yz:2}],
"black": [{tr:"s. siyah, kara",yz:3}, {tr:"i. siyah renk",yz:1}],
"blame": [{tr:"f. suçlamak, sorumlu tutmak",yz:4}, {tr:"i. suç, kabahat, sorumluluk",yz:2}],
"blend": [{tr:"f. karıştırmak, harmanlamak",yz:3}, {tr:"i. karışım, harman",yz:3}],
"block": [{tr:"f. engellemek, tıkamak",yz:4}, {tr:"i. blok, engel",yz:3}],
"blow": [{tr:"f. esmek",yz:3}, {tr:"i. darbe",yz:3}],
"blue": [{tr:"s./i. mavi",yz:4}, {tr:"f. maviye boyamak",yz:1}],
"board": [{tr:"i. kurul, yönetim kurulu",yz:4}, {tr:"f. binmek (araca)",yz:2}],
"boat": [{tr:"i. tekne, kayık",yz:4}, {tr:"f. tekneyle gitmek",yz:1}],
"bodily": [{tr:"s. bedensel",yz:4}, {tr:"z. bedenen, bütünüyle",yz:1}],
"bond": [{tr:"i. bağ, ilişki",yz:4}, {tr:"i. tahvil",yz:2}],
"bones": [{tr:"i. kemikler",yz:4}, {tr:"i. (mecazi) temel yapı, iskelet",yz:1}],
"boom": [{tr:"i. ani yükseliş, patlama",yz:4}, {tr:"f. hızla gelişmek, patlama yapmak",yz:3}],
"boost": [{tr:"f. artırmak, güçlendirmek",yz:4}, {tr:"i. artış, destek",yz:3}],
"border": [{tr:"i. sınır",yz:4}, {tr:"f. sınırdaş olmak, komşu olmak, bitişik olmak",yz:2}],
"bottle": [{tr:"i. şişe",yz:3}, {tr:"f. şişelemek",yz:1}],
"bottom": [{tr:"i. dip, taban",yz:4}, {tr:"f. dibe vurmak, en düşük noktaya ulaşmak",yz:1}],
"box": [{tr:"i. kutu",yz:4}, {tr:"f. kutulamak; boks yapmak",yz:1}],
"branch": [{tr:"i. dal, kol; şube",yz:4}, {tr:"f. dallanmak, kollara ayrılmak",yz:2}],
"brand": [{tr:"i. marka",yz:4}, {tr:"f. markalamak, damgalamak",yz:1}],
"bread": [{tr:"i. ekmek",yz:3}, {tr:"f. galeta ununa bulamak (yemek hazırlarken)",yz:1}],
"breakdown": [{tr:"i. ayrıntılı döküm",yz:3}, {tr:"i. arıza, bozulma; (sinirsel) çöküntü",yz:3}],
"breast": [{tr:"i. göğüs, meme",yz:4}, {tr:"f. (nad.) göğüs germek, karşı koymak",yz:1}],
"breed": [{tr:"i. tür, cins, ırk (hayvan)",yz:3}, {tr:"f. üretmek, yol açmak; üremek",yz:4}],
"brief": [{tr:"f. bilgilendirmek, bilgi vermek",yz:3}, {tr:"s. kısa, özlü",yz:4}],
"bright": [{tr:"s. zeki",yz:3}, {tr:"s. parlak",yz:4}],
"brilliant": [{tr:"s. olağanüstü, muhteşem (zekâ/başarı için)",yz:4}, {tr:"s. parlak (ışık için)",yz:2}],
"bring-up": [{tr:"f. (bring up) gündeme getirmek",yz:4}, {tr:"f. (bring up) yetiştirmek, büyütmek (çocuk)",yz:3}],
"broken": [{tr:"s. (konuşma için) kesik kesik, düzensiz",yz:2}, {tr:"s. kırık",yz:3}],
"bubble": [{tr:"i. kabarcık, baloncuk",yz:3}, {tr:"i. (ekonomik) balon",yz:4}, {tr:"f. kabarcık çıkarmak, fokurdamak",yz:1}],
"building": [{tr:"i. bina, yapı",yz:4}, {tr:"i. inşa etme, yapım",yz:2}],
"built": [{tr:"s. inşa edilmiş, yapılmış",yz:4}, {tr:"s. yapılı, güçlü yapıya sahip",yz:1}],
"bulk": [{tr:"i. büyük kısım, çoğunluk; hacim",yz:4}, {tr:"f. iri görünmek, kabarmak",yz:1}],
"burden": [{tr:"i. yük, külfet",yz:4}, {tr:"f. yüklemek, sıkıntı vermek",yz:2}],
"burn": [{tr:"f. yanmak, yakmak",yz:4}, {tr:"i. yanık",yz:2}],
"busy": [{tr:"s. yoğun, işlek",yz:3}, {tr:"s. meşgul",yz:4}],
"cable": [{tr:"i. kablo; halat",yz:3}, {tr:"f. telgraf çekmek",yz:1}],
"cake": [{tr:"i. kek, pasta",yz:3}, {tr:"i. kalıp (sabun vb.)",yz:1}],
"calm": [{tr:"s. sakin, durgun",yz:4}, {tr:"f. sakinleştirmek",yz:2}],
"came": [{tr:"f. (come'un geçmiş biçimi) geldi",yz:4}, {tr:"i. (nadir) vitray kurşun çıtası",yz:1}],
"campaign": [{tr:"i. kampanya",yz:4}, {tr:"f. kampanya yürütmek, mücadele etmek",yz:2}],
"capital": [{tr:"i. sermaye",yz:4}, {tr:"i. başkent",yz:3}],
"capture": [{tr:"f. kaydetmek",yz:3}, {tr:"f. yakalamak, ele geçirmek",yz:4}],
"career": [{tr:"i. kariyer, meslek hayatı",yz:4}, {tr:"f. hızla ve kontrolsüzce gitmek",yz:1}],
"cash": [{tr:"i. nakit, peşin para",yz:4}, {tr:"f. bozdurmak, paraya çevirmek",yz:1}],
"catch": [{tr:"f. yakalamak",yz:4}, {tr:"f. anlamak, kavramak",yz:2}],
"cease": [{tr:"f. durmak, sona ermek, bırakmak",yz:4}, {tr:"i. (without cease) durma, ara verme",yz:1}],
"center": [{tr:"f. odaklanmak, merkezinde olmak",yz:3}, {tr:"i. merkez",yz:4}],
"centre": [{tr:"i. merkez",yz:4}, {tr:"f. merkezileştirmek, odaklanmak",yz:2}],
"chain": [{tr:"i. zincir",yz:4}, {tr:"f. zincirlemek",yz:1}],
"chamber": [{tr:"i. oda, hazne, bölme",yz:4}, {tr:"i. meclis, yasama meclisi (parlamentonun bir kanadı)",yz:2}],
"chance": [{tr:"i. şans, olasılık, fırsat",yz:4}, {tr:"s. tesadüfi",yz:2}],
"channel": [{tr:"i. kanal",yz:3}, {tr:"f. yönlendirmek, kanalize etmek",yz:3}],
"chapter": [{tr:"i. bölüm",yz:4}, {tr:"i. dönem, evre",yz:3}],
"character": [{tr:"i. karakter, özellik",yz:3}, {tr:"i. kişilik",yz:4}],
"charge": [{tr:"f. ücret almak",yz:3}, {tr:"i. suçlama, itham",yz:3}],
"chart": [{tr:"i. grafik, çizelge",yz:4}, {tr:"f. haritasını çıkarmak, planlamak (bir rota/süreç)",yz:2}],
"chase": [{tr:"f. kovalamak, peşine düşmek",yz:3}, {tr:"i. kovalamaca, takip",yz:2}],
"cheap": [{tr:"s. ucuz",yz:4}, {tr:"s. değersiz, adi, kalitesiz",yz:2}],
"cheat": [{tr:"f. hile yapmak, kopya çekmek; aldatmak",yz:3}, {tr:"i. hilekâr, dolandırıcı",yz:1}],
"chemistry": [{tr:"i. kimya",yz:4}, {tr:"i. (kişiler arası) uyum, çekim",yz:1}],
"chicken": [{tr:"i. tavuk",yz:3}, {tr:"s. (günlük dil) korkak",yz:1}],
"chief": [{tr:"s. başlıca, ana",yz:4}, {tr:"i. şef, reis, lider",yz:2}],
"chocolate": [{tr:"i. çikolata",yz:3}, {tr:"s. (renk) koyu kahverengi",yz:1}],
"circle": [{tr:"f. etrafında dönmek, dolanmak",yz:3}, {tr:"i. daire, çember; grup, çevre",yz:4}],
"circulate": [{tr:"f. dolaşmak",yz:4}, {tr:"f. yaymak, (haber/söylenti) dolaştırmak",yz:3}],
"circulation": [{tr:"i. dolaşım (kan, hava, para)",yz:4}, {tr:"i. tiraj (gazete/dergi)",yz:2}],
"civil": [{tr:"s. sivil, medeni",yz:4}, {tr:"s. nazik, kibar, saygılı",yz:2}],
"claim": [{tr:"f. iddia etmek",yz:4}, {tr:"i. iddia",yz:3}],
"class": [{tr:"i. sınıf",yz:4}, {tr:"i. ders",yz:2}],
"classic": [{tr:"i. klasik eser",yz:2}, {tr:"s. klasik",yz:3}],
"clean": [{tr:"s. temiz",yz:4}, {tr:"f. temizlemek",yz:3}],
"client": [{tr:"i. müvekkil",yz:2}, {tr:"i. müşteri",yz:4}],
"climb": [{tr:"i. tırmanış, yokuş",yz:2}, {tr:"f. tırmanmak, çıkmak",yz:4}],
"clinical": [{tr:"s. klinik",yz:4}, {tr:"s. tarafsız, duygusuz",yz:1}],
"clip": [{tr:"i. kısa video, görüntü",yz:3}, {tr:"i. ataş, klips",yz:2}],
"clock": [{tr:"i. saat (duvar/masa)",yz:3}, {tr:"f. süre ölçmek, kaydetmek",yz:1}],
"clone": [{tr:"f. klonlamak, kopyalamak",yz:4}, {tr:"i. klon, kopya",yz:3}],
"closer": [{tr:"z. daha yakın",yz:3}, {tr:"i. kapatan kişi/şey, sonuca bağlayan",yz:1}],
"cloud": [{tr:"f. bulandırmak, gölgelemek",yz:3}, {tr:"i. bulut",yz:4}],
"club": [{tr:"i. kulüp, dernek",yz:4}, {tr:"i. sopa, cop",yz:1}, {tr:"f. sopayla vurmak, coplamak",yz:1}],
"coast": [{tr:"i. sahil, kıyı",yz:4}, {tr:"f. süzülerek ilerlemek",yz:1}],
"code": [{tr:"i. yasa, kurallar",yz:3}, {tr:"i. kod, şifre; f. kodlamak",yz:3}],
"coin": [{tr:"f. (yeni sözcük) türetmek",yz:4}, {tr:"i. madeni para, bozuk para",yz:3}],
"cold": [{tr:"s. soğuk",yz:4}, {tr:"i. soğuk algınlığı",yz:2}],
"collapse": [{tr:"i. çöküş",yz:4}, {tr:"f. çökmek",yz:3}],
"collection": [{tr:"i. koleksiyon, derleme",yz:4}, {tr:"i. toplama",yz:3}],
"collective": [{tr:"s. ortak, kolektif, toplu",yz:4}, {tr:"i. kolektif, ortak girişim",yz:1}],
"colonial": [{tr:"s. sömürgeyle ilgili, sömürge dönemine ait",yz:4}, {tr:"i. sömürge sakini",yz:1}],
"colony": [{tr:"i. koloni, sömürge",yz:4}, {tr:"i. (hayvan) topluluk",yz:3}],
"colour": [{tr:"i. renk",yz:4}, {tr:"f. boyamak, renklendirmek",yz:2}],
"colours": [{tr:"i. renkler",yz:4}, {tr:"i. bayrak, sancak",yz:1}],
"column": [{tr:"i. sütun, kolon",yz:4}, {tr:"i. köşe yazısı",yz:2}],
"combat": [{tr:"f. mücadele etmek, savaşmak",yz:4}, {tr:"i. çatışma, muharebe",yz:2}],
"combine": [{tr:"f. birleştirmek, bir araya getirmek",yz:4}, {tr:"i. biçerdöver",yz:1}],
"comfort": [{tr:"i. rahat, konfor",yz:3}, {tr:"f. teselli etmek, avutmak",yz:2}],
"coming": [{tr:"s. gelecek, yaklaşan",yz:4}, {tr:"i. geliş, gelme",yz:1}],
"comment": [{tr:"f. yorum yapmak",yz:3}, {tr:"i. yorum",yz:4}],
"commercial": [{tr:"s. ticari",yz:4}, {tr:"i. reklam (TV/radyo)",yz:2}],
"commission": [{tr:"f. sipariş vermek, görevlendirmek",yz:3}, {tr:"i. komisyon, kurul",yz:4}],
"commit": [{tr:"f. taahhüt etmek",yz:4}, {tr:"f. işlemek (suç)",yz:3}],
"communicative": [{tr:"s. iletişimsel",yz:3}, {tr:"s. iletişime açık, konuşkan",yz:3}],
"compact": [{tr:"s. kompakt, küçük ve pratik",yz:4}, {tr:"i. anlaşma, sözleşme",yz:2}, {tr:"f. sıkıştırmak",yz:2}],
"competition": [{tr:"i. rekabet",yz:4}, {tr:"i. yarışma",yz:2}],
"complement": [{tr:"f. tamamlamak",yz:4}, {tr:"i. tamamlayıcı",yz:2}],
"compound": [{tr:"i. bileşik",yz:3}, {tr:"f. birleştirmek, ağırlaştırmak",yz:4}],
"conceive": [{tr:"f. tasarlamak, aklına getirmek, düşünmek",yz:4}, {tr:"f. gebe kalmak",yz:2}],
"concentrate": [{tr:"f. odaklanmak, konsantre olmak",yz:4}, {tr:"f. yoğunlaştırmak, koyulaştırmak",yz:2}],
"concentration": [{tr:"i. yoğunluk, derişim",yz:4}, {tr:"i. konsantrasyon, dikkat",yz:3}],
"conception": [{tr:"i. anlayış, kavrayış",yz:4}, {tr:"i. gebe kalma, döllenme",yz:2}],
"concerned": [{tr:"endişeli, kaygılı",yz:4}, {tr:"ilgili",yz:3}],
"concert": [{tr:"i. konser",yz:3}, {tr:"i. uyum, birlik (in concert: birlikte, uyum içinde)",yz:2}],
"concrete": [{tr:"s. somut",yz:4}, {tr:"i. beton",yz:2}],
"confine": [{tr:"f. sınırlamak, kısıtlamak",yz:4}, {tr:"f. kapatmak, hapsetmek",yz:3}],
"conflict": [{tr:"i. çatışma, anlaşmazlık",yz:4}, {tr:"f. çelişmek, çatışmak",yz:3}],
"consent": [{tr:"i. onay, rıza",yz:4}, {tr:"f. onaylamak, razı olmak",yz:2}],
"consideration": [{tr:"i. dikkate alma, değerlendirme",yz:4}, {tr:"i. saygı, düşüncelilik",yz:2}],
"constant": [{tr:"i. sabit (matematik)",yz:1}, {tr:"s. sabit, sürekli",yz:4}],
"constitution": [{tr:"i. anayasa",yz:4}, {tr:"i. yapı, bünye",yz:2}],
"constrain": [{tr:"f. kısıtlamak, sınırlamak",yz:4}, {tr:"f. zorlamak (bir şey yapmaya)",yz:1}],
"construct": [{tr:"f. inşa etmek, kurmak",yz:4}, {tr:"i. kavram, yapı",yz:2}],
"contact": [{tr:"i. temas, iletişim",yz:4}, {tr:"f. temas kurmak",yz:2}],
"contemporary": [{tr:"s. çağdaş, güncel",yz:4}, {tr:"s./i. aynı dönemden (olan kişi), çağdaşı",yz:2}],
"content": [{tr:"i. içerik",yz:4}, {tr:"s. memnun, hoşnut",yz:2}],
"contract": [{tr:"f. (hastalık) kapmak, yakalanmak",yz:3}, {tr:"i. sözleşme",yz:4}],
"contrast": [{tr:"i. karşıtlık, zıtlık, tezat",yz:4}, {tr:"f. karşılaştırmak, kıyaslamak",yz:2}],
"controlling": [{tr:"s. hakim, denetleyici",yz:3}, {tr:"s. (kişi için) baskıcı",yz:2}],
"convert": [{tr:"f. dönüştürmek",yz:4}, {tr:"i. dönme, mühtedi",yz:1}],
"cook": [{tr:"f. pişirmek, yemek yapmak",yz:3}, {tr:"i. aşçı",yz:2}],
"cool": [{tr:"f. soğumak, soğutmak",yz:3}, {tr:"s. serin",yz:3}],
"coordinate": [{tr:"f. koordine etmek, eşgüdümlemek",yz:4}, {tr:"i. koordinat",yz:2}],
"coordination": [{tr:"i. koordinasyon, eşgüdüm",yz:4}, {tr:"i. (beden) uyum",yz:2}],
"copy": [{tr:"i. kopya, nüsha",yz:4}, {tr:"f. kopyalamak, taklit etmek",yz:3}],
"correct": [{tr:"f. düzeltmek",yz:3}, {tr:"s. doğru",yz:4}],
"correspond": [{tr:"f. karşılık gelmek, örtüşmek",yz:4}, {tr:"f. yazışmak",yz:2}],
"count": [{tr:"f. önemli olmak",yz:3}, {tr:"f. saymak",yz:4}],
"counter": [{tr:"f. karşılık vermek, karşı çıkmak",yz:4}, {tr:"i. tezgah (mağaza/mutfak)",yz:1}],
"couple": [{tr:"f. birleştirmek, eşleştirmek",yz:3}, {tr:"i. çift, iki",yz:4}],
"court": [{tr:"i. mahkeme; saray; (spor) kort",yz:4}, {tr:"f. gönlünü kazanmaya çalışmak, kur yapmak",yz:1}],
"cover": [{tr:"f. kaplamak, örtmek",yz:4}, {tr:"f. kapsamak, içermek",yz:3}],
"covered": [{tr:"s. örtülü, kaplı",yz:3}, {tr:"s. kapsam dahilinde, güvence altında",yz:2}],
"cow": [{tr:"i. inek",yz:3}, {tr:"f. korkutmak, yıldırmak, sindirmek",yz:1}],
"crash": [{tr:"f. düşmek, çarpmak",yz:4}, {tr:"i. çarpışma, kaza",yz:3}],
"credit": [{tr:"i. kredi",yz:3}, {tr:"i. övgü, itibar; f. atfetmek",yz:4}],
"criminal": [{tr:"i. suçlu",yz:3}, {tr:"s. cezai, suça ilişkin",yz:3}],
"critical": [{tr:"s. kritik, çok önemli",yz:4}, {tr:"s. eleştirel",yz:3}],
"crop": [{tr:"i. mahsul, ürün",yz:4}, {tr:"f. hasat etmek, kırpmak",yz:1}],
"cross": [{tr:"f. karşıdan karşıya geçmek, kesişmek",yz:4}, {tr:"i. haç; çarpı",yz:2}, {tr:"s. kızgın, ters",yz:1}],
"crude": [{tr:"s. ham, işlenmemiş",yz:4}, {tr:"s. kaba, terbiyesiz",yz:2}],
"cue": [{tr:"i. işaret, ipucu",yz:4}, {tr:"f. işaret vermek",yz:2}],
"cup": [{tr:"i. fincan, kupa",yz:3}, {tr:"f. avuçlamak",yz:1}],
"cure": [{tr:"i. tedavi, çare",yz:4}, {tr:"f. tedavi etmek, iyileştirmek",yz:3}],
"curious": [{tr:"s. meraklı",yz:4}, {tr:"s. tuhaf, garip",yz:2}],
"current": [{tr:"i. akım",yz:3}, {tr:"s. güncel, şimdiki",yz:4}],
"custom": [{tr:"i. gelenek, âdet",yz:4}, {tr:"s. ısmarlama, özel yapım",yz:2}],
"cutting": [{tr:"s. keskin, acı (rüzgâr/söz)",yz:3}, {tr:"i. gazete kupürü",yz:1}],
"cycle": [{tr:"i. döngü, çevrim",yz:4}, {tr:"f. bisiklete binmek",yz:1}],
"dairy": [{tr:"i. süt ürünleri",yz:4}, {tr:"i. mandıra, süt çiftliği",yz:1}],
"dance": [{tr:"i. dans",yz:3}, {tr:"f. dans etmek",yz:2}],
"dark": [{tr:"s. karanlık",yz:4}, {tr:"i. (the dark) karanlık",yz:1}],
"date": [{tr:"f. tarihini belirlemek",yz:3}, {tr:"i. randevu",yz:1}],
"days": [{tr:"i. dönem, çağ",yz:3}, {tr:"i. günler",yz:3}],
"dead": [{tr:"s. ölü, cansız",yz:4}, {tr:"z. tamamen",yz:1}],
"deadly": [{tr:"s. ölümcül",yz:4}, {tr:"z. son derece, aşırı",yz:2}],
"dealing": [{tr:"i. muamele, davranış tarzı",yz:3}, {tr:"i. ticaret, alışveriş",yz:3}],
"debate": [{tr:"f. tartışmak",yz:3}, {tr:"i. tartışma",yz:4}],
"decay": [{tr:"i. çürüme, bozulma, bozunma",yz:4}, {tr:"f. çürümek, bozulmak",yz:3}],
"dedicate": [{tr:"f. adamak, vakfetmek",yz:4}, {tr:"f. ithaf etmek",yz:2}],
"deep": [{tr:"s./z. derin",yz:4}, {tr:"i. derinlik",yz:1}],
"defeat": [{tr:"i. yenilgi, mağlubiyet",yz:3}, {tr:"f. yenmek, mağlup etmek; (tasarıyı) düşürmek",yz:4}],
"definition": [{tr:"i. tanım",yz:4}, {tr:"i. netlik",yz:1}],
"degree": [{tr:"i. derece",yz:4}, {tr:"i. (üniversite) diploma",yz:3}],
"delay": [{tr:"i. gecikme",yz:4}, {tr:"f. geciktirmek, ertelemek",yz:3}],
"deliberately": [{tr:"z. kasıtlı olarak, bilerek",yz:4}, {tr:"z. ağır ağır, temkinli bir şekilde",yz:1}],
"delight": [{tr:"f. çok mutlu etmek, hoşnut etmek",yz:2}, {tr:"i. keyif, zevk, sevinç",yz:3}],
"deliver": [{tr:"f. teslim etmek, sunmak",yz:4}, {tr:"f. doğurtmak",yz:1}],
"delivery": [{tr:"i. teslimat, dağıtım",yz:4}, {tr:"i. doğum (çocuk doğurma)",yz:2}],
"demonstrate": [{tr:"f. göstermek, kanıtlamak",yz:4}, {tr:"f. gösteri yapmak",yz:2}],
"dependent": [{tr:"s. bağımlı, bağlı",yz:4}, {tr:"i. bakmakla yükümlü olunan kişi",yz:1}],
"depress": [{tr:"f. moralini bozmak, bunaltmak",yz:3}, {tr:"f. düşürmek, bastırmak",yz:3}],
"depression": [{tr:"i. depresyon, bunalım",yz:4}, {tr:"i. çöküntü, alçalma",yz:2}],
"depth": [{tr:"i. derinlik",yz:4}, {tr:"i. (mecazi) yoğunluk, kapsamlılık",yz:2}],
"desert": [{tr:"i. çöl",yz:4}, {tr:"f. terk etmek, firar etmek",yz:2}],
"desire": [{tr:"i. arzu, istek",yz:4}, {tr:"f. arzulamak, istemek",yz:2}],
"detail": [{tr:"i. ayrıntı, detay",yz:4}, {tr:"f. ayrıntılandırmak, ayrıntılarıyla açıklamak",yz:2}],
"developing": [{tr:"s. gelişmekte olan",yz:4}, {tr:"i. (fotoğraf) banyo etme",yz:1}],
"devices": [{tr:"i. cihazlar, aygıtlar",yz:4}, {tr:"(left to one's own devices) kendi hâline/başına bırakılmak",yz:1}],
"devise": [{tr:"f. tasarlamak, icat etmek",yz:4}, {tr:"i. (hukuk) gayrimenkul vasiyeti, miras bırakılan mülk",yz:1}],
"die": [{tr:"f. ölmek",yz:4}, {tr:"i. kalıp, zar",yz:1}],
"direct": [{tr:"f. yönetmek, yönlendirmek",yz:2}, {tr:"s./z. doğrudan",yz:4}],
"direction": [{tr:"i. yön",yz:4}, {tr:"i. yönetim, idare",yz:2}],
"director": [{tr:"i. müdür, direktör",yz:3}, {tr:"i. yönetmen (film/tiyatro)",yz:3}],
"disadvantage": [{tr:"i. dezavantaj, sakınca",yz:4}, {tr:"f. zarara uğratmak",yz:1}],
"discipline": [{tr:"i. bilim dalı, alan",yz:4}, {tr:"i. disiplin, öz denetim; f. disipline etmek, cezalandırmak",yz:3}],
"discriminate": [{tr:"f. ayrımcılık yapmak",yz:3}, {tr:"f. ayırt etmek, fark etmek",yz:4}],
"dish": [{tr:"i. tabak; yemek",yz:3}, {tr:"f. dağıtmak, servis yapmak",yz:1}],
"display": [{tr:"f. sergilemek, göstermek",yz:4}, {tr:"i. sergi, gösterim",yz:2}],
"dispute": [{tr:"i. anlaşmazlık, uyuşmazlık",yz:4}, {tr:"f. itiraz etmek, tartışmak",yz:4}],
"dissolve": [{tr:"f. erimek, çözünmek",yz:4}, {tr:"f. feshetmek, dağıtmak",yz:3}],
"distance": [{tr:"i. mesafe, uzaklık",yz:4}, {tr:"f. uzaklaştırmak, mesafe koymak",yz:2}],
"distinction": [{tr:"i. ayrım, fark",yz:4}, {tr:"i. seçkinlik, üstünlük",yz:2}],
"divide": [{tr:"f. bölmek, ayırmak",yz:4}, {tr:"i. bölünme, ayrım, uçurum",yz:3}],
"division": [{tr:"i. bölüm, kısım",yz:4}, {tr:"i. ayrılık, anlaşmazlık",yz:3}],
"doctor": [{tr:"i. doktor",yz:4}, {tr:"f. tedavi etmek",yz:1}],
"document": [{tr:"f. belgelemek, kayıt altına almak",yz:3}, {tr:"i. belge, doküman",yz:4}],
"dog": [{tr:"i. köpek",yz:4}, {tr:"f. peşini bırakmamak, musallat olmak",yz:2}],
"domestic": [{tr:"s. yerli, iç (ülkeye ait)",yz:4}, {tr:"s. eve ait, ev içi",yz:3}],
"dominant": [{tr:"s. baskın, egemen, hâkim",yz:4}, {tr:"i. (genetik) baskın gen",yz:1}],
"done": [{tr:"s. bitmiş, tamamlanmış",yz:4}, {tr:"s. pişmiş",yz:1}],
"dose": [{tr:"i. doz",yz:4}, {tr:"f. doz vermek, ilaç vermek",yz:1}],
"double": [{tr:"f. iki katına çıkmak/çıkarmak",yz:4}, {tr:"s. çift, iki katı",yz:3}],
"doubt": [{tr:"f. şüphelenmek, şüphe duymak",yz:3}, {tr:"i. şüphe",yz:4}],
"draft": [{tr:"i. taslak",yz:4}, {tr:"f. taslak hazırlamak",yz:3}],
"drain": [{tr:"i. gider, drenaj borusu",yz:1}, {tr:"f. boşaltmak, akıtmak; (seviyeyi) düşürmek",yz:3}, {tr:"f. tüketmek, zayıflatmak (enerji, kaynak)",yz:4}],
"drama": [{tr:"i. dram, tiyatro oyunu",yz:3}, {tr:"i. (mecazi) heyecanlı/gergin olay",yz:2}],
"draw": [{tr:"f. (sonuç) çıkarmak",yz:4}, {tr:"f. çizmek",yz:2}],
"drawing": [{tr:"i. çizim, resim",yz:3}, {tr:"i. çekiliş, kura",yz:1}],
"drawn": [{tr:"s. yorgun, bitkin görünen (yüz)",yz:3}, {tr:"s. çekilmiş (perde vb.)",yz:2}],
"dream": [{tr:"f. hayal etmek, rüya görmek",yz:3}, {tr:"i. hayal, rüya",yz:3}],
"dress": [{tr:"i. elbise",yz:3}, {tr:"f. giyinmek, giydirmek",yz:3}],
"drift": [{tr:"f. sürüklenmek, sapmak; i. sürüklenme",yz:4}, {tr:"i. genel eğilim, gidişat",yz:1}],
"drink": [{tr:"i. içecek",yz:3}, {tr:"f. içmek",yz:4}],
"drive": [{tr:"f. sürmek, yönlendirmek",yz:4}, {tr:"i. güdü, dürtü",yz:2}],
"driving": [{tr:"i. araç kullanma, sürüş",yz:2}, {tr:"s. itici, sürükleyici",yz:4}],
"drop": [{tr:"i. düşüş",yz:4}, {tr:"f. düşmek, bırakmak",yz:3}],
"dry": [{tr:"s. kuru, kurak",yz:4}, {tr:"f. kurumak, kurutmak",yz:2}],
"dust": [{tr:"i. toz",yz:3}, {tr:"f. serpmek, ince tabaka hâlinde kaplamak",yz:1}],
"duty": [{tr:"i. görev, ödev, yükümlülük",yz:4}, {tr:"i. (ithalat) gümrük vergisi",yz:2}],
"dynamic": [{tr:"s. dinamik, enerjik",yz:4}, {tr:"i. dinamik, itici güç",yz:2}],
"ear": [{tr:"i. kulak",yz:4}, {tr:"(müzik/dil için) kulak, işitme yeteneği",yz:1}],
"earlier": [{tr:"z. daha önce",yz:4}, {tr:"s. önceki, daha erken",yz:3}],
"ease": [{tr:"f. hafifletmek, kolaylaştırmak",yz:4}, {tr:"i. kolaylık, rahatlık",yz:3}],
"east": [{tr:"z. doğuya",yz:2}, {tr:"i. doğu",yz:3}],
"eaten": [{tr:"s. (eaten away) aşınmış, kemirilmiş",yz:2}, {tr:"s. yenmiş, yenilmiş (yemek)",yz:3}],
"economically": [{tr:"z. ekonomik açıdan",yz:4}, {tr:"z. tutumlu biçimde",yz:1}],
"edge": [{tr:"i. kenar, kıyı; üstünlük",yz:4}, {tr:"f. yavaşça ilerlemek",yz:1}],
"edit": [{tr:"f. düzenlemek, redakte etmek",yz:4}, {tr:"f. kurgulamak",yz:2}],
"effectively": [{tr:"z. etkili biçimde",yz:4}, {tr:"z. fiilen, gerçekte",yz:2}],
"egg": [{tr:"i. yumurta",yz:4}, {tr:"f. kışkırtmak (egg on)",yz:1}],
"elaborate": [{tr:"s. ayrıntılı, özenli",yz:4}, {tr:"f. detaylandırmak, ayrıntıya girmek",yz:3}],
"elderly": [{tr:"s. yaşlı",yz:4}, {tr:"i. (the elderly) yaşlılar",yz:3}],
"electric": [{tr:"s. elektrikli, elektrik",yz:4}, {tr:"i. elektrikli taşıt",yz:1}],
"element": [{tr:"i. öge, unsur",yz:4}, {tr:"i. element (kimyasal)",yz:2}],
"elementary": [{tr:"s. temel, basit",yz:3}, {tr:"s. ilköğretime ait, ilkokul düzeyinde",yz:3}],
"elite": [{tr:"i. seçkinler, elit tabaka",yz:4}, {tr:"s. seçkin",yz:3}],
"else": [{tr:"z. aksi halde",yz:3}, {tr:"z. başka",yz:4}],
"embrace": [{tr:"f. (bir fikri) benimsemek",yz:4}, {tr:"f. kucaklamak",yz:2}],
"emergency": [{tr:"i. olağanüstü hâl",yz:3}, {tr:"i. acil durum",yz:4}],
"employ": [{tr:"f. istihdam etmek",yz:3}, {tr:"f. kullanmak, yararlanmak",yz:4}],
"employed": [{tr:"s. çalışan, istihdam edilmiş",yz:3}, {tr:"s. kullanılan (yöntem, teknik vb.)",yz:4}],
"empty": [{tr:"s. boş",yz:4}, {tr:"f. boşaltmak",yz:2}],
"encounter": [{tr:"f. karşılaşmak, rastlamak",yz:4}, {tr:"i. karşılaşma",yz:3}],
"ended": [{tr:"s. (bileşiklerde) -uçlu",yz:3}, {tr:"s. sona ermiş, bitmiş",yz:2}],
"engage": [{tr:"f. katılmak, meşgul olmak",yz:4}, {tr:"f. birbirine geçmek (mekanik)",yz:1}],
"engineer": [{tr:"i. mühendis",yz:4}, {tr:"f. tasarlamak, planlamak, düzenlemek",yz:2}],
"enter": [{tr:"f. girmek, katılmak",yz:4}, {tr:"f. kaydetmek",yz:2}],
"entertain": [{tr:"f. eğlendirmek",yz:3}, {tr:"f. (bir fikri) göz önünde bulundurmak",yz:3}],
"entire": [{tr:"s. bütün, tüm, tam",yz:4}, {tr:"i. (nadir) aygır",yz:1}],
"epidemic": [{tr:"i. salgın",yz:4}, {tr:"s. salgın halinde, çok yaygın",yz:2}],
"equal": [{tr:"s. eşit",yz:4}, {tr:"f. eşit olmak, denk gelmek",yz:2}],
"equivalent": [{tr:"s. eşdeğer, denk",yz:4}, {tr:"i. karşılık, eşdeğer",yz:3}],
"escape": [{tr:"f. kaçmak, kurtulmak",yz:4}, {tr:"i. kaçış, firar",yz:2}],
"essence": [{tr:"i. öz, esas",yz:4}, {tr:"i. esans",yz:1}],
"essential": [{tr:"s. temel, zorunlu",yz:4}, {tr:"i. temel gereksinim, olmazsa olmaz unsur",yz:2}],
"establishment": [{tr:"i. kurma, tesis etme",yz:4}, {tr:"i. kuruluş, kurum",yz:3}],
"estate": [{tr:"i. mülk, mal varlığı",yz:4}, {tr:"i. malikâne, geniş arazili konut",yz:2}],
"ethnic": [{tr:"s. etnik",yz:4}, {tr:"i. etnik grup üyesi",yz:1}],
"evil": [{tr:"s. kötü, şeytani",yz:3}, {tr:"i. kötülük, fenalık",yz:3}],
"evolution": [{tr:"i. evrim",yz:4}, {tr:"i. (kademeli) gelişim, değişim",yz:3}],
"exact": [{tr:"s. tam, kesin, doğru",yz:4}, {tr:"f. talep etmek, zorla almak",yz:1}],
"examination": [{tr:"i. inceleme, muayene",yz:4}, {tr:"i. sınav",yz:3}],
"except": [{tr:"e. hariç, -den başka",yz:4}, {tr:"f. hariç tutmak, dışında bırakmak",yz:1}],
"excess": [{tr:"s. fazla, aşırı",yz:3}, {tr:"i. fazlalık, aşırılık",yz:4}],
"exchange": [{tr:"i. değişim, alışveriş, takas",yz:4}, {tr:"f. değiştirmek, takas etmek",yz:3}],
"excite": [{tr:"f. heyecanlandırmak",yz:4}, {tr:"f. uyarmak (örn. fizikte)",yz:1}],
"excuse": [{tr:"i. mazeret, bahane",yz:3}, {tr:"f. affetmek, mazur görmek; muaf tutmak",yz:2}],
"execute": [{tr:"f. uygulamaya koymak, yerine getirmek",yz:4}, {tr:"f. idam etmek",yz:2}],
"execution": [{tr:"i. idam, infaz",yz:3}, {tr:"i. uygulama, icra, gerçekleştirme",yz:4}],
"exhaust": [{tr:"f. tüketmek, bitirmek",yz:4}, {tr:"f. yormak, bitkin düşürmek",yz:2}, {tr:"i. egzoz, egzoz gazı",yz:3}],
"exhibit": [{tr:"f. sergilemek, göstermek",yz:4}, {tr:"i. sergi, eser",yz:2}],
"exit": [{tr:"f. çıkmak, ayrılmak",yz:3}, {tr:"i. çıkış (kapısı/yeri)",yz:3}],
"experiment": [{tr:"i. deney",yz:4}, {tr:"f. deney yapmak",yz:2}],
"exploit": [{tr:"f. sömürmek, kötüye kullanmak; yararlanmak",yz:4}, {tr:"i. kahramanlık, başarı",yz:1}],
"exploitation": [{tr:"i. sömürü",yz:4}, {tr:"i. (doğal kaynakların) işletilmesi, yararlanma",yz:3}],
"export": [{tr:"f. ihraç etmek",yz:4}, {tr:"i. ihracat, dışsatım",yz:3}],
"exposure": [{tr:"i. maruz kalma",yz:4}, {tr:"i. pozlama (fotoğrafçılıkta)",yz:1}],
"express": [{tr:"f. ifade etmek, dile getirmek",yz:4}, {tr:"s. ekspres, hızlı",yz:1}],
"extension": [{tr:"i. uzatma; genişletme",yz:4}, {tr:"i. dahili telefon hattı",yz:1}],
"extinct": [{tr:"s. (tür) nesli tükenmiş",yz:4}, {tr:"s. (yanardağ) sönmüş",yz:2}],
"extra": [{tr:"s. ek, ilave",yz:4}, {tr:"i. figüran",yz:1}],
"extract": [{tr:"f. çıkarmak, elde etmek",yz:4}, {tr:"i. alıntı, özet parça",yz:2}],
"extreme": [{tr:"s. aşırı, uç",yz:4}, {tr:"i. uç nokta, aşırılık",yz:2}],
"eye": [{tr:"i. göz",yz:4}, {tr:"f. dikkatle süzmek, gözlemek",yz:1}],
"eyes": [{tr:"i. bakış, görüş (birinin gözünde)",yz:3}, {tr:"i. gözler",yz:4}],
"fabric": [{tr:"i. yapı, doku (mecaz)",yz:3}, {tr:"i. kumaş",yz:4}],
"facility": [{tr:"i. tesis",yz:4}, {tr:"i. kolaylık, yetenek",yz:2}],
"failure": [{tr:"i. arıza, yetmezlik",yz:3}, {tr:"i. başarısızlık",yz:4}],
"fairly": [{tr:"z. oldukça",yz:4}, {tr:"z. adil biçimde",yz:2}],
"fan": [{tr:"i. hayran; yelpaze, vantilatör",yz:4}, {tr:"f. yelpazelemek, körüklemek",yz:2}],
"farm": [{tr:"i. çiftlik",yz:4}, {tr:"f. çiftçilik yapmak, toprağı işlemek",yz:2}],
"farming": [{tr:"i. tarım, çiftçilik",yz:4}, {tr:"s. tarıma ait",yz:3}],
"fashion": [{tr:"f. biçimlendirmek, şekillendirmek",yz:2}, {tr:"i. moda",yz:4}],
"fat": [{tr:"i. yağ",yz:4}, {tr:"s. şişman, yağlı",yz:2}],
"father": [{tr:"i. baba, kurucu",yz:4}, {tr:"f. -in babası olmak",yz:1}],
"fatigue": [{tr:"i. yorgunluk, bitkinlik",yz:4}, {tr:"f. yormak, bitkin düşürmek",yz:2}],
"fault": [{tr:"i. fay",yz:3}, {tr:"i. kusur, hata",yz:4}],
"favour": [{tr:"f. desteklemek, tercih etmek",yz:4}, {tr:"i. iyilik, lütuf",yz:1}],
"fear": [{tr:"f. korkmak",yz:3}, {tr:"i. korku",yz:4}],
"feed": [{tr:"f. beslemek",yz:4}, {tr:"i. yem",yz:2}],
"fell": [{tr:"f. (fall'ın geçmiş zamanı) düştü, azaldı",yz:4}, {tr:"f. (ağaç) kesmek, devirmek",yz:2}],
"female": [{tr:"s. dişi, kadınlara özgü",yz:4}, {tr:"i. dişi",yz:3}],
"fertile": [{tr:"s. verimli, bereketli",yz:4}, {tr:"s. doğurgan",yz:2}],
"fertility": [{tr:"i. doğurganlık",yz:4}, {tr:"i. verimlilik",yz:3}],
"fever": [{tr:"i. ateş (hastalıkta)",yz:4}, {tr:"i. heyecan, humma",yz:1}],
"fight": [{tr:"f. savaşmak, mücadele etmek",yz:4}, {tr:"i. mücadele, kavga",yz:3}],
"file": [{tr:"f. dosyalamak",yz:2}, {tr:"i. dosya",yz:3}],
"film": [{tr:"i. film",yz:4}, {tr:"i. ince tabaka, film",yz:2}],
"final": [{tr:"s. son, nihai",yz:4}, {tr:"i. final (sınav/maç)",yz:1}],
"finance": [{tr:"f. finanse etmek",yz:3}, {tr:"i. maliye, finans",yz:4}],
"fine": [{tr:"f. cezalandırmak, para cezası kesmek",yz:1}, {tr:"s. ince, güzel, iyi",yz:3}],
"finish": [{tr:"f. bitirmek, tamamlamak",yz:4}, {tr:"i. son, bitiş",yz:2}],
"firm": [{tr:"s. sağlam, kararlı",yz:3}, {tr:"i. firma, şirket",yz:4}],
"fish": [{tr:"f. balık tutmak",yz:2}, {tr:"i. balık",yz:4}],
"fit": [{tr:"s. formda, sağlıklı",yz:3}, {tr:"s. uygun",yz:4}],
"five": [{tr:"s. beş",yz:3}, {tr:"i. beş (sayısı)",yz:2}],
"fix": [{tr:"f. onarmak, tamir etmek, düzeltmek, sabitlemek",yz:4}, {tr:"i. çıkmaz, zor durum",yz:1}],
"flavour": [{tr:"i. tat, lezzet",yz:3}, {tr:"f. tat katmak, lezzetlendirmek",yz:1}],
"flesh": [{tr:"i. et, doku, beden",yz:3}, {tr:"i. (meyve) öz",yz:2}],
"flight": [{tr:"i. uçuş",yz:4}, {tr:"i. kaçış",yz:2}],
"flood": [{tr:"i. sel, taşkın",yz:4}, {tr:"f. su basmak",yz:3}],
"floor": [{tr:"i. taban, alt sınır (fiyat/ücret)",yz:2}, {tr:"i. zemin, kat (bina)",yz:3}],
"flourish": [{tr:"f. gelişmek, serpilmek, büyümek",yz:4}, {tr:"i. gösterişli hareket",yz:1}],
"flow": [{tr:"i. akış, akım",yz:4}, {tr:"f. akmak",yz:3}],
"flower": [{tr:"f. çiçek açmak",yz:2}, {tr:"i. çiçek",yz:4}],
"fluid": [{tr:"i. sıvı, akışkan",yz:4}, {tr:"s. değişken, akıcı",yz:2}],
"fly": [{tr:"f. uçmak",yz:4}, {tr:"i. sinek",yz:1}],
"foot": [{tr:"i. ayak",yz:4}, {tr:"f. (foot the bill) ödemek, üstlenmek",yz:1}],
"forced": [{tr:"s. zorunlu, zorla yapılan",yz:4}, {tr:"s. yapmacık",yz:2}],
"forest": [{tr:"i. orman",yz:4}, {tr:"f. ağaçlandırmak",yz:1}],
"formal": [{tr:"s. resmi, biçimsel",yz:4}, {tr:"i. resmi davet, balo",yz:1}],
"format": [{tr:"i. biçim, format",yz:4}, {tr:"f. biçimlendirmek",yz:2}],
"former": [{tr:"s. eski, önceki",yz:4}, {tr:"i. (the former) ilki",yz:2}],
"formula": [{tr:"formül",yz:4}, {tr:"bebek maması",yz:1}],
"formulation": [{tr:"i. formülasyon",yz:3}, {tr:"i. ifade etme, dile getirme",yz:3}],
"forward": [{tr:"z. ileri, ileriye doğru",yz:4}, {tr:"f. iletmek, göndermek",yz:1}],
"fossil": [{tr:"i. fosil",yz:3}, {tr:"s. fosil (yakıt)",yz:4}],
"foster": [{tr:"f. teşvik etmek, geliştirmek",yz:4}, {tr:"s. koruyucu (aile)",yz:1}],
"foundation": [{tr:"i. vakıf, kuruluş",yz:3}, {tr:"i. temel",yz:4}],
"fraction": [{tr:"i. küçük bölüm, parça",yz:4}, {tr:"i. kesir (matematik)",yz:1}],
"frame": [{tr:"f. çerçevelemek, çerçeve içine almak",yz:3}, {tr:"f. (birini) suçlu göstermek, tuzağa düşürmek",yz:1}],
"free": [{tr:"s. özgür; ücretsiz; serbest",yz:4}, {tr:"f. serbest bırakmak, kurtarmak",yz:2}],
"freeze": [{tr:"f. donmak, dondurmak",yz:4}, {tr:"i. donma, dondurma",yz:2}],
"frequency": [{tr:"i. sıklık",yz:4}, {tr:"i. frekans",yz:2}],
"frequent": [{tr:"s. sık, sık sık olan",yz:4}, {tr:"f. sık sık gitmek, devam etmek",yz:1}],
"fresh": [{tr:"s. taze",yz:4}, {tr:"z. yeni yeni",yz:1}],
"front": [{tr:"i. ön taraf, cephe",yz:4}, {tr:"s. ön",yz:3}],
"fruit": [{tr:"i. meyve",yz:4}, {tr:"f. meyve vermek",yz:1}],
"fuel": [{tr:"f. körüklemek, beslemek",yz:4}, {tr:"i. yakıt",yz:3}],
"full": [{tr:"s. dolu, tam",yz:4}, {tr:"z. tamamen",yz:1}],
"fun": [{tr:"s. eğlenceli",yz:3}, {tr:"i. eğlence",yz:3}],
"functioning": [{tr:"i. işleyiş, çalışma",yz:3}, {tr:"s. çalışan, işler durumda",yz:3}],
"fund": [{tr:"f. finanse etmek, fon sağlamak",yz:4}, {tr:"i. fon, kaynak",yz:3}],
"fundamental": [{tr:"s. temel, esas",yz:4}, {tr:"i. temel ilke",yz:2}],
"further": [{tr:"f. ilerletmek, geliştirmek",yz:2}, {tr:"s./z. daha fazla, ek",yz:4}],
"game": [{tr:"i. oyun",yz:4}, {tr:"s. istekli, gönüllü",yz:1}],
"garden": [{tr:"i. bahçe",yz:4}, {tr:"f. bahçıvanlık yapmak",yz:1}],
"gas": [{tr:"i. gaz",yz:4}, {tr:"i. benzin",yz:2}],
"gather": [{tr:"f. toplamak",yz:4}, {tr:"f. bir araya gelmek, toplanmak",yz:3}],
"general": [{tr:"s. genel",yz:4}, {tr:"i. general (askeri rütbe)",yz:1}],
"giant": [{tr:"s. dev, kocaman",yz:4}, {tr:"i. dev",yz:2}],
"giving": [{tr:"i. verme, bağışta bulunma",yz:3}, {tr:"s. cömert, eli açık",yz:2}],
"glass": [{tr:"f. camla kaplamak",yz:1}, {tr:"i. cam, bardak",yz:4}],
"gold": [{tr:"i. altın",yz:4}, {tr:"s. altından yapılmış; altın rengi",yz:2}],
"gone": [{tr:"s. gitmiş, geçmiş; tükenmiş",yz:3}, {tr:"s. ölmüş, hayatını kaybetmiş",yz:2}],
"grade": [{tr:"i. not",yz:3}, {tr:"i. sınıf (okul kademesi)",yz:3}],
"graduate": [{tr:"f. mezun olmak",yz:4}, {tr:"s. lisansüstü",yz:3}],
"grant": [{tr:"i. hibe, burs",yz:3}, {tr:"f. vermek, bahşetmek; kabul etmek",yz:4}],
"grasp": [{tr:"i. kavrayış, hâkimiyet",yz:3}, {tr:"f. kavramak, anlamak; sıkıca tutmak",yz:4}],
"grass": [{tr:"i. çim, ot, çayır",yz:4}, {tr:"f. (hayvanı) otlatmak",yz:1}],
"gravity": [{tr:"i. yerçekimi",yz:4}, {tr:"i. ciddiyet, önem",yz:3}],
"green": [{tr:"s. çevreci, çevre dostu",yz:4}, {tr:"s. yeşil (renk)",yz:3}],
"greenhouse": [{tr:"s. sera etkisiyle ilgili",yz:4}, {tr:"i. sera",yz:2}],
"grind": [{tr:"f. öğütmek",yz:4}, {tr:"i. angarya",yz:1}],
"gross": [{tr:"s. brüt; kaba, iğrenç",yz:4}, {tr:"f. brüt hasılat elde etmek",yz:1}],
"ground": [{tr:"f. dayandırmak, temellendirmek",yz:2}, {tr:"i. zemin, yer; temel",yz:4}],
"grown": [{tr:"yetişkin, tam gelişmiş",yz:3}, {tr:"yetiştirilmiş",yz:3}],
"guarantee": [{tr:"f. garanti etmek, güvence vermek",yz:4}, {tr:"i. garanti, güvence",yz:3}],
"guard": [{tr:"f. korumak, nöbet tutmak",yz:3}, {tr:"i. koruma, nöbetçi, muhafız",yz:3}],
"guess": [{tr:"f. tahmin etmek",yz:3}, {tr:"i. tahmin",yz:2}],
"guide": [{tr:"i. rehber, kılavuz",yz:3}, {tr:"f. yol göstermek, rehberlik etmek",yz:4}],
"gut": [{tr:"i. bağırsak",yz:4}, {tr:"f. içini boşaltmak, tahrip etmek",yz:1}],
"hair": [{tr:"i. saç",yz:3}, {tr:"i. kıl, tüy",yz:3}],
"handle": [{tr:"f. ele almak, başa çıkmak",yz:4}, {tr:"i. sap, kulp, tutamaç",yz:1}],
"hands": [{tr:"i. eller",yz:4}, {tr:"i. işçiler, emek gücü",yz:1}],
"harm": [{tr:"f. zarar vermek",yz:4}, {tr:"i. zarar",yz:3}],
"harvest": [{tr:"i. hasat, ürün",yz:3}, {tr:"f. hasat etmek, toplamak",yz:3}],
"hawk": [{tr:"i. şahin, atmaca",yz:3}, {tr:"f. seyyar satıcılık yapmak, gezerek satmak",yz:1}],
"head": [{tr:"f. yönetmek, yönelmek",yz:3}, {tr:"i. baş, kafa, yönetici",yz:4}],
"hearing": [{tr:"i. işitme, duyma",yz:4}, {tr:"i. duruşma, oturum (mahkeme, komisyon)",yz:3}, {tr:"s. işiten, işitebilen",yz:1}],
"heat": [{tr:"i. ısı, sıcaklık",yz:4}, {tr:"f. ısıtmak",yz:2}],
"heavy": [{tr:"s. yoğun, şiddetli",yz:4}, {tr:"s. ağır",yz:3}],
"held": [{tr:"s. yaygın olarak kabul edilen (widely held)",yz:4}, {tr:"s. tutulan, sahip olunan",yz:2}],
"helpful": [{tr:"s. yararlı, faydalı",yz:4}, {tr:"s. yardımsever",yz:2}],
"here": [{tr:"z. burada, buraya",yz:4}, {tr:"i. burası",yz:1}],
"hide": [{tr:"f. saklamak, gizlemek",yz:4}, {tr:"i. hayvan derisi, post",yz:1}],
"highlight": [{tr:"f. vurgulamak, öne çıkarmak",yz:4}, {tr:"i. öne çıkan nokta, doruk",yz:2}],
"hill": [{tr:"i. tepe",yz:3}, {tr:"f. (toprağı) tepe şeklinde yığmak",yz:1}],
"hire": [{tr:"f. işe almak",yz:4}, {tr:"f. kiralamak (araç/ekipman)",yz:2}],
"hit": [{tr:"f. çarpmak, vurmak",yz:4}, {tr:"i. darbe, isabet",yz:2}],
"hole": [{tr:"i. delik, çukur",yz:4}, {tr:"i. kusur, açık (mecazi)",yz:2}],
"holiday": [{tr:"i. tatil",yz:3}, {tr:"i. bayram, resmî tatil günü",yz:2}, {tr:"f. tatil yapmak, tatile gitmek",yz:1}],
"honest": [{tr:"s. dürüst",yz:4}, {tr:"s. hakiki, gerçek",yz:2}],
"hope": [{tr:"f. ummak",yz:3}, {tr:"i. umut",yz:3}],
"host": [{tr:"f. ev sahipliği yapmak, barındırmak",yz:4}, {tr:"i. ev sahibi",yz:3}],
"hot": [{tr:"s. sıcak",yz:4}, {tr:"s. taze, yeni (haber vb.)",yz:1}],
"house": [{tr:"f. barındırmak",yz:3}, {tr:"i. ev, konut",yz:4}],
"humanity": [{tr:"i. insanlık",yz:4}, {tr:"i. şefkat, insaniyet",yz:2}],
"hunt": [{tr:"f. avlamak, avlanmak",yz:4}, {tr:"f. aramak, peşinde olmak",yz:2}],
"hurt": [{tr:"f. incitmek, acıtmak, zarar vermek",yz:4}, {tr:"s. yaralı, incinmiş",yz:2}],
"ice": [{tr:"i. buz",yz:4}, {tr:"f. buzla kaplamak, donmak",yz:1}],
"ideal": [{tr:"s. ideal, mükemmel",yz:4}, {tr:"i. ülkü, ideal",yz:3}],
"identification": [{tr:"i. tanımlama, teşhis",yz:4}, {tr:"i. kimlik (belgesi)",yz:2}],
"ill": [{tr:"s. kötü, zararlı",yz:3}, {tr:"s. hasta",yz:4}],
"illusion": [{tr:"i. yanılsama, illüzyon",yz:4}, {tr:"i. kuruntu, boş inanç",yz:2}],
"immune": [{tr:"s. bağışık, muaf",yz:4}, {tr:"i. bağışıklık kazanmış kimse",yz:1}],
"implement": [{tr:"f. uygulamak, yürürlüğe koymak",yz:4}, {tr:"i. alet, araç",yz:1}],
"implication": [{tr:"i. sonuç, etki",yz:4}, {tr:"i. ima, sezdirme",yz:3}],
"impression": [{tr:"i. izlenim",yz:4}, {tr:"i. baskı, iz",yz:1}],
"incline": [{tr:"f. (yol vb.) eğim kazanmak, yükselmeye başlamak",yz:2}, {tr:"f. (incline to) -e eğilimli olmak, meyletmek",yz:4}],
"incorporate": [{tr:"f. dahil etmek, birleştirmek",yz:4}, {tr:"s. birleşmiş, tüzel",yz:1}],
"independent": [{tr:"s. bağımsız",yz:4}, {tr:"i. bağımsız (kişi), bağımsız aday",yz:1}],
"index": [{tr:"i. dizin, indeks, gösterge",yz:4}, {tr:"f. dizinlemek, endekslemek",yz:1}],
"inevitable": [{tr:"s. kaçınılmaz",yz:4}, {tr:"i. kaçınılmaz olay/durum",yz:1}],
"initial": [{tr:"s. ilk, başlangıç",yz:4}, {tr:"i. baş harf",yz:1}],
"initiate": [{tr:"f. başlatmak",yz:4}, {tr:"i. yeni üye, acemi",yz:1}],
"inject": [{tr:"f. enjekte etmek, iğne yapmak",yz:4}, {tr:"f. katmak, aşılamak",yz:3}],
"injure": [{tr:"f. yaralamak",yz:4}, {tr:"f. (gururunu/duygularını) incitmek, gücendirmek",yz:2}],
"innocent": [{tr:"s. masum, suçsuz; saf",yz:4}, {tr:"i. masum kişi",yz:1}],
"input": [{tr:"i. girdi",yz:3}, {tr:"i. katkı, görüş",yz:2}],
"insert": [{tr:"f. eklemek, yerleştirmek",yz:3}, {tr:"i. ek, ilave sayfa (broşür/dergi eki)",yz:1}],
"inside": [{tr:"z. içeride, içeriye",yz:4}, {tr:"s. iç, dahili",yz:2}],
"inspired": [{tr:"s. ilhamla yaratılmış, ilham alınarak yapılmış",yz:4}, {tr:"s. parlak, dâhiyane (çok yaratıcı)",yz:1}],
"institute": [{tr:"f. kurmak, başlatmak, yürürlüğe koymak",yz:3}, {tr:"i. enstitü",yz:4}],
"instruction": [{tr:"i. talimat, yönerge",yz:3}, {tr:"i. öğretim, eğitim",yz:4}],
"instrument": [{tr:"i. alet, araç",yz:4}, {tr:"çalgı",yz:2}],
"intake": [{tr:"i. alım, tüketim",yz:4}, {tr:"i. giriş, giriş ağzı",yz:1}],
"integral": [{tr:"s. ayrılmaz, temel; bütünleyici",yz:4}, {tr:"i. integral",yz:1}],
"intellectual": [{tr:"s. entelektüel, zihinsel, akli",yz:4}, {tr:"i. aydın, entelektüel",yz:2}],
"interior": [{tr:"i. iç kısım, iç mekân",yz:3}, {tr:"s. iç, dahili",yz:3}],
"intermediate": [{tr:"s. orta düzey, ara",yz:4}, {tr:"i. ara aşama, ara ürün",yz:1}],
"interpretation": [{tr:"i. yorum, yorumlama",yz:4}, {tr:"i. sözlü çeviri",yz:1}],
"interview": [{tr:"i. görüşme, mülakat, röportaj",yz:4}, {tr:"f. görüşme yapmak",yz:3}],
"introduce": [{tr:"f. başlatmak, yürürlüğe koymak",yz:4}, {tr:"f. tanıtmak, sunmak",yz:3}],
"introduction": [{tr:"i. (bir şeyi) yürürlüğe koyma, uygulamaya sokma",yz:4}, {tr:"i. giriş (kitap/konuşma başlangıcı)",yz:3}],
"invent": [{tr:"f. icat etmek, bulmak",yz:4}, {tr:"f. uydurmak",yz:2}],
"involved": [{tr:"s. dahil olan, ilgili",yz:4}, {tr:"s. karmaşık",yz:2}],
"iron": [{tr:"i. demir",yz:4}, {tr:"i. ütü; f. ütülemek",yz:1}],
"japan": [{tr:"f. bu cilayla kaplamak, cilalamak",yz:2}, {tr:"i. sert siyah cila (Japon cilası)",yz:3}],
"join": [{tr:"f. katılmak",yz:4}, {tr:"f. birleştirmek, bitiştirmek",yz:2}],
"joint": [{tr:"s. ortak, müşterek",yz:4}, {tr:"i. eklem",yz:2}],
"journal": [{tr:"i. dergi (akademik)",yz:4}, {tr:"i. günlük",yz:2}],
"journey": [{tr:"i. yolculuk",yz:4}, {tr:"f. yolculuk etmek",yz:1}],
"judge": [{tr:"f. yargılamak, değerlendirmek",yz:4}, {tr:"i. yargıç, hakem",yz:3}],
"jump": [{tr:"i. sıçrama, atlama; ani artış",yz:3}, {tr:"f. atlamak, sıçramak",yz:3}],
"justice": [{tr:"i. adalet",yz:4}, {tr:"i. yargıç",yz:2}],
"keeping": [{tr:"i. uyum (in keeping with)",yz:3}, {tr:"i. koruma, muhafaza, saklama",yz:2}],
"kept": [{tr:"s. tutulmuş, yerine getirilmiş",yz:3}, {tr:"s. korunmuş, muhafaza edilmiş",yz:2}],
"key": [{tr:"s. kilit, çok önemli",yz:4}, {tr:"i. anahtar",yz:2}],
"kid": [{tr:"i. çocuk",yz:3}, {tr:"f. şaka yapmak, takılmak",yz:1}],
"kingdom": [{tr:"i. (biyoloji) âlem",yz:2}, {tr:"i. krallık",yz:4}],
"knowing": [{tr:"i. bilme, farkındalık",yz:3}, {tr:"s. bilgili, bilinçli, anlamlı",yz:2}],
"label": [{tr:"f. etiketlemek, nitelendirmek",yz:3}, {tr:"i. etiket",yz:3}],
"labour": [{tr:"i. emek, iş gücü",yz:4}, {tr:"i. doğum, doğum sancısı",yz:1}],
"landscape": [{tr:"i. manzara, peyzaj",yz:4}, {tr:"f. peyzaj düzenlemesi yapmak",yz:1}],
"later": [{tr:"z. daha sonra",yz:4}, {tr:"s. sonraki",yz:3}],
"laugh": [{tr:"f. gülmek",yz:3}, {tr:"i. gülüş, kahkaha",yz:2}],
"launch": [{tr:"f. fırlatmak, başlatmak",yz:4}, {tr:"i. fırlatma, lansman",yz:3}],
"law": [{tr:"i. hukuk",yz:3}, {tr:"i. kanun, yasa",yz:4}],
"lay": [{tr:"f. yumurtlamak",yz:2}, {tr:"f. koymak, sermek, döşemek",yz:3}],
"layer": [{tr:"i. katman, tabaka",yz:4}, {tr:"f. katman katman düzenlemek",yz:1}],
"leaf": [{tr:"i. yaprak",yz:3}, {tr:"f. (leaf through) sayfaları çevirmek, göz gezdirmek",yz:1}],
"learned": [{tr:"s. bilgili, tahsilli",yz:2}, {tr:"s. öğrenilmiş",yz:4}],
"leather": [{tr:"i. (işlenmiş) deri",yz:4}, {tr:"s. deriden yapılma",yz:2}],
"lecture": [{tr:"i. ders, konferans",yz:4}, {tr:"f. azarlamak, azar vermek",yz:1}],
"leg": [{tr:"i. (yolculuk/yarış) etap",yz:2}, {tr:"i. bacak",yz:3}],
"legend": [{tr:"i. efsane",yz:4}, {tr:"i. (harita/şekil) açıklama notu, lejant",yz:1}],
"legitimate": [{tr:"s. meşru, yasal; geçerli",yz:4}, {tr:"f. meşrulaştırmak, haklı çıkarmak",yz:1}],
"length": [{tr:"i. uzunluk",yz:4}, {tr:"i. süre",yz:2}],
"lens": [{tr:"i. mercek, lens",yz:4}, {tr:"i. (mecaz) bakış açısı, pencere",yz:3}],
"let": [{tr:"f. izin vermek, bırakmak",yz:4}, {tr:"i. kiralık (mülk)",yz:1}],
"letter": [{tr:"i. mektup",yz:4}, {tr:"i. harf",yz:3}],
"letters": [{tr:"i. mektuplar",yz:3}, {tr:"i. harfler (alfabe)",yz:3}],
"liable": [{tr:"s. sorumlu, yükümlü (hukuken)",yz:3}, {tr:"s. (liable to) -e eğilimli, -me olasılığı yüksek",yz:3}],
"liberal": [{tr:"s. özgürlükçü, liberal",yz:4}, {tr:"s. bol, cömertçe verilen",yz:2}],
"lift": [{tr:"f. kaldırmak, yükseltmek",yz:4}, {tr:"i. asansör",yz:2}],
"limb": [{tr:"i. uzuv (kol, bacak)",yz:4}, {tr:"i. büyük ağaç dalı",yz:1}],
"limitation": [{tr:"i. sınırlama, kısıtlama",yz:4}, {tr:"i. eksiklik, kusur",yz:3}],
"line": [{tr:"i. çizgi, hat, sınır",yz:4}, {tr:"i. sıra, kuyruk",yz:2}],
"liquid": [{tr:"i. sıvı",yz:3}, {tr:"s. sıvı, akışkan",yz:3}],
"list": [{tr:"i. liste",yz:3}, {tr:"f. listelemek, sıralamak",yz:2}],
"load": [{tr:"f. yüklemek",yz:3}, {tr:"i. yük, taşınan ağırlık",yz:3}],
"loan": [{tr:"i. kredi, borç",yz:4}, {tr:"f. ödünç vermek",yz:2}],
"local": [{tr:"s. yerel",yz:4}, {tr:"i. yerel sakin",yz:2}],
"log": [{tr:"f. kaydetmek",yz:3}, {tr:"i. kütük, seyir defteri",yz:2}],
"longer": [{tr:"z. daha uzun süre",yz:4}, {tr:"s. daha uzun",yz:3}],
"looking": [{tr:"i. bakış, arama",yz:1}, {tr:"s. (bileşik) ...görünümlü",yz:3}],
"lots": [{tr:"i. çok miktar",yz:3}, {tr:"z. çok, epeyce (gayriresmî)",yz:1}],
"loud": [{tr:"s. yüksek sesli, gürültülü",yz:4}, {tr:"z. yüksek sesle",yz:2}],
"love": [{tr:"i. sevgi, aşk",yz:3}, {tr:"f. sevmek, çok hoşlanmak",yz:3}],
"lower": [{tr:"f. düşürmek, azaltmak",yz:4}, {tr:"s. daha düşük, alt",yz:3}],
"lunch": [{tr:"i. öğle yemeği",yz:3}, {tr:"f. öğle yemeği yemek",yz:1}],
"lying": [{tr:"i. yalan söyleme",yz:3}, {tr:"s. yatan, uzanan",yz:2}],
"machine": [{tr:"i. makine",yz:4}, {tr:"f. makineyle işlemek",yz:1}],
"made-up": [{tr:"s. uydurma, hayali",yz:3}, {tr:"s. (yol için) kaplanmış, döşenmiş, asfaltlanmış",yz:1}],
"magnetic": [{tr:"s. manyetik",yz:4}, {tr:"s. çekici, cazibeli",yz:1}],
"make-up": [{tr:"i. yapı, bileşim",yz:3}, {tr:"i. makyaj",yz:2}],
"male": [{tr:"s. erkek",yz:4}, {tr:"i. erkek (birey)",yz:3}],
"manage": [{tr:"f. üstesinden gelmek, kontrol altında tutmak",yz:4}, {tr:"f. yönetmek, idare etmek",yz:3}],
"manipulate": [{tr:"f. manipüle etmek",yz:4}, {tr:"f. ustaca kullanmak, elle işlemek",yz:2}],
"manipulation": [{tr:"i. manipülasyon",yz:4}, {tr:"i. (elle) işleme, kullanma",yz:2}],
"manner": [{tr:"i. tarz, biçim, yol",yz:4}, {tr:"i. tavır, hâl, davranış biçimi",yz:3}],
"manual": [{tr:"i. kılavuz, el kitabı",yz:2}, {tr:"s. elle yapılan",yz:3}],
"manufacture": [{tr:"f. üretmek, imal etmek",yz:4}, {tr:"i. üretim, imalat",yz:3}],
"manuscript": [{tr:"i. el yazması",yz:4}, {tr:"(yayımlanmamış) yazı, makale metni",yz:2}],
"map": [{tr:"f. haritalamak, haritasını çıkarmak",yz:3}, {tr:"i. harita",yz:4}],
"march": [{tr:"f. yürümek, yürüyüş yapmak",yz:3}, {tr:"i. yürüyüş",yz:3}],
"margin": [{tr:"i. fark, pay",yz:4}, {tr:"i. kenar, kenar boşluğu",yz:2}],
"marine": [{tr:"s. denizel, denizle ilgili",yz:4}, {tr:"i. deniz piyadesi (asker)",yz:1}],
"mark": [{tr:"f. işaretlemek",yz:4}, {tr:"i. not, puan",yz:2}],
"market": [{tr:"f. pazarlamak",yz:2}, {tr:"i. pazar, piyasa",yz:4}],
"mass": [{tr:"i. kütle",yz:3}, {tr:"s. kitlesel",yz:4}],
"master": [{tr:"f. iyice öğrenmek, ustalaşmak",yz:4}, {tr:"i. usta",yz:3}],
"match": [{tr:"i. eşleşme, eş",yz:3}, {tr:"i. maç (spor karşılaşması)",yz:2}],
"mate": [{tr:"i. eş, çift (hayvanlarda)",yz:4}, {tr:"i. arkadaş (BrE)",yz:1}],
"mathematical": [{tr:"s. matematiksel",yz:4}, {tr:"s. kesin, şüphe götürmez",yz:1}],
"mature": [{tr:"s. olgun, yetişkin",yz:4}, {tr:"f. olgunlaşmak",yz:3}],
"maximum": [{tr:"s. azami, en yüksek",yz:4}, {tr:"i. en yüksek miktar",yz:3}],
"meaning": [{tr:"i. anlam",yz:4}, {tr:"s. anlamlı, çok şey ifade eden",yz:2}],
"measured": [{tr:"s. ölçülü, temkinli",yz:3}, {tr:"s. ölçülmüş",yz:2}],
"mechanic": [{tr:"i. tamirci, makinist",yz:3}, {tr:"s. mekanik, makinelerle ilgili",yz:2}],
"mediate": [{tr:"f. arabuluculuk yapmak, aracılık etmek",yz:4}, {tr:"s. dolaylı",yz:1}],
"meet": [{tr:"f. karşılamak",yz:4}, {tr:"f. buluşmak, tanışmak",yz:2}],
"meeting": [{tr:"i. toplantı",yz:4}, {tr:"i. buluşma, rastlaşma",yz:2}],
"melt": [{tr:"f. erimek",yz:4}, {tr:"i. erime",yz:2}],
"memory": [{tr:"i. hafıza, bellek",yz:4}, {tr:"i. anı",yz:2}],
"mention": [{tr:"f. bahsetmek, değinmek",yz:4}, {tr:"i. söz, atıf",yz:2}],
"mentor": [{tr:"i. akıl hocası, rehber",yz:3}, {tr:"f. rehberlik etmek, akıl hocalığı yapmak",yz:2}],
"message": [{tr:"i. mesaj, ileti",yz:4}, {tr:"f. mesaj göndermek",yz:1}],
"metal": [{tr:"i. metal, maden",yz:4}, {tr:"s. metalden yapılmış",yz:2}],
"metre": [{tr:"i. metre (uzunluk birimi)",yz:4}, {tr:"i. (şiir) vezin, ölçü",yz:1}],
"middle": [{tr:"i./s. orta",yz:4}, {tr:"f. ortalamak",yz:1}],
"military": [{tr:"s. askeri",yz:4}, {tr:"i. ordu, askeri güç",yz:3}],
"milk": [{tr:"f. sağmak",yz:2}, {tr:"i. süt",yz:4}],
"mine": [{tr:"f. maden çıkarmak",yz:2}, {tr:"i. maden (ocağı)",yz:3}],
"mineral": [{tr:"i. mineral, maden",yz:4}, {tr:"s. madensel",yz:2}],
"minimize": [{tr:"f. en aza indirmek",yz:4}, {tr:"f. küçümsemek, önemsizleştirmek",yz:2}],
"minimum": [{tr:"s. asgari, en az",yz:4}, {tr:"i. asgari düzey, en az miktar",yz:3}],
"minor": [{tr:"s. küçük, önemsiz",yz:4}, {tr:"i. reşit olmayan kişi",yz:1}],
"minute": [{tr:"s. çok küçük, ayrıntılı",yz:4}, {tr:"i. dakika",yz:2}],
"minutes": [{tr:"i. (toplantı) tutanak, zabıt",yz:4}, {tr:"i. dakikalar (zaman birimi)",yz:3}],
"mission": [{tr:"i. görev, misyon",yz:4}, {tr:"i. heyet",yz:1}],
"mistake": [{tr:"f. yanlış anlamak, karıştırmak",yz:2}, {tr:"i. hata, yanlış",yz:4}],
"mix": [{tr:"f. karıştırmak, karışmak",yz:3}, {tr:"i. karışım",yz:3}],
"mobile": [{tr:"s. hareketli, taşınabilir, gezici",yz:4}, {tr:"i. cep telefonu",yz:2}],
"mobility": [{tr:"i. hareketlilik, hareket kabiliyeti",yz:3}, {tr:"i. (toplumsal) hareketlilik",yz:4}],
"mode": [{tr:"i. tarz, biçim, yöntem",yz:4}, {tr:"i. mod (istatistikte en sık görülen değer)",yz:1}],
"moderate": [{tr:"s. ılımlı, orta düzeyde",yz:4}, {tr:"f. yönetmek, başkanlık etmek",yz:2}],
"monitor": [{tr:"f. izlemek, denetlemek",yz:4}, {tr:"i. ekran, monitör",yz:1}],
"monkey": [{tr:"i. maymun",yz:3}, {tr:"f. kurcalamak",yz:1}],
"moon": [{tr:"i. ay, uydu",yz:4}, {tr:"f. aylak aylak dolaşmak",yz:1}],
"moral": [{tr:"s. ahlaki",yz:4}, {tr:"i. kıssadan hisse, ahlaki ders",yz:1}],
"mother": [{tr:"i. anne",yz:4}, {tr:"f. annelik etmek, kollayıp gözetmek",yz:1}],
"motion": [{tr:"i. hareket, devinim",yz:4}, {tr:"i. önerge",yz:2}],
"motive": [{tr:"i. güdü, saik, dürtü",yz:4}, {tr:"s. harekete geçirici",yz:1}],
"motor": [{tr:"i. motor",yz:3}, {tr:"s. motorlu; hareket ettiren",yz:3}, {tr:"f. arabayla gitmek",yz:1}],
"mount": [{tr:"f. artmak, yükselmek",yz:4}, {tr:"f. binmek",yz:1}],
"mountain": [{tr:"i. dağ",yz:4}, {tr:"i. (mec.) yığın",yz:1}],
"mouse": [{tr:"i. fare",yz:3}, {tr:"f. fare avlamak",yz:1}],
"mouth": [{tr:"i. ağız",yz:4}, {tr:"nehir ağzı",yz:1}],
"moving": [{tr:"s. hareket eden, hareketli",yz:3}, {tr:"s. dokunaklı",yz:3}],
"multiple": [{tr:"s. çoklu, birden fazla",yz:4}, {tr:"i. kat, misli",yz:1}],
"muscle": [{tr:"i. kas",yz:4}, {tr:"f. zorla ilerlemek",yz:1}],
"musical": [{tr:"s. müzikal, müzikle ilgili",yz:4}, {tr:"i. müzikal (sahne oyunu)",yz:2}],
"naked": [{tr:"s. çıplak",yz:4}, {tr:"s. (mecazi) yalın, katıksız",yz:1}],
"name": [{tr:"f. adlandırmak, atamak",yz:3}, {tr:"i. isim, ad",yz:4}],
"names": [{tr:"i. isimler, adlar",yz:4}, {tr:"i. hakaret sözleri (call sb names deyiminde)",yz:1}],
"narrative": [{tr:"i. anlatı, öykü",yz:4}, {tr:"s. anlatısal, öyküleyici",yz:2}],
"nasty": [{tr:"s. kötü, iğrenç, nahoş",yz:3}, {tr:"s. huysuz",yz:2}],
"nation": [{tr:"i. ülke, devlet",yz:4}, {tr:"i. ulus, millet",yz:3}],
"native": [{tr:"s. yerli, doğuştan",yz:4}, {tr:"i. yerli (kişi)",yz:2}],
"naturally": [{tr:"z. doğal olarak",yz:4}, {tr:"z. tabii ki",yz:2}],
"near": [{tr:"e. yakınında",yz:4}, {tr:"f. yaklaşmak",yz:2}],
"nearby": [{tr:"s. yakındaki",yz:3}, {tr:"z. yakında, civarda",yz:3}],
"neglect": [{tr:"i. ihmal",yz:3}, {tr:"f. ihmal etmek",yz:4}],
"neighbour": [{tr:"i. komşu",yz:4}, {tr:"f. bitişik olmak, sınırı olmak",yz:1}],
"nerve": [{tr:"i. sinir",yz:4}, {tr:"i. cesaret",yz:1}],
"nervous": [{tr:"gergin, endişeli",yz:3}, {tr:"sinirsel",yz:4}],
"nest": [{tr:"i. yuva",yz:3}, {tr:"f. yuva yapmak",yz:2}],
"network": [{tr:"i. ağ, şebeke",yz:4}, {tr:"f. bağlantı kurmak",yz:1}],
"neutral": [{tr:"s. tarafsız",yz:4}, {tr:"s. nötr",yz:2}],
"nice": [{tr:"s. (ayrım için) ince, hassas",yz:3}, {tr:"s. hoş, güzel, nazik",yz:2}],
"nobody": [{tr:"i. hiç kimse",yz:4}, {tr:"i. önemsiz kişi, değersiz biri",yz:1}],
"noise": [{tr:"i. gürültü, ses",yz:4}, {tr:"f. (noise about/abroad) yaymak, ortalığa duyurmak",yz:1}],
"normal": [{tr:"s. normal, olağan",yz:4}, {tr:"i. norm, ortalama",yz:2}],
"north": [{tr:"z. kuzeye",yz:3}, {tr:"i. kuzey",yz:4}],
"note": [{tr:"f. not etmek, belirtmek, dikkat çekmek",yz:4}, {tr:"i. not",yz:2}],
"notice": [{tr:"i. bildiri, ihbar, duyuru",yz:2}, {tr:"f. fark etmek",yz:4}],
"novel": [{tr:"s. yeni, özgün",yz:4}, {tr:"i. roman",yz:3}],
"nutrient": [{tr:"i. besin öğesi",yz:4}, {tr:"s. besleyici",yz:2}],
"object": [{tr:"f. itiraz etmek",yz:3}, {tr:"i. nesne, obje, amaç",yz:4}],
"objective": [{tr:"s. nesnel, tarafsız",yz:4}, {tr:"i. amaç, hedef",yz:3}],
"obscure": [{tr:"f. gizlemek, gölgelemek, örtmek",yz:3}, {tr:"s. belirsiz, az bilinen",yz:4}],
"observe": [{tr:"f. gözlemlemek",yz:4}, {tr:"f. belirtmek, söylemek",yz:2}],
"occasion": [{tr:"i. vesile, fırsat; özel gün",yz:4}, {tr:"f. -e yol açmak, sebep olmak",yz:1}],
"occupation": [{tr:"i. meslek, iş",yz:3}, {tr:"i. işgal",yz:3}],
"occupy": [{tr:"f. işgal etmek",yz:3}, {tr:"f. kaplamak, meşgul etmek",yz:4}],
"odd": [{tr:"s. tuhaf, garip",yz:4}, {tr:"s. tek (sayı)",yz:1}],
"offering": [{tr:"i. sunulan şey, ürün",yz:3}, {tr:"i. adak, kurban",yz:2}],
"office": [{tr:"ofis, büro",yz:3}, {tr:"makam, görev",yz:3}],
"officer": [{tr:"i. memur, görevli",yz:4}, {tr:"i. subay",yz:2}],
"official": [{tr:"i. yetkili, görevli",yz:3}, {tr:"s. resmi",yz:4}],
"oil": [{tr:"f. yağlamak",yz:1}, {tr:"i. petrol, yağ",yz:4}],
"online": [{tr:"s. çevrimiçi",yz:3}, {tr:"z. çevrimiçi olarak",yz:3}],
"open": [{tr:"f. açmak, açılmak",yz:4}, {tr:"s. açık",yz:3}],
"operate": [{tr:"çalışmak, işletmek",yz:4}, {tr:"ameliyat etmek",yz:2}],
"operation": [{tr:"i. operasyon",yz:4}, {tr:"i. ameliyat",yz:3}],
"opposite": [{tr:"s. karşı, zıt",yz:4}, {tr:"i. karşıt, zıt şey",yz:3}],
"oral": [{tr:"s. sözlü, ağızdan",yz:4}, {tr:"i. sözlü sınav",yz:1}],
"organ": [{tr:"i. organ (vücut)",yz:4}, {tr:"i. org (müzik aleti)",yz:1}],
"organic": [{tr:"s. organik",yz:4}, {tr:"i. organik ürün",yz:1}],
"organisation": [{tr:"i. örgüt, kuruluş",yz:4}, {tr:"i. düzen, tertip, organizasyon",yz:2}],
"organization": [{tr:"i. örgüt, kuruluş, organizasyon",yz:4}, {tr:"i. düzenleme",yz:3}],
"organize": [{tr:"f. düzenlemek, organize etmek",yz:4}, {tr:"f. örgütlemek (işçileri/bir hareketi bir araya getirmek)",yz:2}],
"organs": [{tr:"i. organ(lar)",yz:4}, {tr:"(müzik) org",yz:1}],
"orient": [{tr:"f. yönlendirmek, alıştırmak",yz:3}, {tr:"i. (the Orient) Doğu",yz:1}],
"orientation": [{tr:"i. uyum eğitimi, tanıtım programı",yz:2}, {tr:"i. yönelim",yz:4}],
"original": [{tr:"s. özgün, orijinal",yz:4}, {tr:"i. asıl nüsha, orijinal",yz:2}],
"otherwise": [{tr:"z. aksi takdirde, başka türlü",yz:4}, {tr:"s. farklı",yz:2}],
"output": [{tr:"i. çıktı, üretim",yz:4}, {tr:"f. üretmek, çıktı vermek",yz:1}],
"outside": [{tr:"z./e. dışarıda, dışında",yz:4}, {tr:"i. dış taraf",yz:2}],
"overall": [{tr:"s. genel, toplam",yz:4}, {tr:"i. tulum (giysi)",yz:1}],
"overlap": [{tr:"i. çakışma, örtüşme",yz:3}, {tr:"f. çakışmak, örtüşmek",yz:3}],
"owing": [{tr:"(owing to) -den dolayı, nedeniyle",yz:4}, {tr:"s. borçlu, ödenmemiş",yz:1}],
"pace": [{tr:"i. hız, tempo",yz:4}, {tr:"f. adımlamak, volta atmak",yz:1}],
"package": [{tr:"i. paket",yz:4}, {tr:"f. paketlemek",yz:2}],
"pain": [{tr:"i. ağrı, acı",yz:4}, {tr:"f. acı vermek",yz:1}],
"paint": [{tr:"i. boya",yz:2}, {tr:"f. boyamak, resim yapmak",yz:3}],
"pair": [{tr:"i. çift, iki taneden oluşan takım",yz:4}, {tr:"f. eşleştirmek",yz:2}],
"panel": [{tr:"i. panel, kurul",yz:4}, {tr:"f. panele seçmek/atamak",yz:1}],
"paper": [{tr:"i. makale, bildiri",yz:4}, {tr:"i. kağıt",yz:2}],
"papers": [{tr:"i. (bilimsel) makale",yz:4}, {tr:"i. evrak, belgeler, kimlik kağıtları",yz:2}],
"par": [{tr:"i. eşit düzey, ortalama",yz:3}, {tr:"i. par (golf)",yz:1}],
"parallel": [{tr:"s. paralel, koşut",yz:4}, {tr:"i. benzerlik, koşutluk",yz:3}, {tr:"f. benzemek, koşut olmak",yz:2}],
"park": [{tr:"i. park",yz:3}, {tr:"f. park etmek",yz:2}],
"partial": [{tr:"s. kısmi",yz:4}, {tr:"s. taraflı, önyargılı",yz:2}],
"partner": [{tr:"f. iş birliği yapmak",yz:2}, {tr:"i. ortak, eş",yz:4}],
"parts": [{tr:"i. yöreler, bölgeler",yz:3}, {tr:"i. parçalar, kısımlar",yz:4}],
"party": [{tr:"i. parti",yz:4}, {tr:"f. eğlenmek",yz:1}],
"pass": [{tr:"f. (yasa) çıkarmak",yz:3}, {tr:"f. geçmek (zaman, mekân)",yz:4}],
"path": [{tr:"i. yol, izlenecek yol",yz:4}, {tr:"i. patika, keçi yolu",yz:2}],
"patient": [{tr:"i. hasta",yz:4}, {tr:"s. sabırlı",yz:2}],
"pattern": [{tr:"i. örüntü, desen",yz:4}, {tr:"f. desenlendirmek",yz:1}],
"peak": [{tr:"i. zirve, doruk",yz:4}, {tr:"f. zirveye ulaşmak, doruğa çıkmak",yz:3}],
"peer": [{tr:"i. akran, eş",yz:4}, {tr:"f. dikkatle bakmak, gözünü dikmek",yz:2}],
"pen": [{tr:"f. yazmak, kaleme almak",yz:2}, {tr:"i. kalem",yz:3}],
"penalty": [{tr:"i. ceza, yaptırım",yz:4}, {tr:"i. penaltı (futbolda)",yz:1}],
"perfect": [{tr:"f. mükemmelleştirmek",yz:2}, {tr:"s. mükemmel, kusursuz",yz:4}],
"permanent": [{tr:"s. kalıcı, daimi",yz:4}, {tr:"i. perma",yz:1}],
"personality": [{tr:"i. kişilik",yz:4}, {tr:"i. ünlü kişi (medya)",yz:1}],
"pest": [{tr:"i. haşere, zararlı böcek",yz:4}, {tr:"(mecazi) baş belası",yz:1}],
"phase": [{tr:"i. evre, aşama, safha",yz:4}, {tr:"f. aşamalı olarak uygulamak",yz:1}],
"phone": [{tr:"i. telefon",yz:4}, {tr:"f. telefon etmek, aramak",yz:2}],
"photograph": [{tr:"i. fotoğraf",yz:4}, {tr:"f. fotoğrafını çekmek",yz:2}],
"pick": [{tr:"f. toplamak, koparmak",yz:2}, {tr:"f. seçmek",yz:4}],
"picture": [{tr:"f. tasavvur etmek, gözünde canlandırmak",yz:2}, {tr:"i. resim, fotoğraf",yz:4}],
"plane": [{tr:"i. uçak",yz:3}, {tr:"i. düzlem",yz:2}],
"plastic": [{tr:"i. plastik",yz:4}, {tr:"s. biçimlendirilebilir, esnek",yz:1}],
"plate": [{tr:"i. levha, plaka",yz:4}, {tr:"i. tabak",yz:2}],
"platform": [{tr:"i. platform",yz:4}, {tr:"i. peron",yz:2}],
"player": [{tr:"i. (mecazi) önemli aktör, taraf",yz:4}, {tr:"i. oyuncu",yz:2}],
"playing": [{tr:"i. çalma (müzik)",yz:2}, {tr:"i. oynama",yz:3}],
"please": [{tr:"f. memnun etmek, hoşnut etmek",yz:3}, {tr:"z. lütfen",yz:2}],
"pleasure": [{tr:"i. zevk, memnuniyet",yz:4}, {tr:"i. istek, arzu",yz:1}],
"plenty": [{tr:"i. bolluk, çokluk",yz:4}, {tr:"z. epey, oldukça",yz:1}],
"plot": [{tr:"i. olay örgüsü",yz:3}, {tr:"i. arsa, arazi parçası",yz:2}],
"plus": [{tr:"bağ. ayrıca, -e ek olarak",yz:3}, {tr:"i. artı, avantaj",yz:2}],
"pointed": [{tr:"s. belirgin, alaycı (mecazi)",yz:3}, {tr:"s. sivri",yz:2}],
"polar": [{tr:"s. kutupsal, kutba ait",yz:4}, {tr:"s. (polar opposite) tamamen zıt, taban tabana zıt",yz:2}],
"pole": [{tr:"i. kutup",yz:4}, {tr:"i. direk, sırık",yz:2}],
"pop": [{tr:"f. patlamak, pat diye ses çıkarmak",yz:2}, {tr:"s. (pop music/culture) popüler",yz:3}],
"portray": [{tr:"f. tasvir etmek, betimlemek",yz:4}, {tr:"f. canlandırmak",yz:2}],
"pose": [{tr:"f. oluşturmak, teşkil etmek",yz:4}, {tr:"i. duruş, poz",yz:1}],
"position": [{tr:"i. konum, pozisyon",yz:4}, {tr:"i. görev, makam",yz:3}],
"positively": [{tr:"z. olumlu biçimde",yz:4}, {tr:"z. kesinlikle, gerçekten (vurgu için)",yz:1}],
"possession": [{tr:"i. (çoğul) eşya, mal, eşyalar",yz:3}, {tr:"i. sahiplik, mülkiyet, zilyetlik",yz:3}],
"post": [{tr:"f. asmak, ilan etmek, göndermek",yz:3}, {tr:"i. direk, kazık",yz:1}],
"pot": [{tr:"i. tencere, çömlek",yz:3}, {tr:"i. saksı",yz:2}],
"powder": [{tr:"i. toz, pudra",yz:3}, {tr:"f. toz haline getirmek",yz:1}],
"practise": [{tr:"f. uygulamak, alıştırma yapmak",yz:4}, {tr:"f. icra etmek",yz:2}],
"praise": [{tr:"f. övmek",yz:4}, {tr:"i. övgü",yz:3}],
"prejudice": [{tr:"i. ön yargı",yz:4}, {tr:"f. zarar vermek",yz:1}],
"preliminary": [{tr:"s. ön, hazırlık niteliğinde",yz:4}, {tr:"i. ön hazırlık, ön aşama",yz:1}],
"presence": [{tr:"i. varlık, mevcudiyet",yz:4}, {tr:"i. huzur (birinin huzurunda)",yz:1}],
"preserve": [{tr:"f. korumak, muhafaza etmek",yz:4}, {tr:"i. koruma alanı",yz:2}],
"pretty": [{tr:"z. oldukça, epey",yz:3}, {tr:"s. güzel, hoş",yz:1}],
"prey": [{tr:"i. av, kurban",yz:4}, {tr:"f. avlamak, yem etmek",yz:2}],
"price": [{tr:"i. fiyat, bedel",yz:4}, {tr:"f. fiyatlandırmak, fiyat koymak",yz:1}],
"pride": [{tr:"f. (pride oneself on) gurur duymak, övünmek",yz:3}, {tr:"i. gurur, onur",yz:4}],
"prime": [{tr:"s. asal (sayı için)",yz:2}, {tr:"s. baş, birincil, asıl",yz:4}],
"primitive": [{tr:"s. ilkel",yz:4}, {tr:"i. ilkel insan",yz:1}],
"principal": [{tr:"s. başlıca, asıl, ana",yz:4}, {tr:"i. okul müdürü",yz:2}],
"print": [{tr:"f. basmak, yazdırmak",yz:4}, {tr:"i. baskı, basılı eser; iz",yz:2}],
"private": [{tr:"s. özel",yz:4}, {tr:"i. er (asker rütbesi)",yz:1}],
"privilege": [{tr:"i. ayrıcalık, imtiyaz",yz:4}, {tr:"f. ayrıcalık tanımak, imtiyazlı kılmak",yz:2}],
"prize": [{tr:"i. ödül",yz:4}, {tr:"f. değer vermek, kıymet vermek",yz:2}],
"probe": [{tr:"i. soruşturma; (uzay) sonda",yz:3}, {tr:"f. araştırmak, didiklemek",yz:3}],
"producer": [{tr:"i. üretici",yz:4}, {tr:"i. yapımcı",yz:2}],
"profile": [{tr:"i. profil",yz:4}, {tr:"f. profilini çıkarmak, tanımlamak",yz:2}],
"profit": [{tr:"f. kâr etmek, yararlanmak",yz:2}, {tr:"i. kâr, kazanç",yz:4}],
"programme": [{tr:"i. program",yz:4}, {tr:"f. programlamak",yz:2}],
"progress": [{tr:"i. ilerleme, gelişme",yz:4}, {tr:"f. ilerlemek",yz:3}],
"prominent": [{tr:"önde gelen, tanınmış",yz:4}, {tr:"belirgin",yz:3}],
"promise": [{tr:"i. söz, vaat; umut vaat etme",yz:3}, {tr:"f. söz vermek, vaat etmek",yz:3}],
"promotion": [{tr:"i. terfi",yz:3}, {tr:"i. tanıtım, promosyon",yz:3}],
"prompt": [{tr:"f. harekete geçirmek, teşvik etmek, yöneltmek",yz:4}, {tr:"s. hızlı, çabuk",yz:2}],
"prone": [{tr:"s. (prone to) eğilimli, yatkın",yz:4}, {tr:"yüzükoyun yatan",yz:2}],
"pronounce": [{tr:"f. telaffuz etmek",yz:4}, {tr:"f. ilan etmek, bildirmek, açıklamak",yz:2}],
"proof": [{tr:"i. kanıt, delil",yz:4}, {tr:"s. dayanıklı, geçirmez",yz:2}, {tr:"f. (metin) düzeltisini yapmak",yz:1}],
"property": [{tr:"i. özellik, nitelik",yz:4}, {tr:"i. mülk, taşınmaz",yz:3}],
"proportion": [{tr:"i. oran, orantı",yz:4}, {tr:"f. orantılamak",yz:1}],
"proposal": [{tr:"i. öneri, teklif",yz:4}, {tr:"i. evlilik teklifi",yz:1}],
"prospect": [{tr:"i. olasılık, beklenti",yz:4}, {tr:"f. maden aramak",yz:1}],
"pull": [{tr:"i. çekiş, çekim gücü",yz:3}, {tr:"f. çekmek",yz:3}],
"purchase": [{tr:"f. satın almak",yz:4}, {tr:"i. satın alma",yz:3}],
"push": [{tr:"f. zorlamak, baskı yapmak",yz:4}, {tr:"i. itiş, hamle",yz:2}],
"puzzle": [{tr:"f. şaşırtmak, kafasını karıştırmak",yz:3}, {tr:"i. bulmaca, muamma",yz:3}],
"qualify": [{tr:"f. hak kazanmak; şartları taşımak",yz:4}, {tr:"f. (bir ifadeyi) sınırlamak, koşula bağlamak",yz:2}],
"quality": [{tr:"i. kalite, nitelik",yz:4}, {tr:"s. kaliteli",yz:2}],
"quantum": [{tr:"i. kuantum",yz:4}, {tr:"i. miktar, nicelik, ölçü",yz:1}],
"quarter": [{tr:"i. çeyrek",yz:4}, {tr:"f. dörde bölmek",yz:1}],
"quick": [{tr:"s. hızlı, çabuk",yz:4}, {tr:"z. çabuk (gayriresmî)",yz:1}],
"quote": [{tr:"f. (fiyat) belirtmek, teklif vermek",yz:2}, {tr:"f./i. alıntı yapmak, alıntı",yz:4}],
"race": [{tr:"i. yarış",yz:3}, {tr:"i. ırk",yz:3}],
"radical": [{tr:"s. köklü, radikal",yz:4}, {tr:"i. radikal (kişi)",yz:1}],
"radio": [{tr:"i. radyo",yz:3}, {tr:"f. telsizle bildirmek",yz:1}],
"rail": [{tr:"i. ray, demiryolu",yz:4}, {tr:"f. çıkışmak, veryansın etmek",yz:1}],
"rain": [{tr:"i. yağmur",yz:4}, {tr:"f. yağmur yağmak",yz:2}],
"raised": [{tr:"s. yükseltilmiş, artmış",yz:3}, {tr:"s. kabartmalı",yz:1}],
"raising": [{tr:"i. toplama, artırma",yz:4}, {tr:"i. (çocuk) yetiştirme, büyütme",yz:2}],
"ranging": [{tr:"s. arasında değişen",yz:4}, {tr:"s. serbestçe dolaşan, özgürce gezen",yz:1}],
"rank": [{tr:"i. rütbe, derece, sıra",yz:4}, {tr:"f. sıralamak, sınıflandırmak",yz:3}],
"rates": [{tr:"i. oranlar",yz:4}, {tr:"i. fiyatlar, ücretler",yz:2}],
"rational": [{tr:"s. akılcı, mantıklı",yz:4}, {tr:"i. rasyonel sayı",yz:1}],
"ray": [{tr:"i. ışın",yz:4}, {tr:"i. (a ray of hope) umut ışığı, kırıntı",yz:2}],
"react": [{tr:"f. tepki vermek",yz:4}, {tr:"f. tepkimeye girmek (kimya)",yz:2}],
"readily": [{tr:"z. kolayca, hemen",yz:4}, {tr:"z. isteyerek, seve seve (gönüllü olarak)",yz:2}],
"reading": [{tr:"i. okuma",yz:4}, {tr:"i. (ölçüm) değer",yz:2}],
"real": [{tr:"s. gerçek, hakiki",yz:4}, {tr:"z. gerçekten (gayriresmî)",yz:1}],
"realise": [{tr:"f. fark etmek, anlamak",yz:4}, {tr:"f. gerçekleştirmek",yz:3}],
"realize": [{tr:"fark etmek, anlamak",yz:4}, {tr:"gerçekleştirmek",yz:3}],
"recall": [{tr:"f. hatırlamak, anımsamak",yz:4}, {tr:"f. geri çağırmak, toplatmak",yz:2}],
"received": [{tr:"s. (genel olarak) kabul görmüş",yz:3}, {tr:"s. alınmış",yz:2}],
"recipe": [{tr:"i. yemek tarifi",yz:3}, {tr:"i. formül, sır, reçete (mecaz)",yz:3}],
"recognise": [{tr:"f. tanımak, fark etmek",yz:4}, {tr:"f. resmen kabul etmek, resmen tanımak",yz:3}],
"recognition": [{tr:"i. takdir, kabul görme",yz:4}, {tr:"i. tanıma",yz:3}],
"recognize": [{tr:"f. (resmi olarak) kabul etmek, tanımak",yz:4}, {tr:"f. tanımak (kişi/yüz)",yz:2}],
"recover": [{tr:"f. iyileşmek, toparlanmak",yz:4}, {tr:"f. geri kazanmak",yz:3}],
"reducing": [{tr:"i. zayıflama, kilo verme (diyetle)",yz:1}, {tr:"i. azaltma",yz:4}],
"reference": [{tr:"i. referans, kaynak, atıf",yz:4}, {tr:"f. atıfta bulunmak",yz:2}],
"reflect": [{tr:"f. yansıtmak",yz:4}, {tr:"f. (üzerinde) düşünmek",yz:3}],
"reform": [{tr:"i. reform, ıslahat",yz:4}, {tr:"f. reform yapmak, ıslah etmek",yz:3}],
"refuse": [{tr:"f. reddetmek",yz:4}, {tr:"i. çöp, atık",yz:2}],
"regime": [{tr:"i. (tedavi/beslenme) rejimi, program",yz:2}, {tr:"i. rejim, yönetim (siyasi)",yz:4}],
"register": [{tr:"f. kaydetmek, kaydolmak",yz:4}, {tr:"i. kayıt, sicil",yz:2}],
"regular": [{tr:"s. düzenli",yz:4}, {tr:"i. daimi müşteri",yz:1}],
"regulation": [{tr:"i. düzenleme, yönetmelik",yz:4}, {tr:"s. standart, kurallara uygun",yz:1}],
"relate": [{tr:"f. ilgili olmak, ilişkili olmak",yz:4}, {tr:"f. anlatmak",yz:1}],
"relative": [{tr:"s. göreli, nispi; i. akraba",yz:4}, {tr:"i. akraba",yz:2}],
"relief": [{tr:"i. yardım",yz:3}, {tr:"i. rahatlama, ferahlama",yz:4}],
"relieve": [{tr:"f. hafifletmek, yatıştırmak",yz:4}, {tr:"f. (yükten/görevden) kurtarmak, muaf tutmak",yz:2}],
"religious": [{tr:"s. dini",yz:4}, {tr:"s. dindar",yz:2}],
"remote": [{tr:"s. uzak",yz:4}, {tr:"i. uzaktan kumanda",yz:1}],
"rent": [{tr:"i. kira",yz:4}, {tr:"f. kiralamak",yz:3}],
"repair": [{tr:"f. onarmak, tamir etmek",yz:4}, {tr:"i. onarım, tamirat",yz:3}],
"repeat": [{tr:"f. tekrarlamak, yinelemek",yz:4}, {tr:"i. tekrar",yz:1}],
"report": [{tr:"i. rapor",yz:4}, {tr:"f. bildirmek, rapor etmek, haber vermek",yz:4}],
"represent": [{tr:"f. temsil etmek",yz:4}, {tr:"f. ifade etmek, betimlemek",yz:2}],
"representative": [{tr:"i. temsilci, vekil",yz:3}, {tr:"s. temsili, tipik (bir grubu yansıtan)",yz:3}],
"reproduce": [{tr:"f. üremek, çoğalmak",yz:4}, {tr:"f. yeniden üretmek, kopyalamak",yz:3}],
"reproduction": [{tr:"i. üreme",yz:4}, {tr:"i. çoğaltma, kopya",yz:2}],
"rescue": [{tr:"f. kurtarmak",yz:4}, {tr:"i. kurtarma, kurtarış",yz:2}],
"reserve": [{tr:"i. rezerv, yedek",yz:3}, {tr:"f. ayırmak, saklamak",yz:3}],
"reservoir": [{tr:"i. rezervuar, su deposu",yz:4}, {tr:"i. (bilgi/duygu) birikim, kaynak",yz:2}],
"resident": [{tr:"i. sakin, oturan kişi",yz:4}, {tr:"s. yerleşik, ikamet eden",yz:2}],
"resistance": [{tr:"i. direnç",yz:4}, {tr:"i. direniş, karşı koyma",yz:3}],
"resolve": [{tr:"f. çözmek, karara bağlamak",yz:4}, {tr:"i. kararlılık",yz:2}],
"respect": [{tr:"f. saygı duymak",yz:3}, {tr:"i. saygı",yz:3}],
"rest": [{tr:"f. dinlenmek",yz:2}, {tr:"i. geri kalan",yz:4}],
"return": [{tr:"f. dönmek, geri vermek",yz:4}, {tr:"i. getiri",yz:3}],
"reverse": [{tr:"f. tersine çevirmek, iptal etmek",yz:4}, {tr:"s. ters, zıt",yz:3}],
"review": [{tr:"f. gözden geçirmek, incelemek",yz:4}, {tr:"i. inceleme, eleştiri",yz:3}],
"revolution": [{tr:"i. devrim",yz:4}, {tr:"i. dönüş, devir (fiziksel)",yz:1}],
"reward": [{tr:"f. ödüllendirmek",yz:3}, {tr:"i. ödül",yz:3}],
"rewrite": [{tr:"f. yeniden yazmak",yz:4}, {tr:"i. yeniden yazım",yz:1}],
"rice": [{tr:"i. pirinç, çeltik",yz:3}, {tr:"f. pirinç kıvamında ezmek (patates vb.)",yz:1}],
"ride": [{tr:"i. yolculuk, biniş",yz:2}, {tr:"f. binmek (ata, bisiklete vb.)",yz:3}],
"rising": [{tr:"s. yükselen, artan",yz:4}, {tr:"i. yükseliş, ayaklanma",yz:1}],
"ritual": [{tr:"i. ayin, tören, ritüel",yz:4}, {tr:"s. ayinle ilgili, alışılagelmiş",yz:2}],
"rival": [{tr:"f. boy ölçüşmek",yz:3}, {tr:"i. rakip",yz:4}],
"rock": [{tr:"i. kaya, taş",yz:4}, {tr:"f. sallamak, sarsmak",yz:2}],
"roman": [{tr:"i. dik yazı karakteri (italik olmayan)",yz:1}, {tr:"s. Roma'ya ait",yz:3}],
"room": [{tr:"i. yer, alan, imkan",yz:4}, {tr:"i. oda",yz:2}],
"root": [{tr:"i. kök, köken; f. kök salmak, dayanmak",yz:4}, {tr:"f. kök salmak, dayanmak",yz:2}],
"rotation": [{tr:"i. dönme, dönüş",yz:4}, {tr:"i. rotasyon, nöbetleşme (görev değişimi)",yz:2}],
"roughly": [{tr:"z. yaklaşık olarak",yz:4}, {tr:"z. kabaca, sertçe",yz:1}],
"round": [{tr:"s. yuvarlak",yz:3}, {tr:"i. tur, aşama, raunt",yz:4}, {tr:"z./e. (BrE) etrafında, çevresinde",yz:1}, {tr:"f. (sayıyı) yuvarlamak",yz:2}],
"route": [{tr:"i. güzergâh, yol",yz:4}, {tr:"f. yönlendirmek",yz:1}],
"routine": [{tr:"s. rutin, alışılmış",yz:3}, {tr:"i. rutin, alışkanlık",yz:3}],
"royal": [{tr:"s. kraliyete ait, kraliyet",yz:4}, {tr:"i. kraliyet üyesi",yz:1}],
"ruin": [{tr:"i. yıkıntı, harabe; mahvolma",yz:3}, {tr:"f. mahvetmek, harap etmek",yz:4}],
"rule": [{tr:"f. yönetmek, hükmetmek",yz:3}, {tr:"i. kural, yönetmelik",yz:4}],
"ruler": [{tr:"i. hükümdar, yönetici",yz:4}, {tr:"i. cetvel",yz:1}],
"running": [{tr:"i. koşu",yz:3}, {tr:"s. sürekli, akan",yz:2}],
"rush": [{tr:"f. acele etmek, koşuşturmak",yz:4}, {tr:"i. (rush hour) yoğun saat, izdiham",yz:2}],
"sad": [{tr:"s. üzgün, hüzünlü",yz:3}, {tr:"s. üzücü, acıklı",yz:3}],
"safe": [{tr:"s. güvenli, emniyetli",yz:4}, {tr:"i. kasa",yz:1}],
"salt": [{tr:"i. tuz",yz:3}, {tr:"f. tuzlamak",yz:1}],
"sample": [{tr:"i. örnek, numune",yz:4}, {tr:"f. örnek almak, tatmak",yz:2}],
"sand": [{tr:"i. kum",yz:3}, {tr:"f. zımparalamak",yz:1}],
"satisfaction": [{tr:"i. memnuniyet, tatmin",yz:4}, {tr:"i. (hukuk) tazmin, giderim",yz:1}],
"save": [{tr:"f. kurtarmak",yz:4}, {tr:"f. biriktirmek, tasarruf etmek",yz:3}],
"saw": [{tr:"i. testere",yz:3}, {tr:"f. testereyle kesmek",yz:2}],
"scale": [{tr:"f. ölçeklendirmek",yz:1}, {tr:"i. ölçek, boyut",yz:4}],
"scan": [{tr:"i. tarama, tetkik",yz:3}, {tr:"f. taramak, gözden geçirmek",yz:4}],
"scatter": [{tr:"f. dağıtmak, saçmak, dağılmak",yz:4}, {tr:"i. dağılma, saçılma",yz:1}],
"scene": [{tr:"olay yeri",yz:2}, {tr:"sahne",yz:3}],
"schedule": [{tr:"f. planlamak",yz:3}, {tr:"i. program, çizelge",yz:4}],
"scheme": [{tr:"i. plan, program",yz:4}, {tr:"entrika",yz:2}],
"scholar": [{tr:"i. bilim insanı, akademisyen",yz:4}, {tr:"i. burslu öğrenci",yz:1}],
"scope": [{tr:"i. kapsam, alan",yz:4}, {tr:"i. olanak",yz:2}],
"score": [{tr:"i. skor, puan",yz:4}, {tr:"f. puan kaydetmek, sayı yapmak",yz:2}, {tr:"f. (müzik) beste yazmak, müziğini yapmak",yz:1}],
"screen": [{tr:"f. taramak, elemek",yz:3}, {tr:"i. ekran",yz:3}],
"seal": [{tr:"f. mühürlemek, kapatmak, sızdırmaz hale getirmek",yz:3}, {tr:"i. fok (hayvan)",yz:2}],
"search": [{tr:"i. arama",yz:3}, {tr:"f. aramak",yz:4}],
"season": [{tr:"f. baharatlamak, tatlandırmak",yz:1}, {tr:"i. mevsim, sezon",yz:4}],
"seat": [{tr:"i. koltuk, oturma yeri",yz:3}, {tr:"i. (parlamentoda) sandalye, milletvekilliği",yz:3}, {tr:"f. oturtmak; (kapasite olarak) almak",yz:2}],
"secondary": [{tr:"s. ikincil, tali",yz:4}, {tr:"ortaöğretime ait (secondary school)",yz:3}],
"secret": [{tr:"i. sır",yz:4}, {tr:"s. gizli, saklı",yz:3}],
"section": [{tr:"i. bölüm, kısım",yz:4}, {tr:"f. bölmek, kısımlara ayırmak",yz:1}],
"secure": [{tr:"f. sağlamak, güvence altına almak",yz:4}, {tr:"s. güvenli, emin",yz:3}],
"security": [{tr:"i. güvenlik, emniyet",yz:4}, {tr:"i. teminat, güvence (finansal)",yz:1}],
"seed": [{tr:"i. tohum, çekirdek",yz:4}, {tr:"f. tohum ekmek",yz:2}],
"seeing": [{tr:"s. görebilen, gören (kör olmayan)",yz:1}, {tr:"i. görme",yz:3}],
"segment": [{tr:"i. kesim, bölüm, dilim",yz:4}, {tr:"f. bölmek, ayırmak",yz:3}],
"select": [{tr:"f. seçmek",yz:4}, {tr:"s. seçkin, seçilmiş",yz:1}],
"sensation": [{tr:"i. duyu, his",yz:4}, {tr:"i. büyük heyecan/ilgi uyandıran şey, sansasyon",yz:2}],
"separate": [{tr:"f. ayırmak, ayrılmak",yz:4}, {tr:"s. ayrı, farklı",yz:3}],
"separated": [{tr:"s. ayrılmış, ayrı (birbirinden uzak)",yz:4}, {tr:"s. (eşinden) ayrı yaşayan",yz:1}],
"sequence": [{tr:"f. sıraya koymak, dizilemek",yz:3}, {tr:"i. sıra, dizilim",yz:4}],
"serve": [{tr:"f. hizmet etmek",yz:4}, {tr:"f. sunmak, servis yapmak",yz:2}],
"setting": [{tr:"i. ortam, mekân",yz:4}, {tr:"i. ayar",yz:2}],
"settle": [{tr:"f. yerleşmek",yz:4}, {tr:"f. çözüme kavuşturmak, halletmek",yz:3}],
"sex": [{tr:"i. cinsiyet",yz:4}, {tr:"i. cinsellik",yz:2}],
"shake": [{tr:"f. sallamak, sarsmak",yz:4}, {tr:"i. sarsıntı, sallama",yz:2}],
"shallow": [{tr:"s. sığ",yz:4}, {tr:"s. yüzeysel, sığ (mecaz, kişilik için)",yz:2}],
"share": [{tr:"f. paylaşmak",yz:4}, {tr:"i. pay, hisse",yz:3}],
"shark": [{tr:"i. köpekbalığı",yz:3}, {tr:"i. (mecaz) açgözlü dolandırıcı, tefeci",yz:1}],
"sharp": [{tr:"s. keskin, sivri, zeki",yz:4}, {tr:"z. tam (saatinde)",yz:1}],
"shelf": [{tr:"i. (continental shelf) kıta sahanlığı",yz:2}, {tr:"i. raf (eşya koymak için)",yz:3}],
"shelter": [{tr:"i. sığınak, barınak",yz:4}, {tr:"f. barındırmak, korumak; sığınmak",yz:3}],
"shift": [{tr:"i. değişim, kayma",yz:4}, {tr:"i. vardiya",yz:2}],
"ship": [{tr:"f. göndermek, sevk etmek",yz:3}, {tr:"i. gemi",yz:4}],
"shock": [{tr:"i. şok, sarsıntı",yz:3}, {tr:"f. sarsmak, şoke etmek",yz:3}],
"shoe": [{tr:"i. ayakkabı",yz:3}, {tr:"f. nallamak",yz:1}],
"shop": [{tr:"i. dükkân, mağaza",yz:3}, {tr:"f. alışveriş yapmak",yz:3}],
"side": [{tr:"f. taraf tutmak",yz:2}, {tr:"i. taraf, yan",yz:4}],
"sight": [{tr:"i. görme yetisi, görme duyusu",yz:4}, {tr:"i. görüntü, manzara",yz:3}, {tr:"f. görmek, gözle görmek, fark etmek",yz:1}],
"sign": [{tr:"i. işaret, belirti",yz:4}, {tr:"f. imzalamak",yz:2}],
"signal": [{tr:"i. sinyal, işaret",yz:4}, {tr:"f. işaret etmek, bildirmek",yz:3}],
"site": [{tr:"i. alan, saha, yer",yz:4}, {tr:"f. konumlandırmak",yz:1}],
"skin": [{tr:"i. deri, cilt",yz:4}, {tr:"f. derisini yüzmek",yz:1}],
"slave": [{tr:"i. köle",yz:3}, {tr:"f. köle gibi çalışmak",yz:1}],
"sleep": [{tr:"i. uyku",yz:4}, {tr:"f. uyumak",yz:3}],
"slight": [{tr:"s. hafif, küçük",yz:4}, {tr:"f. önemsememek, küçümsemek",yz:1}],
"slow": [{tr:"f. yavaşlamak, yavaşlatmak",yz:3}, {tr:"s./z. yavaş",yz:4}],
"smart": [{tr:"s. akıllı, zeki, şık",yz:4}, {tr:"f. sızlamak, acımak",yz:1}],
"smell": [{tr:"f. koklamak; koku almak/vermek",yz:3}, {tr:"i. koku",yz:2}],
"smoke": [{tr:"i. duman",yz:4}, {tr:"f. sigara içmek",yz:3}],
"snake": [{tr:"i. yılan",yz:3}, {tr:"f. kıvrılarak ilerlemek",yz:1}],
"snow": [{tr:"i. kar",yz:3}, {tr:"f. kar yağmak",yz:2}],
"soil": [{tr:"i. toprak",yz:4}, {tr:"f. kirletmek, lekelemek",yz:1}],
"sold": [{tr:"s. satılmış",yz:3}, {tr:"s. (sold on) ikna olmuş, hayran",yz:1}],
"soldier": [{tr:"i. asker",yz:4}, {tr:"f. asker olarak hizmet etmek",yz:1}],
"solution": [{tr:"i. çözüm",yz:4}, {tr:"i. çözelti (kimyasal)",yz:2}],
"sometime": [{tr:"z. ileride bir zaman, bir ara",yz:3}, {tr:"s. eski, bir zamanlar olan",yz:1}],
"song": [{tr:"i. şarkı",yz:3}, {tr:"(for a song) çok ucuza",yz:1}],
"sophisticate": [{tr:"i. görmüş geçirmiş kimse",yz:3}, {tr:"f. inceltmek, karmaşıklaştırmak, geliştirmek",yz:2}],
"sorry": [{tr:"s. acınacak halde, berbat, kötü durumda",yz:1}, {tr:"s. üzgün, pişman",yz:3}],
"sort": [{tr:"f. sınıflandırmak, ayırmak",yz:2}, {tr:"i. tür, çeşit",yz:4}],
"span": [{tr:"i. açıklık, uzunluk",yz:2}, {tr:"i. süre, aralık",yz:4}],
"spare": [{tr:"s. yedek, fazladan",yz:3}, {tr:"f. (zaman/kaynak) ayırmak, esirgemek",yz:3}],
"speaker": [{tr:"i. konuşmacı",yz:4}, {tr:"i. hoparlör",yz:1}],
"speaking": [{tr:"i. konuşma",yz:3}, {tr:"s. konuşan, konuşkan",yz:3}],
"special": [{tr:"s. özel",yz:4}, {tr:"i. özel program/ürün",yz:1}],
"spectrum": [{tr:"i. spektrum, tayf",yz:3}, {tr:"i. yelpaze",yz:4}],
"speech": [{tr:"i. konuşma, söylev",yz:4}, {tr:"i. konuşma yetisi",yz:3}],
"speed": [{tr:"f. hızlanmak, hızlandırmak",yz:2}, {tr:"i. hız",yz:4}],
"sphere": [{tr:"i. alan, çevre",yz:4}, {tr:"i. küre",yz:2}],
"spite": [{tr:"e. (in spite of) rağmen",yz:4}, {tr:"i. kin, garez",yz:1}],
"sport": [{tr:"i. spor",yz:4}, {tr:"f. takınmak, sergilemek",yz:1}],
"spot": [{tr:"f. fark etmek, saptamak",yz:4}, {tr:"i. yer",yz:3}],
"spray": [{tr:"i. sprey, püskürtü; deniz serpintisi",yz:3}, {tr:"f. püskürtmek",yz:3}],
"spring": [{tr:"i. ilkbahar",yz:4}, {tr:"i. kaynak, pınar",yz:2}],
"stable": [{tr:"s. istikrarlı, dengeli",yz:4}, {tr:"i. ahır",yz:1}],
"staff": [{tr:"i. personel, kadro",yz:4}, {tr:"f. personel sağlamak",yz:1}],
"stage": [{tr:"i. aşama, evre",yz:4}, {tr:"f. sahnelemek, düzenlemek",yz:2}],
"stand": [{tr:"f. durmak, ayakta durmak",yz:4}, {tr:"i. duruş, tavır",yz:2}],
"standard": [{tr:"i. standart, ölçüt",yz:4}, {tr:"s. standart, alışılmış",yz:3}],
"star": [{tr:"i. yıldız",yz:4}, {tr:"f. başrolde oynamak, baş rolü üstlenmek",yz:1}],
"starting": [{tr:"s. başlangıçtaki, ilk",yz:4}, {tr:"i. başlama, başlangıç",yz:2}],
"static": [{tr:"s. durağan, sabit",yz:4}, {tr:"i. parazit (radyoda)",yz:1}],
"station": [{tr:"f. konuşlandırmak, yerleştirmek",yz:2}, {tr:"i. istasyon",yz:4}],
"steal": [{tr:"f. çalmak, hırsızlık yapmak",yz:4}, {tr:"i. kelepir, ucuz/karlı alışveriş",yz:1}],
"steel": [{tr:"i. çelik",yz:4}, {tr:"f. kendini hazırlamak, cesaretini toplamak",yz:1}],
"stem": [{tr:"f. kaynaklanmak, durdurmak",yz:4}, {tr:"i. sap, gövde",yz:2}],
"step": [{tr:"f. adım atmak",yz:3}, {tr:"i. adım",yz:4}],
"stereotype": [{tr:"i. klişe, basmakalıp yargı",yz:4}, {tr:"f. kalıplaştırmak, klişeleştirmek",yz:2}],
"stick": [{tr:"f. dayanmak, sadık kalmak",yz:4}, {tr:"i. sopa, çubuk",yz:2}],
"stimulus": [{tr:"i. teşvik",yz:3}, {tr:"i. uyarıcı, uyaran",yz:4}],
"stir": [{tr:"i. heyecan, telaş, yaygara",yz:3}, {tr:"f. karıştırmak",yz:2}],
"stock": [{tr:"i. stok, envanter; hisse senedi",yz:4}, {tr:"s. basmakalıp, klişe",yz:1}, {tr:"f. stoklamak, bulundurmak",yz:2}],
"stomach": [{tr:"f. katlanmak, tahammül etmek, hazmetmek",yz:2}, {tr:"i. mide",yz:4}],
"stone": [{tr:"i. taş",yz:4}, {tr:"f. taşlamak",yz:1}],
"stopped": [{tr:"s. (burun için) tıkalı",yz:1}, {tr:"s. durmuş, durdurulmuş",yz:3}],
"store": [{tr:"f. depolamak, saklamak",yz:4}, {tr:"i. mağaza",yz:2}],
"storm": [{tr:"i. fırtına",yz:4}, {tr:"f. hücum etmek; öfkeyle dalmak",yz:1}],
"straightforward": [{tr:"s. basit, anlaşılır",yz:4}, {tr:"s. açık sözlü, dürüst",yz:3}],
"strain": [{tr:"i. gerginlik, zorlanma, baskı",yz:4}, {tr:"i. (biyoloji) tür, soy (bakteri/virüs türü)",yz:3}],
"strange": [{tr:"garip, tuhaf",yz:4}, {tr:"yabancı",yz:2}],
"stream": [{tr:"i. dere, akış",yz:4}, {tr:"f. akmak; (çevrimiçi) yayın yapmak",yz:2}],
"stretch": [{tr:"f. germek, uzanmak",yz:3}, {tr:"i. uzanan alan, bölüm, kesim",yz:2}],
"strike": [{tr:"i. grev",yz:3}, {tr:"f. vurmak, çarpmak",yz:3}],
"stroke": [{tr:"i. inme, felç",yz:4}, {tr:"f. okşamak",yz:2}],
"struggle": [{tr:"f. mücadele etmek, uğraşmak",yz:4}, {tr:"i. mücadele",yz:3}],
"studied": [{tr:"s. kasıtlı, bilinçli",yz:2}, {tr:"s. incelenmiş, araştırılmış",yz:4}],
"stuff": [{tr:"i. şey, eşya; malzeme",yz:3}, {tr:"f. doldurmak, tıkıştırmak",yz:2}],
"submit": [{tr:"f. sunmak, teslim etmek (başvuru vb.)",yz:4}, {tr:"f. boyun eğmek, teslim olmak",yz:2}],
"substance": [{tr:"i. madde",yz:4}, {tr:"i. öz, esas",yz:3}],
"substitute": [{tr:"i. vekil, yedek, ikame",yz:3}, {tr:"f. yerine koymak/geçmek",yz:4}],
"succeed": [{tr:"f. başarılı olmak",yz:4}, {tr:"f. yerine geçmek",yz:3}],
"sugar": [{tr:"i. şeker",yz:4}, {tr:"f. şeker katmak",yz:1}],
"sum": [{tr:"i. toplam, meblağ",yz:3}, {tr:"f. (sum up) özetlemek",yz:2}],
"summary": [{tr:"i. özet",yz:4}, {tr:"s. özet niteliğinde, kısa",yz:1}],
"summer": [{tr:"i. yaz",yz:4}, {tr:"f. yazı geçirmek",yz:1}],
"sun": [{tr:"i. güneş",yz:4}, {tr:"f. güneşlenmek",yz:1}],
"super": [{tr:"z. son derece, aşırı",yz:3}, {tr:"s. süper, olağanüstü, mükemmel",yz:2}],
"superior": [{tr:"s. üstün, daha iyi",yz:4}, {tr:"i. üst, amir",yz:2}],
"supplement": [{tr:"i. takviye, ek",yz:3}, {tr:"f. desteklemek, tamamlamak",yz:4}],
"supply": [{tr:"i. arz, tedarik, kaynak",yz:4}, {tr:"f. sağlamak",yz:3}],
"surface": [{tr:"f. yüzeye çıkmak, ortaya çıkmak",yz:3}, {tr:"i. yüzey",yz:4}],
"surgery": [{tr:"i. ameliyat, cerrahi",yz:4}, {tr:"i. muayenehane",yz:1}],
"surprise": [{tr:"f. şaşırtmak",yz:3}, {tr:"i. sürpriz, şaşkınlık",yz:3}],
"survey": [{tr:"i. anket, inceleme",yz:4}, {tr:"f. incelemek, anket yapmak",yz:2}],
"suspect": [{tr:"f. şüphelenmek",yz:4}, {tr:"i. şüpheli (kişi)",yz:2}],
"suspend": [{tr:"f. askıya almak, ertelemek",yz:4}, {tr:"f. asmak (fiziksel olarak)",yz:2}],
"swallow": [{tr:"f. yutmak",yz:4}, {tr:"i. kırlangıç",yz:1}],
"switch": [{tr:"f. değiştirmek, geçiş yapmak",yz:4}, {tr:"i. şalter, anahtar",yz:2}],
"table": [{tr:"i. tablo, çizelge",yz:4}, {tr:"i. masa",yz:2}],
"tackle": [{tr:"f. ele almak, üstesinden gelmek",yz:4}, {tr:"i. donanım, takım",yz:1}],
"take-up": [{tr:"i. talep, katılım oranı",yz:3}, {tr:"i. emilim",yz:1}],
"taken": [{tr:"s. dolu, meşgul",yz:3}, {tr:"s. ele geçirilmiş",yz:1}],
"tap": [{tr:"i. musluk",yz:2}, {tr:"i. hafif vuruş, dokunuş",yz:1}, {tr:"f. hafifçe vurmak, dokunmak",yz:1}, {tr:"f. (kaynağı) kullanmak, yararlanmak",yz:4}],
"tape": [{tr:"i. bant, şerit; kaset",yz:3}, {tr:"f. bantla yapıştırmak; kayda almak",yz:2}],
"target": [{tr:"i. hedef, amaç",yz:4}, {tr:"f. hedeflemek, hedef almak",yz:3}],
"taste": [{tr:"i. tat, zevk",yz:3}, {tr:"f. tat almak, tatmak",yz:2}],
"tax": [{tr:"f. vergilendirmek",yz:3}, {tr:"i. vergi",yz:4}],
"teaching": [{tr:"i. öğreti, doktrin",yz:3}, {tr:"i. öğretim",yz:4}],
"telescope": [{tr:"i. teleskop",yz:4}, {tr:"f. iç içe geçirerek kısaltmak, sıkıştırmak",yz:1}],
"telling": [{tr:"s. çarpıcı, etkileyici, açığa vuran",yz:4}, {tr:"i. anlatma, anlatım",yz:1}],
"temporary": [{tr:"s. geçici",yz:4}, {tr:"i. geçici işçi",yz:1}],
"tense": [{tr:"s. gergin",yz:4}, {tr:"i. (gramer) zaman kipi",yz:1}],
"text": [{tr:"i. metin",yz:4}, {tr:"f. mesaj göndermek, mesajlaşmak",yz:1}],
"textbook": [{tr:"i. ders kitabı",yz:4}, {tr:"s. tipik, klasik (örnek)",yz:2}],
"thermal": [{tr:"s. termal, ısıl",yz:4}, {tr:"i. sıcak hava akımı, termal (planörcülükte)",yz:1}],
"thesis": [{tr:"i. tez",yz:3}, {tr:"i. sav, iddia",yz:4}],
"thin": [{tr:"s. ince, zayıf; seyrek",yz:4}, {tr:"f. inceltmek, seyreltmek",yz:2}],
"thinking": [{tr:"i. düşünme, düşünce",yz:4}, {tr:"s. düşünen",yz:1}],
"third": [{tr:"s. üçüncü",yz:4}, {tr:"i. üçte bir",yz:3}, {tr:"z. üçüncü olarak",yz:2}],
"throw": [{tr:"f. atmak, fırlatmak",yz:4}, {tr:"i. atış",yz:1}],
"thumb": [{tr:"f. (kitabı) elleyerek karıştırmak, çevirmek",yz:1}, {tr:"i. başparmak",yz:3}],
"tie": [{tr:"i. bağ, ilişki",yz:4}, {tr:"i. kravat",yz:1}, {tr:"i. beraberlik, berabere biten maç",yz:1}, {tr:"f. bağlamak; (be tied to) bağlı kılmak, kısıtlamak",yz:3}],
"tip": [{tr:"i. uç",yz:3}, {tr:"i. bahşiş",yz:2}],
"tissue": [{tr:"i. doku",yz:4}, {tr:"i. kağıt mendil",yz:1}],
"title": [{tr:"i. başlık",yz:4}, {tr:"i. unvan",yz:2}],
"tolerance": [{tr:"i. tolerans, hoşgörü",yz:4}, {tr:"i. dayanıklılık, direnç (bağışıklık)",yz:3}],
"tone": [{tr:"i. üslup, ton (yazı/konuşmada)",yz:4}, {tr:"i. ses tonu",yz:2}],
"top": [{tr:"i. üst, tepe, doruk",yz:4}, {tr:"f. aşmak",yz:2}],
"total": [{tr:"s. toplam, tüm",yz:4}, {tr:"f. toplamak",yz:1}],
"touch": [{tr:"f. dokunmak, temas etmek",yz:4}, {tr:"i. dokunuş, temas",yz:2}],
"trace": [{tr:"f. izini sürmek, saptamak",yz:4}, {tr:"i. iz",yz:3}],
"track": [{tr:"f. izlemek, takip etmek",yz:4}, {tr:"i. iz; parkur, yol",yz:2}],
"tract": [{tr:"i. arazi parçası, bölge",yz:3}, {tr:"i. (anat.) kanal, yol",yz:3}],
"trade": [{tr:"i. ticaret",yz:4}, {tr:"f. ticaret yapmak",yz:3}],
"traffic": [{tr:"i. trafik",yz:4}, {tr:"f. kaçakçılığını yapmak",yz:2}],
"training": [{tr:"eğitim, yetiştirme",yz:4}, {tr:"antrenman",yz:2}],
"transmission": [{tr:"i. bulaşma",yz:4}, {tr:"i. iletim, aktarım",yz:3}],
"transmit": [{tr:"f. (hastalık) bulaştırmak",yz:3}, {tr:"f. iletmek, aktarmak",yz:4}],
"transplant": [{tr:"i. nakil, organ nakli",yz:4}, {tr:"f. nakletmek",yz:3}],
"transport": [{tr:"i. ulaşım, taşımacılık",yz:4}, {tr:"f. taşımak, nakletmek",yz:3}],
"trap": [{tr:"f. hapsetmek, tuzağa düşürmek",yz:4}, {tr:"i. tuzak, kapan",yz:3}],
"travel": [{tr:"f. yayılmak, ilerlemek",yz:3}, {tr:"f. seyahat etmek",yz:4}],
"treat": [{tr:"f. tedavi etmek",yz:4}, {tr:"f. davranmak, muamele etmek",yz:3}],
"treated": [{tr:"s. işlem görmüş, arıtılmış",yz:3}, {tr:"s. tedavi edilmiş",yz:3}],
"tree": [{tr:"i. ağaç",yz:4}, {tr:"f. ağaçlandırmak",yz:1}],
"trend": [{tr:"i. eğilim, gidişat",yz:4}, {tr:"f. yönelmek",yz:1}],
"trial": [{tr:"i. deneme, deney",yz:4}, {tr:"i. dava, yargılama",yz:2}],
"trick": [{tr:"f. kandırmak, aldatmak",yz:3}, {tr:"i. hile, oyun; marifet",yz:3}],
"trigger": [{tr:"f. tetiklemek, başlatmak",yz:4}, {tr:"i. tetik",yz:1}],
"trouble": [{tr:"f. rahatsız etmek, üzmek",yz:2}, {tr:"i. sorun, dert, güçlük",yz:4}],
"trust": [{tr:"i. güven",yz:4}, {tr:"f. güvenmek",yz:3}],
"turn-down": [{tr:"f. (turn down) reddetmek",yz:4}, {tr:"f. (turn down) (ses/ısıyı) kısmak, azaltmak",yz:2}],
"turn-out": [{tr:"f. ortaya çıkmak, sonuçlanmak",yz:4}, {tr:"f. üretmek, ortaya koymak",yz:2}],
"turned": [{tr:"s. (besin için) bozulmuş, ekşimiş",yz:1}, {tr:"s. dönmüş, dönük",yz:3}],
"turning": [{tr:"i. dönüm noktası",yz:4}, {tr:"i. dönüş, viraj",yz:1}],
"ultimate": [{tr:"s. nihai, en son, temel",yz:4}, {tr:"i. en üstünü, doruk noktası",yz:1}],
"underline": [{tr:"f. altını çizmek, vurgulamak",yz:4}, {tr:"i. alt çizgi",yz:1}],
"unemployed": [{tr:"s. işsiz",yz:4}, {tr:"i. (the unemployed) işsizler",yz:2}],
"uniform": [{tr:"s. tek tip, tekdüze, değişmez",yz:4}, {tr:"i. üniforma",yz:2}],
"union": [{tr:"i. sendika",yz:3}, {tr:"i. birlik, ittifak",yz:3}],
"unknown": [{tr:"s. bilinmeyen",yz:4}, {tr:"i. bilinmeyen kişi/şey",yz:1}],
"vessel": [{tr:"i. gemi, tekne",yz:3}, {tr:"i. (anat.) damar",yz:4}],
"viable": [{tr:"s. uygulanabilir, gerçekleştirilebilir",yz:4}, {tr:"s. yaşayabilir, canlılığını sürdürebilir (biyoloji)",yz:2}],
"visit": [{tr:"f. ziyaret etmek",yz:3}, {tr:"i. ziyaret",yz:3}],
"voice": [{tr:"f. dile getirmek",yz:3}, {tr:"i. ses",yz:4}],
"volume": [{tr:"i. hacim",yz:4}, {tr:"i. ses düzeyi",yz:2}],
"volunteer": [{tr:"f. gönüllü olmak",yz:3}, {tr:"i. gönüllü",yz:4}],
"wage": [{tr:"i. ücret, maaş",yz:4}, {tr:"f. (savaş/mücadele) yürütmek, sürdürmek",yz:3}],
"wait": [{tr:"f. beklemek",yz:4}, {tr:"i. bekleyiş, bekleme",yz:2}],
"walk": [{tr:"f. yürümek",yz:3}, {tr:"i. yürüyüş",yz:2}],
"wall": [{tr:"i. duvar",yz:4}, {tr:"f. duvarla çevirmek",yz:1}],
"warming": [{tr:"i. ısınma",yz:4}, {tr:"s. ısıtan",yz:1}],
"waste": [{tr:"i. atık, israf",yz:4}, {tr:"f. israf etmek, boşa harcamak",yz:3}],
"watch": [{tr:"f. izlemek, gözlemek",yz:4}, {tr:"i. kol saati",yz:1}],
"watching": [{tr:"i. izleme, seyretme",yz:3}, {tr:"i. gözetleme",yz:2}],
"waters": [{tr:"i. kara suları, deniz",yz:4}, {tr:"i. sular",yz:2}],
"wave": [{tr:"i. dalga",yz:4}, {tr:"f. el sallamak",yz:1}],
"wear": [{tr:"f. giymek, takmak",yz:4}, {tr:"aşındırmak; i. aşınma",yz:2}],
"weather": [{tr:"i. hava, hava durumu",yz:4}, {tr:"f. atlatmak, dayanmak",yz:2}],
"web": [{tr:"i. ağ",yz:4}, {tr:"i. örümcek ağı",yz:2}],
"weigh": [{tr:"f. (fayda/zarar) tartmak, değerlendirmek",yz:4}, {tr:"f. (ağırlığını) tartmak, ölçmek",yz:2}],
"weight": [{tr:"i. ağırlık",yz:4}, {tr:"f. ağırlık vermek",yz:1}],
"welcome": [{tr:"f. hoş karşılamak, memnuniyetle kabul etmek",yz:4}, {tr:"s. hoş karşılanan, memnuniyet verici",yz:3}],
"welfare": [{tr:"sosyal yardım",yz:3}, {tr:"refah, esenlik",yz:4}],
"west": [{tr:"z. batıya",yz:2}, {tr:"i. batı",yz:3}],
"western": [{tr:"s. batı, batıdaki",yz:4}, {tr:"i. kovboy filmi",yz:1}],
"white": [{tr:"s. beyaz",yz:4}, {tr:"i. beyaz renk",yz:2}, {tr:"f. beyazlatmak, örtmek",yz:1}],
"wide": [{tr:"s. geniş; yaygın",yz:4}, {tr:"z. ardına kadar, tamamen",yz:1}],
"wild": [{tr:"i. (the wild) doğa, yaban hayatı",yz:3}, {tr:"s. vahşi, yabani",yz:4}],
"win": [{tr:"i. zafer, galibiyet, kazanç",yz:2}, {tr:"f. kazanmak",yz:4}],
"wind": [{tr:"i. rüzgâr",yz:4}, {tr:"f. sarmak, dolamak; kıvrılmak",yz:2}],
"window": [{tr:"i. (fırsat) aralığı, süre",yz:3}, {tr:"i. pencere",yz:4}],
"winter": [{tr:"f. kışı geçirmek",yz:2}, {tr:"i. kış",yz:4}],
"wish": [{tr:"f. dilemek, istemek",yz:4}, {tr:"i. dilek, arzu",yz:2}],
"withdraw": [{tr:"f. geri çekmek; çekilmek",yz:4}, {tr:"f. (bankadan) para çekmek",yz:2}],
"witness": [{tr:"f. tanık olmak, şahit olmak",yz:4}, {tr:"i. tanık, şahit",yz:3}],
"wonder": [{tr:"f. merak etmek, hayret etmek",yz:4}, {tr:"i. harika",yz:2}],
"wood": [{tr:"i. ahşap, odun, tahta",yz:4}, {tr:"i. koru",yz:1}],
"words": [{tr:"i. sözler, sözcükler",yz:4}, {tr:"i. tartışma, ağız kavgası",yz:1}],
"works": [{tr:"i. eserler",yz:4}, {tr:"i. tesis, fabrika",yz:1}],
"worse": [{tr:"s./z. daha kötü",yz:4}, {tr:"i. daha kötü durum, kötüsü",yz:1}],
"worst": [{tr:"s./z. en kötü",yz:4}, {tr:"i. en kötüsü, en kötü durum",yz:2}],
"worth": [{tr:"s. değerinde",yz:4}, {tr:"i. değer",yz:2}],
"writing": [{tr:"i. yazma, yazı",yz:4}, {tr:"i. yazın, edebiyat",yz:2}],
"yellow": [{tr:"s. sarı",yz:3}, {tr:"f. sararmak",yz:1}],
"yield": [{tr:"i. verim, ürün",yz:3}, {tr:"f. vermek, üretmek",yz:4}],
"youth": [{tr:"i. gençlik",yz:4}, {tr:"i. genç kişi",yz:2}],
"zone": [{tr:"i. bölge, kuşak",yz:4}, {tr:"f. bölgelere ayırmak",yz:1}]
};
