/* ============================================================
   Anlam yıldızları — dönüştürücü girdisi (site bu dosyayı YÜKLEMEZ)

   Çok anlamlı kelimelerde her anlamın YDS önemi: 4 = sınavda asıl
   sorulan anlam, 1 = nadir/ikincil. Her kelimenin en yüksek yıldızı
   en az 3'tür. listeyi-aktar.py bunu okuyup anlamlara "yz" alanı
   olarak yazar ve anlamları yıldıza göre büyükten küçüğe sıralar.

   Yıldız anlam METNİNE bağlıdır; kaynak listedeki sıra değişse bile
   eşleşme bozulmaz. Metin değişirse o anlam yıldızsız kalır.
   Üretim: tools/test-uretim (agent + yildiz-dogrula.py) · 353 kelime
   ============================================================ */

window.ANLAM_YILDIZ = {
"above": [{tr:"e. üstünde, üzerinde",yz:4}, {tr:"s. yukarıda adı geçen",yz:2}],
"academic": [{tr:"s. akademik",yz:4}, {tr:"i. akademisyen",yz:3}],
"account": [{tr:"f. (for) oluşturmak, açıklamak",yz:4}, {tr:"i. hesap",yz:2}],
"acid": [{tr:"i. asit",yz:4}, {tr:"s. asitli, ekşi",yz:2}],
"adapt": [{tr:"f. uyum sağlamak",yz:4}, {tr:"f. uyarlamak",yz:2}],
"administration": [{tr:"i. yönetim, idare",yz:4}, {tr:"i. (başkanlık) dönemi",yz:2}],
"adopt": [{tr:"f. benimsemek, kabul etmek",yz:4}, {tr:"f. evlat edinmek",yz:2}],
"advocate": [{tr:"f. savunmak, desteklemek",yz:4}, {tr:"i. savunucu",yz:3}],
"aid": [{tr:"i. yardım",yz:4}, {tr:"f. yardım etmek",yz:3}],
"aim": [{tr:"f. amaçlamak",yz:4}, {tr:"i. amaç, hedef",yz:3}],
"antibiotic": [{tr:"i. antibiyotik",yz:4}, {tr:"s. antibiyotik özellikli",yz:2}],
"apart": [{tr:"z. ayrı, birbirinden ayrı",yz:4}, {tr:"s. parçalara ayrılmış",yz:2}],
"appearance": [{tr:"i. ortaya çıkış",yz:3}, {tr:"i. görünüş, görünüm",yz:4}],
"application": [{tr:"i. uygulama",yz:4}, {tr:"i. başvuru",yz:3}],
"apply": [{tr:"f. uygulamak",yz:4}, {tr:"f. başvurmak",yz:3}],
"approach": [{tr:"i. yaklaşım",yz:4}, {tr:"f. yaklaşmak",yz:3}],
"appropriate": [{tr:"s. uygun",yz:4}, {tr:"f. ayırmak, tahsis etmek",yz:1}],
"argue": [{tr:"f. iddia etmek, savunmak",yz:4}, {tr:"f. tartışmak, atışmak",yz:2}],
"article": [{tr:"i. makale",yz:4}, {tr:"i. madde",yz:2}],
"association": [{tr:"i. dernek, birlik",yz:3}, {tr:"i. ilişki, bağlantı",yz:4}],
"assume": [{tr:"f. varsaymak",yz:4}, {tr:"f. üstlenmek",yz:2}],
"atmosphere": [{tr:"i. atmosfer",yz:4}, {tr:"i. hava, ortam (ambiyans)",yz:3}],
"attack": [{tr:"f. saldırmak",yz:3}, {tr:"i. saldırı",yz:4}],
"attribute": [{tr:"f. atfetmek, bağlamak",yz:4}, {tr:"i. nitelik, özellik",yz:3}],
"audience": [{tr:"i. izleyici kitlesi, dinleyiciler",yz:4}, {tr:"i. resmi görüşme",yz:1}],
"average": [{tr:"s./i. ortalama",yz:4}, {tr:"s. sıradan, vasat",yz:2}],
"balance": [{tr:"i. denge",yz:4}, {tr:"f. dengelemek",yz:2}],
"bear": [{tr:"f. taşımak, katlanmak",yz:4}, {tr:"i. ayı",yz:2}],
"beginning": [{tr:"i. başlangıç, başlama",yz:4}, {tr:"s. başlangıç düzeyinde, yeni başlayan",yz:1}],
"behave": [{tr:"f. davranmak",yz:4}, {tr:"f. terbiyeli davranmak, uslu durmak",yz:1}],
"behind": [{tr:"e. arkasında, gerisinde",yz:4}, {tr:"z. geride",yz:2}],
"bite": [{tr:"f. ısırmak, sokmak",yz:3}, {tr:"i. ısırık",yz:2}],
"bond": [{tr:"i. bağ, ilişki",yz:4}, {tr:"i. tahvil",yz:2}],
"boost": [{tr:"f. artırmak, güçlendirmek",yz:4}, {tr:"i. artış, destek",yz:3}],
"building": [{tr:"i. bina, yapı",yz:4}, {tr:"i. inşa etme, yapım",yz:2}],
"built": [{tr:"s. inşa edilmiş, yapılmış",yz:4}, {tr:"s. yapılı, güçlü yapıya sahip",yz:1}],
"came": [{tr:"f. (come'un geçmiş biçimi) geldi",yz:4}, {tr:"i. (nadir) vitray kurşun çıtası",yz:1}],
"career": [{tr:"i. kariyer, meslek hayatı",yz:4}, {tr:"f. hızla ve kontrolsüzce gitmek",yz:1}],
"catch": [{tr:"f. yakalamak",yz:4}, {tr:"f. anlamak, kavramak",yz:2}],
"centre": [{tr:"i. merkez",yz:4}, {tr:"f. merkezileştirmek, odaklanmak",yz:2}],
"chance": [{tr:"i. şans, olasılık, fırsat",yz:4}, {tr:"s. tesadüfi",yz:2}],
"character": [{tr:"i. karakter, özellik",yz:3}, {tr:"i. kişilik",yz:4}],
"cheap": [{tr:"s. ucuz",yz:4}, {tr:"s. değersiz, adi, kalitesiz",yz:2}],
"chemistry": [{tr:"i. kimya",yz:4}, {tr:"i. (kişiler arası) uyum, çekim",yz:1}],
"civil": [{tr:"s. sivil, medeni",yz:4}, {tr:"s. nazik, kibar, saygılı",yz:2}],
"claim": [{tr:"f. iddia etmek",yz:4}, {tr:"i. iddia",yz:3}],
"class": [{tr:"i. sınıf",yz:4}, {tr:"i. ders",yz:2}],
"clean": [{tr:"s. temiz",yz:4}, {tr:"f. temizlemek",yz:3}],
"code": [{tr:"i. yasa, kurallar",yz:3}, {tr:"i. kod, şifre; f. kodlamak",yz:3}],
"cold": [{tr:"s. soğuk",yz:4}, {tr:"i. soğuk algınlığı",yz:2}],
"collapse": [{tr:"i. çöküş",yz:4}, {tr:"f. çökmek",yz:3}],
"commercial": [{tr:"s. ticari",yz:4}, {tr:"i. reklam (TV/radyo)",yz:2}],
"commission": [{tr:"f. sipariş vermek, görevlendirmek",yz:3}, {tr:"i. komisyon, kurul",yz:4}],
"commit": [{tr:"f. taahhüt etmek",yz:4}, {tr:"f. işlemek (suç)",yz:3}],
"compound": [{tr:"i. bileşik",yz:3}, {tr:"f. birleştirmek, ağırlaştırmak",yz:4}],
"concentrate": [{tr:"f. odaklanmak, konsantre olmak",yz:4}, {tr:"f. yoğunlaştırmak, koyulaştırmak",yz:2}],
"confine": [{tr:"f. sınırlamak, kısıtlamak",yz:4}, {tr:"f. kapatmak, hapsetmek",yz:3}],
"conflict": [{tr:"i. çatışma, anlaşmazlık",yz:4}, {tr:"f. çelişmek, çatışmak",yz:3}],
"constant": [{tr:"i. sabit (matematik)",yz:1}, {tr:"s. sabit, sürekli",yz:4}],
"construct": [{tr:"f. inşa etmek, kurmak",yz:4}, {tr:"i. kavram, yapı",yz:2}],
"contact": [{tr:"i. temas, iletişim",yz:4}, {tr:"f. temas kurmak",yz:2}],
"contemporary": [{tr:"s. çağdaş, güncel",yz:4}, {tr:"s./i. aynı dönemden (olan kişi), çağdaşı",yz:2}],
"content": [{tr:"i. içerik",yz:4}, {tr:"s. memnun, hoşnut",yz:2}],
"contrast": [{tr:"i. karşıtlık, zıtlık, tezat",yz:4}, {tr:"f. karşılaştırmak, kıyaslamak",yz:2}],
"cook": [{tr:"f. pişirmek, yemek yapmak",yz:3}, {tr:"i. aşçı",yz:2}],
"cool": [{tr:"f. soğumak, soğutmak",yz:3}, {tr:"s. serin",yz:3}],
"correct": [{tr:"f. düzeltmek",yz:3}, {tr:"s. doğru",yz:4}],
"couple": [{tr:"f. birleştirmek, eşleştirmek",yz:3}, {tr:"i. çift, iki",yz:4}],
"cover": [{tr:"f. kaplamak, örtmek",yz:4}, {tr:"f. kapsamak, içermek",yz:3}],
"credit": [{tr:"i. kredi",yz:3}, {tr:"i. övgü, itibar; f. atfetmek",yz:4}],
"critical": [{tr:"s. kritik, çok önemli",yz:4}, {tr:"s. eleştirel",yz:3}],
"crop": [{tr:"i. mahsul, ürün",yz:4}, {tr:"f. hasat etmek, kırpmak",yz:1}],
"cure": [{tr:"i. tedavi, çare",yz:4}, {tr:"f. tedavi etmek, iyileştirmek",yz:3}],
"current": [{tr:"i. akım",yz:3}, {tr:"s. güncel, şimdiki",yz:4}],
"cycle": [{tr:"i. döngü, çevrim",yz:4}, {tr:"f. bisiklete binmek",yz:1}],
"date": [{tr:"f. tarihini belirlemek",yz:3}, {tr:"i. randevu",yz:1}],
"days": [{tr:"i. dönem, çağ",yz:3}, {tr:"i. günler",yz:3}],
"debate": [{tr:"f. tartışmak",yz:3}, {tr:"i. tartışma",yz:4}],
"deep": [{tr:"s./z. derin",yz:4}, {tr:"i. derinlik",yz:1}],
"degree": [{tr:"i. derece",yz:4}, {tr:"i. (üniversite) diploma",yz:3}],
"demonstrate": [{tr:"f. göstermek, kanıtlamak",yz:4}, {tr:"f. gösteri yapmak",yz:2}],
"depression": [{tr:"i. depresyon, bunalım",yz:4}, {tr:"i. çöküntü, alçalma",yz:2}],
"desire": [{tr:"i. arzu, istek",yz:4}, {tr:"f. arzulamak, istemek",yz:2}],
"detail": [{tr:"i. ayrıntı, detay",yz:4}, {tr:"f. ayrıntılandırmak, ayrıntılarıyla açıklamak",yz:2}],
"developing": [{tr:"s. gelişmekte olan",yz:4}, {tr:"i. (fotoğraf) banyo etme",yz:1}],
"die": [{tr:"f. ölmek",yz:4}, {tr:"i. kalıp, zar",yz:1}],
"direct": [{tr:"f. yönetmek, yönlendirmek",yz:2}, {tr:"s./z. doğrudan",yz:4}],
"discipline": [{tr:"i. bilim dalı, alan",yz:4}, {tr:"i. disiplin, öz denetim; f. disipline etmek, cezalandırmak",yz:3}],
"display": [{tr:"f. sergilemek, göstermek",yz:4}, {tr:"i. sergi, gösterim",yz:2}],
"distance": [{tr:"i. mesafe, uzaklık",yz:4}, {tr:"f. uzaklaştırmak, mesafe koymak",yz:2}],
"doctor": [{tr:"i. doktor",yz:4}, {tr:"f. tedavi etmek",yz:1}],
"document": [{tr:"f. belgelemek, kayıt altına almak",yz:3}, {tr:"i. belge, doküman",yz:4}],
"domestic": [{tr:"s. yerli, iç (ülkeye ait)",yz:4}, {tr:"s. eve ait, ev içi",yz:3}],
"done": [{tr:"s. bitmiş, tamamlanmış",yz:4}, {tr:"s. pişmiş",yz:1}],
"draw": [{tr:"f. (sonuç) çıkarmak",yz:4}, {tr:"f. çizmek",yz:2}],
"dream": [{tr:"f. hayal etmek, rüya görmek",yz:3}, {tr:"i. hayal, rüya",yz:3}],
"drink": [{tr:"i. içecek",yz:3}, {tr:"f. içmek",yz:4}],
"drive": [{tr:"f. sürmek, yönlendirmek",yz:4}, {tr:"i. güdü, dürtü",yz:2}],
"dry": [{tr:"s. kuru, kurak",yz:4}, {tr:"f. kurumak, kurutmak",yz:2}],
"east": [{tr:"z. doğuya",yz:2}, {tr:"i. doğu",yz:3}],
"element": [{tr:"i. öge, unsur",yz:4}, {tr:"i. element (kimyasal)",yz:2}],
"else": [{tr:"z. aksi halde",yz:3}, {tr:"z. başka",yz:4}],
"encounter": [{tr:"f. karşılaşmak, rastlamak",yz:4}, {tr:"i. karşılaşma",yz:3}],
"engage": [{tr:"f. katılmak, meşgul olmak",yz:4}, {tr:"f. birbirine geçmek (mekanik)",yz:1}],
"engineer": [{tr:"i. mühendis",yz:4}, {tr:"f. tasarlamak, planlamak, düzenlemek",yz:2}],
"enter": [{tr:"f. girmek, katılmak",yz:4}, {tr:"f. kaydetmek",yz:2}],
"entire": [{tr:"s. bütün, tüm, tam",yz:4}, {tr:"i. (nadir) aygır",yz:1}],
"equivalent": [{tr:"s. eşdeğer, denk",yz:4}, {tr:"i. karşılık, eşdeğer",yz:3}],
"essential": [{tr:"s. temel, zorunlu",yz:4}, {tr:"i. temel gereksinim, olmazsa olmaz unsur",yz:2}],
"ethnic": [{tr:"s. etnik",yz:4}, {tr:"i. etnik grup üyesi",yz:1}],
"except": [{tr:"e. hariç, -den başka",yz:4}, {tr:"f. hariç tutmak, dışında bırakmak",yz:1}],
"exhibit": [{tr:"f. sergilemek, göstermek",yz:4}, {tr:"i. sergi, eser",yz:2}],
"experiment": [{tr:"i. deney",yz:4}, {tr:"f. deney yapmak",yz:2}],
"exploit": [{tr:"f. sömürmek, kötüye kullanmak; yararlanmak",yz:4}, {tr:"i. kahramanlık, başarı",yz:1}],
"export": [{tr:"f. ihraç etmek",yz:4}, {tr:"i. ihracat, dışsatım",yz:3}],
"express": [{tr:"f. ifade etmek, dile getirmek",yz:4}, {tr:"s. ekspres, hızlı",yz:1}],
"eye": [{tr:"i. göz",yz:4}, {tr:"f. dikkatle süzmek, gözlemek",yz:1}],
"failure": [{tr:"i. arıza, yetmezlik",yz:3}, {tr:"i. başarısızlık",yz:4}],
"farm": [{tr:"i. çiftlik",yz:4}, {tr:"f. çiftçilik yapmak, toprağı işlemek",yz:2}],
"fat": [{tr:"i. yağ",yz:4}, {tr:"s. şişman, yağlı",yz:2}],
"father": [{tr:"i. baba, kurucu",yz:4}, {tr:"f. -in babası olmak",yz:1}],
"favour": [{tr:"f. desteklemek, tercih etmek",yz:4}, {tr:"i. iyilik, lütuf",yz:1}],
"fear": [{tr:"f. korkmak",yz:3}, {tr:"i. korku",yz:4}],
"feed": [{tr:"f. beslemek",yz:4}, {tr:"i. yem",yz:2}],
"fight": [{tr:"f. savaşmak, mücadele etmek",yz:4}, {tr:"i. mücadele, kavga",yz:3}],
"film": [{tr:"i. film",yz:4}, {tr:"i. ince tabaka, film",yz:2}],
"final": [{tr:"s. son, nihai",yz:4}, {tr:"i. final (sınav/maç)",yz:1}],
"fish": [{tr:"f. balık tutmak",yz:2}, {tr:"i. balık",yz:4}],
"fit": [{tr:"s. formda, sağlıklı",yz:3}, {tr:"s. uygun",yz:4}],
"fix": [{tr:"f. onarmak, tamir etmek, düzeltmek, sabitlemek",yz:4}, {tr:"i. çıkmaz, zor durum",yz:1}],
"flight": [{tr:"i. uçuş",yz:4}, {tr:"i. kaçış",yz:2}],
"flood": [{tr:"i. sel, taşkın",yz:4}, {tr:"f. su basmak",yz:3}],
"flow": [{tr:"i. akış, akım",yz:4}, {tr:"f. akmak",yz:3}],
"fly": [{tr:"f. uçmak",yz:4}, {tr:"i. sinek",yz:1}],
"forward": [{tr:"z. ileri, ileriye doğru",yz:4}, {tr:"f. iletmek, göndermek",yz:1}],
"fossil": [{tr:"i. fosil",yz:3}, {tr:"s. fosil (yakıt)",yz:4}],
"foundation": [{tr:"i. vakıf, kuruluş",yz:3}, {tr:"i. temel",yz:4}],
"free": [{tr:"s. özgür; ücretsiz; serbest",yz:4}, {tr:"f. serbest bırakmak, kurtarmak",yz:2}],
"fuel": [{tr:"f. körüklemek, beslemek",yz:4}, {tr:"i. yakıt",yz:3}],
"full": [{tr:"s. dolu, tam",yz:4}, {tr:"z. tamamen",yz:1}],
"fund": [{tr:"f. finanse etmek, fon sağlamak",yz:4}, {tr:"i. fon, kaynak",yz:3}],
"fundamental": [{tr:"s. temel, esas",yz:4}, {tr:"i. temel ilke",yz:2}],
"further": [{tr:"f. ilerletmek, geliştirmek",yz:2}, {tr:"s./z. daha fazla, ek",yz:4}],
"game": [{tr:"i. oyun",yz:4}, {tr:"s. istekli, gönüllü",yz:1}],
"gas": [{tr:"i. gaz",yz:4}, {tr:"i. benzin",yz:2}],
"gather": [{tr:"f. toplamak",yz:4}, {tr:"f. bir araya gelmek, toplanmak",yz:3}],
"general": [{tr:"s. genel",yz:4}, {tr:"i. general (askeri rütbe)",yz:1}],
"grant": [{tr:"i. hibe, burs",yz:3}, {tr:"f. vermek, bahşetmek; kabul etmek",yz:4}],
"ground": [{tr:"f. dayandırmak, temellendirmek",yz:2}, {tr:"i. zemin, yer; temel",yz:4}],
"guarantee": [{tr:"f. garanti etmek, güvence vermek",yz:4}, {tr:"i. garanti, güvence",yz:3}],
"guess": [{tr:"f. tahmin etmek",yz:3}, {tr:"i. tahmin",yz:2}],
"handle": [{tr:"f. ele almak, başa çıkmak",yz:4}, {tr:"i. sap, kulp, tutamaç",yz:1}],
"harm": [{tr:"f. zarar vermek",yz:4}, {tr:"i. zarar",yz:3}],
"head": [{tr:"f. yönetmek, yönelmek",yz:3}, {tr:"i. baş, kafa, yönetici",yz:4}],
"heat": [{tr:"i. ısı, sıcaklık",yz:4}, {tr:"f. ısıtmak",yz:2}],
"heavy": [{tr:"s. yoğun, şiddetli",yz:4}, {tr:"s. ağır",yz:3}],
"held": [{tr:"s. yaygın olarak kabul edilen (widely held)",yz:4}, {tr:"s. tutulan, sahip olunan",yz:2}],
"here": [{tr:"z. burada, buraya",yz:4}, {tr:"i. burası",yz:1}],
"highlight": [{tr:"f. vurgulamak, öne çıkarmak",yz:4}, {tr:"i. öne çıkan nokta, doruk",yz:2}],
"hope": [{tr:"f. ummak",yz:3}, {tr:"i. umut",yz:3}],
"host": [{tr:"f. ev sahipliği yapmak, barındırmak",yz:4}, {tr:"i. ev sahibi",yz:3}],
"house": [{tr:"f. barındırmak",yz:3}, {tr:"i. ev, konut",yz:4}],
"hunt": [{tr:"f. avlamak, avlanmak",yz:4}, {tr:"f. aramak, peşinde olmak",yz:2}],
"ice": [{tr:"i. buz",yz:4}, {tr:"f. buzla kaplamak, donmak",yz:1}],
"ill": [{tr:"s. kötü, zararlı",yz:3}, {tr:"s. hasta",yz:4}],
"implement": [{tr:"f. uygulamak, yürürlüğe koymak",yz:4}, {tr:"i. alet, araç",yz:1}],
"impression": [{tr:"i. izlenim",yz:4}, {tr:"i. baskı, iz",yz:1}],
"initial": [{tr:"s. ilk, başlangıç",yz:4}, {tr:"i. baş harf",yz:1}],
"initiate": [{tr:"f. başlatmak",yz:4}, {tr:"i. yeni üye, acemi",yz:1}],
"inside": [{tr:"z. içeride, içeriye",yz:4}, {tr:"s. iç, dahili",yz:2}],
"intellectual": [{tr:"s. entelektüel, zihinsel, akli",yz:4}, {tr:"i. aydın, entelektüel",yz:2}],
"introduce": [{tr:"f. başlatmak, yürürlüğe koymak",yz:4}, {tr:"f. tanıtmak, sunmak",yz:3}],
"invent": [{tr:"f. icat etmek, bulmak",yz:4}, {tr:"f. uydurmak",yz:2}],
"involved": [{tr:"s. dahil olan, ilgili",yz:4}, {tr:"s. karmaşık",yz:2}],
"keeping": [{tr:"i. uyum (in keeping with)",yz:3}, {tr:"i. koruma, muhafaza, saklama",yz:2}],
"key": [{tr:"s. kilit, çok önemli",yz:4}, {tr:"i. anahtar",yz:2}],
"label": [{tr:"f. etiketlemek, nitelendirmek",yz:3}, {tr:"i. etiket",yz:3}],
"labour": [{tr:"i. emek, iş gücü",yz:4}, {tr:"i. doğum, doğum sancısı",yz:1}],
"later": [{tr:"z. daha sonra",yz:4}, {tr:"s. sonraki",yz:3}],
"law": [{tr:"i. hukuk",yz:3}, {tr:"i. kanun, yasa",yz:4}],
"layer": [{tr:"i. katman, tabaka",yz:4}, {tr:"f. katman katman düzenlemek",yz:1}],
"let": [{tr:"f. izin vermek, bırakmak",yz:4}, {tr:"i. kiralık (mülk)",yz:1}],
"line": [{tr:"i. çizgi, hat, sınır",yz:4}, {tr:"i. sıra, kuyruk",yz:2}],
"list": [{tr:"i. liste",yz:3}, {tr:"f. listelemek, sıralamak",yz:2}],
"local": [{tr:"s. yerel",yz:4}, {tr:"i. yerel sakin",yz:2}],
"longer": [{tr:"z. daha uzun süre",yz:4}, {tr:"s. daha uzun",yz:3}],
"looking": [{tr:"i. bakış, arama",yz:1}, {tr:"s. (bileşik) ...görünümlü",yz:3}],
"love": [{tr:"i. sevgi, aşk",yz:3}, {tr:"f. sevmek, çok hoşlanmak",yz:3}],
"lower": [{tr:"f. düşürmek, azaltmak",yz:4}, {tr:"s. daha düşük, alt",yz:3}],
"machine": [{tr:"i. makine",yz:4}, {tr:"f. makineyle işlemek",yz:1}],
"make-up": [{tr:"i. yapı, bileşim",yz:3}, {tr:"i. makyaj",yz:2}],
"manage": [{tr:"f. üstesinden gelmek, kontrol altında tutmak",yz:4}, {tr:"f. yönetmek, idare etmek",yz:3}],
"manipulate": [{tr:"f. manipüle etmek",yz:4}, {tr:"f. ustaca kullanmak, elle işlemek",yz:2}],
"manual": [{tr:"i. kılavuz, el kitabı",yz:2}, {tr:"s. elle yapılan",yz:3}],
"mark": [{tr:"f. işaretlemek",yz:4}, {tr:"i. not, puan",yz:2}],
"market": [{tr:"f. pazarlamak",yz:2}, {tr:"i. pazar, piyasa",yz:4}],
"mass": [{tr:"i. kütle",yz:3}, {tr:"s. kitlesel",yz:4}],
"meaning": [{tr:"i. anlam",yz:4}, {tr:"s. anlamlı, çok şey ifade eden",yz:2}],
"meet": [{tr:"f. karşılamak",yz:4}, {tr:"f. buluşmak, tanışmak",yz:2}],
"memory": [{tr:"i. hafıza, bellek",yz:4}, {tr:"i. anı",yz:2}],
"message": [{tr:"i. mesaj, ileti",yz:4}, {tr:"f. mesaj göndermek",yz:1}],
"metal": [{tr:"i. metal, maden",yz:4}, {tr:"s. metalden yapılmış",yz:2}],
"middle": [{tr:"i./s. orta",yz:4}, {tr:"f. ortalamak",yz:1}],
"military": [{tr:"s. askeri",yz:4}, {tr:"i. ordu, askeri güç",yz:3}],
"minute": [{tr:"s. çok küçük, ayrıntılı",yz:4}, {tr:"i. dakika",yz:2}],
"monitor": [{tr:"f. izlemek, denetlemek",yz:4}, {tr:"i. ekran, monitör",yz:1}],
"mother": [{tr:"i. anne",yz:4}, {tr:"f. annelik etmek, kollayıp gözetmek",yz:1}],
"motion": [{tr:"i. hareket, devinim",yz:4}, {tr:"i. önerge",yz:2}],
"muscle": [{tr:"i. kas",yz:4}, {tr:"f. zorla ilerlemek",yz:1}],
"name": [{tr:"f. adlandırmak, atamak",yz:3}, {tr:"i. isim, ad",yz:4}],
"nation": [{tr:"i. ülke, devlet",yz:4}, {tr:"i. ulus, millet",yz:3}],
"native": [{tr:"s. yerli, doğuştan",yz:4}, {tr:"i. yerli (kişi)",yz:2}],
"near": [{tr:"e. yakınında",yz:4}, {tr:"f. yaklaşmak",yz:2}],
"network": [{tr:"i. ağ, şebeke",yz:4}, {tr:"f. bağlantı kurmak",yz:1}],
"neutral": [{tr:"s. tarafsız",yz:4}, {tr:"s. nötr",yz:2}],
"normal": [{tr:"s. normal, olağan",yz:4}, {tr:"i. norm, ortalama",yz:2}],
"north": [{tr:"z. kuzeye",yz:3}, {tr:"i. kuzey",yz:4}],
"note": [{tr:"f. not etmek, belirtmek, dikkat çekmek",yz:4}, {tr:"i. not",yz:2}],
"object": [{tr:"f. itiraz etmek",yz:3}, {tr:"i. nesne, obje, amaç",yz:4}],
"objective": [{tr:"s. nesnel, tarafsız",yz:4}, {tr:"i. amaç, hedef",yz:3}],
"observe": [{tr:"f. gözlemlemek",yz:4}, {tr:"f. belirtmek, söylemek",yz:2}],
"oil": [{tr:"f. yağlamak",yz:1}, {tr:"i. petrol, yağ",yz:4}],
"online": [{tr:"s. çevrimiçi",yz:3}, {tr:"z. çevrimiçi olarak",yz:3}],
"open": [{tr:"f. açmak, açılmak",yz:4}, {tr:"s. açık",yz:3}],
"organ": [{tr:"i. organ (vücut)",yz:4}, {tr:"i. org (müzik aleti)",yz:1}],
"organization": [{tr:"i. örgüt, kuruluş, organizasyon",yz:4}, {tr:"i. düzenleme",yz:3}],
"original": [{tr:"s. özgün, orijinal",yz:4}, {tr:"i. asıl nüsha, orijinal",yz:2}],
"otherwise": [{tr:"z. aksi takdirde, başka türlü",yz:4}, {tr:"s. farklı",yz:2}],
"outside": [{tr:"z./e. dışarıda, dışında",yz:4}, {tr:"i. dış taraf",yz:2}],
"overall": [{tr:"s. genel, toplam",yz:4}, {tr:"i. tulum (giysi)",yz:1}],
"pain": [{tr:"i. ağrı, acı",yz:4}, {tr:"f. acı vermek",yz:1}],
"paper": [{tr:"i. makale, bildiri",yz:4}, {tr:"i. kağıt",yz:2}],
"parts": [{tr:"i. yöreler, bölgeler",yz:3}, {tr:"i. parçalar, kısımlar",yz:4}],
"pass": [{tr:"f. (yasa) çıkarmak",yz:3}, {tr:"f. geçmek (zaman, mekân)",yz:4}],
"patient": [{tr:"i. hasta",yz:4}, {tr:"s. sabırlı",yz:2}],
"pattern": [{tr:"i. örüntü, desen",yz:4}, {tr:"f. desenlendirmek",yz:1}],
"peer": [{tr:"i. akran, eş",yz:4}, {tr:"f. dikkatle bakmak, gözünü dikmek",yz:2}],
"personality": [{tr:"i. kişilik",yz:4}, {tr:"i. ünlü kişi (medya)",yz:1}],
"phone": [{tr:"i. telefon",yz:4}, {tr:"f. telefon etmek, aramak",yz:2}],
"pick": [{tr:"f. toplamak, koparmak",yz:2}, {tr:"f. seçmek",yz:4}],
"picture": [{tr:"f. tasavvur etmek, gözünde canlandırmak",yz:2}, {tr:"i. resim, fotoğraf",yz:4}],
"plus": [{tr:"bağ. ayrıca, -e ek olarak",yz:3}, {tr:"i. artı, avantaj",yz:2}],
"pose": [{tr:"f. oluşturmak, teşkil etmek",yz:4}, {tr:"i. duruş, poz",yz:1}],
"position": [{tr:"i. konum, pozisyon",yz:4}, {tr:"i. görev, makam",yz:3}],
"preliminary": [{tr:"s. ön, hazırlık niteliğinde",yz:4}, {tr:"i. ön hazırlık, ön aşama",yz:1}],
"preserve": [{tr:"f. korumak, muhafaza etmek",yz:4}, {tr:"i. koruma alanı",yz:2}],
"price": [{tr:"i. fiyat, bedel",yz:4}, {tr:"f. fiyatlandırmak, fiyat koymak",yz:1}],
"progress": [{tr:"i. ilerleme, gelişme",yz:4}, {tr:"f. ilerlemek",yz:3}],
"purchase": [{tr:"f. satın almak",yz:4}, {tr:"i. satın alma",yz:3}],
"quality": [{tr:"i. kalite, nitelik",yz:4}, {tr:"s. kaliteli",yz:2}],
"quick": [{tr:"s. hızlı, çabuk",yz:4}, {tr:"z. çabuk (gayriresmî)",yz:1}],
"race": [{tr:"i. yarış",yz:3}, {tr:"i. ırk",yz:3}],
"rain": [{tr:"i. yağmur",yz:4}, {tr:"f. yağmur yağmak",yz:2}],
"react": [{tr:"f. tepki vermek",yz:4}, {tr:"f. tepkimeye girmek (kimya)",yz:2}],
"real": [{tr:"s. gerçek, hakiki",yz:4}, {tr:"z. gerçekten (gayriresmî)",yz:1}],
"recognition": [{tr:"i. takdir, kabul görme",yz:4}, {tr:"i. tanıma",yz:3}],
"recover": [{tr:"f. iyileşmek, toparlanmak",yz:4}, {tr:"f. geri kazanmak",yz:3}],
"reflect": [{tr:"f. yansıtmak",yz:4}, {tr:"f. (üzerinde) düşünmek",yz:3}],
"regular": [{tr:"s. düzenli",yz:4}, {tr:"i. daimi müşteri",yz:1}],
"relate": [{tr:"f. ilgili olmak, ilişkili olmak",yz:4}, {tr:"f. anlatmak",yz:1}],
"relative": [{tr:"s. göreli, nispi; i. akraba",yz:4}, {tr:"i. akraba",yz:2}],
"religious": [{tr:"s. dini",yz:4}, {tr:"s. dindar",yz:2}],
"report": [{tr:"i. rapor",yz:4}, {tr:"f. bildirmek, rapor etmek, haber vermek",yz:4}],
"represent": [{tr:"f. temsil etmek",yz:4}, {tr:"f. ifade etmek, betimlemek",yz:2}],
"rest": [{tr:"f. dinlenmek",yz:2}, {tr:"i. geri kalan",yz:4}],
"reverse": [{tr:"f. tersine çevirmek, iptal etmek",yz:4}, {tr:"s. ters, zıt",yz:3}],
"revolution": [{tr:"i. devrim",yz:4}, {tr:"i. dönüş, devir (fiziksel)",yz:1}],
"ritual": [{tr:"i. ayin, tören, ritüel",yz:4}, {tr:"s. ayinle ilgili, alışılagelmiş",yz:2}],
"rock": [{tr:"i. kaya, taş",yz:4}, {tr:"f. sallamak, sarsmak",yz:2}],
"room": [{tr:"i. yer, alan, imkan",yz:4}, {tr:"i. oda",yz:2}],
"root": [{tr:"i. kök, köken; f. kök salmak, dayanmak",yz:4}, {tr:"f. kök salmak, dayanmak",yz:2}],
"rule": [{tr:"f. yönetmek, hükmetmek",yz:3}, {tr:"i. kural, yönetmelik",yz:4}],
"safe": [{tr:"s. güvenli, emniyetli",yz:4}, {tr:"i. kasa",yz:1}],
"save": [{tr:"f. kurtarmak",yz:4}, {tr:"f. biriktirmek, tasarruf etmek",yz:3}],
"saw": [{tr:"i. testere",yz:3}, {tr:"f. testereyle kesmek",yz:2}],
"scale": [{tr:"f. ölçeklendirmek",yz:1}, {tr:"i. ölçek, boyut",yz:4}],
"scholar": [{tr:"i. bilim insanı, akademisyen",yz:4}, {tr:"i. burslu öğrenci",yz:1}],
"search": [{tr:"i. arama",yz:3}, {tr:"f. aramak",yz:4}],
"security": [{tr:"i. güvenlik, emniyet",yz:4}, {tr:"i. teminat, güvence (finansal)",yz:1}],
"select": [{tr:"f. seçmek",yz:4}, {tr:"s. seçkin, seçilmiş",yz:1}],
"separate": [{tr:"f. ayırmak, ayrılmak",yz:4}, {tr:"s. ayrı, farklı",yz:3}],
"serve": [{tr:"f. hizmet etmek",yz:4}, {tr:"f. sunmak, servis yapmak",yz:2}],
"sex": [{tr:"i. cinsiyet",yz:4}, {tr:"i. cinsellik",yz:2}],
"share": [{tr:"f. paylaşmak",yz:4}, {tr:"i. pay, hisse",yz:3}],
"shift": [{tr:"i. değişim, kayma",yz:4}, {tr:"i. vardiya",yz:2}],
"side": [{tr:"f. taraf tutmak",yz:2}, {tr:"i. taraf, yan",yz:4}],
"sign": [{tr:"i. işaret, belirti",yz:4}, {tr:"f. imzalamak",yz:2}],
"signal": [{tr:"i. sinyal, işaret",yz:4}, {tr:"f. işaret etmek, bildirmek",yz:3}],
"site": [{tr:"i. alan, saha, yer",yz:4}, {tr:"f. konumlandırmak",yz:1}],
"skin": [{tr:"i. deri, cilt",yz:4}, {tr:"f. derisini yüzmek",yz:1}],
"sleep": [{tr:"i. uyku",yz:4}, {tr:"f. uyumak",yz:3}],
"slow": [{tr:"f. yavaşlamak, yavaşlatmak",yz:3}, {tr:"s./z. yavaş",yz:4}],
"smell": [{tr:"f. koklamak; koku almak/vermek",yz:3}, {tr:"i. koku",yz:2}],
"soil": [{tr:"i. toprak",yz:4}, {tr:"f. kirletmek, lekelemek",yz:1}],
"solution": [{tr:"i. çözüm",yz:4}, {tr:"i. çözelti (kimyasal)",yz:2}],
"sophisticate": [{tr:"i. görmüş geçirmiş kimse",yz:3}, {tr:"f. inceltmek, karmaşıklaştırmak, geliştirmek",yz:2}],
"speaker": [{tr:"i. konuşmacı",yz:4}, {tr:"i. hoparlör",yz:1}],
"special": [{tr:"s. özel",yz:4}, {tr:"i. özel program/ürün",yz:1}],
"speed": [{tr:"f. hızlanmak, hızlandırmak",yz:2}, {tr:"i. hız",yz:4}],
"sport": [{tr:"i. spor",yz:4}, {tr:"f. takınmak, sergilemek",yz:1}],
"spring": [{tr:"i. ilkbahar",yz:4}, {tr:"i. kaynak, pınar",yz:2}],
"stable": [{tr:"s. istikrarlı, dengeli",yz:4}, {tr:"i. ahır",yz:1}],
"stage": [{tr:"i. aşama, evre",yz:4}, {tr:"f. sahnelemek, düzenlemek",yz:2}],
"stand": [{tr:"f. durmak, ayakta durmak",yz:4}, {tr:"i. duruş, tavır",yz:2}],
"standard": [{tr:"i. standart, ölçüt",yz:4}, {tr:"s. standart, alışılmış",yz:3}],
"star": [{tr:"i. yıldız",yz:4}, {tr:"f. başrolde oynamak, baş rolü üstlenmek",yz:1}],
"step": [{tr:"f. adım atmak",yz:3}, {tr:"i. adım",yz:4}],
"stone": [{tr:"i. taş",yz:4}, {tr:"f. taşlamak",yz:1}],
"store": [{tr:"f. depolamak, saklamak",yz:4}, {tr:"i. mağaza",yz:2}],
"strike": [{tr:"i. grev",yz:3}, {tr:"f. vurmak, çarpmak",yz:3}],
"struggle": [{tr:"f. mücadele etmek, uğraşmak",yz:4}, {tr:"i. mücadele",yz:3}],
"substance": [{tr:"i. madde",yz:4}, {tr:"i. öz, esas",yz:3}],
"sun": [{tr:"i. güneş",yz:4}, {tr:"f. güneşlenmek",yz:1}],
"supply": [{tr:"i. arz, tedarik, kaynak",yz:4}, {tr:"f. sağlamak",yz:3}],
"surface": [{tr:"f. yüzeye çıkmak, ortaya çıkmak",yz:3}, {tr:"i. yüzey",yz:4}],
"surprise": [{tr:"f. şaşırtmak",yz:3}, {tr:"i. sürpriz, şaşkınlık",yz:3}],
"taken": [{tr:"s. dolu, meşgul",yz:3}, {tr:"s. ele geçirilmiş",yz:1}],
"target": [{tr:"i. hedef, amaç",yz:4}, {tr:"f. hedeflemek, hedef almak",yz:3}],
"taste": [{tr:"i. tat, zevk",yz:3}, {tr:"f. tat almak, tatmak",yz:2}],
"teaching": [{tr:"i. öğreti, doktrin",yz:3}, {tr:"i. öğretim",yz:4}],
"text": [{tr:"i. metin",yz:4}, {tr:"f. mesaj göndermek, mesajlaşmak",yz:1}],
"thinking": [{tr:"i. düşünme, düşünce",yz:4}, {tr:"s. düşünen",yz:1}],
"title": [{tr:"i. başlık",yz:4}, {tr:"i. unvan",yz:2}],
"top": [{tr:"i. üst, tepe, doruk",yz:4}, {tr:"f. aşmak",yz:2}],
"total": [{tr:"s. toplam, tüm",yz:4}, {tr:"f. toplamak",yz:1}],
"trace": [{tr:"f. izini sürmek, saptamak",yz:4}, {tr:"i. iz",yz:3}],
"track": [{tr:"f. izlemek, takip etmek",yz:4}, {tr:"i. iz; parkur, yol",yz:2}],
"trade": [{tr:"i. ticaret",yz:4}, {tr:"f. ticaret yapmak",yz:3}],
"transmit": [{tr:"f. (hastalık) bulaştırmak",yz:3}, {tr:"f. iletmek, aktarmak",yz:4}],
"transport": [{tr:"i. ulaşım, taşımacılık",yz:4}, {tr:"f. taşımak, nakletmek",yz:3}],
"travel": [{tr:"f. yayılmak, ilerlemek",yz:3}, {tr:"f. seyahat etmek",yz:4}],
"treat": [{tr:"f. tedavi etmek",yz:4}, {tr:"f. davranmak, muamele etmek",yz:3}],
"tree": [{tr:"i. ağaç",yz:4}, {tr:"f. ağaçlandırmak",yz:1}],
"trend": [{tr:"i. eğilim, gidişat",yz:4}, {tr:"f. yönelmek",yz:1}],
"trigger": [{tr:"f. tetiklemek, başlatmak",yz:4}, {tr:"i. tetik",yz:1}],
"ultimate": [{tr:"s. nihai, en son, temel",yz:4}, {tr:"i. en üstünü, doruk noktası",yz:1}],
"unknown": [{tr:"s. bilinmeyen",yz:4}, {tr:"i. bilinmeyen kişi/şey",yz:1}],
"visit": [{tr:"f. ziyaret etmek",yz:3}, {tr:"i. ziyaret",yz:3}],
"walk": [{tr:"f. yürümek",yz:3}, {tr:"i. yürüyüş",yz:2}],
"warming": [{tr:"i. ısınma",yz:4}, {tr:"s. ısıtan",yz:1}],
"waste": [{tr:"i. atık, israf",yz:4}, {tr:"f. israf etmek, boşa harcamak",yz:3}],
"watch": [{tr:"f. izlemek, gözlemek",yz:4}, {tr:"i. kol saati",yz:1}],
"wave": [{tr:"i. dalga",yz:4}, {tr:"f. el sallamak",yz:1}],
"weather": [{tr:"i. hava, hava durumu",yz:4}, {tr:"f. atlatmak, dayanmak",yz:2}],
"weight": [{tr:"i. ağırlık",yz:4}, {tr:"f. ağırlık vermek",yz:1}],
"west": [{tr:"z. batıya",yz:2}, {tr:"i. batı",yz:3}],
"western": [{tr:"s. batı, batıdaki",yz:4}, {tr:"i. kovboy filmi",yz:1}],
"white": [{tr:"s. beyaz",yz:4}, {tr:"i. beyaz renk",yz:2}, {tr:"f. beyazlatmak, örtmek",yz:1}],
"wide": [{tr:"s. geniş; yaygın",yz:4}, {tr:"z. ardına kadar, tamamen",yz:1}],
"wild": [{tr:"i. (the wild) doğa, yaban hayatı",yz:3}, {tr:"s. vahşi, yabani",yz:4}],
"wind": [{tr:"i. rüzgâr",yz:4}, {tr:"f. sarmak, dolamak; kıvrılmak",yz:2}],
"words": [{tr:"i. sözler, sözcükler",yz:4}, {tr:"i. tartışma, ağız kavgası",yz:1}],
"works": [{tr:"i. eserler",yz:4}, {tr:"i. tesis, fabrika",yz:1}]
};
