/* ============================================================
   Anlam yıldızları — dönüştürücü girdisi (site bu dosyayı YÜKLEMEZ)

   Çok anlamlı kelimelerde her anlamın YDS önemi: 4 = sınavda asıl
   sorulan anlam, 1 = nadir/ikincil. Her kelimenin en yüksek yıldızı
   en az 3'tür. listeyi-aktar.py bunu okuyup anlamlara "yz" alanı
   olarak yazar ve anlamları yıldıza göre büyükten küçüğe sıralar.

   Yıldız anlam METNİNE bağlıdır; kaynak listedeki sıra değişse bile
   eşleşme bozulmaz. Metin değişirse o anlam yıldızsız kalır.
   Üretim: tools/test-uretim (agent + yildiz-dogrula.py) · 150 kelime
   ============================================================ */

window.ANLAM_YILDIZ = {
"academic": [{tr:"s. akademik",yz:4}, {tr:"i. akademisyen",yz:3}],
"account": [{tr:"f. (for) oluşturmak, açıklamak",yz:4}, {tr:"i. hesap",yz:2}],
"adapt": [{tr:"f. uyum sağlamak",yz:4}, {tr:"f. uyarlamak",yz:2}],
"aim": [{tr:"f. amaçlamak",yz:4}, {tr:"i. amaç, hedef",yz:3}],
"appearance": [{tr:"i. ortaya çıkış",yz:3}, {tr:"i. görünüş, görünüm",yz:4}],
"application": [{tr:"i. uygulama",yz:4}, {tr:"i. başvuru",yz:3}],
"apply": [{tr:"f. uygulamak",yz:4}, {tr:"f. başvurmak",yz:3}],
"approach": [{tr:"i. yaklaşım",yz:4}, {tr:"f. yaklaşmak",yz:3}],
"appropriate": [{tr:"s. uygun",yz:4}, {tr:"f. ayırmak, tahsis etmek",yz:1}],
"argue": [{tr:"f. iddia etmek, savunmak",yz:4}, {tr:"f. tartışmak, atışmak",yz:2}],
"article": [{tr:"i. makale",yz:4}, {tr:"i. madde",yz:2}],
"assume": [{tr:"f. varsaymak",yz:4}, {tr:"f. üstlenmek",yz:2}],
"attack": [{tr:"f. saldırmak",yz:3}, {tr:"i. saldırı",yz:4}],
"balance": [{tr:"i. denge",yz:4}, {tr:"f. dengelemek",yz:2}],
"bear": [{tr:"f. taşımak, katlanmak",yz:4}, {tr:"i. ayı",yz:2}],
"beginning": [{tr:"i. başlangıç, başlama",yz:4}, {tr:"s. başlangıç düzeyinde, yeni başlayan",yz:1}],
"behind": [{tr:"e. arkasında, gerisinde",yz:4}, {tr:"z. geride",yz:2}],
"bite": [{tr:"f. ısırmak, sokmak",yz:3}, {tr:"i. ısırık",yz:2}],
"came": [{tr:"f. (come'un geçmiş biçimi) geldi",yz:4}, {tr:"i. (nadir) vitray kurşun çıtası",yz:1}],
"career": [{tr:"i. kariyer, meslek hayatı",yz:4}, {tr:"f. hızla ve kontrolsüzce gitmek",yz:1}],
"chance": [{tr:"i. şans, olasılık, fırsat",yz:4}, {tr:"s. tesadüfi",yz:2}],
"character": [{tr:"i. karakter, özellik",yz:3}, {tr:"i. kişilik",yz:4}],
"claim": [{tr:"f. iddia etmek",yz:4}, {tr:"i. iddia",yz:3}],
"cold": [{tr:"s. soğuk",yz:4}, {tr:"i. soğuk algınlığı",yz:2}],
"conflict": [{tr:"i. çatışma, anlaşmazlık",yz:4}, {tr:"f. çelişmek, çatışmak",yz:3}],
"constant": [{tr:"i. sabit (matematik)",yz:1}, {tr:"s. sabit, sürekli",yz:4}],
"contact": [{tr:"i. temas, iletişim",yz:4}, {tr:"f. temas kurmak",yz:2}],
"contrast": [{tr:"i. karşıtlık, zıtlık, tezat",yz:4}, {tr:"f. karşılaştırmak, kıyaslamak",yz:2}],
"cover": [{tr:"f. kaplamak, örtmek",yz:4}, {tr:"f. kapsamak, içermek",yz:3}],
"current": [{tr:"i. akım",yz:3}, {tr:"s. güncel, şimdiki",yz:4}],
"date": [{tr:"f. tarihini belirlemek",yz:3}, {tr:"i. randevu",yz:1}],
"debate": [{tr:"f. tartışmak",yz:3}, {tr:"i. tartışma",yz:4}],
"deep": [{tr:"s./z. derin",yz:4}, {tr:"i. derinlik",yz:1}],
"demonstrate": [{tr:"f. göstermek, kanıtlamak",yz:4}, {tr:"f. gösteri yapmak",yz:2}],
"detail": [{tr:"i. ayrıntı, detay",yz:4}, {tr:"f. ayrıntılandırmak, ayrıntılarıyla açıklamak",yz:2}],
"die": [{tr:"f. ölmek",yz:4}, {tr:"i. kalıp, zar",yz:1}],
"direct": [{tr:"f. yönetmek, yönlendirmek",yz:2}, {tr:"s./z. doğrudan",yz:4}],
"display": [{tr:"f. sergilemek, göstermek",yz:4}, {tr:"i. sergi, gösterim",yz:2}],
"done": [{tr:"s. bitmiş, tamamlanmış",yz:4}, {tr:"s. pişmiş",yz:1}],
"draw": [{tr:"f. (sonuç) çıkarmak",yz:4}, {tr:"f. çizmek",yz:2}],
"drink": [{tr:"i. içecek",yz:3}, {tr:"f. içmek",yz:4}],
"element": [{tr:"i. öge, unsur",yz:4}, {tr:"i. element (kimyasal)",yz:2}],
"else": [{tr:"z. aksi halde",yz:3}, {tr:"z. başka",yz:4}],
"engineer": [{tr:"i. mühendis",yz:4}, {tr:"f. tasarlamak, planlamak, düzenlemek",yz:2}],
"entire": [{tr:"s. bütün, tüm, tam",yz:4}, {tr:"i. (nadir) aygır",yz:1}],
"essential": [{tr:"s. temel, zorunlu",yz:4}, {tr:"i. temel gereksinim, olmazsa olmaz unsur",yz:2}],
"experiment": [{tr:"i. deney",yz:4}, {tr:"f. deney yapmak",yz:2}],
"eye": [{tr:"i. göz",yz:4}, {tr:"f. dikkatle süzmek, gözlemek",yz:1}],
"fat": [{tr:"i. yağ",yz:4}, {tr:"s. şişman, yağlı",yz:2}],
"father": [{tr:"i. baba, kurucu",yz:4}, {tr:"f. -in babası olmak",yz:1}],
"fear": [{tr:"f. korkmak",yz:3}, {tr:"i. korku",yz:4}],
"feed": [{tr:"f. beslemek",yz:4}, {tr:"i. yem",yz:2}],
"fight": [{tr:"f. savaşmak, mücadele etmek",yz:4}, {tr:"i. mücadele, kavga",yz:3}],
"film": [{tr:"i. film",yz:4}, {tr:"i. ince tabaka, film",yz:2}],
"fish": [{tr:"f. balık tutmak",yz:2}, {tr:"i. balık",yz:4}],
"flood": [{tr:"i. sel, taşkın",yz:4}, {tr:"f. su basmak",yz:3}],
"fossil": [{tr:"i. fosil",yz:3}, {tr:"s. fosil (yakıt)",yz:4}],
"free": [{tr:"s. özgür; ücretsiz; serbest",yz:4}, {tr:"f. serbest bırakmak, kurtarmak",yz:2}],
"full": [{tr:"s. dolu, tam",yz:4}, {tr:"z. tamamen",yz:1}],
"further": [{tr:"f. ilerletmek, geliştirmek",yz:2}, {tr:"s./z. daha fazla, ek",yz:4}],
"game": [{tr:"i. oyun",yz:4}, {tr:"s. istekli, gönüllü",yz:1}],
"gas": [{tr:"i. gaz",yz:4}, {tr:"i. benzin",yz:2}],
"general": [{tr:"s. genel",yz:4}, {tr:"i. general (askeri rütbe)",yz:1}],
"guess": [{tr:"f. tahmin etmek",yz:3}, {tr:"i. tahmin",yz:2}],
"heat": [{tr:"i. ısı, sıcaklık",yz:4}, {tr:"f. ısıtmak",yz:2}],
"heavy": [{tr:"s. yoğun, şiddetli",yz:4}, {tr:"s. ağır",yz:3}],
"hunt": [{tr:"f. avlamak, avlanmak",yz:4}, {tr:"f. aramak, peşinde olmak",yz:2}],
"ill": [{tr:"s. kötü, zararlı",yz:3}, {tr:"s. hasta",yz:4}],
"initial": [{tr:"s. ilk, başlangıç",yz:4}, {tr:"i. baş harf",yz:1}],
"inside": [{tr:"z. içeride, içeriye",yz:4}, {tr:"s. iç, dahili",yz:2}],
"involved": [{tr:"s. dahil olan, ilgili",yz:4}, {tr:"s. karmaşık",yz:2}],
"key": [{tr:"s. kilit, çok önemli",yz:4}, {tr:"i. anahtar",yz:2}],
"later": [{tr:"z. daha sonra",yz:4}, {tr:"s. sonraki",yz:3}],
"law": [{tr:"i. hukuk",yz:3}, {tr:"i. kanun, yasa",yz:4}],
"layer": [{tr:"i. katman, tabaka",yz:4}, {tr:"f. katman katman düzenlemek",yz:1}],
"let": [{tr:"f. izin vermek, bırakmak",yz:4}, {tr:"i. kiralık (mülk)",yz:1}],
"local": [{tr:"s. yerel",yz:4}, {tr:"i. yerel sakin",yz:2}],
"longer": [{tr:"z. daha uzun süre",yz:4}, {tr:"s. daha uzun",yz:3}],
"looking": [{tr:"i. bakış, arama",yz:1}, {tr:"s. (bileşik) ...görünümlü",yz:3}],
"make-up": [{tr:"i. yapı, bileşim",yz:3}, {tr:"i. makyaj",yz:2}],
"manipulate": [{tr:"f. manipüle etmek",yz:4}, {tr:"f. ustaca kullanmak, elle işlemek",yz:2}],
"market": [{tr:"f. pazarlamak",yz:2}, {tr:"i. pazar, piyasa",yz:4}],
"mass": [{tr:"i. kütle",yz:3}, {tr:"s. kitlesel",yz:4}],
"meet": [{tr:"f. karşılamak",yz:4}, {tr:"f. buluşmak, tanışmak",yz:2}],
"memory": [{tr:"i. hafıza, bellek",yz:4}, {tr:"i. anı",yz:2}],
"middle": [{tr:"i./s. orta",yz:4}, {tr:"f. ortalamak",yz:1}],
"military": [{tr:"s. askeri",yz:4}, {tr:"i. ordu, askeri güç",yz:3}],
"monitor": [{tr:"f. izlemek, denetlemek",yz:4}, {tr:"i. ekran, monitör",yz:1}],
"muscle": [{tr:"i. kas",yz:4}, {tr:"f. zorla ilerlemek",yz:1}],
"name": [{tr:"f. adlandırmak, atamak",yz:3}, {tr:"i. isim, ad",yz:4}],
"nation": [{tr:"i. ülke, devlet",yz:4}, {tr:"i. ulus, millet",yz:3}],
"near": [{tr:"e. yakınında",yz:4}, {tr:"f. yaklaşmak",yz:2}],
"network": [{tr:"i. ağ, şebeke",yz:4}, {tr:"f. bağlantı kurmak",yz:1}],
"north": [{tr:"z. kuzeye",yz:3}, {tr:"i. kuzey",yz:4}],
"object": [{tr:"f. itiraz etmek",yz:3}, {tr:"i. nesne, obje, amaç",yz:4}],
"objective": [{tr:"s. nesnel, tarafsız",yz:4}, {tr:"i. amaç, hedef",yz:3}],
"open": [{tr:"f. açmak, açılmak",yz:4}, {tr:"s. açık",yz:3}],
"otherwise": [{tr:"z. aksi takdirde, başka türlü",yz:4}, {tr:"s. farklı",yz:2}],
"overall": [{tr:"s. genel, toplam",yz:4}, {tr:"i. tulum (giysi)",yz:1}],
"pain": [{tr:"i. ağrı, acı",yz:4}, {tr:"f. acı vermek",yz:1}],
"parts": [{tr:"i. yöreler, bölgeler",yz:3}, {tr:"i. parçalar, kısımlar",yz:4}],
"pass": [{tr:"f. (yasa) çıkarmak",yz:3}, {tr:"f. geçmek (zaman, mekân)",yz:4}],
"patient": [{tr:"i. hasta",yz:4}, {tr:"s. sabırlı",yz:2}],
"pattern": [{tr:"i. örüntü, desen",yz:4}, {tr:"f. desenlendirmek",yz:1}],
"picture": [{tr:"f. tasavvur etmek, gözünde canlandırmak",yz:2}, {tr:"i. resim, fotoğraf",yz:4}],
"preserve": [{tr:"f. korumak, muhafaza etmek",yz:4}, {tr:"i. koruma alanı",yz:2}],
"purchase": [{tr:"f. satın almak",yz:4}, {tr:"i. satın alma",yz:3}],
"quality": [{tr:"i. kalite, nitelik",yz:4}, {tr:"s. kaliteli",yz:2}],
"real": [{tr:"s. gerçek, hakiki",yz:4}, {tr:"z. gerçekten (gayriresmî)",yz:1}],
"relate": [{tr:"f. ilgili olmak, ilişkili olmak",yz:4}, {tr:"f. anlatmak",yz:1}],
"report": [{tr:"i. rapor",yz:4}, {tr:"f. bildirmek, rapor etmek, haber vermek",yz:4}],
"represent": [{tr:"f. temsil etmek",yz:4}, {tr:"f. ifade etmek, betimlemek",yz:2}],
"rest": [{tr:"f. dinlenmek",yz:2}, {tr:"i. geri kalan",yz:4}],
"revolution": [{tr:"i. devrim",yz:4}, {tr:"i. dönüş, devir (fiziksel)",yz:1}],
"rule": [{tr:"f. yönetmek, hükmetmek",yz:3}, {tr:"i. kural, yönetmelik",yz:4}],
"safe": [{tr:"s. güvenli, emniyetli",yz:4}, {tr:"i. kasa",yz:1}],
"scale": [{tr:"f. ölçeklendirmek",yz:1}, {tr:"i. ölçek, boyut",yz:4}],
"search": [{tr:"i. arama",yz:3}, {tr:"f. aramak",yz:4}],
"serve": [{tr:"f. hizmet etmek",yz:4}, {tr:"f. sunmak, servis yapmak",yz:2}],
"share": [{tr:"f. paylaşmak",yz:4}, {tr:"i. pay, hisse",yz:3}],
"side": [{tr:"f. taraf tutmak",yz:2}, {tr:"i. taraf, yan",yz:4}],
"site": [{tr:"i. alan, saha, yer",yz:4}, {tr:"f. konumlandırmak",yz:1}],
"slow": [{tr:"f. yavaşlamak, yavaşlatmak",yz:3}, {tr:"s./z. yavaş",yz:4}],
"solution": [{tr:"i. çözüm",yz:4}, {tr:"i. çözelti (kimyasal)",yz:2}],
"special": [{tr:"s. özel",yz:4}, {tr:"i. özel program/ürün",yz:1}],
"speed": [{tr:"f. hızlanmak, hızlandırmak",yz:2}, {tr:"i. hız",yz:4}],
"standard": [{tr:"i. standart, ölçüt",yz:4}, {tr:"s. standart, alışılmış",yz:3}],
"step": [{tr:"f. adım atmak",yz:3}, {tr:"i. adım",yz:4}],
"store": [{tr:"f. depolamak, saklamak",yz:4}, {tr:"i. mağaza",yz:2}],
"struggle": [{tr:"f. mücadele etmek, uğraşmak",yz:4}, {tr:"i. mücadele",yz:3}],
"supply": [{tr:"i. arz, tedarik, kaynak",yz:4}, {tr:"f. sağlamak",yz:3}],
"surface": [{tr:"f. yüzeye çıkmak, ortaya çıkmak",yz:3}, {tr:"i. yüzey",yz:4}],
"taken": [{tr:"s. dolu, meşgul",yz:3}, {tr:"s. ele geçirilmiş",yz:1}],
"target": [{tr:"i. hedef, amaç",yz:4}, {tr:"f. hedeflemek, hedef almak",yz:3}],
"thinking": [{tr:"i. düşünme, düşünce",yz:4}, {tr:"s. düşünen",yz:1}],
"title": [{tr:"i. başlık",yz:4}, {tr:"i. unvan",yz:2}],
"top": [{tr:"i. üst, tepe, doruk",yz:4}, {tr:"f. aşmak",yz:2}],
"total": [{tr:"s. toplam, tüm",yz:4}, {tr:"f. toplamak",yz:1}],
"trade": [{tr:"i. ticaret",yz:4}, {tr:"f. ticaret yapmak",yz:3}],
"transport": [{tr:"i. ulaşım, taşımacılık",yz:4}, {tr:"f. taşımak, nakletmek",yz:3}],
"travel": [{tr:"f. yayılmak, ilerlemek",yz:3}, {tr:"f. seyahat etmek",yz:4}],
"treat": [{tr:"f. tedavi etmek",yz:4}, {tr:"f. davranmak, muamele etmek",yz:3}],
"tree": [{tr:"i. ağaç",yz:4}, {tr:"f. ağaçlandırmak",yz:1}],
"trend": [{tr:"i. eğilim, gidişat",yz:4}, {tr:"f. yönelmek",yz:1}],
"trigger": [{tr:"f. tetiklemek, başlatmak",yz:4}, {tr:"i. tetik",yz:1}],
"weight": [{tr:"i. ağırlık",yz:4}, {tr:"f. ağırlık vermek",yz:1}],
"western": [{tr:"s. batı, batıdaki",yz:4}, {tr:"i. kovboy filmi",yz:1}],
"wide": [{tr:"s. geniş; yaygın",yz:4}, {tr:"z. ardına kadar, tamamen",yz:1}],
"words": [{tr:"i. sözler, sözcükler",yz:4}, {tr:"i. tartışma, ağız kavgası",yz:1}],
"works": [{tr:"i. eserler",yz:4}, {tr:"i. tesis, fabrika",yz:1}]
};
