/* ============================================================
   Kullanım kalıpları — dönüştürücü girdisi (site bu dosyayı YÜKLEMEZ)

   Kelimenin anlamı değil, NASIL kullanıldığı: hangi edatı alır, hangi
   sözcüklerle birlikte gelir. YDS bu kalıpları bolca sorar; Türkçe fiilin
   istediği ek İngilizceye taşınınca hata çıkar ("comply to" değil "comply with").

   Kalıbı olmayan somut kelimeler (tiger, table) burada yoktur.
   Üretim: tools/test-uretim (agent + kalip-dogrula.py) · 485 kelime, 1202 kalıp
   ============================================================ */

window.KALIPLAR = {
"abandon": [{en:"abandon a plan",tr:"bir planı bırakmak"}, {en:"abandon an idea",tr:"bir fikirden vazgeçmek"}],
"absorb": [{en:"be absorbed in sth",tr:"bir şeye dalmak"}, {en:"absorb water",tr:"su emmek"}, {en:"absorb information",tr:"bilgiyi özümsemek"}],
"academic": [{en:"academic performance",tr:"akademik başarı"}, {en:"academic year",tr:"öğretim yılı"}, {en:"academic research",tr:"akademik araştırma"}],
"accompany": [{en:"be accompanied by sb",tr:"birinin eşliğinde olmak"}, {en:"accompany sb to the airport",tr:"birine havaalanına kadar eşlik etmek"}],
"account": [{en:"account for sth",tr:"bir şeyi oluşturmak, açıklamak"}, {en:"take sth into account",tr:"bir şeyi hesaba katmak"}, {en:"on account of sth",tr:"bir şey yüzünden"}],
"accurately": [{en:"accurately predict sth",tr:"bir şeyi doğru biçimde öngörmek"}, {en:"accurately reflect sth",tr:"bir şeyi doğru yansıtmak"}],
"achievement": [{en:"a sense of achievement",tr:"başarma duygusu"}, {en:"a great achievement",tr:"büyük bir başarı"}, {en:"academic achievement",tr:"akademik başarı"}],
"acknowledge": [{en:"acknowledge a mistake",tr:"hatayı kabul etmek"}, {en:"widely acknowledged",tr:"yaygın olarak kabul edilen"}, {en:"be acknowledged as sth",tr:"bir şey olarak kabul edilmek"}],
"acquire": [{en:"acquire knowledge",tr:"bilgi edinmek"}, {en:"acquire new skills",tr:"yeni beceriler kazanmak"}],
"active": [{en:"be active in sth",tr:"bir alanda faal olmak"}, {en:"play an active role",tr:"etkin bir rol oynamak"}],
"adapt": [{en:"adapt to change",tr:"değişime uyum sağlamak"}, {en:"adapt to new conditions",tr:"yeni koşullara uyum sağlamak"}],
"add": [{en:"add sth to sth",tr:"bir şeye bir şey eklemek"}, {en:"add to the problem",tr:"sorunu artırmak"}, {en:"add up to",tr:"toplamda bir şey etmek"}],
"agricultural": [{en:"agricultural land",tr:"tarım arazisi"}, {en:"agricultural production",tr:"tarımsal üretim"}],
"agriculture": [{en:"intensive agriculture",tr:"yoğun tarım"}, {en:"sustainable agriculture",tr:"sürdürülebilir tarım"}, {en:"depend on agriculture",tr:"tarıma bağımlı olmak"}],
"aid": [{en:"with the aid of",tr:"bir şeyin yardımıyla"}, {en:"come to sb's aid",tr:"birinin yardımına koşmak"}, {en:"financial aid",tr:"mali yardım"}],
"aim": [{en:"aim to do sth",tr:"bir şeyi yapmayı amaçlamak"}, {en:"be aimed at sb",tr:"birini hedeflemek"}, {en:"achieve the aim",tr:"amaca ulaşmak"}],
"alone": [{en:"leave sb alone",tr:"birini rahat bırakmak"}, {en:"let alone",tr:"şöyle dursun, bir yana"}, {en:"live alone",tr:"yalnız yaşamak"}],
"appearance": [{en:"make an appearance",tr:"boy göstermek, görünmek"}, {en:"physical appearance",tr:"fiziksel görünüm"}, {en:"judge by appearance",tr:"görünüşe göre yargılamak"}],
"application": [{en:"an application for a job",tr:"iş başvurusu"}, {en:"submit an application",tr:"başvuru yapmak"}, {en:"the application of a theory",tr:"bir kuramın uygulanması"}],
"apply": [{en:"apply for a job",tr:"işe başvurmak"}, {en:"apply to a university",tr:"üniversiteye başvurmak"}, {en:"apply the rules",tr:"kuralları uygulamak"}],
"appreciate": [{en:"appreciate the importance",tr:"önemini kavramak"}, {en:"greatly appreciate sth",tr:"bir şey için çok minnettar olmak"}],
"approach": [{en:"an approach to sth",tr:"bir şeye yaklaşım"}, {en:"adopt a new approach",tr:"yeni bir yaklaşım benimsemek"}, {en:"approach a problem",tr:"bir soruna yaklaşmak"}],
"appropriate": [{en:"be appropriate for sth",tr:"bir şey için uygun olmak"}, {en:"take appropriate action",tr:"uygun adımı atmak"}, {en:"appropriate funds",tr:"ödenek ayırmak"}],
"argue": [{en:"argue with sb",tr:"biriyle tartışmak"}, {en:"argue about sth",tr:"bir şey hakkında tartışmak"}, {en:"argue against sth",tr:"bir şeye karşı çıkmak"}],
"arise": [{en:"arise from sth",tr:"bir şeyden kaynaklanmak"}, {en:"problems arise",tr:"sorunlar ortaya çıkar"}],
"article": [{en:"an article on sth",tr:"bir şey üzerine makale"}, {en:"publish an article",tr:"makale yayımlamak"}, {en:"a newspaper article",tr:"gazete yazısı"}],
"artificial": [{en:"artificial intelligence",tr:"yapay zeka"}, {en:"artificial light",tr:"yapay ışık"}],
"ask": [{en:"ask sb for sth",tr:"birinden bir şey istemek"}, {en:"ask sb to do sth",tr:"birinden bir şey yapmasını istemek"}, {en:"ask a question",tr:"soru sormak"}],
"assume": [{en:"assume responsibility for sth",tr:"bir şeyin sorumluluğunu üstlenmek"}, {en:"assume control",tr:"kontrolü ele almak"}, {en:"it is assumed that",tr:"varsayılıyor ki"}],
"attach": [{en:"attach importance to sth",tr:"bir şeye önem vermek"}, {en:"be attached to sb",tr:"birine bağlı olmak"}, {en:"attach a file",tr:"dosyayı iliştirmek, dosya eklemek"}],
"attack": [{en:"an attack on sb",tr:"birine yönelik saldırı"}, {en:"come under attack",tr:"saldırıya uğramak"}, {en:"launch an attack",tr:"saldırı başlatmak"}],
"attitude": [{en:"attitude towards sth",tr:"bir şeye karşı tutum"}, {en:"a positive attitude",tr:"olumlu bir tutum"}],
"attract": [{en:"attract attention",tr:"dikkat çekmek"}, {en:"attract tourists",tr:"turist çekmek"}, {en:"be attracted to sb",tr:"birinden hoşlanmak"}],
"attractive": [{en:"attractive to sb",tr:"birine çekici gelen"}, {en:"an attractive option",tr:"cazip bir seçenek"}],
"awareness": [{en:"raise awareness of sth",tr:"bir şeye ilişkin farkındalık yaratmak"}, {en:"public awareness",tr:"kamuoyu farkındalığı"}],
"bacteria": [{en:"harmful bacteria",tr:"zararlı bakteriler"}, {en:"kill bacteria",tr:"bakterileri öldürmek"}],
"balance": [{en:"strike a balance between",tr:"iki şey arasında denge kurmak"}, {en:"keep your balance",tr:"düşmeden dengede durmak"}, {en:"the balance of power",tr:"güç dengesi"}],
"bear": [{en:"bear sth in mind",tr:"bir şeyi akılda tutmak"}, {en:"bear responsibility for sth",tr:"bir şeyin sorumluluğunu taşımak"}, {en:"bear a resemblance to",tr:"benzerlik taşımak"}],
"beginning": [{en:"at the beginning of sth",tr:"bir şeyin başında"}, {en:"from the beginning",tr:"en baştan"}],
"behaviour": [{en:"human behaviour",tr:"insan davranışı"}, {en:"behaviour towards sb",tr:"birine karşı davranış"}, {en:"a change in behaviour",tr:"davranış değişikliği"}],
"behind": [{en:"the reason behind sth",tr:"bir şeyin ardındaki neden"}, {en:"fall behind",tr:"geri kalmak"}, {en:"leave sth behind",tr:"bir şeyi geride bırakmak"}],
"belief": [{en:"belief in sth",tr:"bir şeye inanç"}, {en:"contrary to popular belief",tr:"yaygın inanışın aksine"}, {en:"a widespread belief",tr:"yaygın bir inanış"}],
"beneficial": [{en:"beneficial to sb",tr:"birine yararlı"}, {en:"mutually beneficial",tr:"karşılıklı yarar sağlayan"}],
"beyond": [{en:"go beyond sth",tr:"bir şeyin ötesine geçmek"}, {en:"beyond our control",tr:"kontrolümüzün dışında"}, {en:"beyond doubt",tr:"şüphesiz, kuşkuya yer bırakmayan"}],
"bit": [{en:"a bit of sth",tr:"biraz, azıcık"}, {en:"quite a bit",tr:"epeyce, oldukça"}, {en:"bit by bit",tr:"azar azar, yavaş yavaş"}],
"bite": [{en:"bite one's nails",tr:"tırnaklarını yemek"}, {en:"a mosquito bite",tr:"sivrisinek ısırığı"}, {en:"grab a bite",tr:"bir şeyler atıştırmak"}],
"building": [{en:"an office building",tr:"bir ofis binası"}, {en:"the building blocks of sth",tr:"bir şeyin yapı taşları"}],
"built": [{en:"be built on sth",tr:"bir şeyin üzerine kurulmak"}, {en:"newly built",tr:"yeni inşa edilmiş"}],
"came": [{en:"came across sth",tr:"bir şeye rastlamak"}, {en:"came up with an idea",tr:"bir fikir öne sürmek"}, {en:"came to a conclusion",tr:"bir sonuca ulaşmak"}],
"cancer": [{en:"lung cancer",tr:"akciğer kanseri"}, {en:"be diagnosed with cancer",tr:"kanser teşhisi konmak"}, {en:"cause cancer",tr:"kansere yol açmak"}],
"car": [{en:"by car",tr:"arabayla"}],
"carbon": [{en:"carbon dioxide",tr:"karbondioksit gazı"}, {en:"carbon emissions",tr:"karbon salımları"}],
"career": [{en:"pursue a career in",tr:"bir alanda kariyer peşinde koşmak"}, {en:"a career change",tr:"kariyer değişikliği"}, {en:"career prospects",tr:"kariyer olanakları"}],
"careful": [{en:"be careful with sth",tr:"bir şeye dikkat etmek"}, {en:"careful about sth",tr:"bir şey konusunda dikkatli"}, {en:"careful consideration",tr:"dikkatli değerlendirme"}],
"catch": [{en:"catch sb doing sth",tr:"birini bir şey yaparken yakalamak"}, {en:"catch up with sb",tr:"birine yetişmek"}, {en:"catch a glimpse of",tr:"bir an için görmek"}],
"central": [{en:"central to the argument",tr:"savın merkezinde olan"}, {en:"play a central role",tr:"merkezi bir rol oynamak"}],
"centre": [{en:"in the centre of",tr:"bir şeyin merkezinde"}, {en:"centre on sth",tr:"bir şey üzerinde yoğunlaşmak"}, {en:"the city centre",tr:"şehir merkezi"}],
"chance": [{en:"by chance",tr:"tesadüfen"}, {en:"the chance of success",tr:"başarı şansı"}, {en:"take a chance",tr:"şansını denemek"}],
"changed": [{en:"a changed man",tr:"değişmiş bir insan"}],
"character": [{en:"out of character",tr:"kişiliğine aykırı"}, {en:"the main character",tr:"başkarakter, başrol kişisi"}, {en:"a strong character",tr:"güçlü bir kişilik"}],
"china": [{en:"a china cup",tr:"porselen çay fincanı"}, {en:"fine china",tr:"kaliteli porselen takımı"}],
"chronic": [{en:"chronic disease",tr:"kronik hastalık"}, {en:"chronic pain",tr:"süreğen ağrı"}, {en:"a chronic shortage",tr:"kronik bir kıtlık"}],
"claim": [{en:"claim to be sth",tr:"bir şey olduğunu iddia etmek"}, {en:"claim responsibility for sth",tr:"bir şeyin sorumluluğunu üstlenmek"}, {en:"make a claim",tr:"iddiada bulunmak"}],
"class": [{en:"middle class",tr:"orta sınıf"}, {en:"working class",tr:"işçi sınıfı"}, {en:"in class",tr:"derste, sınıfta"}],
"clean": [{en:"clean up the mess",tr:"dağınıklığı toplamak"}, {en:"keep sth clean",tr:"bir şeyi temiz tutmak"}],
"closely": [{en:"work closely with sb",tr:"biriyle yakın çalışmak"}, {en:"be closely linked to",tr:"yakından bağlantılı olmak"}, {en:"watch closely",tr:"yakından, dikkatle izlemek"}],
"code": [{en:"a code of conduct",tr:"davranış kuralları"}, {en:"crack a code",tr:"şifreyi çözmek"}],
"cognitive": [{en:"cognitive ability",tr:"bilişsel yetenek"}, {en:"cognitive development",tr:"bilişsel gelişim"}],
"cold": [{en:"catch a cold",tr:"soğuk algınlığına yakalanmak"}, {en:"in cold blood",tr:"soğukkanlılıkla"}],
"collapse": [{en:"the collapse of sth",tr:"bir şeyin çöküşü"}, {en:"collapse under pressure",tr:"baskı altında çökmek"}],
"commit": [{en:"commit to doing sth",tr:"bir şey yapmayı taahhüt etmek"}, {en:"be committed to sth",tr:"bir şeye bağlı olmak"}, {en:"commit a crime",tr:"suç işlemek"}],
"commonly": [{en:"commonly used",tr:"yaygın olarak kullanılan"}, {en:"commonly known as",tr:"yaygın olarak bilinen adıyla"}, {en:"commonly referred to as",tr:"yaygın olarak şöyle anılan"}],
"compensate": [{en:"compensate for sth",tr:"bir şeyi telafi etmek"}, {en:"compensate sb for sth",tr:"birine bir şey için tazminat ödemek"}],
"component": [{en:"a component of sth",tr:"bir şeyin bileşeni"}, {en:"a key component",tr:"kilit bir unsur"}],
"compound": [{en:"compound the problem",tr:"sorunu ağırlaştırmak"}, {en:"a chemical compound",tr:"kimyasal bir bileşik"}, {en:"compound interest",tr:"bileşik faiz"}],
"conclude": [{en:"conclude from sth",tr:"bir şeyden sonuç çıkarmak"}, {en:"conclude an agreement",tr:"anlaşma yapmak"}],
"confirm": [{en:"confirm the findings",tr:"bulguları doğrulamak"}, {en:"confirm a booking",tr:"rezervasyonu onaylamak"}],
"conflict": [{en:"conflict with sth",tr:"bir şeyle çelişmek"}, {en:"conflict of interest",tr:"çıkar çatışması"}, {en:"armed conflict",tr:"silahlı çatışma"}],
"connection": [{en:"a connection between sth",tr:"bir şeyler arasındaki bağlantı"}, {en:"in connection with sth",tr:"bir şeyle bağlantılı olarak"}, {en:"make a connection",tr:"bağlantı kurmak"}],
"constant": [{en:"under constant pressure",tr:"sürekli baskı altında"}, {en:"remain constant",tr:"değişmeden kalmak"}, {en:"constant change",tr:"sürekli değişim"}],
"constitute": [{en:"constitute a threat",tr:"tehdit oluşturmak"}, {en:"constitute a majority",tr:"çoğunluğu oluşturmak"}],
"construct": [{en:"construct a building",tr:"bina inşa etmek"}, {en:"construct an argument",tr:"bir sav kurmak"}],
"consumer": [{en:"consumer goods",tr:"tüketim malları"}, {en:"consumer demand",tr:"tüketici talebi"}],
"consumption": [{en:"energy consumption",tr:"enerji tüketimi"}, {en:"reduce consumption",tr:"tüketimi azaltmak"}],
"contact": [{en:"come into contact with sb",tr:"biriyle temasa geçmek"}, {en:"keep in contact with sb",tr:"biriyle iletişimi sürdürmek"}, {en:"contact details",tr:"iletişim bilgileri"}],
"contemporary": [{en:"contemporary society",tr:"çağdaş toplum"}, {en:"contemporary art",tr:"çağdaş sanat"}, {en:"a contemporary of sb",tr:"birinin çağdaşı"}],
"content": [{en:"be content with sth",tr:"bir şeyden memnun olmak"}, {en:"the content of sth",tr:"bir şeyin içeriği"}],
"context": [{en:"in the context of",tr:"bir şeyin bağlamında"}, {en:"out of context",tr:"bağlamından kopuk"}],
"continent": [{en:"the African continent",tr:"Afrika kıtası"}],
"contrast": [{en:"in contrast to sth",tr:"bir şeyin aksine"}, {en:"contrast sth with sth",tr:"bir şeyi bir şeyle karşılaştırmak"}, {en:"by contrast",tr:"buna karşılık"}],
"contribution": [{en:"make a contribution to",tr:"bir şeye katkıda bulunmak"}, {en:"a valuable contribution",tr:"değerli bir katkı"}],
"convince": [{en:"convince sb of sth",tr:"birini bir şeye ikna etmek"}, {en:"convince sb to do sth",tr:"birini bir şey yapmaya ikna etmek"}],
"cool": [{en:"cool down",tr:"soğumak, sakinleşmek"}, {en:"keep cool",tr:"sakin kalmak"}, {en:"a cool breeze",tr:"serin bir esinti"}],
"cope": [{en:"cope with sth",tr:"bir şeyle başa çıkmak"}, {en:"unable to cope",tr:"baş edememek"}],
"cover": [{en:"be covered with snow",tr:"karla kaplı olmak"}, {en:"cover a wide range",tr:"geniş bir yelpazeyi kapsamak"}, {en:"cover the costs",tr:"masrafları karşılamak"}],
"critical": [{en:"be critical of sb",tr:"birini eleştirmek"}, {en:"critical to success",tr:"başarı için kritik"}, {en:"play a critical role",tr:"kritik bir rol oynamak"}],
"crop": [{en:"grow crops",tr:"ürün yetiştirmek"}, {en:"crop yields",tr:"mahsul verimi"}],
"crucial": [{en:"crucial to success",tr:"başarı için hayati"}, {en:"crucial for development",tr:"gelişim için çok önemli"}, {en:"play a crucial role",tr:"belirleyici bir rol oynamak"}],
"current": [{en:"the current situation",tr:"mevcut durum, şu anki durum"}, {en:"against the current",tr:"akıntıya karşı"}, {en:"current affairs",tr:"güncel olaylar"}],
"customer": [{en:"a regular customer",tr:"daimi bir müşteri"}, {en:"customer service",tr:"müşteri hizmetleri"}, {en:"attract customers",tr:"müşteri çekmek"}],
"danger": [{en:"in danger of sth",tr:"bir şey tehlikesiyle karşı karşıya"}, {en:"out of danger",tr:"tehlikeyi atlatmış"}, {en:"pose a danger to sb",tr:"birine tehlike oluşturmak"}],
"dangerous": [{en:"dangerous to health",tr:"sağlığa zararlı"}, {en:"dangerous for children",tr:"çocuklar için tehlikeli"}, {en:"extremely dangerous",tr:"aşırı derecede tehlikeli"}],
"date": [{en:"out of date",tr:"modası geçmiş"}, {en:"up to date",tr:"güncel, güncellenmiş"}, {en:"to date",tr:"bugüne kadar"}],
"debate": [{en:"a debate over sth",tr:"bir şey üzerine tartışma"}, {en:"open to debate",tr:"tartışmaya açık"}, {en:"debate the issue",tr:"meseleyi tartışmak"}],
"decide": [{en:"decide on sth",tr:"bir şeye karar vermek"}, {en:"decide against sth",tr:"bir şeyden vazgeçmek"}, {en:"decide to do sth",tr:"bir şey yapmaya karar vermek"}],
"decision": [{en:"a decision on sth",tr:"bir şey hakkında karar"}, {en:"make a decision",tr:"karar vermek"}, {en:"reach a decision",tr:"bir karara varmak"}],
"deep": [{en:"a deep understanding of",tr:"derin bir kavrayış"}, {en:"take a deep breath",tr:"derin nefes almak, sakinleşmek"}, {en:"in deep trouble",tr:"başı büyük dertte"}],
"demonstrate": [{en:"demonstrate the importance of sth",tr:"bir şeyin önemini göstermek"}, {en:"clearly demonstrate sth",tr:"bir şeyi açıkça göstermek"}, {en:"demonstrate against the government",tr:"hükümete karşı gösteri yapmak"}],
"depression": [{en:"suffer from depression",tr:"depresyondan muzdarip olmak"}, {en:"the Great Depression",tr:"Büyük Buhran"}],
"desire": [{en:"a desire for sth",tr:"bir şeye duyulan arzu"}, {en:"a strong desire to",tr:"güçlü bir istek duymak"}],
"destroy": [{en:"destroy the environment",tr:"çevreyi tahrip etmek"}, {en:"completely destroyed",tr:"tamamen yok edilmiş"}, {en:"destroy evidence",tr:"kanıt yok etmek"}],
"detail": [{en:"in detail",tr:"ayrıntılı olarak"}, {en:"go into detail",tr:"ayrıntıya girmek"}, {en:"pay attention to detail",tr:"ayrıntıya dikkat etmek"}],
"developing": [{en:"a developing country",tr:"gelişmekte olan bir ülke"}, {en:"developing economies",tr:"gelişmekte olan ekonomiler"}],
"dialogue": [{en:"dialogue between two sides",tr:"iki taraf arasında diyalog"}, {en:"engage in dialogue",tr:"diyaloğa girmek"}, {en:"open a dialogue with",tr:"biriyle diyalog başlatmak"}],
"die": [{en:"die of cancer",tr:"kanserden ölmek"}, {en:"die from injuries",tr:"yaralanmalardan ölmek"}, {en:"die out",tr:"soyu tükenmek"}],
"digital": [{en:"digital technology",tr:"sayısal teknoloji, dijital teknoloji"}, {en:"the digital age",tr:"dijital çağ"}],
"dioxide": [{en:"carbon dioxide",tr:"karbondioksit gazı"}, {en:"carbon dioxide emissions",tr:"karbondioksit salımı"}],
"direct": [{en:"direct attention to sth",tr:"dikkati bir şeye yöneltmek"}, {en:"a direct impact on",tr:"üzerinde doğrudan etki"}, {en:"in direct contrast to",tr:"tam tersine, taban tabana zıt"}],
"discipline": [{en:"an academic discipline",tr:"akademik bir bilim dalı"}, {en:"strict discipline",tr:"sıkı disiplin"}, {en:"across disciplines",tr:"farklı bilim dalları arasında"}],
"discovery": [{en:"the discovery of sth",tr:"bir şeyin keşfi"}, {en:"make a discovery",tr:"keşif yapmak"}, {en:"a scientific discovery",tr:"bilimsel bir keşif"}],
"discuss": [{en:"discuss sth with sb",tr:"bir şeyi biriyle görüşmek"}, {en:"discuss sth in detail",tr:"bir şeyi ayrıntılı biçimde tartışmak"}],
"display": [{en:"on display",tr:"göz önünde, sergide"}, {en:"put sth on display",tr:"bir şeyi sergilemek"}, {en:"display an interest in sth",tr:"bir şeye ilgi göstermek"}],
"distribution": [{en:"the distribution of sth",tr:"bir şeyin dağılımı"}, {en:"uneven distribution",tr:"eşitsiz dağılım"}, {en:"distribution of wealth",tr:"servet dağılımı"}],
"diverse": [{en:"a diverse range of sth",tr:"çok çeşitli bir yelpaze"}, {en:"diverse backgrounds",tr:"farklı geçmişler"}, {en:"culturally diverse",tr:"kültürel açıdan çeşitli"}],
"doctor": [{en:"see a doctor",tr:"doktora görünmek"}, {en:"consult a doctor",tr:"doktora danışmak"}],
"document": [{en:"document the findings",tr:"bulguları belgelemek"}, {en:"a written document",tr:"yazılı bir belge"}],
"domestic": [{en:"the domestic market",tr:"iç pazar"}, {en:"domestic violence",tr:"aile içi şiddet"}, {en:"domestic animals",tr:"evcil hayvanlar"}],
"done": [{en:"get sth done",tr:"bir şeyi hallettirmek"}, {en:"be done with sth",tr:"bir şeyi bitirmiş olmak"}, {en:"easier said than done",tr:"söylemesi kolay, yapması zor"}],
"dramatic": [{en:"a dramatic increase",tr:"çarpıcı bir artış"}, {en:"a dramatic change",tr:"çarpıcı bir değişim"}],
"dramatically": [{en:"increase dramatically",tr:"çarpıcı biçimde artmak"}, {en:"change dramatically",tr:"köklü biçimde değişmek"}, {en:"drop dramatically",tr:"hızla düşmek"}],
"draw": [{en:"draw a conclusion",tr:"sonuç çıkarmak"}, {en:"draw attention to sth",tr:"bir şeye dikkat çekmek"}, {en:"draw a picture",tr:"resim çizmek"}],
"dream": [{en:"dream of doing sth",tr:"bir şey yapmayı hayal etmek"}, {en:"a dream come true",tr:"gerçekleşen bir hayal"}, {en:"have a dream",tr:"rüya görmek"}],
"drink": [{en:"have a drink",tr:"bir şeyler içmek"}, {en:"a soft drink",tr:"alkolsüz içecek"}],
"drive": [{en:"drive sb to do sth",tr:"birini bir şey yapmaya itmek"}, {en:"drive economic growth",tr:"ekonomik büyümeyi sürüklemek"}, {en:"drive a car",tr:"araba kullanmak"}],
"dry": [{en:"dry up",tr:"kurumak, tükenmek"}, {en:"keep sth dry",tr:"bir şeyi kuru tutmak"}, {en:"the dry season",tr:"kurak mevsim, yağışsız dönem"}],
"earn": [{en:"earn a living",tr:"geçimini sağlamak"}, {en:"earn a reputation",tr:"itibar kazanmak"}],
"east": [{en:"to the east of",tr:"bir şeyin doğusunda"}, {en:"in the east",tr:"doğuda"}],
"eating": [{en:"healthy eating habits",tr:"sağlıklı beslenme alışkanlıkları"}, {en:"an eating disorder",tr:"bir yeme bozukluğu"}],
"efficient": [{en:"energy efficient",tr:"enerji açısından verimli"}, {en:"a more efficient system",tr:"daha verimli bir sistem"}],
"either": [{en:"either ... or",tr:"ya ... ya da"}, {en:"on either side",tr:"her iki tarafta"}],
"electricity": [{en:"generate electricity",tr:"elektrik üretmek"}, {en:"run on electricity",tr:"elektrikle çalışmak"}],
"element": [{en:"a key element of sth",tr:"bir şeyin temel ögesi"}, {en:"an element of risk",tr:"risk unsuru"}],
"eliminate": [{en:"eliminate the need for sth",tr:"bir şeye olan ihtiyacı ortadan kaldırmak"}, {en:"eliminate poverty",tr:"yoksulluğu ortadan kaldırmak"}, {en:"eliminate the risk",tr:"riski ortadan kaldırmak"}],
"else": [{en:"or else",tr:"yoksa, öbür türlü"}, {en:"somewhere else",tr:"başka bir yerde"}, {en:"everyone else",tr:"diğer herkes"}],
"emotion": [{en:"express emotions",tr:"duyguları ifade etmek"}, {en:"mixed emotions",tr:"karışık duygular"}],
"emotional": [{en:"provide emotional support",tr:"duygusal destek sağlamak"}, {en:"become emotional",tr:"duygusallaşmak, duygulanmak"}, {en:"an emotional response",tr:"duygusal tepki gösterme"}],
"emphasis": [{en:"place emphasis on sth",tr:"bir şeye vurgu yapmak"}, {en:"with emphasis on sth",tr:"bir şeye ağırlık vererek"}, {en:"the main emphasis",tr:"asıl vurgu"}],
"engage": [{en:"engage in sth",tr:"bir şeyle uğraşmak"}, {en:"engage with sb",tr:"biriyle ilişki kurmak"}],
"engineer": [{en:"a civil engineer",tr:"inşaat mühendisi"}, {en:"software engineer",tr:"yazılım mühendisi"}],
"enormous": [{en:"an enormous amount of sth",tr:"muazzam miktarda bir şey"}, {en:"enormous pressure",tr:"muazzam baskı"}],
"entire": [{en:"the entire process",tr:"sürecin tamamı"}, {en:"the entire population",tr:"nüfusun tamamı"}],
"environmental": [{en:"environmental impact",tr:"çevresel etki"}, {en:"environmental protection",tr:"çevre koruma"}, {en:"environmental issues",tr:"çevre sorunları"}],
"essential": [{en:"essential for survival",tr:"hayatta kalmak için zorunlu"}, {en:"an essential part of sth",tr:"bir şeyin temel parçası"}],
"established": [{en:"well established",tr:"iyice yerleşmiş, köklü"}, {en:"an established fact",tr:"yerleşik bir gerçek"}, {en:"become established",tr:"yerleşmek, kabul görmek"}],
"eventually": [{en:"eventually lead to sth",tr:"sonunda bir şeye yol açmak"}],
"everything": [{en:"everything else",tr:"diğer her şey"}, {en:"do everything possible",tr:"elinden gelen her şeyi yapmak"}],
"exactly": [{en:"exactly the same",tr:"tam olarak aynı"}, {en:"not exactly",tr:"tam sayılmaz"}],
"examine": [{en:"examine the evidence",tr:"kanıtları incelemek"}, {en:"examine a patient",tr:"bir hastayı muayene etmek"}],
"expensive": [{en:"an expensive mistake",tr:"pahalıya mal olan hata"}, {en:"prohibitively expensive",tr:"aşırı derecede pahalı"}],
"experienced": [{en:"experienced in sth",tr:"bir konuda deneyimli"}, {en:"an experienced teacher",tr:"deneyimli bir öğretmen"}],
"experiment": [{en:"experiment with sth",tr:"bir şey üzerinde deneme yapmak"}, {en:"conduct an experiment",tr:"deney yapmak"}],
"exploit": [{en:"exploit workers",tr:"işçileri sömürmek"}, {en:"exploit an opportunity",tr:"bir fırsattan yararlanmak"}, {en:"exploit natural resources",tr:"doğal kaynakları kullanmak"}],
"explore": [{en:"explore the possibility of",tr:"olasılığını araştırmak"}, {en:"explore an issue",tr:"bir konuyu araştırmak, irdelemek"}],
"export": [{en:"export goods",tr:"mal ihraç etmek"}, {en:"export sth to a country",tr:"bir ülkeye ihraç etmek"}],
"expose": [{en:"expose sb to sth",tr:"birini bir şeye maruz bırakmak"}, {en:"be exposed to risk",tr:"riske maruz kalmak"}, {en:"expose the truth",tr:"gerçeği açığa çıkarmak"}],
"express": [{en:"express an opinion",tr:"görüş bildirmek"}, {en:"express concern",tr:"endişe dile getirmek"}, {en:"clearly express sth",tr:"bir şeyi açıkça ifade etmek"}],
"extent": [{en:"to some extent",tr:"bir ölçüde, bir dereceye kadar"}, {en:"to a large extent",tr:"büyük ölçüde"}, {en:"the extent of the damage",tr:"hasarın boyutu"}],
"external": [{en:"external factors",tr:"dış etkenler"}, {en:"external pressure",tr:"dış baskı"}],
"extremely": [{en:"extremely important",tr:"son derece önemli"}, {en:"extremely difficult",tr:"aşırı derecede zor"}],
"eye": [{en:"keep an eye on sth",tr:"bir şeye göz kulak olmak"}, {en:"catch sb's eye",tr:"birinin dikkatini çekmek"}],
"facilitate": [{en:"facilitate communication",tr:"iletişimi kolaylaştırmak"}, {en:"facilitate the process",tr:"süreci kolaylaştırmak"}],
"famous": [{en:"famous for sth",tr:"bir şeyle ünlü"}, {en:"become famous",tr:"ünlü olmak"}],
"farm": [{en:"work on a farm",tr:"çiftlikte çalışmak"}, {en:"a dairy farm",tr:"süt çiftliği"}],
"fat": [{en:"low in fat",tr:"az yağlı"}, {en:"body fat",tr:"vücut yağı"}, {en:"saturated fat",tr:"doymuş yağ"}],
"father": [{en:"the father of sth",tr:"bir şeyin babası, kurucusu"}, {en:"father a child",tr:"bir çocuğun babası olmak"}],
"favour": [{en:"in favour of sth",tr:"bir şeyden yana, lehine"}, {en:"do sb a favour",tr:"birine iyilik yapmak, yardım etmek"}],
"fear": [{en:"for fear of sth",tr:"bir şeyden korktuğu için"}, {en:"the fear of failure",tr:"başarısızlık korkusu"}, {en:"overcome fear",tr:"korkuyu aşmak"}],
"feed": [{en:"feed on insects",tr:"böceklerle beslenmek"}, {en:"feed the animals",tr:"hayvanları beslemek"}],
"fight": [{en:"fight against sth",tr:"bir şeyle mücadele etmek"}, {en:"fight for sth",tr:"bir şey için mücadele etmek"}, {en:"put up a fight",tr:"direnç göstermek"}],
"film": [{en:"make a film",tr:"film çekmek"}, {en:"a thin film",tr:"ince bir tabaka"}],
"financial": [{en:"provide financial support",tr:"mali destek sağlamak"}, {en:"financial difficulties",tr:"mali sıkıntılar"}],
"fish": [{en:"catch fish",tr:"balık tutmak"}, {en:"a fish out of water",tr:"sudan çıkmış balık gibi"}],
"fit": [{en:"be fit for sth",tr:"bir şeye uygun olmak"}, {en:"keep fit",tr:"formda ve sağlıklı kalmak"}, {en:"fit in with sth",tr:"bir şeye uyum sağlamak"}],
"flood": [{en:"a flood of complaints",tr:"şikayet yağmuru"}, {en:"be flooded with sth",tr:"bir şeye boğulmak"}, {en:"flood damage",tr:"sel hasarı"}],
"fly": [{en:"time flies",tr:"zaman çabuk geçer"}],
"foreign": [{en:"a foreign language",tr:"yabancı dil"}, {en:"foreign policy",tr:"dış politika"}, {en:"foreign to sb",tr:"birine yabancı gelen"}],
"fossil": [{en:"fossil fuels",tr:"fosil yakıtlar"}],
"free": [{en:"free of charge",tr:"ücretsiz"}, {en:"free from sth",tr:"bir şeyden uzak, arınmış"}, {en:"set sb free",tr:"birini serbest bırakmak"}],
"frequently": [{en:"frequently asked questions",tr:"sıkça sorulan sorular"}, {en:"occur frequently",tr:"sık sık meydana gelmek"}],
"friend": [{en:"make friends with sb",tr:"biriyle arkadaş olmak"}, {en:"a close friend",tr:"yakın arkadaş"}, {en:"a friend of mine",tr:"bir arkadaşım"}],
"fuel": [{en:"fuel growth",tr:"büyümeyi körüklemek"}, {en:"fuel concerns",tr:"endişeleri körüklemek"}, {en:"run out of fuel",tr:"yakıtı bitmek"}],
"full": [{en:"be full of sth",tr:"bir şeyle dolu olmak"}, {en:"in full",tr:"eksiksiz olarak, tümüyle"}, {en:"full of energy",tr:"enerji dolu, dinç"}],
"fundamental": [{en:"fundamental to sth",tr:"bir şey için temel olan"}, {en:"a fundamental change",tr:"köklü bir değişim"}, {en:"fundamental rights",tr:"temel haklar"}],
"further": [{en:"further our understanding",tr:"anlayışımızı ilerletmek"}, {en:"further research is needed",tr:"daha fazla araştırma gerekli"}, {en:"further your career",tr:"kariyerini ileriye taşımak"}],
"game": [{en:"play a game",tr:"oyun oynamak, maç yapmak"}, {en:"the rules of the game",tr:"oyunun kuralları"}],
"gas": [{en:"greenhouse gas emissions",tr:"sera gazı salımları"}, {en:"natural gas",tr:"doğal gaz"}],
"gender": [{en:"gender equality",tr:"cinsiyet eşitliği"}, {en:"gender differences",tr:"cinsiyet farklılıkları"}],
"general": [{en:"in general",tr:"genel olarak"}, {en:"as a general rule",tr:"genel kural olarak"}, {en:"the general public",tr:"halk, geniş kitleler"}],
"generate": [{en:"generate income",tr:"gelir sağlamak"}, {en:"generate electricity",tr:"elektrik üretmek"}, {en:"generate interest",tr:"ilgi çekmek, merak uyandırmak"}],
"genetic": [{en:"genetic disorder",tr:"genetik hastalık"}, {en:"genetic engineering",tr:"genetik mühendislik"}, {en:"genetic factors",tr:"genetik faktörler"}],
"getting": [{en:"getting used to sth",tr:"bir şeye alışmak"}, {en:"getting rid of sth",tr:"bir şeyden kurtulmak"}],
"globe": [{en:"around the globe",tr:"dünyanın her yerinde"}, {en:"across the globe",tr:"dünyanın dört bir yanında"}],
"greater": [{en:"greater than",tr:"-den daha büyük"}, {en:"to a greater extent",tr:"daha büyük ölçüde"}, {en:"greater emphasis on sth",tr:"bir şeye daha fazla vurgu"}],
"greatly": [{en:"vary greatly",tr:"büyük ölçüde değişmek"}, {en:"greatly increase",tr:"büyük ölçüde artmak"}],
"growing": [{en:"a growing number of",tr:"giderek artan sayıda"}, {en:"growing concern",tr:"artan endişe"}],
"guess": [{en:"make a guess",tr:"tahmin yürütmek"}, {en:"an educated guess",tr:"bilgiye dayalı tahmin"}],
"habit": [{en:"get into the habit of",tr:"bir şeyi alışkanlık edinmek"}, {en:"out of habit",tr:"alışkanlıktan"}, {en:"break a habit",tr:"bir alışkanlıktan kurtulmak"}],
"habitat": [{en:"natural habitat",tr:"doğal yaşam alanı"}, {en:"habitat loss",tr:"yaşam alanı kaybı"}, {en:"destroy habitats",tr:"yaşam alanlarını yok etmek"}],
"happy": [{en:"be happy with sth",tr:"bir şeyden memnun olmak"}, {en:"happy to help",tr:"memnuniyetle yardım etmek"}],
"hardly": [{en:"hardly ever",tr:"neredeyse hiç"}, {en:"hardly any",tr:"hemen hemen hiç"}, {en:"hardly had he arrived",tr:"o varır varmaz"}],
"harm": [{en:"do harm to sb",tr:"birine zarar vermek"}, {en:"cause serious harm",tr:"ciddi zarar vermek"}, {en:"harm the environment",tr:"çevreye zarar vermek"}],
"harmful": [{en:"harmful to health",tr:"sağlığa zararlı"}, {en:"harmful effects of sth",tr:"bir şeyin zararlı etkileri"}],
"have-not": [{en:"the haves and have-nots",tr:"varsıllar ve yoksullar"}],
"heat": [{en:"extreme heat",tr:"aşırı sıcak"}, {en:"heat sth up",tr:"bir şeyi ısıtmak"}],
"heavily": [{en:"rely heavily on sth",tr:"bir şeye büyük ölçüde bağlı olmak"}, {en:"invest heavily in sth",tr:"bir şeye büyük yatırım yapmak"}, {en:"rain heavily",tr:"şiddetli yağmur yağmak"}],
"heavy": [{en:"heavy rain",tr:"şiddetli yağmur"}, {en:"heavy traffic",tr:"yoğun trafik"}],
"higher": [{en:"higher education",tr:"yükseköğretim"}, {en:"higher than average",tr:"ortalamanın üzerinde"}],
"hope": [{en:"hope for sth",tr:"bir şeyi ummak"}, {en:"in the hope of",tr:"bir şey umuduyla"}, {en:"hope to do sth",tr:"bir şeyi yapmayı ummak"}],
"hour": [{en:"rush hour",tr:"trafiğin yoğun olduğu saat"}, {en:"working hours",tr:"çalışma saatleri"}],
"hours": [{en:"working hours",tr:"çalışma saatleri"}, {en:"work long hours",tr:"uzun saatler çalışmak"}],
"house": [{en:"house prices",tr:"konut fiyatları"}, {en:"move house",tr:"başka eve taşınmak"}],
"huge": [{en:"a huge amount of",tr:"çok büyük miktarda"}, {en:"a huge impact on",tr:"çok büyük bir etki"}, {en:"a huge success",tr:"büyük bir başarı"}],
"hundred": [{en:"hundreds of people",tr:"yüzlerce insan"}, {en:"a hundred years ago",tr:"yüz yıl önce"}],
"hunt": [{en:"hunt for sth",tr:"bir şeyi aramak"}, {en:"go hunting",tr:"ava çıkmak"}],
"identity": [{en:"a sense of identity",tr:"kimlik duygusu"}, {en:"national identity",tr:"ulusal kimlik"}, {en:"identity theft",tr:"kimlik hırsızlığı"}],
"ignore": [{en:"ignore a warning",tr:"uyarıyı dikkate almamak"}, {en:"ignore the evidence",tr:"kanıtları görmezden gelmek"}],
"ill": [{en:"fall ill",tr:"hastalanmak, rahatsızlanmak"}, {en:"speak ill of sb",tr:"birinin arkasından kötü konuşmak"}, {en:"ill effects",tr:"zararlı etkiler"}],
"illness": [{en:"suffer from an illness",tr:"bir hastalıktan muzdarip olmak"}, {en:"mental illness",tr:"akıl hastalığı"}],
"implement": [{en:"implement a policy",tr:"bir politikayı uygulamak"}, {en:"implement changes",tr:"değişiklikleri hayata geçirmek"}],
"importance": [{en:"the importance of sth",tr:"bir şeyin önemi"}, {en:"attach importance to sth",tr:"bir şeye önem vermek"}, {en:"of great importance",tr:"büyük önem taşıyan"}],
"improved": [{en:"greatly improved",tr:"büyük ölçüde iyileştirilmiş"}, {en:"improved performance",tr:"gelişmiş performans"}],
"improvement": [{en:"an improvement in sth",tr:"bir şeyde iyileşme"}, {en:"room for improvement",tr:"gelişme payı"}, {en:"a significant improvement",tr:"kayda değer bir iyileşme"}],
"incentive": [{en:"an incentive to do sth",tr:"bir şey yapma teşviki"}, {en:"provide an incentive",tr:"teşvik sağlamak"}, {en:"financial incentives",tr:"mali teşvikler"}],
"income": [{en:"a source of income",tr:"gelir kaynağı"}, {en:"low income families",tr:"düşük gelirli aileler"}, {en:"annual income",tr:"yıllık gelir"}],
"increasing": [{en:"an increasing number of",tr:"giderek artan sayıda"}, {en:"increasing demand for",tr:"bir şeye yönelik artan talep"}],
"increasingly": [{en:"increasingly important",tr:"giderek daha önemli"}, {en:"become increasingly difficult",tr:"giderek zorlaşmak"}],
"indicate": [{en:"the results indicate that",tr:"sonuçlar şunu göstermektedir"}, {en:"indicate a willingness to",tr:"istekli olduğunu göstermek"}, {en:"clearly indicate",tr:"açıkça göstermek"}],
"industrial": [{en:"the industrial revolution",tr:"sanayi devrimi, endüstri devrimi"}, {en:"industrial waste",tr:"endüstriyel atık"}, {en:"industrial production",tr:"sanayi üretimi"}],
"infer": [{en:"infer sth from sth",tr:"bir şeyden bir şey çıkarmak"}, {en:"it can be inferred",tr:"şu sonuç çıkarılabilir"}],
"inform": [{en:"inform sb of sth",tr:"birine bir şeyi bildirmek"}, {en:"inform sb about sth",tr:"birine bir şey hakkında bilgi vermek"}, {en:"keep sb informed",tr:"birini sürekli bilgilendirmek"}],
"initial": [{en:"the initial stage",tr:"başlangıç aşaması"}, {en:"an initial reaction",tr:"ilk tepki, ilk yanıt"}, {en:"initial results",tr:"ilk sonuçlar"}],
"inside": [{en:"inside out",tr:"tersyüz, içi dışına"}, {en:"inside information",tr:"içeriden bilgi"}, {en:"inside the building",tr:"binanın içinde"}],
"insight": [{en:"gain insight into sth",tr:"bir şeye dair içgörü kazanmak"}, {en:"provide insight into sth",tr:"bir şeye ışık tutmak"}],
"inspire": [{en:"inspire sb to do sth",tr:"birine bir şey yapması için ilham vermek"}, {en:"be inspired by sth",tr:"bir şeyden ilham almak"}, {en:"inspire confidence",tr:"güven vermek"}],
"intense": [{en:"intense pressure",tr:"yoğun baskı"}, {en:"intense competition",tr:"yoğun rekabet"}],
"interact": [{en:"interact with sb",tr:"biriyle etkileşmek"}, {en:"interact with each other",tr:"birbiriyle etkileşmek"}],
"interaction": [{en:"interaction with others",tr:"başkalarıyla etkileşim"}, {en:"social interaction",tr:"sosyal etkileşim"}],
"interested": [{en:"be interested in sth",tr:"bir şeyle ilgilenmek"}, {en:"interested in doing sth",tr:"bir şeyi yapmakla ilgilenmek"}],
"international": [{en:"international relations",tr:"uluslararası ilişkiler"}, {en:"the international community",tr:"uluslararası toplum"}],
"internet": [{en:"on the internet",tr:"internet üzerinde, internette"}, {en:"internet access",tr:"internet erişimi"}, {en:"browse the internet",tr:"internette dolaşmak"}],
"interpret": [{en:"interpret sth as sth",tr:"bir şeyi bir şey olarak yorumlamak"}, {en:"interpret the results",tr:"sonuçları yorumlamak"}, {en:"be interpreted as sth",tr:"bir şey olarak yorumlanmak"}],
"introduce": [{en:"introduce sb to sb",tr:"birini biriyle tanıştırmak"}, {en:"introduce a new law",tr:"yeni bir yasa çıkarmak"}, {en:"introduce a measure",tr:"bir önlem getirmek"}],
"invest": [{en:"invest in sth",tr:"bir şeye yatırım yapmak"}, {en:"invest heavily in sth",tr:"bir şeye büyük yatırım yapmak"}, {en:"invest time in sth",tr:"bir şeye zaman ayırmak"}],
"investment": [{en:"investment in sth",tr:"bir şeye yapılan yatırım"}, {en:"a return on investment",tr:"yatırım getirisi"}, {en:"make an investment",tr:"yatırım yapmak"}],
"involved": [{en:"be involved in sth",tr:"bir şeye dahil olmak"}, {en:"get involved in a project",tr:"bir projeye katılmak"}, {en:"the people involved",tr:"ilgili kişiler"}],
"item": [{en:"an item of clothing",tr:"bir giyim eşyası"}, {en:"items on the agenda",tr:"gündem maddeleri"}],
"key": [{en:"the key to success",tr:"başarının anahtarı"}, {en:"play a key role",tr:"kilit bir rol üstlenmek"}, {en:"a key factor",tr:"başlıca etken"}],
"kill": [{en:"be killed in an accident",tr:"kazada hayatını kaybetmek"}, {en:"kill time",tr:"vakit öldürmek"}],
"labour": [{en:"the labour force",tr:"iş gücü"}, {en:"cheap labour",tr:"ucuz iş gücü"}, {en:"child labour",tr:"çocuk işçiliği"}],
"largely": [{en:"largely due to sth",tr:"büyük ölçüde bir şeyden dolayı"}, {en:"largely responsible for",tr:"büyük ölçüde sorumlu"}, {en:"largely ignored",tr:"büyük ölçüde göz ardı edilen"}],
"larger": [{en:"on a larger scale",tr:"daha büyük ölçekte"}, {en:"a larger proportion",tr:"daha büyük bir oran"}],
"later": [{en:"sooner or later",tr:"er ya da geç"}, {en:"later on",tr:"daha sonra"}],
"law": [{en:"break the law",tr:"yasayı çiğnemek"}, {en:"against the law",tr:"yasaya aykırı"}, {en:"pass a law",tr:"yasa çıkarmak"}],
"layer": [{en:"a layer of dust",tr:"bir toz tabakası"}, {en:"the ozone layer",tr:"ozon tabakası"}, {en:"layer upon layer",tr:"kat kat, üst üste"}],
"let": [{en:"let sb know",tr:"birine haber vermek, bilgi ulaştırmak"}, {en:"let go of sth",tr:"bir şeyi bırakmak"}, {en:"let alone",tr:"şöyle dursun"}],
"limited": [{en:"be limited to sth",tr:"bir şeyle sınırlı olmak"}, {en:"a limited number of",tr:"sınırlı sayıda"}, {en:"limited resources",tr:"kısıtlı kaynaklar"}],
"local": [{en:"local government",tr:"yerel yönetim"}, {en:"the local community",tr:"yerel halk, yöre halkı"}, {en:"local authorities",tr:"yerel yönetim birimleri"}],
"location": [{en:"the location of sth",tr:"bir şeyin konumu"}, {en:"a remote location",tr:"ücra bir konum"}],
"long-time": [{en:"a long-time friend",tr:"uzun süredir dost olan kişi"}, {en:"a long-time resident",tr:"uzun süredir orada yaşayan kişi"}],
"longer": [{en:"no longer",tr:"artık değil"}, {en:"any longer",tr:"artık, daha fazla"}],
"looking": [{en:"looking forward to sth",tr:"bir şeyi dört gözle beklemek"}, {en:"be good-looking",tr:"yakışıklı, güzel görünümlü olmak"}],
"lost": [{en:"get lost",tr:"kaybolmak"}, {en:"lost in thought",tr:"düşüncelere dalmış"}, {en:"a lost opportunity",tr:"kaçırılmış bir fırsat"}],
"love": [{en:"fall in love with sb",tr:"birine aşık olmak"}, {en:"love doing sth",tr:"bir şeyi yapmayı sevmek"}],
"lower": [{en:"lower the risk of sth",tr:"bir şeyin riskini azaltmak"}, {en:"lower costs",tr:"maliyetleri düşürmek"}, {en:"a lower rate",tr:"daha düşük bir oran"}],
"machine": [{en:"a washing machine",tr:"çamaşır makinesi"}, {en:"machine learning",tr:"makine öğrenmesi"}],
"majority": [{en:"the majority of sth",tr:"bir şeyin çoğunluğu"}, {en:"a vast majority",tr:"büyük bir çoğunluk"}, {en:"in the majority",tr:"çoğunlukta"}],
"make-up": [{en:"the make-up of sth",tr:"bir şeyin yapısı"}, {en:"wear make-up",tr:"makyaj yapmış olmak"}],
"manage": [{en:"manage to do sth",tr:"bir şeyi yapmayı başarmak"}, {en:"manage a company",tr:"bir şirketi yönetmek"}, {en:"manage resources",tr:"kaynakları yönetmek"}],
"management": [{en:"senior management",tr:"üst yönetim"}, {en:"time management",tr:"zaman yönetimi"}, {en:"management skills",tr:"yönetim becerileri"}],
"manager": [{en:"a project manager",tr:"bir proje yöneticisi"}, {en:"a senior manager",tr:"üst düzey bir yönetici"}],
"manipulate": [{en:"manipulate sb into sth",tr:"birini bir şeye yönlendirmek"}, {en:"manipulate data",tr:"veriyi manipüle etmek"}, {en:"manipulate public opinion",tr:"kamuoyunu yönlendirmek"}],
"manual": [{en:"a user manual",tr:"kullanım kılavuzu"}, {en:"manual labour",tr:"el emeği, bedensel iş"}],
"market": [{en:"on the market",tr:"piyasada, satışta"}, {en:"market share",tr:"pazar payı"}, {en:"enter the market",tr:"piyasaya girmek, pazara açılmak"}],
"mass": [{en:"mass production",tr:"seri üretim"}, {en:"mass media",tr:"kitle iletişim araçları"}, {en:"weapons of mass destruction",tr:"kitle imha silahları"}],
"meet": [{en:"meet a deadline",tr:"son teslim tarihine yetişmek"}, {en:"meet the requirements",tr:"koşulları karşılamak"}, {en:"meet sb's needs",tr:"birinin ihtiyaçlarını karşılamak"}],
"memory": [{en:"in memory of sb",tr:"birinin anısına"}, {en:"have a good memory",tr:"hafızası iyi olmak"}],
"middle": [{en:"in the middle of sth",tr:"bir şeyin ortasında"}, {en:"the middle class",tr:"orta sınıf"}],
"military": [{en:"military force",tr:"askeri güç"}, {en:"join the military",tr:"orduya katılmak"}],
"monitor": [{en:"monitor progress",tr:"ilerlemeyi izlemek"}, {en:"closely monitor sth",tr:"bir şeyi yakından izlemek"}],
"month": [{en:"last month",tr:"geçen ay"}, {en:"a month ago",tr:"bir ay önce"}],
"mother": [{en:"mother tongue",tr:"ana dil, kişinin ilk dili"}],
"muscle": [{en:"build muscle",tr:"kas geliştirmek"}, {en:"pull a muscle",tr:"kasını incitmek"}, {en:"muscle strength",tr:"kas gücü"}],
"name": [{en:"name sth after sb",tr:"bir şeye birinin adını vermek"}, {en:"in the name of",tr:"adına, namına"}, {en:"make a name for yourself",tr:"ad yapmak, tanınmak"}],
"nation": [{en:"developing nations",tr:"gelişmekte olan ülkeler"}, {en:"the United Nations",tr:"Birleşmiş Milletler"}],
"native": [{en:"be native to sth",tr:"bir yere özgü olmak"}, {en:"native speaker",tr:"ana dili konuşan kişi"}],
"near": [{en:"in the near future",tr:"yakın gelecekte"}, {en:"near the end of sth",tr:"bir şeyin sonuna doğru"}],
"neither": [{en:"neither good nor bad",tr:"ne iyi ne kötü"}, {en:"neither of them",tr:"ikisi de değil"}, {en:"neither do I",tr:"ben de değilim"}],
"network": [{en:"a network of roads",tr:"yol ağı"}, {en:"social network",tr:"sosyal ağ"}, {en:"build a network",tr:"ağ kurmak"}],
"neutral": [{en:"remain neutral",tr:"tarafsız kalmak"}, {en:"a neutral stance",tr:"tarafsız bir tutum"}],
"nor": [{en:"neither ... nor",tr:"ne ... ne de"}, {en:"nor do I",tr:"ben de değilim"}],
"norm": [{en:"deviate from the norm",tr:"normdan sapmak"}, {en:"become the norm",tr:"olağan hale gelmek"}, {en:"social norms",tr:"toplumsal normlar"}],
"normal": [{en:"back to normal",tr:"normale dönmek"}, {en:"under normal circumstances",tr:"normal koşullarda"}],
"north": [{en:"to the north of sth",tr:"bir şeyin kuzeyinde"}, {en:"in the north",tr:"kuzeyde, kuzey bölgesinde"}, {en:"head north",tr:"kuzeye yönelmek"}],
"nuclear": [{en:"a nuclear power plant",tr:"nükleer santral"}, {en:"nuclear weapons",tr:"nükleer silahlar"}],
"object": [{en:"object to sth",tr:"bir şeye itiraz etmek"}, {en:"object to doing sth",tr:"bir şeyi yapmaya itiraz etmek"}, {en:"the object of study",tr:"çalışmanın konusu"}],
"objective": [{en:"the main objective",tr:"asıl amaç"}, {en:"achieve an objective",tr:"hedefe ulaşmak"}, {en:"an objective view",tr:"nesnel bakış açısı"}],
"observe": [{en:"observe behaviour",tr:"davranışı gözlemlemek"}, {en:"observe changes closely",tr:"değişimleri yakından gözlemlemek"}, {en:"observe safety rules",tr:"güvenlik kurallarına uymak"}],
"obtain": [{en:"obtain information",tr:"bilgi edinmek"}, {en:"obtain permission",tr:"izin almak"}],
"obvious": [{en:"it is obvious that",tr:"açıkça görülmektedir ki"}, {en:"for obvious reasons",tr:"bariz nedenlerle"}],
"oil": [{en:"crude oil",tr:"ham petrol"}, {en:"oil prices",tr:"petrol fiyatları"}],
"older": [{en:"older than me",tr:"benden daha yaşlı"}, {en:"grow older",tr:"yaşlanmak"}, {en:"older people",tr:"yaşlı insanlar"}],
"online": [{en:"available online",tr:"çevrimiçi erişilebilir"}, {en:"shop online",tr:"çevrimiçi alışveriş yapmak"}, {en:"an online course",tr:"çevrimiçi bir kurs"}],
"open": [{en:"be open to sth",tr:"bir şeye açık olmak"}, {en:"in the open air",tr:"açık havada"}, {en:"open an account",tr:"hesap açmak"}],
"opinion": [{en:"in my opinion",tr:"bence, bana göre"}, {en:"public opinion",tr:"kamuoyu, halkın görüşü"}, {en:"express an opinion",tr:"görüş belirtmek"}],
"oppose": [{en:"be opposed to sth",tr:"bir şeye karşı olmak"}, {en:"as opposed to",tr:"aksine, karşıt olarak"}, {en:"strongly oppose sth",tr:"bir şeye şiddetle karşı çıkmak"}],
"organ": [{en:"organ donation",tr:"organ bağışı"}, {en:"internal organs",tr:"iç organlar"}],
"origin": [{en:"the origin of sth",tr:"bir şeyin kökeni"}, {en:"country of origin",tr:"menşe ülke"}, {en:"be of Greek origin",tr:"Yunan kökenli olmak"}],
"otherwise": [{en:"unless otherwise stated",tr:"aksi belirtilmedikçe"}, {en:"otherwise known as",tr:"diğer adıyla"}],
"outcome": [{en:"the outcome of sth",tr:"bir şeyin sonucu"}, {en:"a positive outcome",tr:"olumlu sonuç"}, {en:"affect the outcome",tr:"sonuca etki etmek, sonucu değiştirmek"}],
"overall": [{en:"the overall effect",tr:"genel etki, bütünsel etki"}, {en:"overall performance",tr:"genel başarı düzeyi"}],
"overcome": [{en:"overcome difficulties",tr:"zorlukların üstesinden gelmek"}, {en:"overcome an obstacle",tr:"bir engeli aşmak"}, {en:"be overcome by fear",tr:"korkuya yenik düşmek"}],
"pain": [{en:"in pain",tr:"acı içinde"}, {en:"relieve the pain",tr:"ağrıyı dindirmek"}, {en:"chest pain",tr:"göğüs ağrısı"}],
"participate": [{en:"participate in sth",tr:"bir şeye katılmak"}, {en:"actively participate in sth",tr:"bir şeye etkin biçimde katılmak"}],
"parts": [{en:"spare parts",tr:"yedek parçalar"}, {en:"in these parts",tr:"bu yörelerde"}],
"pass": [{en:"pass a law",tr:"yasa çıkarmak"}, {en:"pass an exam",tr:"sınavı geçmek"}, {en:"as time passes",tr:"zaman geçtikçe"}],
"patient": [{en:"be patient with sb",tr:"birine karşı sabırlı olmak"}, {en:"treat a patient",tr:"bir hastayı tedavi etmek"}],
"pattern": [{en:"a pattern of behaviour",tr:"davranış örüntüsü"}, {en:"follow a pattern",tr:"bir örüntüyü izlemek"}, {en:"a similar pattern",tr:"benzer bir örüntü"}],
"perform": [{en:"perform a task",tr:"bir görevi yerine getirmek"}, {en:"perform an experiment",tr:"deney yapmak"}, {en:"perform well",tr:"iyi performans göstermek"}],
"perhaps": [{en:"perhaps the most important",tr:"belki de en önemlisi"}],
"personality": [{en:"a strong personality",tr:"güçlü bir kişilik"}, {en:"personality traits",tr:"kişilik özellikleri"}],
"perspective": [{en:"from a different perspective",tr:"farklı bir bakış açısından"}, {en:"put sth into perspective",tr:"bir şeyi doğru çerçeveye oturtmak"}],
"phenomenon": [{en:"a natural phenomenon",tr:"doğal bir olgu"}, {en:"a widespread phenomenon",tr:"yaygın bir olgu"}, {en:"explain the phenomenon",tr:"olguyu açıklamak"}],
"phone": [{en:"answer the phone",tr:"telefonu açmak"}, {en:"on the phone",tr:"telefonda, telefonla konuşurken"}],
"physically": [{en:"physically demanding",tr:"bedensel güç isteyen"}, {en:"physically active",tr:"fiziksel açıdan hareketli"}],
"picture": [{en:"paint a picture of",tr:"bir tablo çizmek"}, {en:"take a picture",tr:"fotoğraf çekmek"}, {en:"the big picture",tr:"büyük resim, genel görünüm"}],
"piece": [{en:"a piece of advice",tr:"bir tavsiye"}, {en:"a piece of information",tr:"bir bilgi"}],
"pollution": [{en:"air pollution",tr:"hava kirliliği"}, {en:"reduce pollution",tr:"kirliliği azaltmak"}],
"portion": [{en:"a large portion of sth",tr:"bir şeyin büyük bölümü"}, {en:"a small portion",tr:"küçük bir porsiyon"}],
"pose": [{en:"pose a threat to",tr:"bir şeye tehdit oluşturmak"}, {en:"pose a problem",tr:"sorun yaratmak"}, {en:"pose a question",tr:"soru yöneltmek"}],
"position": [{en:"apply for a position",tr:"bir işe başvurmak"}, {en:"hold a position",tr:"bir görevde bulunmak"}, {en:"in a strong position",tr:"güçlü bir konumda"}],
"powerful": [{en:"a powerful effect on sb",tr:"biri üzerinde güçlü etki"}, {en:"a powerful tool",tr:"güçlü bir araç"}],
"prefer": [{en:"prefer sth to sth",tr:"bir şeyi bir şeye tercih etmek"}, {en:"prefer to do sth",tr:"bir şeyi yapmayı tercih etmek"}],
"prepare": [{en:"prepare for sth",tr:"bir şeye hazırlanmak"}, {en:"prepare sb for sth",tr:"birini bir şeye hazırlamak"}],
"preserve": [{en:"preserve the environment",tr:"çevreyi korumak"}, {en:"preserve traditions",tr:"gelenekleri yaşatmak"}, {en:"well preserved",tr:"iyi korunmuş"}],
"price": [{en:"the price of sth",tr:"bir şeyin fiyatı"}, {en:"at a low price",tr:"düşük fiyata"}, {en:"pay the price for sth",tr:"bir şeyin bedelini ödemek"}],
"primarily": [{en:"primarily concerned with sth",tr:"esas olarak bir şeyle ilgili"}, {en:"primarily due to sth",tr:"başlıca bir şey yüzünden"}],
"principle": [{en:"in principle",tr:"ilke olarak, kuramsal açıdan"}, {en:"on principle",tr:"ilke gereği"}, {en:"a basic principle",tr:"temel ilke, başlıca kural"}],
"prior": [{en:"prior to sth",tr:"bir şeyden önce"}, {en:"prior experience",tr:"önceki deneyim"}, {en:"prior knowledge",tr:"ön bilgi"}],
"priority": [{en:"give priority to sth",tr:"bir şeye öncelik vermek"}, {en:"a top priority",tr:"en büyük öncelik"}, {en:"take priority over sth",tr:"bir şeyin önüne geçmek"}],
"progress": [{en:"make progress in sth",tr:"bir şeyde ilerleme kaydetmek"}, {en:"in progress",tr:"sürmekte, devam etmekte"}, {en:"progress towards sth",tr:"bir şeye doğru ilerleme"}],
"propose": [{en:"propose a solution",tr:"bir çözüm önermek"}, {en:"propose to do sth",tr:"bir şey yapmayı önermek"}],
"protection": [{en:"protection against sth",tr:"bir şeye karşı koruma"}, {en:"environmental protection",tr:"çevre koruma"}, {en:"provide protection for sb",tr:"birine koruma sağlamak"}],
"psychological": [{en:"psychological effects",tr:"psikolojik etkiler, ruhsal sonuçlar"}, {en:"psychological problems",tr:"psikolojik sorunlar, ruhsal sıkıntılar"}],
"publish": [{en:"be published in a journal",tr:"bir dergide yayımlanmak"}, {en:"publish a book",tr:"kitap yayımlamak"}, {en:"publish research findings",tr:"araştırma bulgularını yayımlamak"}],
"purchase": [{en:"the purchase of sth",tr:"bir şeyin satın alınması"}, {en:"make a purchase",tr:"satın alma yapmak"}, {en:"purchase a property",tr:"mülk satın almak"}],
"quality": [{en:"high quality",tr:"yüksek kalite"}, {en:"quality of life",tr:"yaşam kalitesi"}],
"quick": [{en:"make a quick decision",tr:"çabuk karar vermek"}, {en:"take a quick look",tr:"kısaca göz atmak"}, {en:"be quick to do sth",tr:"bir şeyi hemen yapmak"}],
"quickly": [{en:"as quickly as possible",tr:"mümkün olduğunca çabuk"}, {en:"spread quickly",tr:"hızla yayılmak"}],
"race": [{en:"race against time",tr:"zamana karşı yarışmak"}, {en:"win a race",tr:"bir yarışı kazanmak"}, {en:"the human race",tr:"insan ırkı"}],
"rapid": [{en:"rapid growth",tr:"hızlı büyüme"}, {en:"a rapid decline",tr:"hızlı bir düşüş"}],
"rarely": [{en:"rarely, if ever",tr:"nadiren, neredeyse hiç"}, {en:"rarely used",tr:"nadiren kullanılan"}],
"react": [{en:"react to sth",tr:"bir şeye tepki vermek"}, {en:"react against sth",tr:"bir şeye karşı çıkmak"}, {en:"react with sth",tr:"bir şeyle tepkimeye girmek"}],
"reaction": [{en:"a reaction to sth",tr:"bir şeye tepki"}, {en:"in reaction to sth",tr:"bir şeye tepki olarak"}, {en:"a chemical reaction",tr:"kimyasal tepkime, kimyasal değişim"}],
"ready": [{en:"be ready for sth",tr:"bir şeye hazır olmak"}, {en:"get ready to do sth",tr:"bir şeyi yapmaya hazırlanmak"}],
"real": [{en:"in real life",tr:"gerçek hayatta"}, {en:"the real world",tr:"gerçek dünya"}],
"receive": [{en:"receive attention",tr:"ilgi görmek"}, {en:"receive treatment",tr:"tedavi görmek"}, {en:"receive an award",tr:"ödül almak"}],
"recover": [{en:"recover from an illness",tr:"bir hastalıktan iyileşmek"}, {en:"recover the cost",tr:"maliyeti geri kazanmak"}],
"regardless": [{en:"regardless of sth",tr:"bir şeye bakılmaksızın"}, {en:"regardless of the cost",tr:"maliyeti ne olursa olsun"}],
"regular": [{en:"on a regular basis",tr:"düzenli olarak"}, {en:"a regular customer",tr:"daimi bir müşteri"}],
"reject": [{en:"reject a proposal",tr:"bir öneriyi reddetmek"}, {en:"reject an offer",tr:"bir teklifi geri çevirmek"}, {en:"flatly reject sth",tr:"bir şeyi kesinlikle reddetmek"}],
"relate": [{en:"relate to sth",tr:"bir şeyle ilgili olmak"}, {en:"be closely related to",tr:"yakından ilişkili olmak"}, {en:"relate sth to sth",tr:"bir şeyi bir şeyle ilişkilendirmek"}],
"related": [{en:"related to sth",tr:"bir şeyle ilgili"}, {en:"closely related",tr:"yakından ilişkili"}],
"relation": [{en:"in relation to sth",tr:"bir şeye ilişkin olarak"}, {en:"the relation between two things",tr:"iki şey arasındaki ilişki"}, {en:"public relations",tr:"halkla ilişkiler"}],
"relatively": [{en:"relatively small",tr:"nispeten küçük"}, {en:"relatively few",tr:"nispeten az sayıda"}],
"relevant": [{en:"relevant to sth",tr:"bir şeyle ilgili"}, {en:"highly relevant",tr:"son derece yerinde, çok ilgili"}],
"remove": [{en:"remove sth from sth",tr:"bir şeyi bir şeyden çıkarmak"}, {en:"remove an obstacle",tr:"bir engeli ortadan kaldırmak"}],
"rephrase": [{en:"rephrase the question",tr:"soruyu yeniden ifade etmek"}, {en:"let me rephrase that",tr:"şunu başka türlü söyleyeyim"}],
"report": [{en:"report on sth",tr:"bir şey hakkında rapor vermek"}, {en:"report sth to sb",tr:"bir şeyi birine bildirmek"}, {en:"according to the report",tr:"rapora göre"}],
"represent": [{en:"represent a threat to",tr:"bir tehdit oluşturmak"}, {en:"be represented by sb",tr:"biri tarafından temsil edilmek"}, {en:"represent a challenge",tr:"bir zorluk teşkil etmek"}],
"response": [{en:"in response to sth",tr:"bir şeye yanıt olarak"}, {en:"an immediate response",tr:"anında verilen bir tepki"}],
"responsible": [{en:"be responsible for sth",tr:"bir şeyden sorumlu olmak"}, {en:"hold sb responsible for sth",tr:"birini bir şeyden sorumlu tutmak"}],
"rest": [{en:"the rest of sth",tr:"bir şeyin geri kalanı"}, {en:"take a rest",tr:"dinlenmek, kısa mola vermek"}],
"restrict": [{en:"restrict access to sth",tr:"bir şeye erişimi kısıtlamak"}, {en:"be restricted to sth",tr:"bir şeyle sınırlı olmak"}, {en:"restrict freedom",tr:"özgürlüğü kısıtlamak"}],
"revolution": [{en:"the industrial revolution",tr:"sanayi devrimi"}, {en:"a revolution in sth",tr:"bir alanda devrim"}],
"rule": [{en:"break the rules",tr:"kuralları çiğnemek"}, {en:"as a rule",tr:"kural olarak, genelde"}, {en:"rule out the possibility",tr:"olasılığı dışlamak"}],
"safe": [{en:"safe from danger",tr:"tehlikeden uzak, güvende"}, {en:"keep sb safe",tr:"birini güvende tutmak"}],
"safety": [{en:"for safety reasons",tr:"güvenlik nedeniyle"}, {en:"ensure the safety of",tr:"bir şeyin güvenliğini sağlamak"}, {en:"safety measures",tr:"güvenlik önlemleri"}],
"said": [{en:"it is said that",tr:"söylendiğine göre"}, {en:"easier said than done",tr:"söylemesi kolay, yapması zor"}, {en:"the said person",tr:"adı geçen kişi"}],
"scale": [{en:"on a large scale",tr:"büyük ölçekte"}, {en:"the scale of the problem",tr:"sorunun büyüklüğü"}, {en:"scale up production",tr:"üretimi büyütmek"}],
"scholar": [{en:"a leading scholar",tr:"önde gelen bir bilim insanı"}],
"search": [{en:"search for sth",tr:"bir şeyi aramak"}, {en:"in search of sth",tr:"bir şeyin arayışı içinde"}],
"select": [{en:"select sb for sth",tr:"birini bir şey için seçmek"}, {en:"randomly select participants",tr:"katılımcıları rastgele seçmek"}, {en:"a select group",tr:"seçkin bir grup"}],
"sell": [{en:"sell sth to sb",tr:"bir şeyi birine satmak"}, {en:"sell out",tr:"tükenmek, satılıp bitmek"}, {en:"sell well",tr:"iyi satmak"}],
"serve": [{en:"serve as an example",tr:"örnek teşkil etmek"}, {en:"serve a purpose",tr:"bir işe yaramak"}, {en:"serve customers",tr:"müşterilere hizmet vermek"}],
"severe": [{en:"severe damage",tr:"ağır hasar"}, {en:"a severe shortage",tr:"ciddi bir kıtlık"}, {en:"severe weather conditions",tr:"ağır hava koşulları"}],
"share": [{en:"share sth with sb",tr:"bir şeyi biriyle paylaşmak"}, {en:"market share",tr:"pazar payı"}],
"shift": [{en:"a shift in sth",tr:"bir şeydeki değişim"}, {en:"shift the focus to",tr:"odağı bir şeye kaydırmak"}, {en:"work night shifts",tr:"gece vardiyasında çalışmak"}],
"side": [{en:"on the other side",tr:"diğer tarafta"}, {en:"take sides",tr:"birinin tarafını tutmak"}, {en:"from side to side",tr:"bir yandan öbür yana"}],
"sign": [{en:"a sign of sth",tr:"bir şeyin belirtisi"}, {en:"sign a contract",tr:"sözleşme imzalamak"}, {en:"show signs of sth",tr:"bir şeyin belirtilerini göstermek"}],
"signal": [{en:"send a signal",tr:"sinyal göndermek"}, {en:"a warning signal",tr:"bir uyarı sinyali"}, {en:"signal a change",tr:"değişimin işareti olmak"}],
"site": [{en:"on site",tr:"iş başında, sahada"}, {en:"a construction site",tr:"inşaat alanı, şantiye"}],
"sleep": [{en:"get a good night's sleep",tr:"gece iyi bir uyku çekmek"}, {en:"lack of sleep",tr:"uyku eksikliği, uykusuzluk"}],
"slow": [{en:"slow down",tr:"yavaşlamak, yavaşlatmak"}, {en:"be slow to respond",tr:"tepki vermekte yavaş olmak"}, {en:"a slow process",tr:"yavaş bir süreç"}],
"soil": [{en:"soil erosion",tr:"toprak aşınması"}, {en:"soil fertility",tr:"toprağın verimliliği"}],
"solution": [{en:"a solution to a problem",tr:"bir soruna çözüm"}, {en:"find a solution",tr:"çözüm bulmak"}],
"solve": [{en:"solve a problem",tr:"bir sorunu çözmek"}, {en:"solve the mystery",tr:"gizemi çözmek"}],
"speak": [{en:"speak to sb about sth",tr:"biriyle bir şey hakkında konuşmak"}, {en:"speak up",tr:"sesini yükseltmek, açıkça söylemek"}, {en:"generally speaking",tr:"genel olarak söylersek"}],
"special": [{en:"pay special attention to",tr:"özel önem vermek"}, {en:"a special case",tr:"özel bir durum"}],
"speed": [{en:"at high speed",tr:"yüksek hızla"}, {en:"speed up the process",tr:"süreci hızlandırmak"}, {en:"pick up speed",tr:"hız kazanmak"}],
"stage": [{en:"at this stage",tr:"bu aşamada"}, {en:"in the early stages",tr:"ilk aşamalarda"}, {en:"stage a protest",tr:"protesto düzenlemek"}],
"stand": [{en:"stand for sth",tr:"bir şeyi temsil etmek"}, {en:"stand out",tr:"öne çıkmak, dikkat çekmek"}, {en:"stand up for sb",tr:"birinin hakkını savunmak"}],
"standard": [{en:"meet the standards",tr:"standartları karşılamak"}, {en:"standard of living",tr:"yaşam standardı"}, {en:"a high standard",tr:"yüksek bir ölçüt"}],
"stated": [{en:"as stated above",tr:"yukarıda belirtildiği gibi"}, {en:"the stated aim",tr:"belirtilen amaç"}],
"step": [{en:"the first step towards sth",tr:"bir şeye doğru atılan ilk adım"}, {en:"take a step",tr:"adım atmak"}, {en:"step by step",tr:"adım adım"}],
"store": [{en:"store sth safely",tr:"bir şeyi güvenle saklamak"}, {en:"be in store for sb",tr:"birini beklemek, başına gelmek"}, {en:"a department store",tr:"büyük mağaza"}],
"strategy": [{en:"a strategy for sth",tr:"bir şey için strateji"}, {en:"develop a strategy",tr:"strateji geliştirmek"}],
"strength": [{en:"strengths and weaknesses",tr:"güçlü ve zayıf yönler"}, {en:"gain strength",tr:"güç kazanmak"}],
"strike": [{en:"go on strike",tr:"greve gitmek"}, {en:"strike a balance",tr:"denge kurmak"}, {en:"strike a deal",tr:"anlaşmaya varmak"}],
"struggle": [{en:"struggle with sth",tr:"bir şeyle boğuşmak"}, {en:"struggle for freedom",tr:"özgürlük için mücadele etmek"}, {en:"struggle to do sth",tr:"bir şeyi yapmakta zorlanmak"}],
"style": [{en:"a style of writing",tr:"bir yazı tarzı"}, {en:"out of style",tr:"modası geçmiş"}],
"substance": [{en:"a toxic substance",tr:"zehirli bir madde"}, {en:"harmful substances",tr:"zararlı maddeler"}],
"sufficient": [{en:"sufficient for sth",tr:"bir şey için yeterli"}, {en:"sufficient evidence",tr:"yeterli kanıt"}],
"sun": [{en:"in the sun",tr:"güneşte"}, {en:"the sun rises",tr:"güneş doğar"}],
"supply": [{en:"supply sb with sth",tr:"birine bir şey sağlamak"}, {en:"in short supply",tr:"kıt, yetersiz"}, {en:"supply and demand",tr:"arz ve talep ilişkisi"}],
"surface": [{en:"on the surface",tr:"görünüşte, yüzeyde"}, {en:"come to the surface",tr:"yüzeye çıkmak"}, {en:"surface area",tr:"yüzey alanı"}],
"surprise": [{en:"to my surprise",tr:"şaşkınlıkla, hayretle"}, {en:"take sb by surprise",tr:"birini hazırlıksız yakalamak"}, {en:"come as a surprise",tr:"sürpriz olmak"}],
"survival": [{en:"chances of survival",tr:"hayatta kalma şansı"}, {en:"a struggle for survival",tr:"varolma mücadelesi"}, {en:"essential for survival",tr:"hayatta kalmak için gerekli"}],
"symbol": [{en:"a symbol of sth",tr:"bir şeyin simgesi"}, {en:"a status symbol",tr:"statü simgesi"}],
"symptom": [{en:"the symptoms of a disease",tr:"bir hastalığın belirtileri"}, {en:"show symptoms",tr:"belirti göstermek"}, {en:"relieve the symptoms",tr:"şikayetleri hafifletmek"}],
"taken": [{en:"be taken for granted",tr:"olağan sayılmak"}, {en:"be taken aback",tr:"şaşırıp kalmak"}, {en:"this seat is taken",tr:"bu koltuk dolu, tutulmuş"}],
"target": [{en:"set a target",tr:"hedef koymak"}, {en:"target audience",tr:"hedef kitle"}],
"taste": [{en:"a taste for sth",tr:"bir şeye düşkünlük"}, {en:"taste like sth",tr:"bir şeyin tadına benzemek"}, {en:"in bad taste",tr:"zevksiz, uygunsuz"}],
"teach": [{en:"teach sb sth",tr:"birine bir şey öğretmek"}, {en:"teach sb to do sth",tr:"birine bir şey yapmayı öğretmek"}],
"technical": [{en:"provide technical support",tr:"teknik destek sağlamak"}, {en:"technical difficulties",tr:"teknik aksaklıklar"}],
"technique": [{en:"develop a new technique",tr:"yeni bir teknik geliştirmek"}, {en:"apply a technique",tr:"bir tekniği uygulamak"}],
"television": [{en:"on television",tr:"televizyonda"}, {en:"watch television",tr:"televizyon izlemek"}],
"temperature": [{en:"at room temperature",tr:"oda sıcaklığında"}, {en:"a rise in temperature",tr:"sıcaklıkta artış"}, {en:"take sb's temperature",tr:"birinin ateşini ölçmek"}],
"tendency": [{en:"a tendency to do sth",tr:"bir şey yapma eğilimi"}, {en:"have a tendency towards",tr:"bir şeye eğilimi olmak"}],
"text": [{en:"a text message",tr:"kısa mesaj"}, {en:"analyse a text",tr:"bir metni çözümlemek"}],
"thinking": [{en:"critical thinking",tr:"eleştirel düşünme"}, {en:"a way of thinking",tr:"bir düşünme biçimi"}, {en:"wishful thinking",tr:"hüsnükuruntu"}],
"thousand": [{en:"thousands of people",tr:"binlerce kişi"}, {en:"a thousand years ago",tr:"bin yıl önce"}],
"threat": [{en:"pose a threat to sth",tr:"bir şeye tehdit oluşturmak"}, {en:"under threat",tr:"tehdit altında"}, {en:"a serious threat",tr:"ciddi bir tehdit"}],
"tiny": [{en:"a tiny amount",tr:"çok küçük bir miktar"}, {en:"a tiny minority",tr:"çok küçük bir azınlık"}],
"title": [{en:"the title of a book",tr:"bir kitabın başlığı"}, {en:"job title",tr:"iş unvanı"}],
"tool": [{en:"a useful tool",tr:"yararlı bir araç"}, {en:"tools and equipment",tr:"alet ve ekipman"}],
"top": [{en:"on top of sth",tr:"bir şeyin üstünde"}, {en:"at the top of",tr:"en üstünde, zirvesinde"}, {en:"from top to bottom",tr:"baştan aşağı"}],
"topic": [{en:"the topic of discussion",tr:"tartışma konusu"}, {en:"change the topic",tr:"konuyu değiştirmek"}],
"total": [{en:"in total",tr:"toplamda, tümü"}, {en:"the total number of sth",tr:"bir şeyin toplam sayısı"}, {en:"a total failure",tr:"tam bir başarısızlık"}],
"trace": [{en:"trace sth back to",tr:"bir şeyin izini geriye doğru sürmek"}, {en:"without a trace",tr:"iz bırakmadan"}, {en:"traces of sth",tr:"bir şeyin izleri"}],
"track": [{en:"keep track of sth",tr:"bir şeyi takip etmek"}, {en:"lose track of sth",tr:"bir şeyin izini kaybetmek"}, {en:"on the right track",tr:"doğru yolda"}],
"trade": [{en:"trade with other countries",tr:"başka ülkelerle ticaret yapmak"}, {en:"foreign trade",tr:"dış ticaret"}, {en:"a trade agreement",tr:"ticaret anlaşması"}],
"tradition": [{en:"a long tradition of sth",tr:"bir şeyin köklü geleneği"}, {en:"according to tradition",tr:"geleneğe göre"}],
"trait": [{en:"personality traits",tr:"kişilik özellikleri"}, {en:"inherited traits",tr:"kalıtsal özellikler"}],
"transform": [{en:"transform sth into sth",tr:"bir şeyi bir şeye dönüştürmek"}, {en:"radically transform sth",tr:"bir şeyi kökten dönüştürmek"}],
"transport": [{en:"public transport",tr:"toplu taşıma"}, {en:"means of transport",tr:"ulaşım aracı"}, {en:"transport goods",tr:"mal taşımak"}],
"travel": [{en:"travel abroad",tr:"yurt dışına seyahat etmek"}, {en:"travel by train",tr:"trenle seyahat etmek"}],
"treat": [{en:"treat a disease",tr:"bir hastalığı tedavi etmek"}, {en:"treat sb with respect",tr:"birine saygıyla davranmak"}],
"tree": [{en:"plant a tree",tr:"ağaç dikmek"}, {en:"family tree",tr:"soy ağacı"}],
"trend": [{en:"a trend towards sth",tr:"bir şeye yönelik eğilim"}, {en:"a growing trend",tr:"artan bir eğilim"}, {en:"set a trend",tr:"çığır açmak, moda başlatmak"}],
"trigger": [{en:"trigger a reaction",tr:"bir tepkiyi tetiklemek"}, {en:"pull the trigger",tr:"tetiği çekmek"}],
"trying": [{en:"a trying time",tr:"zor bir dönem"}, {en:"trying circumstances",tr:"zorlu koşullar"}],
"understood": [{en:"make yourself understood",tr:"kendini anlaşılır kılmak"}, {en:"it is understood that",tr:"anlaşıldığına göre"}, {en:"widely understood",tr:"yaygın olarak anlaşılan"}],
"unite": [{en:"unite against a threat",tr:"bir tehdide karşı birleşmek"}, {en:"unite people",tr:"insanları birleştirmek"}],
"united": [{en:"united against a common enemy",tr:"ortak düşmana karşı birleşmiş"}, {en:"a united front",tr:"birleşik cephe"}, {en:"the United Nations",tr:"Birleşmiş Milletler"}],
"universe": [{en:"the origin of the universe",tr:"evrenin kökeni"}, {en:"the entire universe",tr:"tüm evren"}],
"useful": [{en:"be useful for sth",tr:"bir şey için yararlı olmak"}, {en:"come in useful",tr:"işe yaramak"}],
"vast": [{en:"a vast majority",tr:"büyük bir çoğunluk"}, {en:"vast amounts of sth",tr:"muazzam miktarda bir şey"}],
"version": [{en:"a new version of",tr:"bir şeyin yeni sürümü"}, {en:"the latest version",tr:"en son sürüm"}],
"visible": [{en:"clearly visible",tr:"açıkça görünür"}, {en:"visible to the naked eye",tr:"çıplak gözle görülebilir"}],
"visit": [{en:"pay sb a visit",tr:"birine kısa bir ziyaret yapmak"}, {en:"on a visit to sth",tr:"bir yeri ziyaret sırasında"}],
"visual": [{en:"visual arts",tr:"görsel sanatlar"}, {en:"visual impairment",tr:"görme engeli"}, {en:"visual aids",tr:"görsel araçlar"}],
"waste": [{en:"a waste of time",tr:"zaman kaybı"}, {en:"waste money on sth",tr:"bir şeye boşuna para harcamak"}, {en:"waste disposal",tr:"atık bertarafı"}],
"watch": [{en:"watch out for sth",tr:"bir şeye dikkat etmek"}, {en:"watch sb closely",tr:"birini yakından izlemek"}],
"weather": [{en:"bad weather conditions",tr:"kötü hava koşulları"}, {en:"weather the storm",tr:"fırtınayı atlatmak"}],
"weight": [{en:"put on weight",tr:"kilo almak, şişmanlamak"}, {en:"lose weight",tr:"kilo vermek, zayıflamak"}, {en:"give weight to sth",tr:"bir şeye ağırlık vermek"}],
"west": [{en:"to the west of",tr:"bir şeyin batısında"}, {en:"in the west",tr:"batıda"}],
"western": [{en:"western culture",tr:"batı kültürü"}, {en:"western countries",tr:"batı ülkeleri"}],
"whenever": [{en:"whenever possible",tr:"mümkün oldukça"}, {en:"whenever necessary",tr:"gerektiği zaman"}],
"white": [{en:"black and white",tr:"siyah beyaz; açık ve net"}, {en:"a white lie",tr:"beyaz yalan, zararsız kaçamak"}],
"wide": [{en:"a wide range of sth",tr:"geniş bir yelpazede bir şey"}, {en:"wide open",tr:"ardına kadar açık"}],
"widely": [{en:"widely used",tr:"yaygın olarak kullanılan"}, {en:"widely accepted",tr:"yaygın kabul gören"}, {en:"vary widely",tr:"büyük ölçüde değişmek"}],
"words": [{en:"in other words",tr:"başka bir deyişle"}, {en:"have words with sb",tr:"biriyle ağız kavgası etmek"}],
"worker": [{en:"a factory worker",tr:"fabrika işçisi"}, {en:"skilled workers",tr:"nitelikli işçiler"}, {en:"a social worker",tr:"sosyal hizmet uzmanı"}],
"works": [{en:"collected works",tr:"toplu eserler"}, {en:"public works",tr:"bayındırlık işleri"}],
"written": [{en:"in written form",tr:"yazılı olarak"}, {en:"a written agreement",tr:"yazılı bir anlaşma"}, {en:"written consent",tr:"yazılı onay"}]
};
