/* ============================================================
   Kullanım kalıpları — dönüştürücü girdisi (site bu dosyayı YÜKLEMEZ)

   Kelimenin anlamı değil, NASIL kullanıldığı: hangi edatı alır, hangi
   sözcüklerle birlikte gelir. YDS bu kalıpları bolca sorar; Türkçe fiilin
   istediği ek İngilizceye taşınınca hata çıkar ("comply to" değil "comply with").

   Kalıbı olmayan somut kelimeler (tiger, table) burada yoktur.
   Üretim: tools/test-uretim (agent + kalip-dogrula.py) · 287 kelime, 733 kalıp
   ============================================================ */

window.KALIPLAR = {
"academic": [{en:"academic performance",tr:"akademik başarı"}, {en:"academic year",tr:"öğretim yılı"}, {en:"academic research",tr:"akademik araştırma"}],
"accompany": [{en:"be accompanied by sb",tr:"birinin eşliğinde olmak"}, {en:"accompany sb to the airport",tr:"birine havaalanına kadar eşlik etmek"}],
"account": [{en:"account for sth",tr:"bir şeyi oluşturmak, açıklamak"}, {en:"take sth into account",tr:"bir şeyi hesaba katmak"}, {en:"on account of sth",tr:"bir şey yüzünden"}],
"achievement": [{en:"a sense of achievement",tr:"başarma duygusu"}, {en:"a great achievement",tr:"büyük bir başarı"}, {en:"academic achievement",tr:"akademik başarı"}],
"acquire": [{en:"acquire knowledge",tr:"bilgi edinmek"}, {en:"acquire new skills",tr:"yeni beceriler kazanmak"}],
"adapt": [{en:"adapt to change",tr:"değişime uyum sağlamak"}, {en:"adapt to new conditions",tr:"yeni koşullara uyum sağlamak"}],
"add": [{en:"add sth to sth",tr:"bir şeye bir şey eklemek"}, {en:"add to the problem",tr:"sorunu artırmak"}, {en:"add up to",tr:"toplamda bir şey etmek"}],
"agricultural": [{en:"agricultural land",tr:"tarım arazisi"}, {en:"agricultural production",tr:"tarımsal üretim"}],
"aim": [{en:"aim to do sth",tr:"bir şeyi yapmayı amaçlamak"}, {en:"be aimed at sb",tr:"birini hedeflemek"}, {en:"achieve the aim",tr:"amaca ulaşmak"}],
"alone": [{en:"leave sb alone",tr:"birini rahat bırakmak"}, {en:"let alone",tr:"şöyle dursun, bir yana"}, {en:"live alone",tr:"yalnız yaşamak"}],
"appearance": [{en:"make an appearance",tr:"boy göstermek, görünmek"}, {en:"physical appearance",tr:"fiziksel görünüm"}, {en:"judge by appearance",tr:"görünüşe göre yargılamak"}],
"application": [{en:"an application for a job",tr:"iş başvurusu"}, {en:"submit an application",tr:"başvuru yapmak"}, {en:"the application of a theory",tr:"bir kuramın uygulanması"}],
"apply": [{en:"apply for a job",tr:"işe başvurmak"}, {en:"apply to a university",tr:"üniversiteye başvurmak"}, {en:"apply the rules",tr:"kuralları uygulamak"}],
"appreciate": [{en:"appreciate the importance",tr:"önemini kavramak"}, {en:"greatly appreciate sth",tr:"bir şey için çok minnettar olmak"}],
"approach": [{en:"an approach to sth",tr:"bir şeye yaklaşım"}, {en:"adopt a new approach",tr:"yeni bir yaklaşım benimsemek"}, {en:"approach a problem",tr:"bir soruna yaklaşmak"}],
"appropriate": [{en:"be appropriate for sth",tr:"bir şey için uygun olmak"}, {en:"take appropriate action",tr:"uygun adımı atmak"}, {en:"appropriate funds",tr:"ödenek ayırmak"}],
"argue": [{en:"argue with sb",tr:"biriyle tartışmak"}, {en:"argue about sth",tr:"bir şey hakkında tartışmak"}, {en:"argue against sth",tr:"bir şeye karşı çıkmak"}],
"article": [{en:"an article on sth",tr:"bir şey üzerine makale"}, {en:"publish an article",tr:"makale yayımlamak"}, {en:"a newspaper article",tr:"gazete yazısı"}],
"ask": [{en:"ask sb for sth",tr:"birinden bir şey istemek"}, {en:"ask sb to do sth",tr:"birinden bir şey yapmasını istemek"}, {en:"ask a question",tr:"soru sormak"}],
"assume": [{en:"assume responsibility for sth",tr:"bir şeyin sorumluluğunu üstlenmek"}, {en:"assume control",tr:"kontrolü ele almak"}, {en:"it is assumed that",tr:"varsayılıyor ki"}],
"attach": [{en:"attach importance to sth",tr:"bir şeye önem vermek"}, {en:"be attached to sb",tr:"birine bağlı olmak"}, {en:"attach a file",tr:"dosyayı iliştirmek, dosya eklemek"}],
"attack": [{en:"an attack on sb",tr:"birine yönelik saldırı"}, {en:"come under attack",tr:"saldırıya uğramak"}, {en:"launch an attack",tr:"saldırı başlatmak"}],
"attitude": [{en:"attitude towards sth",tr:"bir şeye karşı tutum"}, {en:"a positive attitude",tr:"olumlu bir tutum"}],
"attract": [{en:"attract attention",tr:"dikkat çekmek"}, {en:"attract tourists",tr:"turist çekmek"}, {en:"be attracted to sb",tr:"birinden hoşlanmak"}],
"bacteria": [{en:"harmful bacteria",tr:"zararlı bakteriler"}, {en:"kill bacteria",tr:"bakterileri öldürmek"}],
"balance": [{en:"strike a balance between",tr:"iki şey arasında denge kurmak"}, {en:"keep your balance",tr:"düşmeden dengede durmak"}, {en:"the balance of power",tr:"güç dengesi"}],
"bear": [{en:"bear sth in mind",tr:"bir şeyi akılda tutmak"}, {en:"bear responsibility for sth",tr:"bir şeyin sorumluluğunu taşımak"}, {en:"bear a resemblance to",tr:"benzerlik taşımak"}],
"beginning": [{en:"at the beginning of sth",tr:"bir şeyin başında"}, {en:"from the beginning",tr:"en baştan"}],
"behaviour": [{en:"human behaviour",tr:"insan davranışı"}, {en:"behaviour towards sb",tr:"birine karşı davranış"}, {en:"a change in behaviour",tr:"davranış değişikliği"}],
"behind": [{en:"the reason behind sth",tr:"bir şeyin ardındaki neden"}, {en:"fall behind",tr:"geri kalmak"}, {en:"leave sth behind",tr:"bir şeyi geride bırakmak"}],
"belief": [{en:"belief in sth",tr:"bir şeye inanç"}, {en:"contrary to popular belief",tr:"yaygın inanışın aksine"}, {en:"a widespread belief",tr:"yaygın bir inanış"}],
"beyond": [{en:"go beyond sth",tr:"bir şeyin ötesine geçmek"}, {en:"beyond our control",tr:"kontrolümüzün dışında"}, {en:"beyond doubt",tr:"şüphesiz, kuşkuya yer bırakmayan"}],
"bite": [{en:"bite one's nails",tr:"tırnaklarını yemek"}, {en:"a mosquito bite",tr:"sivrisinek ısırığı"}, {en:"grab a bite",tr:"bir şeyler atıştırmak"}],
"came": [{en:"came across sth",tr:"bir şeye rastlamak"}, {en:"came up with an idea",tr:"bir fikir öne sürmek"}, {en:"came to a conclusion",tr:"bir sonuca ulaşmak"}],
"carbon": [{en:"carbon dioxide",tr:"karbondioksit gazı"}, {en:"carbon emissions",tr:"karbon salımları"}],
"career": [{en:"pursue a career in",tr:"bir alanda kariyer peşinde koşmak"}, {en:"a career change",tr:"kariyer değişikliği"}, {en:"career prospects",tr:"kariyer olanakları"}],
"careful": [{en:"be careful with sth",tr:"bir şeye dikkat etmek"}, {en:"careful about sth",tr:"bir şey konusunda dikkatli"}, {en:"careful consideration",tr:"dikkatli değerlendirme"}],
"central": [{en:"central to the argument",tr:"savın merkezinde olan"}, {en:"play a central role",tr:"merkezi bir rol oynamak"}],
"chance": [{en:"by chance",tr:"tesadüfen"}, {en:"the chance of success",tr:"başarı şansı"}, {en:"take a chance",tr:"şansını denemek"}],
"changed": [{en:"a changed man",tr:"değişmiş bir insan"}],
"character": [{en:"out of character",tr:"kişiliğine aykırı"}, {en:"the main character",tr:"başkarakter, başrol kişisi"}, {en:"a strong character",tr:"güçlü bir kişilik"}],
"china": [{en:"a china cup",tr:"porselen çay fincanı"}, {en:"fine china",tr:"kaliteli porselen takımı"}],
"claim": [{en:"claim to be sth",tr:"bir şey olduğunu iddia etmek"}, {en:"claim responsibility for sth",tr:"bir şeyin sorumluluğunu üstlenmek"}, {en:"make a claim",tr:"iddiada bulunmak"}],
"closely": [{en:"work closely with sb",tr:"biriyle yakın çalışmak"}, {en:"be closely linked to",tr:"yakından bağlantılı olmak"}, {en:"watch closely",tr:"yakından, dikkatle izlemek"}],
"cold": [{en:"catch a cold",tr:"soğuk algınlığına yakalanmak"}, {en:"in cold blood",tr:"soğukkanlılıkla"}],
"commonly": [{en:"commonly used",tr:"yaygın olarak kullanılan"}, {en:"commonly known as",tr:"yaygın olarak bilinen adıyla"}, {en:"commonly referred to as",tr:"yaygın olarak şöyle anılan"}],
"conflict": [{en:"conflict with sth",tr:"bir şeyle çelişmek"}, {en:"conflict of interest",tr:"çıkar çatışması"}, {en:"armed conflict",tr:"silahlı çatışma"}],
"constant": [{en:"under constant pressure",tr:"sürekli baskı altında"}, {en:"remain constant",tr:"değişmeden kalmak"}, {en:"constant change",tr:"sürekli değişim"}],
"consumer": [{en:"consumer goods",tr:"tüketim malları"}, {en:"consumer demand",tr:"tüketici talebi"}],
"consumption": [{en:"energy consumption",tr:"enerji tüketimi"}, {en:"reduce consumption",tr:"tüketimi azaltmak"}],
"contact": [{en:"come into contact with sb",tr:"biriyle temasa geçmek"}, {en:"keep in contact with sb",tr:"biriyle iletişimi sürdürmek"}, {en:"contact details",tr:"iletişim bilgileri"}],
"contrast": [{en:"in contrast to sth",tr:"bir şeyin aksine"}, {en:"contrast sth with sth",tr:"bir şeyi bir şeyle karşılaştırmak"}, {en:"by contrast",tr:"buna karşılık"}],
"convince": [{en:"convince sb of sth",tr:"birini bir şeye ikna etmek"}, {en:"convince sb to do sth",tr:"birini bir şey yapmaya ikna etmek"}],
"cope": [{en:"cope with sth",tr:"bir şeyle başa çıkmak"}, {en:"unable to cope",tr:"baş edememek"}],
"cover": [{en:"be covered with snow",tr:"karla kaplı olmak"}, {en:"cover a wide range",tr:"geniş bir yelpazeyi kapsamak"}, {en:"cover the costs",tr:"masrafları karşılamak"}],
"crucial": [{en:"crucial to success",tr:"başarı için hayati"}, {en:"crucial for development",tr:"gelişim için çok önemli"}, {en:"play a crucial role",tr:"belirleyici bir rol oynamak"}],
"current": [{en:"the current situation",tr:"mevcut durum, şu anki durum"}, {en:"against the current",tr:"akıntıya karşı"}, {en:"current affairs",tr:"güncel olaylar"}],
"dangerous": [{en:"dangerous to health",tr:"sağlığa zararlı"}, {en:"dangerous for children",tr:"çocuklar için tehlikeli"}, {en:"extremely dangerous",tr:"aşırı derecede tehlikeli"}],
"date": [{en:"out of date",tr:"modası geçmiş"}, {en:"up to date",tr:"güncel, güncellenmiş"}, {en:"to date",tr:"bugüne kadar"}],
"debate": [{en:"a debate over sth",tr:"bir şey üzerine tartışma"}, {en:"open to debate",tr:"tartışmaya açık"}, {en:"debate the issue",tr:"meseleyi tartışmak"}],
"deep": [{en:"a deep understanding of",tr:"derin bir kavrayış"}, {en:"take a deep breath",tr:"derin nefes almak, sakinleşmek"}, {en:"in deep trouble",tr:"başı büyük dertte"}],
"demonstrate": [{en:"demonstrate the importance of sth",tr:"bir şeyin önemini göstermek"}, {en:"clearly demonstrate sth",tr:"bir şeyi açıkça göstermek"}, {en:"demonstrate against the government",tr:"hükümete karşı gösteri yapmak"}],
"destroy": [{en:"destroy the environment",tr:"çevreyi tahrip etmek"}, {en:"completely destroyed",tr:"tamamen yok edilmiş"}, {en:"destroy evidence",tr:"kanıt yok etmek"}],
"detail": [{en:"in detail",tr:"ayrıntılı olarak"}, {en:"go into detail",tr:"ayrıntıya girmek"}, {en:"pay attention to detail",tr:"ayrıntıya dikkat etmek"}],
"dialogue": [{en:"dialogue between two sides",tr:"iki taraf arasında diyalog"}, {en:"engage in dialogue",tr:"diyaloğa girmek"}, {en:"open a dialogue with",tr:"biriyle diyalog başlatmak"}],
"die": [{en:"die of cancer",tr:"kanserden ölmek"}, {en:"die from injuries",tr:"yaralanmalardan ölmek"}, {en:"die out",tr:"soyu tükenmek"}],
"digital": [{en:"digital technology",tr:"sayısal teknoloji, dijital teknoloji"}, {en:"the digital age",tr:"dijital çağ"}],
"direct": [{en:"direct attention to sth",tr:"dikkati bir şeye yöneltmek"}, {en:"a direct impact on",tr:"üzerinde doğrudan etki"}, {en:"in direct contrast to",tr:"tam tersine, taban tabana zıt"}],
"discovery": [{en:"the discovery of sth",tr:"bir şeyin keşfi"}, {en:"make a discovery",tr:"keşif yapmak"}, {en:"a scientific discovery",tr:"bilimsel bir keşif"}],
"display": [{en:"on display",tr:"göz önünde, sergide"}, {en:"put sth on display",tr:"bir şeyi sergilemek"}, {en:"display an interest in sth",tr:"bir şeye ilgi göstermek"}],
"diverse": [{en:"a diverse range of sth",tr:"çok çeşitli bir yelpaze"}, {en:"diverse backgrounds",tr:"farklı geçmişler"}, {en:"culturally diverse",tr:"kültürel açıdan çeşitli"}],
"done": [{en:"get sth done",tr:"bir şeyi hallettirmek"}, {en:"be done with sth",tr:"bir şeyi bitirmiş olmak"}, {en:"easier said than done",tr:"söylemesi kolay, yapması zor"}],
"draw": [{en:"draw a conclusion",tr:"sonuç çıkarmak"}, {en:"draw attention to sth",tr:"bir şeye dikkat çekmek"}, {en:"draw a picture",tr:"resim çizmek"}],
"drink": [{en:"have a drink",tr:"bir şeyler içmek"}, {en:"a soft drink",tr:"alkolsüz içecek"}],
"either": [{en:"either ... or",tr:"ya ... ya da"}, {en:"on either side",tr:"her iki tarafta"}],
"element": [{en:"a key element of sth",tr:"bir şeyin temel ögesi"}, {en:"an element of risk",tr:"risk unsuru"}],
"eliminate": [{en:"eliminate the need for sth",tr:"bir şeye olan ihtiyacı ortadan kaldırmak"}, {en:"eliminate poverty",tr:"yoksulluğu ortadan kaldırmak"}, {en:"eliminate the risk",tr:"riski ortadan kaldırmak"}],
"else": [{en:"or else",tr:"yoksa, öbür türlü"}, {en:"somewhere else",tr:"başka bir yerde"}, {en:"everyone else",tr:"diğer herkes"}],
"emotional": [{en:"provide emotional support",tr:"duygusal destek sağlamak"}, {en:"become emotional",tr:"duygusallaşmak, duygulanmak"}, {en:"an emotional response",tr:"duygusal tepki gösterme"}],
"emphasis": [{en:"place emphasis on sth",tr:"bir şeye vurgu yapmak"}, {en:"with emphasis on sth",tr:"bir şeye ağırlık vererek"}, {en:"the main emphasis",tr:"asıl vurgu"}],
"engineer": [{en:"a civil engineer",tr:"inşaat mühendisi"}, {en:"software engineer",tr:"yazılım mühendisi"}],
"enormous": [{en:"an enormous amount of sth",tr:"muazzam miktarda bir şey"}, {en:"enormous pressure",tr:"muazzam baskı"}],
"entire": [{en:"the entire process",tr:"sürecin tamamı"}, {en:"the entire population",tr:"nüfusun tamamı"}],
"environmental": [{en:"environmental impact",tr:"çevresel etki"}, {en:"environmental protection",tr:"çevre koruma"}, {en:"environmental issues",tr:"çevre sorunları"}],
"essential": [{en:"essential for survival",tr:"hayatta kalmak için zorunlu"}, {en:"an essential part of sth",tr:"bir şeyin temel parçası"}],
"established": [{en:"well established",tr:"iyice yerleşmiş, köklü"}, {en:"an established fact",tr:"yerleşik bir gerçek"}, {en:"become established",tr:"yerleşmek, kabul görmek"}],
"everything": [{en:"everything else",tr:"diğer her şey"}, {en:"do everything possible",tr:"elinden gelen her şeyi yapmak"}],
"exactly": [{en:"exactly the same",tr:"tam olarak aynı"}, {en:"not exactly",tr:"tam sayılmaz"}],
"examine": [{en:"examine the evidence",tr:"kanıtları incelemek"}, {en:"examine a patient",tr:"bir hastayı muayene etmek"}],
"expensive": [{en:"an expensive mistake",tr:"pahalıya mal olan hata"}, {en:"prohibitively expensive",tr:"aşırı derecede pahalı"}],
"experiment": [{en:"experiment with sth",tr:"bir şey üzerinde deneme yapmak"}, {en:"conduct an experiment",tr:"deney yapmak"}],
"explore": [{en:"explore the possibility of",tr:"olasılığını araştırmak"}, {en:"explore an issue",tr:"bir konuyu araştırmak, irdelemek"}],
"expose": [{en:"expose sb to sth",tr:"birini bir şeye maruz bırakmak"}, {en:"be exposed to risk",tr:"riske maruz kalmak"}, {en:"expose the truth",tr:"gerçeği açığa çıkarmak"}],
"extent": [{en:"to some extent",tr:"bir ölçüde, bir dereceye kadar"}, {en:"to a large extent",tr:"büyük ölçüde"}, {en:"the extent of the damage",tr:"hasarın boyutu"}],
"eye": [{en:"keep an eye on sth",tr:"bir şeye göz kulak olmak"}, {en:"catch sb's eye",tr:"birinin dikkatini çekmek"}],
"famous": [{en:"famous for sth",tr:"bir şeyle ünlü"}, {en:"become famous",tr:"ünlü olmak"}],
"fat": [{en:"low in fat",tr:"az yağlı"}, {en:"body fat",tr:"vücut yağı"}, {en:"saturated fat",tr:"doymuş yağ"}],
"father": [{en:"the father of sth",tr:"bir şeyin babası, kurucusu"}, {en:"father a child",tr:"bir çocuğun babası olmak"}],
"fear": [{en:"for fear of sth",tr:"bir şeyden korktuğu için"}, {en:"the fear of failure",tr:"başarısızlık korkusu"}, {en:"overcome fear",tr:"korkuyu aşmak"}],
"feed": [{en:"feed on insects",tr:"böceklerle beslenmek"}, {en:"feed the animals",tr:"hayvanları beslemek"}],
"fight": [{en:"fight against sth",tr:"bir şeyle mücadele etmek"}, {en:"fight for sth",tr:"bir şey için mücadele etmek"}, {en:"put up a fight",tr:"direnç göstermek"}],
"film": [{en:"make a film",tr:"film çekmek"}, {en:"a thin film",tr:"ince bir tabaka"}],
"fish": [{en:"catch fish",tr:"balık tutmak"}, {en:"a fish out of water",tr:"sudan çıkmış balık gibi"}],
"flood": [{en:"a flood of complaints",tr:"şikayet yağmuru"}, {en:"be flooded with sth",tr:"bir şeye boğulmak"}, {en:"flood damage",tr:"sel hasarı"}],
"foreign": [{en:"a foreign language",tr:"yabancı dil"}, {en:"foreign policy",tr:"dış politika"}, {en:"foreign to sb",tr:"birine yabancı gelen"}],
"fossil": [{en:"fossil fuels",tr:"fosil yakıtlar"}],
"free": [{en:"free of charge",tr:"ücretsiz"}, {en:"free from sth",tr:"bir şeyden uzak, arınmış"}, {en:"set sb free",tr:"birini serbest bırakmak"}],
"friend": [{en:"make friends with sb",tr:"biriyle arkadaş olmak"}, {en:"a close friend",tr:"yakın arkadaş"}, {en:"a friend of mine",tr:"bir arkadaşım"}],
"full": [{en:"be full of sth",tr:"bir şeyle dolu olmak"}, {en:"in full",tr:"eksiksiz olarak, tümüyle"}, {en:"full of energy",tr:"enerji dolu, dinç"}],
"further": [{en:"further our understanding",tr:"anlayışımızı ilerletmek"}, {en:"further research is needed",tr:"daha fazla araştırma gerekli"}, {en:"further your career",tr:"kariyerini ileriye taşımak"}],
"game": [{en:"play a game",tr:"oyun oynamak, maç yapmak"}, {en:"the rules of the game",tr:"oyunun kuralları"}],
"gas": [{en:"greenhouse gas emissions",tr:"sera gazı salımları"}, {en:"natural gas",tr:"doğal gaz"}],
"gender": [{en:"gender equality",tr:"cinsiyet eşitliği"}, {en:"gender differences",tr:"cinsiyet farklılıkları"}],
"general": [{en:"in general",tr:"genel olarak"}, {en:"as a general rule",tr:"genel kural olarak"}, {en:"the general public",tr:"halk, geniş kitleler"}],
"generate": [{en:"generate income",tr:"gelir sağlamak"}, {en:"generate electricity",tr:"elektrik üretmek"}, {en:"generate interest",tr:"ilgi çekmek, merak uyandırmak"}],
"genetic": [{en:"genetic disorder",tr:"genetik hastalık"}, {en:"genetic engineering",tr:"genetik mühendislik"}, {en:"genetic factors",tr:"genetik faktörler"}],
"greatly": [{en:"vary greatly",tr:"büyük ölçüde değişmek"}, {en:"greatly increase",tr:"büyük ölçüde artmak"}],
"growing": [{en:"a growing number of",tr:"giderek artan sayıda"}, {en:"growing concern",tr:"artan endişe"}],
"guess": [{en:"make a guess",tr:"tahmin yürütmek"}, {en:"an educated guess",tr:"bilgiye dayalı tahmin"}],
"habitat": [{en:"natural habitat",tr:"doğal yaşam alanı"}, {en:"habitat loss",tr:"yaşam alanı kaybı"}, {en:"destroy habitats",tr:"yaşam alanlarını yok etmek"}],
"happy": [{en:"be happy with sth",tr:"bir şeyden memnun olmak"}, {en:"happy to help",tr:"memnuniyetle yardım etmek"}],
"hardly": [{en:"hardly ever",tr:"neredeyse hiç"}, {en:"hardly any",tr:"hemen hemen hiç"}, {en:"hardly had he arrived",tr:"o varır varmaz"}],
"have-not": [{en:"the haves and have-nots",tr:"varsıllar ve yoksullar"}],
"heat": [{en:"extreme heat",tr:"aşırı sıcak"}, {en:"heat sth up",tr:"bir şeyi ısıtmak"}],
"heavy": [{en:"heavy rain",tr:"şiddetli yağmur"}, {en:"heavy traffic",tr:"yoğun trafik"}],
"higher": [{en:"higher education",tr:"yükseköğretim"}, {en:"higher than average",tr:"ortalamanın üzerinde"}],
"hour": [{en:"rush hour",tr:"trafiğin yoğun olduğu saat"}, {en:"working hours",tr:"çalışma saatleri"}],
"huge": [{en:"a huge amount of",tr:"çok büyük miktarda"}, {en:"a huge impact on",tr:"çok büyük bir etki"}, {en:"a huge success",tr:"büyük bir başarı"}],
"hundred": [{en:"hundreds of people",tr:"yüzlerce insan"}, {en:"a hundred years ago",tr:"yüz yıl önce"}],
"hunt": [{en:"hunt for sth",tr:"bir şeyi aramak"}, {en:"go hunting",tr:"ava çıkmak"}],
"ignore": [{en:"ignore a warning",tr:"uyarıyı dikkate almamak"}, {en:"ignore the evidence",tr:"kanıtları görmezden gelmek"}],
"ill": [{en:"fall ill",tr:"hastalanmak, rahatsızlanmak"}, {en:"speak ill of sb",tr:"birinin arkasından kötü konuşmak"}, {en:"ill effects",tr:"zararlı etkiler"}],
"illness": [{en:"suffer from an illness",tr:"bir hastalıktan muzdarip olmak"}, {en:"mental illness",tr:"akıl hastalığı"}],
"importance": [{en:"the importance of sth",tr:"bir şeyin önemi"}, {en:"attach importance to sth",tr:"bir şeye önem vermek"}, {en:"of great importance",tr:"büyük önem taşıyan"}],
"income": [{en:"a source of income",tr:"gelir kaynağı"}, {en:"low income families",tr:"düşük gelirli aileler"}, {en:"annual income",tr:"yıllık gelir"}],
"increasing": [{en:"an increasing number of",tr:"giderek artan sayıda"}, {en:"increasing demand for",tr:"bir şeye yönelik artan talep"}],
"increasingly": [{en:"increasingly important",tr:"giderek daha önemli"}, {en:"become increasingly difficult",tr:"giderek zorlaşmak"}],
"indicate": [{en:"the results indicate that",tr:"sonuçlar şunu göstermektedir"}, {en:"indicate a willingness to",tr:"istekli olduğunu göstermek"}, {en:"clearly indicate",tr:"açıkça göstermek"}],
"infer": [{en:"infer sth from sth",tr:"bir şeyden bir şey çıkarmak"}, {en:"it can be inferred",tr:"şu sonuç çıkarılabilir"}],
"inform": [{en:"inform sb of sth",tr:"birine bir şeyi bildirmek"}, {en:"inform sb about sth",tr:"birine bir şey hakkında bilgi vermek"}, {en:"keep sb informed",tr:"birini sürekli bilgilendirmek"}],
"initial": [{en:"the initial stage",tr:"başlangıç aşaması"}, {en:"an initial reaction",tr:"ilk tepki, ilk yanıt"}, {en:"initial results",tr:"ilk sonuçlar"}],
"inside": [{en:"inside out",tr:"tersyüz, içi dışına"}, {en:"inside information",tr:"içeriden bilgi"}, {en:"inside the building",tr:"binanın içinde"}],
"inspire": [{en:"inspire sb to do sth",tr:"birine bir şey yapması için ilham vermek"}, {en:"be inspired by sth",tr:"bir şeyden ilham almak"}, {en:"inspire confidence",tr:"güven vermek"}],
"intense": [{en:"intense pressure",tr:"yoğun baskı"}, {en:"intense competition",tr:"yoğun rekabet"}],
"interact": [{en:"interact with sb",tr:"biriyle etkileşmek"}, {en:"interact with each other",tr:"birbiriyle etkileşmek"}],
"interaction": [{en:"interaction with others",tr:"başkalarıyla etkileşim"}, {en:"social interaction",tr:"sosyal etkileşim"}],
"interested": [{en:"be interested in sth",tr:"bir şeyle ilgilenmek"}, {en:"interested in doing sth",tr:"bir şeyi yapmakla ilgilenmek"}],
"international": [{en:"international relations",tr:"uluslararası ilişkiler"}, {en:"the international community",tr:"uluslararası toplum"}],
"internet": [{en:"on the internet",tr:"internet üzerinde, internette"}, {en:"internet access",tr:"internet erişimi"}, {en:"browse the internet",tr:"internette dolaşmak"}],
"interpret": [{en:"interpret sth as sth",tr:"bir şeyi bir şey olarak yorumlamak"}, {en:"interpret the results",tr:"sonuçları yorumlamak"}, {en:"be interpreted as sth",tr:"bir şey olarak yorumlanmak"}],
"involved": [{en:"be involved in sth",tr:"bir şeye dahil olmak"}, {en:"get involved in a project",tr:"bir projeye katılmak"}, {en:"the people involved",tr:"ilgili kişiler"}],
"key": [{en:"the key to success",tr:"başarının anahtarı"}, {en:"play a key role",tr:"kilit bir rol üstlenmek"}, {en:"a key factor",tr:"başlıca etken"}],
"largely": [{en:"largely due to sth",tr:"büyük ölçüde bir şeyden dolayı"}, {en:"largely responsible for",tr:"büyük ölçüde sorumlu"}, {en:"largely ignored",tr:"büyük ölçüde göz ardı edilen"}],
"later": [{en:"sooner or later",tr:"er ya da geç"}, {en:"later on",tr:"daha sonra"}],
"law": [{en:"break the law",tr:"yasayı çiğnemek"}, {en:"against the law",tr:"yasaya aykırı"}, {en:"pass a law",tr:"yasa çıkarmak"}],
"layer": [{en:"a layer of dust",tr:"bir toz tabakası"}, {en:"the ozone layer",tr:"ozon tabakası"}, {en:"layer upon layer",tr:"kat kat, üst üste"}],
"let": [{en:"let sb know",tr:"birine haber vermek, bilgi ulaştırmak"}, {en:"let go of sth",tr:"bir şeyi bırakmak"}, {en:"let alone",tr:"şöyle dursun"}],
"limited": [{en:"be limited to sth",tr:"bir şeyle sınırlı olmak"}, {en:"a limited number of",tr:"sınırlı sayıda"}, {en:"limited resources",tr:"kısıtlı kaynaklar"}],
"local": [{en:"local government",tr:"yerel yönetim"}, {en:"the local community",tr:"yerel halk, yöre halkı"}, {en:"local authorities",tr:"yerel yönetim birimleri"}],
"long-time": [{en:"a long-time friend",tr:"uzun süredir dost olan kişi"}, {en:"a long-time resident",tr:"uzun süredir orada yaşayan kişi"}],
"longer": [{en:"no longer",tr:"artık değil"}, {en:"any longer",tr:"artık, daha fazla"}],
"looking": [{en:"looking forward to sth",tr:"bir şeyi dört gözle beklemek"}, {en:"be good-looking",tr:"yakışıklı, güzel görünümlü olmak"}],
"make-up": [{en:"the make-up of sth",tr:"bir şeyin yapısı"}, {en:"wear make-up",tr:"makyaj yapmış olmak"}],
"management": [{en:"senior management",tr:"üst yönetim"}, {en:"time management",tr:"zaman yönetimi"}, {en:"management skills",tr:"yönetim becerileri"}],
"manipulate": [{en:"manipulate sb into sth",tr:"birini bir şeye yönlendirmek"}, {en:"manipulate data",tr:"veriyi manipüle etmek"}, {en:"manipulate public opinion",tr:"kamuoyunu yönlendirmek"}],
"market": [{en:"on the market",tr:"piyasada, satışta"}, {en:"market share",tr:"pazar payı"}, {en:"enter the market",tr:"piyasaya girmek, pazara açılmak"}],
"mass": [{en:"mass production",tr:"seri üretim"}, {en:"mass media",tr:"kitle iletişim araçları"}, {en:"weapons of mass destruction",tr:"kitle imha silahları"}],
"meet": [{en:"meet a deadline",tr:"son teslim tarihine yetişmek"}, {en:"meet the requirements",tr:"koşulları karşılamak"}, {en:"meet sb's needs",tr:"birinin ihtiyaçlarını karşılamak"}],
"memory": [{en:"in memory of sb",tr:"birinin anısına"}, {en:"have a good memory",tr:"hafızası iyi olmak"}],
"middle": [{en:"in the middle of sth",tr:"bir şeyin ortasında"}, {en:"the middle class",tr:"orta sınıf"}],
"military": [{en:"military force",tr:"askeri güç"}, {en:"join the military",tr:"orduya katılmak"}],
"monitor": [{en:"monitor progress",tr:"ilerlemeyi izlemek"}, {en:"closely monitor sth",tr:"bir şeyi yakından izlemek"}],
"month": [{en:"last month",tr:"geçen ay"}, {en:"a month ago",tr:"bir ay önce"}],
"muscle": [{en:"build muscle",tr:"kas geliştirmek"}, {en:"pull a muscle",tr:"kasını incitmek"}, {en:"muscle strength",tr:"kas gücü"}],
"name": [{en:"name sth after sb",tr:"bir şeye birinin adını vermek"}, {en:"in the name of",tr:"adına, namına"}, {en:"make a name for yourself",tr:"ad yapmak, tanınmak"}],
"nation": [{en:"developing nations",tr:"gelişmekte olan ülkeler"}, {en:"the United Nations",tr:"Birleşmiş Milletler"}],
"near": [{en:"in the near future",tr:"yakın gelecekte"}, {en:"near the end of sth",tr:"bir şeyin sonuna doğru"}],
"neither": [{en:"neither good nor bad",tr:"ne iyi ne kötü"}, {en:"neither of them",tr:"ikisi de değil"}, {en:"neither do I",tr:"ben de değilim"}],
"network": [{en:"a network of roads",tr:"yol ağı"}, {en:"social network",tr:"sosyal ağ"}, {en:"build a network",tr:"ağ kurmak"}],
"nor": [{en:"neither ... nor",tr:"ne ... ne de"}, {en:"nor do I",tr:"ben de değilim"}],
"north": [{en:"to the north of sth",tr:"bir şeyin kuzeyinde"}, {en:"in the north",tr:"kuzeyde, kuzey bölgesinde"}, {en:"head north",tr:"kuzeye yönelmek"}],
"object": [{en:"object to sth",tr:"bir şeye itiraz etmek"}, {en:"object to doing sth",tr:"bir şeyi yapmaya itiraz etmek"}, {en:"the object of study",tr:"çalışmanın konusu"}],
"objective": [{en:"the main objective",tr:"asıl amaç"}, {en:"achieve an objective",tr:"hedefe ulaşmak"}, {en:"an objective view",tr:"nesnel bakış açısı"}],
"obtain": [{en:"obtain information",tr:"bilgi edinmek"}, {en:"obtain permission",tr:"izin almak"}],
"obvious": [{en:"it is obvious that",tr:"açıkça görülmektedir ki"}, {en:"for obvious reasons",tr:"bariz nedenlerle"}],
"older": [{en:"older than me",tr:"benden daha yaşlı"}, {en:"grow older",tr:"yaşlanmak"}, {en:"older people",tr:"yaşlı insanlar"}],
"open": [{en:"be open to sth",tr:"bir şeye açık olmak"}, {en:"in the open air",tr:"açık havada"}, {en:"open an account",tr:"hesap açmak"}],
"opinion": [{en:"in my opinion",tr:"bence, bana göre"}, {en:"public opinion",tr:"kamuoyu, halkın görüşü"}, {en:"express an opinion",tr:"görüş belirtmek"}],
"oppose": [{en:"be opposed to sth",tr:"bir şeye karşı olmak"}, {en:"as opposed to",tr:"aksine, karşıt olarak"}, {en:"strongly oppose sth",tr:"bir şeye şiddetle karşı çıkmak"}],
"origin": [{en:"the origin of sth",tr:"bir şeyin kökeni"}, {en:"country of origin",tr:"menşe ülke"}, {en:"be of Greek origin",tr:"Yunan kökenli olmak"}],
"otherwise": [{en:"unless otherwise stated",tr:"aksi belirtilmedikçe"}, {en:"otherwise known as",tr:"diğer adıyla"}],
"outcome": [{en:"the outcome of sth",tr:"bir şeyin sonucu"}, {en:"a positive outcome",tr:"olumlu sonuç"}, {en:"affect the outcome",tr:"sonuca etki etmek, sonucu değiştirmek"}],
"overall": [{en:"the overall effect",tr:"genel etki, bütünsel etki"}, {en:"overall performance",tr:"genel başarı düzeyi"}],
"overcome": [{en:"overcome difficulties",tr:"zorlukların üstesinden gelmek"}, {en:"overcome an obstacle",tr:"bir engeli aşmak"}, {en:"be overcome by fear",tr:"korkuya yenik düşmek"}],
"pain": [{en:"in pain",tr:"acı içinde"}, {en:"relieve the pain",tr:"ağrıyı dindirmek"}, {en:"chest pain",tr:"göğüs ağrısı"}],
"parts": [{en:"spare parts",tr:"yedek parçalar"}, {en:"in these parts",tr:"bu yörelerde"}],
"pass": [{en:"pass a law",tr:"yasa çıkarmak"}, {en:"pass an exam",tr:"sınavı geçmek"}, {en:"as time passes",tr:"zaman geçtikçe"}],
"patient": [{en:"be patient with sb",tr:"birine karşı sabırlı olmak"}, {en:"treat a patient",tr:"bir hastayı tedavi etmek"}],
"pattern": [{en:"a pattern of behaviour",tr:"davranış örüntüsü"}, {en:"follow a pattern",tr:"bir örüntüyü izlemek"}, {en:"a similar pattern",tr:"benzer bir örüntü"}],
"perform": [{en:"perform a task",tr:"bir görevi yerine getirmek"}, {en:"perform an experiment",tr:"deney yapmak"}, {en:"perform well",tr:"iyi performans göstermek"}],
"perhaps": [{en:"perhaps the most important",tr:"belki de en önemlisi"}],
"perspective": [{en:"from a different perspective",tr:"farklı bir bakış açısından"}, {en:"put sth into perspective",tr:"bir şeyi doğru çerçeveye oturtmak"}],
"phenomenon": [{en:"a natural phenomenon",tr:"doğal bir olgu"}, {en:"a widespread phenomenon",tr:"yaygın bir olgu"}, {en:"explain the phenomenon",tr:"olguyu açıklamak"}],
"picture": [{en:"paint a picture of",tr:"bir tablo çizmek"}, {en:"take a picture",tr:"fotoğraf çekmek"}, {en:"the big picture",tr:"büyük resim, genel görünüm"}],
"pollution": [{en:"air pollution",tr:"hava kirliliği"}, {en:"reduce pollution",tr:"kirliliği azaltmak"}],
"powerful": [{en:"a powerful effect on sb",tr:"biri üzerinde güçlü etki"}, {en:"a powerful tool",tr:"güçlü bir araç"}],
"prefer": [{en:"prefer sth to sth",tr:"bir şeyi bir şeye tercih etmek"}, {en:"prefer to do sth",tr:"bir şeyi yapmayı tercih etmek"}],
"preserve": [{en:"preserve the environment",tr:"çevreyi korumak"}, {en:"preserve traditions",tr:"gelenekleri yaşatmak"}, {en:"well preserved",tr:"iyi korunmuş"}],
"principle": [{en:"in principle",tr:"ilke olarak, kuramsal açıdan"}, {en:"on principle",tr:"ilke gereği"}, {en:"a basic principle",tr:"temel ilke, başlıca kural"}],
"psychological": [{en:"psychological effects",tr:"psikolojik etkiler, ruhsal sonuçlar"}, {en:"psychological problems",tr:"psikolojik sorunlar, ruhsal sıkıntılar"}],
"publish": [{en:"be published in a journal",tr:"bir dergide yayımlanmak"}, {en:"publish a book",tr:"kitap yayımlamak"}, {en:"publish research findings",tr:"araştırma bulgularını yayımlamak"}],
"purchase": [{en:"the purchase of sth",tr:"bir şeyin satın alınması"}, {en:"make a purchase",tr:"satın alma yapmak"}, {en:"purchase a property",tr:"mülk satın almak"}],
"quality": [{en:"high quality",tr:"yüksek kalite"}, {en:"quality of life",tr:"yaşam kalitesi"}],
"quickly": [{en:"as quickly as possible",tr:"mümkün olduğunca çabuk"}, {en:"spread quickly",tr:"hızla yayılmak"}],
"reaction": [{en:"a reaction to sth",tr:"bir şeye tepki"}, {en:"in reaction to sth",tr:"bir şeye tepki olarak"}, {en:"a chemical reaction",tr:"kimyasal tepkime, kimyasal değişim"}],
"real": [{en:"in real life",tr:"gerçek hayatta"}, {en:"the real world",tr:"gerçek dünya"}],
"receive": [{en:"receive attention",tr:"ilgi görmek"}, {en:"receive treatment",tr:"tedavi görmek"}, {en:"receive an award",tr:"ödül almak"}],
"regardless": [{en:"regardless of sth",tr:"bir şeye bakılmaksızın"}, {en:"regardless of the cost",tr:"maliyeti ne olursa olsun"}],
"relate": [{en:"relate to sth",tr:"bir şeyle ilgili olmak"}, {en:"be closely related to",tr:"yakından ilişkili olmak"}, {en:"relate sth to sth",tr:"bir şeyi bir şeyle ilişkilendirmek"}],
"relation": [{en:"in relation to sth",tr:"bir şeye ilişkin olarak"}, {en:"the relation between two things",tr:"iki şey arasındaki ilişki"}, {en:"public relations",tr:"halkla ilişkiler"}],
"report": [{en:"report on sth",tr:"bir şey hakkında rapor vermek"}, {en:"report sth to sb",tr:"bir şeyi birine bildirmek"}, {en:"according to the report",tr:"rapora göre"}],
"represent": [{en:"represent a threat to",tr:"bir tehdit oluşturmak"}, {en:"be represented by sb",tr:"biri tarafından temsil edilmek"}, {en:"represent a challenge",tr:"bir zorluk teşkil etmek"}],
"responsible": [{en:"be responsible for sth",tr:"bir şeyden sorumlu olmak"}, {en:"hold sb responsible for sth",tr:"birini bir şeyden sorumlu tutmak"}],
"rest": [{en:"the rest of sth",tr:"bir şeyin geri kalanı"}, {en:"take a rest",tr:"dinlenmek, kısa mola vermek"}],
"restrict": [{en:"restrict access to sth",tr:"bir şeye erişimi kısıtlamak"}, {en:"be restricted to sth",tr:"bir şeyle sınırlı olmak"}, {en:"restrict freedom",tr:"özgürlüğü kısıtlamak"}],
"revolution": [{en:"the industrial revolution",tr:"sanayi devrimi"}, {en:"a revolution in sth",tr:"bir alanda devrim"}],
"rule": [{en:"break the rules",tr:"kuralları çiğnemek"}, {en:"as a rule",tr:"kural olarak, genelde"}, {en:"rule out the possibility",tr:"olasılığı dışlamak"}],
"safe": [{en:"safe from danger",tr:"tehlikeden uzak, güvende"}, {en:"keep sb safe",tr:"birini güvende tutmak"}],
"said": [{en:"it is said that",tr:"söylendiğine göre"}, {en:"easier said than done",tr:"söylemesi kolay, yapması zor"}, {en:"the said person",tr:"adı geçen kişi"}],
"scale": [{en:"on a large scale",tr:"büyük ölçekte"}, {en:"the scale of the problem",tr:"sorunun büyüklüğü"}, {en:"scale up production",tr:"üretimi büyütmek"}],
"search": [{en:"search for sth",tr:"bir şeyi aramak"}, {en:"in search of sth",tr:"bir şeyin arayışı içinde"}],
"serve": [{en:"serve as an example",tr:"örnek teşkil etmek"}, {en:"serve a purpose",tr:"bir işe yaramak"}, {en:"serve customers",tr:"müşterilere hizmet vermek"}],
"share": [{en:"share sth with sb",tr:"bir şeyi biriyle paylaşmak"}, {en:"market share",tr:"pazar payı"}],
"side": [{en:"on the other side",tr:"diğer tarafta"}, {en:"take sides",tr:"birinin tarafını tutmak"}, {en:"from side to side",tr:"bir yandan öbür yana"}],
"site": [{en:"on site",tr:"iş başında, sahada"}, {en:"a construction site",tr:"inşaat alanı, şantiye"}],
"slow": [{en:"slow down",tr:"yavaşlamak, yavaşlatmak"}, {en:"be slow to respond",tr:"tepki vermekte yavaş olmak"}, {en:"a slow process",tr:"yavaş bir süreç"}],
"solution": [{en:"a solution to a problem",tr:"bir soruna çözüm"}, {en:"find a solution",tr:"çözüm bulmak"}],
"speak": [{en:"speak to sb about sth",tr:"biriyle bir şey hakkında konuşmak"}, {en:"speak up",tr:"sesini yükseltmek, açıkça söylemek"}, {en:"generally speaking",tr:"genel olarak söylersek"}],
"special": [{en:"pay special attention to",tr:"özel önem vermek"}, {en:"a special case",tr:"özel bir durum"}],
"speed": [{en:"at high speed",tr:"yüksek hızla"}, {en:"speed up the process",tr:"süreci hızlandırmak"}, {en:"pick up speed",tr:"hız kazanmak"}],
"standard": [{en:"meet the standards",tr:"standartları karşılamak"}, {en:"standard of living",tr:"yaşam standardı"}, {en:"a high standard",tr:"yüksek bir ölçüt"}],
"step": [{en:"the first step towards sth",tr:"bir şeye doğru atılan ilk adım"}, {en:"take a step",tr:"adım atmak"}, {en:"step by step",tr:"adım adım"}],
"store": [{en:"store sth safely",tr:"bir şeyi güvenle saklamak"}, {en:"be in store for sb",tr:"birini beklemek, başına gelmek"}, {en:"a department store",tr:"büyük mağaza"}],
"strategy": [{en:"a strategy for sth",tr:"bir şey için strateji"}, {en:"develop a strategy",tr:"strateji geliştirmek"}],
"struggle": [{en:"struggle with sth",tr:"bir şeyle boğuşmak"}, {en:"struggle for freedom",tr:"özgürlük için mücadele etmek"}, {en:"struggle to do sth",tr:"bir şeyi yapmakta zorlanmak"}],
"style": [{en:"a style of writing",tr:"bir yazı tarzı"}, {en:"out of style",tr:"modası geçmiş"}],
"sun": [{en:"in the sun",tr:"güneşte"}, {en:"the sun rises",tr:"güneş doğar"}],
"supply": [{en:"supply sb with sth",tr:"birine bir şey sağlamak"}, {en:"in short supply",tr:"kıt, yetersiz"}, {en:"supply and demand",tr:"arz ve talep ilişkisi"}],
"surface": [{en:"on the surface",tr:"görünüşte, yüzeyde"}, {en:"come to the surface",tr:"yüzeye çıkmak"}, {en:"surface area",tr:"yüzey alanı"}],
"survival": [{en:"chances of survival",tr:"hayatta kalma şansı"}, {en:"a struggle for survival",tr:"varolma mücadelesi"}, {en:"essential for survival",tr:"hayatta kalmak için gerekli"}],
"symptom": [{en:"the symptoms of a disease",tr:"bir hastalığın belirtileri"}, {en:"show symptoms",tr:"belirti göstermek"}, {en:"relieve the symptoms",tr:"şikayetleri hafifletmek"}],
"taken": [{en:"be taken for granted",tr:"olağan sayılmak"}, {en:"be taken aback",tr:"şaşırıp kalmak"}, {en:"this seat is taken",tr:"bu koltuk dolu, tutulmuş"}],
"target": [{en:"set a target",tr:"hedef koymak"}, {en:"target audience",tr:"hedef kitle"}],
"teach": [{en:"teach sb sth",tr:"birine bir şey öğretmek"}, {en:"teach sb to do sth",tr:"birine bir şey yapmayı öğretmek"}],
"technique": [{en:"develop a new technique",tr:"yeni bir teknik geliştirmek"}, {en:"apply a technique",tr:"bir tekniği uygulamak"}],
"temperature": [{en:"at room temperature",tr:"oda sıcaklığında"}, {en:"a rise in temperature",tr:"sıcaklıkta artış"}, {en:"take sb's temperature",tr:"birinin ateşini ölçmek"}],
"thinking": [{en:"critical thinking",tr:"eleştirel düşünme"}, {en:"a way of thinking",tr:"bir düşünme biçimi"}, {en:"wishful thinking",tr:"hüsnükuruntu"}],
"thousand": [{en:"thousands of people",tr:"binlerce kişi"}, {en:"a thousand years ago",tr:"bin yıl önce"}],
"threat": [{en:"pose a threat to sth",tr:"bir şeye tehdit oluşturmak"}, {en:"under threat",tr:"tehdit altında"}, {en:"a serious threat",tr:"ciddi bir tehdit"}],
"title": [{en:"the title of a book",tr:"bir kitabın başlığı"}, {en:"job title",tr:"iş unvanı"}],
"tool": [{en:"a useful tool",tr:"yararlı bir araç"}, {en:"tools and equipment",tr:"alet ve ekipman"}],
"top": [{en:"on top of sth",tr:"bir şeyin üstünde"}, {en:"at the top of",tr:"en üstünde, zirvesinde"}, {en:"from top to bottom",tr:"baştan aşağı"}],
"topic": [{en:"the topic of discussion",tr:"tartışma konusu"}, {en:"change the topic",tr:"konuyu değiştirmek"}],
"total": [{en:"in total",tr:"toplamda, tümü"}, {en:"the total number of sth",tr:"bir şeyin toplam sayısı"}, {en:"a total failure",tr:"tam bir başarısızlık"}],
"trade": [{en:"trade with other countries",tr:"başka ülkelerle ticaret yapmak"}, {en:"foreign trade",tr:"dış ticaret"}, {en:"a trade agreement",tr:"ticaret anlaşması"}],
"tradition": [{en:"a long tradition of sth",tr:"bir şeyin köklü geleneği"}, {en:"according to tradition",tr:"geleneğe göre"}],
"trait": [{en:"personality traits",tr:"kişilik özellikleri"}, {en:"inherited traits",tr:"kalıtsal özellikler"}],
"transport": [{en:"public transport",tr:"toplu taşıma"}, {en:"means of transport",tr:"ulaşım aracı"}, {en:"transport goods",tr:"mal taşımak"}],
"travel": [{en:"travel abroad",tr:"yurt dışına seyahat etmek"}, {en:"travel by train",tr:"trenle seyahat etmek"}],
"treat": [{en:"treat a disease",tr:"bir hastalığı tedavi etmek"}, {en:"treat sb with respect",tr:"birine saygıyla davranmak"}],
"tree": [{en:"plant a tree",tr:"ağaç dikmek"}, {en:"family tree",tr:"soy ağacı"}],
"trend": [{en:"a trend towards sth",tr:"bir şeye yönelik eğilim"}, {en:"a growing trend",tr:"artan bir eğilim"}, {en:"set a trend",tr:"çığır açmak, moda başlatmak"}],
"trigger": [{en:"trigger a reaction",tr:"bir tepkiyi tetiklemek"}, {en:"pull the trigger",tr:"tetiği çekmek"}],
"trying": [{en:"a trying time",tr:"zor bir dönem"}, {en:"trying circumstances",tr:"zorlu koşullar"}],
"understood": [{en:"make yourself understood",tr:"kendini anlaşılır kılmak"}, {en:"it is understood that",tr:"anlaşıldığına göre"}, {en:"widely understood",tr:"yaygın olarak anlaşılan"}],
"unite": [{en:"unite against a threat",tr:"bir tehdide karşı birleşmek"}, {en:"unite people",tr:"insanları birleştirmek"}],
"united": [{en:"united against a common enemy",tr:"ortak düşmana karşı birleşmiş"}, {en:"a united front",tr:"birleşik cephe"}, {en:"the United Nations",tr:"Birleşmiş Milletler"}],
"useful": [{en:"be useful for sth",tr:"bir şey için yararlı olmak"}, {en:"come in useful",tr:"işe yaramak"}],
"visual": [{en:"visual arts",tr:"görsel sanatlar"}, {en:"visual impairment",tr:"görme engeli"}, {en:"visual aids",tr:"görsel araçlar"}],
"weight": [{en:"put on weight",tr:"kilo almak, şişmanlamak"}, {en:"lose weight",tr:"kilo vermek, zayıflamak"}, {en:"give weight to sth",tr:"bir şeye ağırlık vermek"}],
"western": [{en:"western culture",tr:"batı kültürü"}, {en:"western countries",tr:"batı ülkeleri"}],
"white": [{en:"black and white",tr:"siyah beyaz; açık ve net"}, {en:"a white lie",tr:"beyaz yalan, zararsız kaçamak"}],
"wide": [{en:"a wide range of sth",tr:"geniş bir yelpazede bir şey"}, {en:"wide open",tr:"ardına kadar açık"}],
"widely": [{en:"widely used",tr:"yaygın olarak kullanılan"}, {en:"widely accepted",tr:"yaygın kabul gören"}, {en:"vary widely",tr:"büyük ölçüde değişmek"}],
"words": [{en:"in other words",tr:"başka bir deyişle"}, {en:"have words with sb",tr:"biriyle ağız kavgası etmek"}],
"worker": [{en:"a factory worker",tr:"fabrika işçisi"}, {en:"skilled workers",tr:"nitelikli işçiler"}, {en:"a social worker",tr:"sosyal hizmet uzmanı"}],
"works": [{en:"collected works",tr:"toplu eserler"}, {en:"public works",tr:"bayındırlık işleri"}]
};
