/* ============================================================
   Öbek tür etiketleri — dönüştürücü girdisi (site bu dosyayı YÜKLEMEZ)

   Kaynak xlsx'teki etiketler karışıktı: gerçek phrasal verb'lerle düz
   fiil+edat birleşmeleri aynı torbadaydı. Buradaki etiketler kaynağın
   üzerine yazılır; "sıradan" işaretliler listeden tamamen düşer.

   Türler: deyimsel fiil | edat kalıbı | sabit ifade | geçiş ifadesi | sıradan
   Üretim: tools/test-uretim/obek-birlestir.py
   ============================================================ */

window.OBEK_TURLERI = {
  "a bit": "sabit ifade",
  "a couple of": "sabit ifade",
  "a few": "sabit ifade",
  "a great deal": "sabit ifade",
  "a little": "sabit ifade",
  "a lot": "sabit ifade",
  "a million times": "sabit ifade",
  "a priori": "sabit ifade",
  "abide by": "deyimsel fiil",
  "able to": "edat kalıbı",
  "above all": "sabit ifade",
  "absorbed into": "edat kalıbı",
  "abstains from": "edat kalıbı",
  "accepted for": "edat kalıbı",
  "accompanied by": "edat kalıbı",
  "according to": "edat kalıbı",
  "account for": "deyimsel fiil",
  "accused of": "edat kalıbı",
  "accustomed to": "edat kalıbı",
  "achieved by": "sıradan",
  "acid rain": "sabit ifade",
  "acquired in": "sıradan",
  "across the country": "sabit ifade",
  "act as": "edat kalıbı",
  "act in": "sıradan",
  "act on": "deyimsel fiil",
  "act out": "deyimsel fiil",
  "activated by": "sıradan",
  "adapt to": "edat kalıbı",
  "adapted for": "edat kalıbı",
  "add to": "edat kalıbı",
  "addicted to": "edat kalıbı",
  "adhere to": "edat kalıbı",
  "adult education": "sabit ifade",
  "adult male": "sıradan",
  "advances in": "edat kalıbı",
  "advertising on": "sıradan",
  "advised to": "sıradan",
  "aerobic exercise": "sabit ifade",
  "affected by": "sıradan",
  "afford to": "sıradan",
  "after all": "geçiş ifadesi",
  "after that": "geçiş ifadesi",
  "age limit": "sabit ifade",
  "age of": "sıradan",
  "age to": "sıradan",
  "ageing in": "sıradan",
  "agree on": "edat kalıbı",
  "agree to": "edat kalıbı",
  "agree upon": "edat kalıbı",
  "agree with": "edat kalıbı",
  "agreed upon": "edat kalıbı",
  "aimed at": "edat kalıbı",
  "aims to": "sıradan",
  "air conditioning": "sabit ifade",
  "air out": "deyimsel fiil",
  "air pollution": "sabit ifade",
  "air pressure": "sabit ifade",
  "air travel": "sabit ifade",
  "align with": "edat kalıbı",
  "all in": "sabit ifade",
  "all over": "sabit ifade",
  "all the time": "sabit ifade",
  "all the way": "sabit ifade",
  "all told": "sabit ifade",
  "all too": "sabit ifade",
  "allow for": "deyimsel fiil",
  "allowed to": "sıradan",
  "alphabetic writing": "sabit ifade",
  "also known as": "sabit ifade",
  "alter ego": "sabit ifade",
  "alternative medicine": "sabit ifade",
  "amount of money": "sabit ifade",
  "ancient history": "sıradan",
  "and how": "sabit ifade",
  "and so": "geçiş ifadesi",
  "and so forth": "sabit ifade",
  "and so on": "sabit ifade",
  "animal husbandry": "sabit ifade",
  "animal material": "sıradan",
  "anorexia nervosa": "sabit ifade",
  "answer for": "deyimsel fiil",
  "antibiotic drug": "sıradan",
  "appeal to": "edat kalıbı",
  "appeared in": "sıradan",
  "appears on": "sıradan",
  "applies to": "edat kalıbı",
  "appropriate for": "edat kalıbı",
  "approved for": "edat kalıbı",
  "argue about": "edat kalıbı",
  "arising from": "edat kalıbı",
  "arm guard": "sıradan",
  "arose in": "sıradan",
  "arrive at": "edat kalıbı",
  "artificial heart": "sıradan",
  "artificial intelligence": "sabit ifade",
  "artificial language": "sıradan",
  "as a matter of fact": "geçiş ifadesi",
  "as a result": "geçiş ifadesi",
  "as a result of": "geçiş ifadesi",
  "as an alternative": "geçiş ifadesi",
  "as far as possible": "sabit ifade",
  "as if": "geçiş ifadesi",
  "as it is": "sabit ifade",
  "as long as": "geçiş ifadesi",
  "as soon as": "geçiş ifadesi",
  "as though": "geçiş ifadesi",
  "as usual": "sabit ifade",
  "as well": "sabit ifade",
  "as yet": "sabit ifade",
  "asexual reproduction": "sabit ifade",
  "aside from": "geçiş ifadesi",
  "ask for": "deyimsel fiil",
  "ask in": "deyimsel fiil",
  "associated with": "edat kalıbı",
  "at a time": "sabit ifade",
  "at all": "sabit ifade",
  "at all costs": "sabit ifade",
  "at any cost": "sabit ifade",
  "at first": "sabit ifade",
  "at first glance": "sabit ifade",
  "at hand": "sabit ifade",
  "at home": "sabit ifade",
  "at least": "sabit ifade",
  "at most": "sabit ifade",
  "at odds": "sabit ifade",
  "at present": "sabit ifade",
  "at sea": "sabit ifade",
  "at stake": "sabit ifade",
  "at the least": "sabit ifade",
  "at the same time": "sabit ifade",
  "at the time": "sabit ifade",
  "at times": "sabit ifade",
  "at work": "sabit ifade",
  "athletic competition": "sıradan",
  "atmospheric pressure": "sabit ifade",
  "attach to": "edat kalıbı",
  "attempt at": "edat kalıbı",
  "attempts to": "sıradan",
  "attend to": "deyimsel fiil",
  "attention deficit hyperactivity disorder": "sabit ifade",
  "attracted by": "sıradan",
  "attracted to": "edat kalıbı",
  "attributed to": "edat kalıbı",
  "auditory cortex": "sabit ifade",
  "aurora borealis": "sabit ifade",
  "autoimmune disorder": "sabit ifade",
  "automobile industry": "sıradan",
  "autonomic nervous system": "sabit ifade",
  "awarded to": "sıradan",
  "back and forth": "sabit ifade",
  "back in": "sabit ifade",
  "back on": "deyimsel fiil",
  "back to": "sıradan",
  "back up": "deyimsel fiil",
  "bacteria species": "sıradan",
  "bad weather": "sıradan",
  "balanced diet": "sabit ifade",
  "bank loan": "sıradan",
  "banking system": "sıradan",
  "based on": "edat kalıbı",
  "be active": "sıradan",
  "be after": "deyimsel fiil",
  "be born": "sabit ifade",
  "be due": "edat kalıbı",
  "be given": "deyimsel fiil",
  "be intimate": "sıradan",
  "be known as": "edat kalıbı",
  "be like": "sabit ifade",
  "be on": "deyimsel fiil",
  "be sick": "deyimsel fiil",
  "bear in mind": "deyimsel fiil",
  "beat back": "deyimsel fiil",
  "because of": "geçiş ifadesi",
  "before and after": "sabit ifade",
  "began to": "sıradan",
  "beginning in": "sıradan",
  "beginning of": "sıradan",
  "begins with": "edat kalıbı",
  "behave in": "sıradan",
  "believe in": "edat kalıbı",
  "believed to": "sıradan",
  "belong to": "edat kalıbı",
  "benefit from": "edat kalıbı",
  "bet on": "deyimsel fiil",
  "beta test": "sabit ifade",
  "better at": "edat kalıbı",
  "better to": "sıradan",
  "big bang": "sabit ifade",
  "big bang theory": "sabit ifade",
  "big cat": "sabit ifade",
  "big fish": "sabit ifade",
  "big-bang theory": "sabit ifade",
  "biological process": "sıradan",
  "bird's nest": "sıradan",
  "birthday cake": "sıradan",
  "bitter chocolate": "sıradan",
  "black comedy": "sabit ifade",
  "black powder": "sabit ifade",
  "blame for": "edat kalıbı",
  "blend in": "deyimsel fiil",
  "blink of an eye": "sabit ifade",
  "blood pressure": "sabit ifade",
  "blood type": "sabit ifade",
  "blow off": "deyimsel fiil",
  "blow up": "deyimsel fiil",
  "bluefin tuna": "sabit ifade",
  "body image": "sabit ifade",
  "body language": "sabit ifade",
  "body temperature": "sıradan",
  "body type": "sıradan",
  "boiling point": "sabit ifade",
  "boiling water": "sıradan",
  "bombarded with": "edat kalıbı",
  "born in": "sıradan",
  "born with": "sıradan",
  "bounce back": "deyimsel fiil",
  "brain cell": "sıradan",
  "brain damage": "sıradan",
  "brain drain": "sabit ifade",
  "break away": "deyimsel fiil",
  "break down": "deyimsel fiil",
  "break in": "deyimsel fiil",
  "break into": "deyimsel fiil",
  "break out": "deyimsel fiil",
  "break through": "deyimsel fiil",
  "break up": "deyimsel fiil",
  "break with": "deyimsel fiil",
  "breast cancer": "sabit ifade",
  "breathe in": "deyimsel fiil",
  "bright side": "sabit ifade",
  "bring about": "deyimsel fiil",
  "bring back": "deyimsel fiil",
  "bring down": "deyimsel fiil",
  "bring in": "deyimsel fiil",
  "bring off": "deyimsel fiil",
  "bring on": "deyimsel fiil",
  "bring out": "deyimsel fiil",
  "bring up": "deyimsel fiil",
  "bringing up": "deyimsel fiil",
  "brought to": "sıradan",
  "brought up in": "deyimsel fiil",
  "build in": "deyimsel fiil",
  "build on": "deyimsel fiil",
  "build up": "deyimsel fiil",
  "built by": "sıradan",
  "built to": "sıradan",
  "bunny rabbit": "sıradan",
  "burn up": "deyimsel fiil",
  "business activity": "sıradan",
  "buy food": "sıradan",
  "buy in": "deyimsel fiil",
  "buy it": "deyimsel fiil",
  "by chance": "sabit ifade",
  "by comparison": "geçiş ifadesi",
  "by contrast": "geçiş ifadesi",
  "by far": "sabit ifade",
  "by nature": "sabit ifade",
  "by the way": "sabit ifade",
  "by word of mouth": "sabit ifade",
  "cable television": "sabit ifade",
  "cacao tree": "sıradan",
  "call attention": "deyimsel fiil",
  "call back": "deyimsel fiil",
  "call for": "deyimsel fiil",
  "call into question": "deyimsel fiil",
  "call off": "deyimsel fiil",
  "call on": "deyimsel fiil",
  "call up": "deyimsel fiil",
  "can tell": "sabit ifade",
  "captivated by": "edat kalıbı",
  "carbon dioxide": "sabit ifade",
  "carbon monoxide": "sabit ifade",
  "cardiovascular disease": "sabit ifade",
  "care about": "edat kalıbı",
  "care for": "deyimsel fiil",
  "cargo liner": "sabit ifade",
  "carotid artery": "sabit ifade",
  "carried out in": "deyimsel fiil",
  "carried out on": "deyimsel fiil",
  "carry away": "deyimsel fiil",
  "carry back": "deyimsel fiil",
  "carry on": "deyimsel fiil",
  "carry out": "deyimsel fiil",
  "carry over": "deyimsel fiil",
  "carrying out": "deyimsel fiil",
  "case study": "sabit ifade",
  "cash in": "deyimsel fiil",
  "cast iron": "sabit ifade",
  "caste system": "sabit ifade",
  "catch cold": "deyimsel fiil",
  "catch fire": "deyimsel fiil",
  "catch up": "deyimsel fiil",
  "catch up with": "deyimsel fiil",
  "caught up": "deyimsel fiil",
  "cause of death": "sabit ifade",
  "caused by": "sıradan",
  "caused in": "sıradan",
  "cave in": "deyimsel fiil",
  "cellular phone": "sabit ifade",
  "central heating": "sabit ifade",
  "central nervous system": "sabit ifade",
  "centre of attention": "sabit ifade",
  "centre stage": "sabit ifade",
  "chain reaction": "sabit ifade",
  "chain up": "sıradan",
  "challenging for": "edat kalıbı",
  "challenging to": "edat kalıbı",
  "change into": "edat kalıbı",
  "change over": "deyimsel fiil",
  "change shape": "sıradan",
  "change taste": "sıradan",
  "change with": "sıradan",
  "changes in": "edat kalıbı",
  "characterised by": "edat kalıbı",
  "cheer up": "deyimsel fiil",
  "chemical reaction": "sabit ifade",
  "chief operating officer": "sabit ifade",
  "chip in": "deyimsel fiil",
  "choose to": "sıradan",
  "circulating in": "sıradan",
  "circulatory system": "sabit ifade",
  "city centre": "sıradan",
  "civil disobedience": "sabit ifade",
  "civil right": "sabit ifade",
  "civil servant": "sabit ifade",
  "claimed to": "sıradan",
  "classical music": "sabit ifade",
  "clean up": "deyimsel fiil",
  "clear from": "edat kalıbı",
  "clear off": "deyimsel fiil",
  "climate change": "sabit ifade",
  "climate in": "sıradan",
  "climb up": "sıradan",
  "cling to": "edat kalıbı",
  "clinical depression": "sabit ifade",
  "clinical trial": "sabit ifade",
  "clock in": "deyimsel fiil",
  "clock on": "deyimsel fiil",
  "close in": "deyimsel fiil",
  "close to": "edat kalıbı",
  "closed-circuit television": "sabit ifade",
  "clue in": "deyimsel fiil",
  "co-occur with": "edat kalıbı",
  "coconut milk": "sıradan",
  "coin collecting": "sıradan",
  "coincided with": "edat kalıbı",
  "coined by": "sıradan",
  "cold war": "sabit ifade",
  "cold weather": "sıradan",
  "collaborate with": "edat kalıbı",
  "collected by": "sıradan",
  "collide with": "edat kalıbı",
  "colour in": "deyimsel fiil",
  "combined with": "edat kalıbı",
  "come about": "deyimsel fiil",
  "come across": "deyimsel fiil",
  "come after": "sıradan",
  "come around": "deyimsel fiil",
  "come by": "deyimsel fiil",
  "come down": "deyimsel fiil",
  "come in": "deyimsel fiil",
  "come into": "deyimsel fiil",
  "come into being": "deyimsel fiil",
  "come of age": "deyimsel fiil",
  "come off": "deyimsel fiil",
  "come out": "deyimsel fiil",
  "come out of": "deyimsel fiil",
  "come to": "deyimsel fiil",
  "come together": "deyimsel fiil",
  "come under": "deyimsel fiil",
  "come up": "deyimsel fiil",
  "come up with": "deyimsel fiil",
  "come with": "sıradan",
  "comes at": "deyimsel fiil",
  "comes from": "sıradan",
  "comfort zone": "sabit ifade",
  "comforting to": "edat kalıbı",
  "commit suicide": "deyimsel fiil",
  "committed to": "edat kalıbı",
  "common good": "sabit ifade",
  "common in": "edat kalıbı",
  "common knowledge": "sabit ifade",
  "common people": "sabit ifade",
  "communicate with": "edat kalıbı",
  "comparable to": "edat kalıbı",
  "comparative psychology": "sabit ifade",
  "compared to": "edat kalıbı",
  "compared with": "edat kalıbı",
  "compensate for": "edat kalıbı",
  "compete with": "edat kalıbı",
  "complain about": "edat kalıbı",
  "comply with": "edat kalıbı",
  "composed of": "edat kalıbı",
  "compound microscope": "sabit ifade",
  "compressed air": "sıradan",
  "computer programming": "sıradan",
  "computer science": "sabit ifade",
  "concentrate on": "edat kalıbı",
  "concerned about": "edat kalıbı",
  "concerned with": "edat kalıbı",
  "concluded from": "edat kalıbı",
  "concrete jungle": "sabit ifade",
  "condition in": "sıradan",
  "conditions to": "edat kalıbı",
  "conducted by": "sıradan",
  "confer with": "edat kalıbı",
  "conference room": "sıradan",
  "confine to": "edat kalıbı",
  "conform to": "edat kalıbı",
  "confronted with": "edat kalıbı",
  "confused about": "edat kalıbı",
  "connected to": "edat kalıbı",
  "considered by": "sıradan",
  "considered to": "sıradan",
  "consist of": "edat kalıbı",
  "consumer goods": "sabit ifade",
  "contaminated by": "sıradan",
  "contemporary world": "sıradan",
  "continue into": "sıradan",
  "continue to": "sıradan",
  "continue with": "edat kalıbı",
  "contract in": "deyimsel fiil",
  "contrary to": "edat kalıbı",
  "contribute to": "edat kalıbı",
  "control in": "sıradan",
  "control room": "sıradan",
  "controlled by": "sıradan",
  "convenient for": "edat kalıbı",
  "convergent thinking": "sabit ifade",
  "cook up": "deyimsel fiil",
  "cool down": "deyimsel fiil",
  "cool it": "deyimsel fiil",
  "cool off": "deyimsel fiil",
  "cope with": "edat kalıbı",
  "corresponds to": "edat kalıbı",
  "cost to": "edat kalıbı",
  "cotton mill": "sıradan",
  "counted in": "sıradan",
  "country people": "sıradan",
  "coupled with": "edat kalıbı",
  "court of justice": "sabit ifade",
  "cover for": "deyimsel fiil",
  "cover up": "deyimsel fiil",
  "covered by": "sıradan",
  "created by": "sıradan",
  "created in": "sıradan",
  "credit card": "sabit ifade",
  "credited with": "edat kalıbı",
  "criticised by": "sıradan",
  "crops in": "sıradan",
  "crowd together": "sıradan",
  "cured by": "sıradan",
  "cut across": "deyimsel fiil",
  "cut back": "deyimsel fiil",
  "cut down": "deyimsel fiil",
  "cut down on": "deyimsel fiil",
  "cut in": "deyimsel fiil",
  "cut off": "deyimsel fiil",
  "cut out": "deyimsel fiil",
  "cut to": "deyimsel fiil",
  "cutting edge": "sabit ifade",
  "cylinder block": "sıradan",
  "damage to": "edat kalıbı",
  "data processing": "sabit ifade",
  "database management": "sıradan",
  "date back": "deyimsel fiil",
  "date from": "edat kalıbı",
  "dated to": "edat kalıbı",
  "dates back to": "deyimsel fiil",
  "day by day": "sabit ifade",
  "day off": "sabit ifade",
  "deal with": "deyimsel fiil",
  "death rate": "sabit ifade",
  "decided to": "sıradan",
  "decrease in": "edat kalıbı",
  "deep space": "sabit ifade",
  "demonstrated by": "sıradan",
  "dengue fever": "sabit ifade",
  "department store": "sabit ifade",
  "depend on": "edat kalıbı",
  "depend upon": "edat kalıbı",
  "dependant on": "edat kalıbı",
  "dependent on": "edat kalıbı",
  "depending on": "edat kalıbı",
  "derived from": "edat kalıbı",
  "descended from": "edat kalıbı",
  "described by": "sıradan",
  "described in": "sıradan",
  "designed in": "sıradan",
  "designed to": "sıradan",
  "designed with": "sıradan",
  "destroyed by": "sıradan",
  "detect from": "sıradan",
  "detected by": "sıradan",
  "determined by": "sıradan",
  "determined to": "sıradan",
  "developed by": "sıradan",
  "developed for": "sıradan",
  "developed in": "sıradan",
  "developed into": "edat kalıbı",
  "developed to": "sıradan",
  "developed with": "sıradan",
  "developmental psychology": "sabit ifade",
  "diagnosed with": "edat kalıbı",
  "die of": "edat kalıbı",
  "die out": "deyimsel fiil",
  "died from": "edat kalıbı",
  "differ from": "edat kalıbı",
  "differ in": "edat kalıbı",
  "difficult for": "edat kalıbı",
  "difficult to": "sıradan",
  "digestive system": "sabit ifade",
  "diminishes in": "sıradan",
  "direct evidence": "sıradan",
  "disagree with": "edat kalıbı",
  "disappears from": "sıradan",
  "disaster area": "sıradan",
  "discouraged by": "edat kalıbı",
  "discovered in": "sıradan",
  "disease to": "sıradan",
  "dispense with": "deyimsel fiil",
  "dispose of": "deyimsel fiil",
  "disputed by": "sıradan",
  "dissolve in": "edat kalıbı",
  "distributed across": "sıradan",
  "disturbed by": "sıradan",
  "divided into": "edat kalıbı",
  "do away with": "deyimsel fiil",
  "do by": "deyimsel fiil",
  "do good": "deyimsel fiil",
  "do in": "deyimsel fiil",
  "do it": "sıradan",
  "do up": "deyimsel fiil",
  "do well": "deyimsel fiil",
  "do work": "sıradan",
  "doctor up": "deyimsel fiil",
  "dog show": "sıradan",
  "dominant gene": "sabit ifade",
  "dominated by": "sıradan",
  "done for": "sabit ifade",
  "done with": "edat kalıbı",
  "double up": "deyimsel fiil",
  "draw a line": "deyimsel fiil",
  "draw in": "deyimsel fiil",
  "draw up": "deyimsel fiil",
  "dream in": "sıradan",
  "dream of": "edat kalıbı",
  "drew on": "deyimsel fiil",
  "drive around": "sıradan",
  "drive in": "sıradan",
  "drive up": "deyimsel fiil",
  "driving force": "sabit ifade",
  "drop by": "deyimsel fiil",
  "drop in": "deyimsel fiil",
  "dropped to": "edat kalıbı",
  "drug abuse": "sabit ifade",
  "drug user": "sıradan",
  "dry land": "sabit ifade",
  "dry season": "sabit ifade",
  "dry up": "deyimsel fiil",
  "due to": "edat kalıbı",
  "due to in": "edat kalıbı",
  "dumped in": "sıradan",
  "each year": "sıradan",
  "early childhood": "sabit ifade",
  "early days": "sabit ifade",
  "early on": "sabit ifade",
  "earth up": "deyimsel fiil",
  "easy for": "edat kalıbı",
  "easy to": "sıradan",
  "eat at": "deyimsel fiil",
  "eat in": "deyimsel fiil",
  "eat out": "deyimsel fiil",
  "eating disorder": "sabit ifade",
  "economic crisis": "sabit ifade",
  "economic development": "sabit ifade",
  "economic growth": "sabit ifade",
  "economic system": "sıradan",
  "economic value": "sıradan",
  "edible seed": "sıradan",
  "egg cell": "sabit ifade",
  "either or": "geçiş ifadesi",
  "elaborate on": "edat kalıbı",
  "electric car": "sıradan",
  "electric company": "sıradan",
  "electric shock": "sabit ifade",
  "electrical system": "sıradan",
  "electromagnetic radiation": "sabit ifade",
  "eliminated by": "sıradan",
  "embark on": "edat kalıbı",
  "emerged in": "sıradan",
  "emerging from": "sıradan",
  "emitted by": "sıradan",
  "emotional intelligence": "sabit ifade",
  "employed in": "sıradan",
  "employed to": "sıradan",
  "encouraged by": "sıradan",
  "encouraged to": "sıradan",
  "end up": "deyimsel fiil",
  "end up in": "deyimsel fiil",
  "end up with": "deyimsel fiil",
  "endangered species": "sabit ifade",
  "ended in": "edat kalıbı",
  "endowed with": "edat kalıbı",
  "energy-saving light": "sıradan",
  "engage in": "edat kalıbı",
  "engineer in": "sıradan",
  "enhanced by": "sıradan",
  "enjoyed by": "sıradan",
  "entertainment industry": "sıradan",
  "equal to": "edat kalıbı",
  "equipped with": "edat kalıbı",
  "erroneous belief": "sıradan",
  "escape from": "edat kalıbı",
  "established by": "sıradan",
  "established in": "sıradan",
  "ethnic minority": "sabit ifade",
  "evaporating from": "sıradan",
  "even if": "geçiş ifadesi",
  "even out": "deyimsel fiil",
  "even so": "geçiş ifadesi",
  "even though": "geçiş ifadesi",
  "even up": "deyimsel fiil",
  "event planner": "sıradan",
  "every night": "sıradan",
  "every quarter": "sıradan",
  "every year": "sıradan",
  "evidence for": "edat kalıbı",
  "evolved in": "sıradan",
  "evolved into": "edat kalıbı",
  "examined in": "sıradan",
  "excelled in": "edat kalıbı",
  "except for": "edat kalıbı",
  "except for in": "sabit ifade",
  "exercised by": "sıradan",
  "exhaust fumes": "sabit ifade",
  "exists in": "sıradan",
  "expanded in": "sıradan",
  "expected from": "edat kalıbı",
  "expected to": "sıradan",
  "experienced by": "sıradan",
  "experienced in": "edat kalıbı",
  "experimental psychology": "sabit ifade",
  "experiments with": "edat kalıbı",
  "explained by": "sıradan",
  "exposed to": "edat kalıbı",
  "express feelings": "sıradan",
  "express joy": "sıradan",
  "extend to": "edat kalıbı",
  "extended family": "sabit ifade",
  "extends from": "sıradan",
  "extinct in": "sıradan",
  "extra large": "sabit ifade",
  "eye contact": "sabit ifade",
  "face from": "sıradan",
  "faced with": "edat kalıbı",
  "faces in": "sıradan",
  "factor in": "deyimsel fiil",
  "factory worker": "sıradan",
  "fade away": "deyimsel fiil",
  "fade out": "deyimsel fiil",
  "failed to": "sıradan",
  "fairy tale": "sabit ifade",
  "fall asleep": "deyimsel fiil",
  "fall back": "deyimsel fiil",
  "fall behind": "deyimsel fiil",
  "fall in": "deyimsel fiil",
  "fall into": "edat kalıbı",
  "fall off": "deyimsel fiil",
  "fall out": "deyimsel fiil",
  "fall short": "deyimsel fiil",
  "fall short of": "deyimsel fiil",
  "fall under": "edat kalıbı",
  "farmer's market": "sabit ifade",
  "fascinated by": "edat kalıbı",
  "fashion industry": "sıradan",
  "fast food": "sabit ifade",
  "fatality rate": "sabit ifade",
  "fatten up": "deyimsel fiil",
  "fax machine": "sıradan",
  "feature film": "sabit ifade",
  "fed up": "sabit ifade",
  "feed back": "deyimsel fiil",
  "feed on": "edat kalıbı",
  "feel about": "edat kalıbı",
  "feel for": "deyimsel fiil",
  "feel like": "deyimsel fiil",
  "feeling of": "sıradan",
  "fictional character": "sıradan",
  "field of study": "sabit ifade",
  "fight against": "edat kalıbı",
  "fight back": "deyimsel fiil",
  "fight down": "deyimsel fiil",
  "fight off": "deyimsel fiil",
  "figure out": "deyimsel fiil",
  "fill in": "deyimsel fiil",
  "fill out": "deyimsel fiil",
  "fill up": "deyimsel fiil",
  "final decision": "sıradan",
  "financial assistance": "sıradan",
  "financial loss": "sıradan",
  "find out": "deyimsel fiil",
  "fire extinguisher": "sabit ifade",
  "first aid": "sabit ifade",
  "first appearance": "sıradan",
  "first half": "sıradan",
  "first language": "sabit ifade",
  "first person": "sabit ifade",
  "first step": "sıradan",
  "fit in": "deyimsel fiil",
  "fit in with": "deyimsel fiil",
  "fit into": "edat kalıbı",
  "fixated on": "edat kalıbı",
  "flight control": "sabit ifade",
  "flood in": "deyimsel fiil",
  "floods of": "sabit ifade",
  "flourished in": "sıradan",
  "flow away": "sıradan",
  "fly on": "deyimsel fiil",
  "fly through": "sıradan",
  "focus on": "edat kalıbı",
  "follow out": "deyimsel fiil",
  "follow suit": "sabit ifade",
  "followed by": "edat kalıbı",
  "food allergy": "sabit ifade",
  "food chain": "sabit ifade",
  "food poisoning": "sabit ifade",
  "food web": "sabit ifade",
  "for a while": "sabit ifade",
  "for certain": "sabit ifade",
  "for example": "geçiş ifadesi",
  "for free": "sabit ifade",
  "for good": "sabit ifade",
  "for instance": "geçiş ifadesi",
  "for short": "sabit ifade",
  "for sure": "sabit ifade",
  "for the moment": "sabit ifade",
  "for the most part": "sabit ifade",
  "forced to": "sıradan",
  "foreign aid": "sabit ifade",
  "foreign minister": "sabit ifade",
  "form in": "sıradan",
  "formed to": "sıradan",
  "fossil fuel": "sabit ifade",
  "found in": "sıradan",
  "found to": "sıradan",
  "four times": "sıradan",
  "frame in": "deyimsel fiil",
  "free fall": "sabit ifade",
  "free time": "sabit ifade",
  "free weight": "sabit ifade",
  "fresh start": "sabit ifade",
  "fresh water": "sabit ifade",
  "from scratch": "sabit ifade",
  "from time to time": "sabit ifade",
  "fuel system": "sabit ifade",
  "full moon": "sabit ifade",
  "full of": "edat kalıbı",
  "full term": "sabit ifade",
  "fully grown": "sabit ifade",
  "function at": "sıradan",
  "functioning of": "sıradan",
  "functions in": "sıradan",
  "funded by": "sıradan",
  "fur coat": "sabit ifade",
  "gain ground": "sabit ifade",
  "gains from": "edat kalıbı",
  "gains in": "sıradan",
  "gas heat": "sıradan",
  "gastrointestinal tract": "sabit ifade",
  "gather in": "deyimsel fiil",
  "general relativity": "sabit ifade",
  "general theory of relativity": "sabit ifade",
  "generated by": "sıradan",
  "generation gap": "sabit ifade",
  "genetic engineering": "sabit ifade",
  "geographic region": "sıradan",
  "geological period": "sabit ifade",
  "get about": "deyimsel fiil",
  "get along": "deyimsel fiil",
  "get along with": "deyimsel fiil",
  "get at": "deyimsel fiil",
  "get away": "deyimsel fiil",
  "get away from": "deyimsel fiil",
  "get back": "deyimsel fiil",
  "get by": "deyimsel fiil",
  "get even": "deyimsel fiil",
  "get from": "sıradan",
  "get hold": "sabit ifade",
  "get hold of": "deyimsel fiil",
  "get in": "deyimsel fiil",
  "get into": "deyimsel fiil",
  "get it": "sıradan",
  "get off": "deyimsel fiil",
  "get on": "deyimsel fiil",
  "get out": "deyimsel fiil",
  "get out of": "deyimsel fiil",
  "get over": "deyimsel fiil",
  "get rid of": "deyimsel fiil",
  "get started": "deyimsel fiil",
  "get through": "deyimsel fiil",
  "get to": "deyimsel fiil",
  "get up": "deyimsel fiil",
  "get used to": "deyimsel fiil",
  "get well": "deyimsel fiil",
  "get worse": "sıradan",
  "give away": "deyimsel fiil",
  "give birth": "deyimsel fiil",
  "give in": "deyimsel fiil",
  "give it a try": "sabit ifade",
  "give off": "deyimsel fiil",
  "give out": "deyimsel fiil",
  "give rise": "deyimsel fiil",
  "give up": "deyimsel fiil",
  "given that": "geçiş ifadesi",
  "giving up": "deyimsel fiil",
  "global demand": "sıradan",
  "global warming": "sabit ifade",
  "go about": "deyimsel fiil",
  "go against": "deyimsel fiil",
  "go along": "deyimsel fiil",
  "go around": "deyimsel fiil",
  "go away": "deyimsel fiil",
  "go back": "deyimsel fiil",
  "go bad": "deyimsel fiil",
  "go down": "deyimsel fiil",
  "go far": "deyimsel fiil",
  "go for": "deyimsel fiil",
  "go in": "sıradan",
  "go into": "deyimsel fiil",
  "go off": "deyimsel fiil",
  "go on": "deyimsel fiil",
  "go on to": "deyimsel fiil",
  "go out": "deyimsel fiil",
  "go over": "deyimsel fiil",
  "go through": "deyimsel fiil",
  "go to": "sıradan",
  "go up": "deyimsel fiil",
  "go with": "deyimsel fiil",
  "go wrong": "deyimsel fiil",
  "god of war": "sabit ifade",
  "good about": "sıradan",
  "good deal": "sabit ifade",
  "good enough": "sabit ifade",
  "good example": "sıradan",
  "good for": "edat kalıbı",
  "good health": "sabit ifade",
  "good luck": "sabit ifade",
  "good time": "sabit ifade",
  "good weather": "sıradan",
  "good word": "sabit ifade",
  "governed by": "sıradan",
  "government officials": "sıradan",
  "great deal": "sabit ifade",
  "great power": "sabit ifade",
  "great white shark": "sabit ifade",
  "greenhouse effect": "sabit ifade",
  "greenhouse gas": "sabit ifade",
  "greenhouse warming": "sabit ifade",
  "grew out": "deyimsel fiil",
  "grew out of": "deyimsel fiil",
  "grew to": "sıradan",
  "grocery store": "sabit ifade",
  "gross domestic product": "sabit ifade",
  "groups in": "sıradan",
  "grow back": "deyimsel fiil",
  "grow over": "deyimsel fiil",
  "grow up": "deyimsel fiil",
  "grow up in": "deyimsel fiil",
  "grown in": "sıradan",
  "grown on": "sıradan",
  "grows from": "sıradan",
  "growth hormone": "sabit ifade",
  "growth rate": "sabit ifade",
  "hand and foot": "sabit ifade",
  "hand down": "deyimsel fiil",
  "hand in hand": "sabit ifade",
  "hand over": "deyimsel fiil",
  "handed in": "deyimsel fiil",
  "handling of": "sıradan",
  "happen in": "sıradan",
  "happen on": "deyimsel fiil",
  "happen to": "deyimsel fiil",
  "hard drive": "sabit ifade",
  "hard time": "sabit ifade",
  "hard to": "sıradan",
  "have a look": "deyimsel fiil",
  "have down": "deyimsel fiil",
  "have on": "sıradan",
  "have sex": "sabit ifade",
  "have to do with": "deyimsel fiil",
  "have words": "sabit ifade",
  "have young": "sabit ifade",
  "hay fever": "sabit ifade",
  "head of state": "sabit ifade",
  "health care": "sabit ifade",
  "health insurance": "sabit ifade",
  "health problem": "sabit ifade",
  "health professional": "sabit ifade",
  "heard about": "edat kalıbı",
  "hearing loss": "sabit ifade",
  "heart attack": "sabit ifade",
  "heart disease": "sabit ifade",
  "heart failure": "sabit ifade",
  "heart rate": "sabit ifade",
  "heat up": "deyimsel fiil",
  "heating system": "sabit ifade",
  "held by": "sıradan",
  "help of": "sabit ifade",
  "help out": "deyimsel fiil",
  "helped to": "sıradan",
  "high blood pressure": "sabit ifade",
  "high gear": "sabit ifade",
  "high ground": "sabit ifade",
  "high in": "edat kalıbı",
  "high on": "edat kalıbı",
  "high point": "sabit ifade",
  "high quality": "sıradan",
  "high school": "sabit ifade",
  "high status": "sıradan",
  "high technology": "sabit ifade",
  "high temperature": "sıradan",
  "high time": "sabit ifade",
  "high wind": "sabit ifade",
  "higher education": "sabit ifade",
  "higher status": "sıradan",
  "hold in": "deyimsel fiil",
  "hold off": "deyimsel fiil",
  "hold on": "deyimsel fiil",
  "hold up": "deyimsel fiil",
  "holiday season": "sabit ifade",
  "home in": "deyimsel fiil",
  "home to": "edat kalıbı",
  "hope to": "sıradan",
  "horned lizard": "sabit ifade",
  "hot spot": "sabit ifade",
  "human activity": "sıradan",
  "human beings": "sabit ifade",
  "human body": "sabit ifade",
  "human face": "sıradan",
  "human growth hormone": "sabit ifade",
  "human nature": "sabit ifade",
  "human race": "sabit ifade",
  "human waste": "sabit ifade",
  "hunted by": "sıradan",
  "hunted for": "deyimsel fiil",
  "hunting in": "sıradan",
  "ice age": "sabit ifade",
  "ice cap": "sabit ifade",
  "ice shelf": "sabit ifade",
  "identical twin": "sabit ifade",
  "if not": "sabit ifade",
  "ignored by": "sıradan",
  "ill health": "sabit ifade",
  "illustrated by": "sıradan",
  "immune response": "sabit ifade",
  "immune system": "sabit ifade",
  "implemented to": "sıradan",
  "implied in": "sıradan",
  "important for": "edat kalıbı",
  "important in": "edat kalıbı",
  "important to": "edat kalıbı",
  "imposed by": "sıradan",
  "improved in": "sıradan",
  "in a similar way": "sabit ifade",
  "in a way": "sabit ifade",
  "in addition": "geçiş ifadesi",
  "in addition to": "geçiş ifadesi",
  "in advance": "sabit ifade",
  "in agreement": "sabit ifade",
  "in all": "sabit ifade",
  "in all probability": "sabit ifade",
  "in and of itself": "sabit ifade",
  "in case": "geçiş ifadesi",
  "in common": "sabit ifade",
  "in common with": "sabit ifade",
  "in conclusion": "geçiş ifadesi",
  "in contrast": "geçiş ifadesi",
  "in darkness": "sıradan",
  "in detail": "sabit ifade",
  "in essence": "geçiş ifadesi",
  "in fact": "geçiş ifadesi",
  "in fashion": "sabit ifade",
  "in for": "sabit ifade",
  "in force": "sabit ifade",
  "in front": "sabit ifade",
  "in full": "sabit ifade",
  "in general": "sabit ifade",
  "in group": "sabit ifade",
  "in hand": "sabit ifade",
  "in height": "sabit ifade",
  "in large quantities": "sabit ifade",
  "in line": "sabit ifade",
  "in on": "sabit ifade",
  "in order": "sabit ifade",
  "in other words": "geçiş ifadesi",
  "in part": "sabit ifade",
  "in particular": "sabit ifade",
  "in person": "sabit ifade",
  "in place": "sabit ifade",
  "in principle": "sabit ifade",
  "in public": "sabit ifade",
  "in question": "sabit ifade",
  "in reality": "geçiş ifadesi",
  "in response to": "geçiş ifadesi",
  "in short": "geçiş ifadesi",
  "in sight": "sabit ifade",
  "in spite of": "geçiş ifadesi",
  "in style": "sabit ifade",
  "in that": "geçiş ifadesi",
  "in the air": "sabit ifade",
  "in the beginning": "sabit ifade",
  "in the end": "geçiş ifadesi",
  "in the first place": "sabit ifade",
  "in the lead": "sabit ifade",
  "in the meantime": "geçiş ifadesi",
  "in the nick of time": "sabit ifade",
  "in the south": "sabit ifade",
  "in the way": "sabit ifade",
  "in this": "sıradan",
  "in this way": "geçiş ifadesi",
  "in time": "sabit ifade",
  "in truth": "geçiş ifadesi",
  "in turn": "geçiş ifadesi",
  "in use": "sabit ifade",
  "in vain": "sabit ifade",
  "in writing": "sabit ifade",
  "increase in": "edat kalıbı",
  "increased to": "sıradan",
  "inductive reasoning": "sabit ifade",
  "industrial revolution": "sabit ifade",
  "infant feeding": "sabit ifade",
  "infected with": "edat kalıbı",
  "infectious disease": "sabit ifade",
  "inferred about": "sıradan",
  "inferred from": "edat kalıbı",
  "influenced by": "sıradan",
  "inner ear": "sabit ifade",
  "inside out": "sabit ifade",
  "insist on": "edat kalıbı",
  "inspired by": "edat kalıbı",
  "instead of": "geçiş ifadesi",
  "insurance policy": "sabit ifade",
  "integrated into": "edat kalıbı",
  "intellectual property": "sabit ifade",
  "intended to": "sıradan",
  "interact with": "edat kalıbı",
  "interest to": "edat kalıbı",
  "interested in": "edat kalıbı",
  "interesting by": "sıradan",
  "interfere with": "edat kalıbı",
  "internal combustion": "sabit ifade",
  "internal-combustion engine": "sabit ifade",
  "international law": "sabit ifade",
  "introduced in": "sıradan",
  "introduced to": "edat kalıbı",
  "invented by": "sıradan",
  "invented in": "sıradan",
  "invest in": "edat kalıbı",
  "involved in": "edat kalıbı",
  "irrespective of": "geçiş ifadesi",
  "issued in": "sıradan",
  "jigsaw puzzle": "sabit ifade",
  "join forces": "sabit ifade",
  "junk food": "sabit ifade",
  "just as": "geçiş ifadesi",
  "just in case": "sabit ifade",
  "keep away": "deyimsel fiil",
  "keep down": "deyimsel fiil",
  "keep going": "sıradan",
  "keep in": "deyimsel fiil",
  "keep off": "deyimsel fiil",
  "keep on": "deyimsel fiil",
  "keep out": "deyimsel fiil",
  "keep to": "deyimsel fiil",
  "keep track": "deyimsel fiil",
  "keep up": "deyimsel fiil",
  "keep up with": "deyimsel fiil",
  "kept up": "deyimsel fiil",
  "kind of": "sabit ifade",
  "know about": "sıradan",
  "know as": "sıradan",
  "knowledge into": "sıradan",
  "known for": "edat kalıbı",
  "known of": "sıradan",
  "known to": "sıradan",
  "land area": "sıradan",
  "language learning": "sabit ifade",
  "language system": "sabit ifade",
  "language teaching": "sabit ifade",
  "language with": "sıradan",
  "large number": "sabit ifade",
  "laser interferometer": "sabit ifade",
  "later on": "sabit ifade",
  "lateral line": "sabit ifade",
  "laugh at": "edat kalıbı",
  "launched in": "sıradan",
  "law enforcement": "sabit ifade",
  "lay in": "deyimsel fiil",
  "lay off": "deyimsel fiil",
  "lay out": "deyimsel fiil",
  "lead off": "deyimsel fiil",
  "lead on": "deyimsel fiil",
  "lead to": "edat kalıbı",
  "learn about": "sıradan",
  "learn from": "edat kalıbı",
  "learn to": "sıradan",
  "learning ability": "sıradan",
  "leave alone": "deyimsel fiil",
  "leave behind": "deyimsel fiil",
  "leave out": "deyimsel fiil",
  "led by": "sıradan",
  "left hemisphere": "sabit ifade",
  "leisure time": "sabit ifade",
  "let alone": "sabit ifade",
  "let in": "deyimsel fiil",
  "let on": "deyimsel fiil",
  "letter of the alphabet": "sabit ifade",
  "liable to": "edat kalıbı",
  "lie at": "edat kalıbı",
  "lie detector": "sabit ifade",
  "lie in": "deyimsel fiil",
  "lie low": "deyimsel fiil",
  "lie with": "edat kalıbı",
  "life expectancy": "sabit ifade",
  "life form": "sabit ifade",
  "life story": "sabit ifade",
  "light air": "sabit ifade",
  "light bulb": "sabit ifade",
  "light source": "sabit ifade",
  "light up": "deyimsel fiil",
  "like to": "sıradan",
  "limited to": "edat kalıbı",
  "linked to": "edat kalıbı",
  "linked with": "edat kalıbı",
  "listed in": "sıradan",
  "listening to": "edat kalıbı",
  "literary critic": "sabit ifade",
  "literary criticism": "sabit ifade",
  "little girl": "sıradan",
  "live in": "sıradan",
  "live on": "deyimsel fiil",
  "live out": "deyimsel fiil",
  "live up to": "deyimsel fiil",
  "live with": "deyimsel fiil",
  "lived by": "deyimsel fiil",
  "lived to": "sıradan",
  "living standards": "sabit ifade",
  "living thing": "sabit ifade",
  "loaded with": "edat kalıbı",
  "located at": "edat kalıbı",
  "located in": "edat kalıbı",
  "lock in": "deyimsel fiil",
  "long ago": "sabit ifade",
  "long run": "sabit ifade",
  "long time": "sabit ifade",
  "long-term memory": "sabit ifade",
  "look after": "deyimsel fiil",
  "look around": "deyimsel fiil",
  "look at": "edat kalıbı",
  "look away": "sıradan",
  "look back": "deyimsel fiil",
  "look down on": "deyimsel fiil",
  "look for": "deyimsel fiil",
  "look forward": "deyimsel fiil",
  "look into": "deyimsel fiil",
  "look like": "deyimsel fiil",
  "look on": "deyimsel fiil",
  "look to": "deyimsel fiil",
  "look up": "deyimsel fiil",
  "look up to": "deyimsel fiil",
  "looking at": "edat kalıbı",
  "looking for": "deyimsel fiil",
  "lose it": "deyimsel fiil",
  "loved to": "sıradan",
  "low status": "sıradan",
  "low temperature": "sıradan",
  "lower in": "edat kalıbı",
  "lying to": "edat kalıbı",
  "made by": "sıradan",
  "made from": "edat kalıbı",
  "made in": "sıradan",
  "made of": "edat kalıbı",
  "made to": "sıradan",
  "made up of": "deyimsel fiil",
  "magazine article": "sabit ifade",
  "magical power": "sıradan",
  "magnetic compass": "sabit ifade",
  "magnetic field": "sabit ifade",
  "magnetic resonance": "sabit ifade",
  "magnetic resonance imaging": "sabit ifade",
  "make believe": "sabit ifade",
  "make do": "sabit ifade",
  "make for": "deyimsel fiil",
  "make good": "deyimsel fiil",
  "make happy": "sıradan",
  "make it": "sıradan",
  "make out": "deyimsel fiil",
  "make over": "deyimsel fiil",
  "make peace": "sabit ifade",
  "make sense": "sabit ifade",
  "make sure": "sabit ifade",
  "make up": "deyimsel fiil",
  "make up for": "deyimsel fiil",
  "make way": "deyimsel fiil",
  "manage to": "sıradan",
  "manipulated to": "sıradan",
  "manual labour": "sabit ifade",
  "maps of": "sıradan",
  "march on": "deyimsel fiil",
  "margin of error": "sabit ifade",
  "marital status": "sabit ifade",
  "mark out": "deyimsel fiil",
  "marked by": "edat kalıbı",
  "mass culture": "sabit ifade",
  "mass production": "sabit ifade",
  "materia medica": "sabit ifade",
  "matter of fact": "sabit ifade",
  "matter to": "edat kalıbı",
  "meals in": "sıradan",
  "mean by": "edat kalıbı",
  "meaning to": "sıradan",
  "means for": "sıradan",
  "means in": "sıradan",
  "means of": "sabit ifade",
  "means of in": "sıradan",
  "measure in": "edat kalıbı",
  "mechanical engineering": "sabit ifade",
  "medical care": "sabit ifade",
  "medical diagnosis": "sabit ifade",
  "medical practice": "sabit ifade",
  "medical profession": "sabit ifade",
  "meet with": "edat kalıbı",
  "melt down": "deyimsel fiil",
  "melt of": "sıradan",
  "melting from": "sıradan",
  "memento mori": "sabit ifade",
  "mental capacity": "sabit ifade",
  "mental condition": "sıradan",
  "mental health": "sabit ifade",
  "mental illness": "sabit ifade",
  "mental image": "sabit ifade",
  "mentioned in": "sıradan",
  "middle class": "sabit ifade",
  "middle school": "sabit ifade",
  "migrating to": "sıradan",
  "military government": "sabit ifade",
  "military headquarters": "sabit ifade",
  "military officer": "sabit ifade",
  "military training": "sabit ifade",
  "milk chocolate": "sabit ifade",
  "misleading in": "sıradan",
  "mixed with": "edat kalıbı",
  "mobile phone": "sabit ifade",
  "modern times": "sabit ifade",
  "modern world": "sabit ifade",
  "moral philosophy": "sabit ifade",
  "more and more": "sabit ifade",
  "more often than not": "sabit ifade",
  "more or less": "sabit ifade",
  "more than": "sabit ifade",
  "mother tongue": "sabit ifade",
  "motion picture": "sabit ifade",
  "motion-picture film": "sabit ifade",
  "mountain goat": "sabit ifade",
  "mouth off": "deyimsel fiil",
  "move around": "sıradan",
  "move in": "deyimsel fiil",
  "move into": "deyimsel fiil",
  "move on": "deyimsel fiil",
  "move out": "deyimsel fiil",
  "move over": "deyimsel fiil",
  "move through": "sıradan",
  "move to": "sıradan",
  "moving picture": "sabit ifade",
  "much as": "geçiş ifadesi",
  "muscles through": "deyimsel fiil",
  "musical instrument": "sabit ifade",
  "musical score": "sabit ifade",
  "musical theme": "sabit ifade",
  "nail polish": "sabit ifade",
  "naked eye": "sabit ifade",
  "name of": "sıradan",
  "named after": "edat kalıbı",
  "national park": "sabit ifade",
  "native language": "sabit ifade",
  "native speaker": "sabit ifade",
  "natural ability": "sıradan",
  "natural history": "sabit ifade",
  "natural resources": "sabit ifade",
  "natural state": "sıradan",
  "neither nor": "geçiş ifadesi",
  "nervous system": "sabit ifade",
  "neural network": "sabit ifade",
  "never again": "sabit ifade",
  "new moon": "sabit ifade",
  "new wave": "sabit ifade",
  "no doubt": "sabit ifade",
  "no longer": "sabit ifade",
  "no matter": "geçiş ifadesi",
  "noise level": "sabit ifade",
  "noise pollution": "sabit ifade",
  "northern lights": "sabit ifade",
  "now that": "geçiş ifadesi",
  "nuclear power": "sabit ifade",
  "nuclear war": "sabit ifade",
  "observed in": "sıradan",
  "obsessed with": "edat kalıbı",
  "obsessive-compulsive disorder": "sabit ifade",
  "obtained from": "sıradan",
  "occupied by": "sıradan",
  "occur at": "sıradan",
  "occur in": "sıradan",
  "ocean floor": "sabit ifade",
  "of age": "sabit ifade",
  "of all time": "sabit ifade",
  "of course": "sabit ifade",
  "offered to": "sıradan",
  "oil industry": "sabit ifade",
  "oil production": "sabit ifade",
  "old age": "sabit ifade",
  "on a regular basis": "sabit ifade",
  "on average": "sabit ifade",
  "on board": "sabit ifade",
  "on earth": "sabit ifade",
  "on it": "sıradan",
  "on that": "sıradan",
  "on the contrary": "geçiş ifadesi",
  "on the job": "sabit ifade",
  "on the one hand": "sabit ifade",
  "on the other hand": "sabit ifade",
  "on the table": "sabit ifade",
  "on trial": "sabit ifade",
  "once again": "sabit ifade",
  "once more": "sabit ifade",
  "one hundred": "sıradan",
  "one thousand": "sıradan",
  "open to": "edat kalıbı",
  "open up": "deyimsel fiil",
  "opera house": "sabit ifade",
  "operate on": "edat kalıbı",
  "operating in": "sıradan",
  "opposed to": "edat kalıbı",
  "opposed to in": "sıradan",
  "opting for": "edat kalıbı",
  "or so": "sabit ifade",
  "oral presentation": "sıradan",
  "order of business": "sabit ifade",
  "order to": "sabit ifade",
  "organ transplant": "sabit ifade",
  "organic chemistry": "sabit ifade",
  "originate in": "edat kalıbı",
  "out in": "sıradan",
  "out of": "sabit ifade",
  "out of it": "sabit ifade",
  "out of reach": "sabit ifade",
  "out of the way": "sabit ifade",
  "out to": "sabit ifade",
  "outer space": "sabit ifade",
  "over again": "sabit ifade",
  "over and over": "sabit ifade",
  "over and over again": "sabit ifade",
  "overwhelmed by": "edat kalıbı",
  "owing to": "edat kalıbı",
  "own up": "deyimsel fiil",
  "ozone layer": "sabit ifade",
  "paid to": "deyimsel fiil",
  "palm oil": "sıradan",
  "paper money": "sabit ifade",
  "paper plate": "sıradan",
  "participate in": "edat kalıbı",
  "particle accelerator": "sabit ifade",
  "pass by": "sıradan",
  "pass off": "deyimsel fiil",
  "pass on": "deyimsel fiil",
  "pass on to": "deyimsel fiil",
  "pass over": "deyimsel fiil",
  "pass through": "sıradan",
  "passed down": "deyimsel fiil",
  "passing of": "sıradan",
  "paved surface": "sıradan",
  "pay for": "edat kalıbı",
  "pay off": "deyimsel fiil",
  "paying attention": "sabit ifade",
  "peaks in": "sıradan",
  "people of": "sıradan",
  "per capita": "sabit ifade",
  "per capita income": "sabit ifade",
  "per year": "sabit ifade",
  "percussion section": "sabit ifade",
  "perform at": "sıradan",
  "performed by": "sıradan",
  "performed in": "sıradan",
  "performed on": "edat kalıbı",
  "performing arts": "sabit ifade",
  "performs with": "sıradan",
  "period of time": "sabit ifade",
  "peripheral nervous system": "sabit ifade",
  "persist in": "edat kalıbı",
  "person over": "sıradan",
  "person to person": "sabit ifade",
  "personal computer": "sabit ifade",
  "personal identification number": "sabit ifade",
  "personal identity": "sıradan",
  "personal matters": "sıradan",
  "phase in": "deyimsel fiil",
  "phone service": "sıradan",
  "physical goods": "sıradan",
  "pick out": "deyimsel fiil",
  "pick up": "deyimsel fiil",
  "picture frame": "sıradan",
  "piece of cake": "sabit ifade",
  "piece of work": "sabit ifade",
  "piece of writing": "sabit ifade",
  "pin down": "deyimsel fiil",
  "pituitary gland": "sabit ifade",
  "place at": "sıradan",
  "place in": "sıradan",
  "place of origin": "sabit ifade",
  "placebo effect": "sabit ifade",
  "placed on": "sıradan",
  "places with": "edat kalıbı",
  "plan to": "sıradan",
  "plant family": "sabit ifade",
  "plant material": "sıradan",
  "play in": "sıradan",
  "play with": "edat kalıbı",
  "played by": "deyimsel fiil",
  "point in time": "sabit ifade",
  "point of reference": "sabit ifade",
  "point of view": "sabit ifade",
  "point out": "deyimsel fiil",
  "point the way": "deyimsel fiil",
  "pointed out in": "edat kalıbı",
  "pointing out": "deyimsel fiil",
  "points for": "sıradan",
  "points to": "edat kalıbı",
  "political movement": "sıradan",
  "poor people": "sabit ifade",
  "pop group": "sıradan",
  "pop in": "deyimsel fiil",
  "pop music": "sabit ifade",
  "popular music": "sabit ifade",
  "positioned in": "sıradan",
  "postage stamp": "sabit ifade",
  "pot plant": "sabit ifade",
  "potassium carbonate": "sabit ifade",
  "potato blight": "sabit ifade",
  "pour out": "deyimsel fiil",
  "power by": "sıradan",
  "power plant": "sabit ifade",
  "prefer to": "sıradan",
  "prepare for": "edat kalıbı",
  "presented at": "sıradan",
  "presented in": "sıradan",
  "preserved by": "sıradan",
  "preserved from": "edat kalıbı",
  "prevailed in": "sıradan",
  "prevented by": "sıradan",
  "prey on": "edat kalıbı",
  "price tag": "sabit ifade",
  "pride in": "edat kalıbı",
  "primary care": "sabit ifade",
  "problem solving": "sabit ifade",
  "process of": "sıradan",
  "produced by": "sıradan",
  "produced for": "sıradan",
  "produced in": "sıradan",
  "professional life": "sıradan",
  "profit from": "edat kalıbı",
  "programmed to": "sıradan",
  "progress to": "edat kalıbı",
  "promise to": "sıradan",
  "proposed by": "sıradan",
  "prostate cancer": "sabit ifade",
  "protected by": "sıradan",
  "proud of": "edat kalıbı",
  "proved to": "sıradan",
  "proven by": "sıradan",
  "provide to": "edat kalıbı",
  "provided by": "sıradan",
  "provided for": "edat kalıbı",
  "provided with": "edat kalıbı",
  "psychic energy": "sabit ifade",
  "psychological condition": "sıradan",
  "public eye": "sabit ifade",
  "public housing": "sabit ifade",
  "public office": "sabit ifade",
  "public relations": "sabit ifade",
  "public school": "sabit ifade",
  "public speaking": "sabit ifade",
  "published in": "sıradan",
  "pull in": "deyimsel fiil",
  "pull out": "deyimsel fiil",
  "pull over": "deyimsel fiil",
  "pull up": "deyimsel fiil",
  "push down": "deyimsel fiil",
  "put aside": "deyimsel fiil",
  "put away": "deyimsel fiil",
  "put back": "deyimsel fiil",
  "put down": "deyimsel fiil",
  "put forward": "deyimsel fiil",
  "put in": "deyimsel fiil",
  "put into": "edat kalıbı",
  "put off": "deyimsel fiil",
  "put on": "deyimsel fiil",
  "put out": "deyimsel fiil",
  "put through": "deyimsel fiil",
  "put together": "deyimsel fiil",
  "put up": "deyimsel fiil",
  "puzzle over": "deyimsel fiil",
  "quality of life": "sabit ifade",
  "queen bee": "sabit ifade",
  "quest for": "edat kalıbı",
  "questions about": "sıradan",
  "quick fix": "sabit ifade",
  "quite a": "sabit ifade",
  "quite an": "sabit ifade",
  "race to": "sıradan",
  "racial segregation": "sabit ifade",
  "radioactive decay": "sabit ifade",
  "radiocarbon dating": "sabit ifade",
  "rail line": "sıradan",
  "raised in": "sıradan",
  "ranging from": "edat kalıbı",
  "rapid growth": "sabit ifade",
  "rates in": "sıradan",
  "rather than": "geçiş ifadesi",
  "rating system": "sıradan",
  "raw meat": "sıradan",
  "raw milk": "sıradan",
  "reach into": "deyimsel fiil",
  "reach out": "deyimsel fiil",
  "react to": "edat kalıbı",
  "reaction time": "sabit ifade",
  "read about": "sıradan",
  "read in": "sıradan",
  "reading material": "sıradan",
  "reading to": "sıradan",
  "ready for": "edat kalıbı",
  "ready to": "sıradan",
  "real life": "sabit ifade",
  "real world": "sabit ifade",
  "recommended for": "sıradan",
  "recommended to": "edat kalıbı",
  "recovering from": "edat kalıbı",
  "red deer": "sıradan",
  "red wine": "sıradan",
  "reduced by": "edat kalıbı",
  "reduced in": "sıradan",
  "refers to": "edat kalıbı",
  "reflected from": "sıradan",
  "refrain from": "edat kalıbı",
  "refuse to": "sıradan",
  "regard as": "edat kalıbı",
  "regard to": "edat kalıbı",
  "regard to in": "sıradan",
  "regarded by": "sıradan",
  "regional anaesthesia": "sabit ifade",
  "regulated by": "sıradan",
  "rein in": "deyimsel fiil",
  "reinforced concrete": "sabit ifade",
  "related to": "edat kalıbı",
  "related with": "edat kalıbı",
  "released into": "sıradan",
  "religious festival": "sıradan",
  "religious leader": "sıradan",
  "rely on": "edat kalıbı",
  "rely upon": "edat kalıbı",
  "remain in": "sıradan",
  "replaced by": "sıradan",
  "report by": "sıradan",
  "reported in": "sıradan",
  "required for": "edat kalıbı",
  "required to": "sıradan",
  "research in": "sıradan",
  "research project": "sıradan",
  "residual oil": "sabit ifade",
  "respond to": "edat kalıbı",
  "respond with": "edat kalıbı",
  "responsible for": "edat kalıbı",
  "rest on": "deyimsel fiil",
  "rest period": "sıradan",
  "restricted to": "edat kalıbı",
  "result in": "edat kalıbı",
  "resulting from": "edat kalıbı",
  "return on investment": "sabit ifade",
  "return to": "sıradan",
  "revealed by": "sıradan",
  "revolve around": "deyimsel fiil",
  "reward for": "edat kalıbı",
  "rhythm and blues": "sabit ifade",
  "rich in": "edat kalıbı",
  "rid of": "deyimsel fiil",
  "right away": "sabit ifade",
  "rip off": "deyimsel fiil",
  "rise of": "sıradan",
  "rise to": "deyimsel fiil",
  "rock and roll": "sabit ifade",
  "root out": "deyimsel fiil",
  "rooted in": "edat kalıbı",
  "royal family": "sabit ifade",
  "rule in": "deyimsel fiil",
  "rule out": "deyimsel fiil",
  "ruling class": "sabit ifade",
  "run around": "sıradan",
  "run away": "deyimsel fiil",
  "run by": "sıradan",
  "run for": "deyimsel fiil",
  "run into": "deyimsel fiil",
  "run on": "deyimsel fiil",
  "run out": "deyimsel fiil",
  "run over": "deyimsel fiil",
  "runs out of": "deyimsel fiil",
  "rush out": "sıradan",
  "safe to": "sıradan",
  "said about": "sıradan",
  "said to": "sıradan",
  "sales force": "sabit ifade",
  "sanitary landfill": "sabit ifade",
  "satisfied with": "edat kalıbı",
  "school of medicine": "sabit ifade",
  "school year": "sabit ifade",
  "science in": "sıradan",
  "scientific knowledge": "sabit ifade",
  "scientific method": "sabit ifade",
  "scientific research": "sabit ifade",
  "sea creature": "sıradan",
  "sea level": "sabit ifade",
  "search for": "edat kalıbı",
  "second language": "sabit ifade",
  "secretary of the treasury": "sabit ifade",
  "see on": "sıradan",
  "see through": "deyimsel fiil",
  "seek out": "deyimsel fiil",
  "seeks to": "sıradan",
  "seems to": "sıradan",
  "seen in": "sıradan",
  "sell off": "deyimsel fiil",
  "sell out": "deyimsel fiil",
  "send out": "sıradan",
  "senile dementia": "sabit ifade",
  "sense of humour": "sabit ifade",
  "sense of right and wrong": "sabit ifade",
  "sense of smell": "sabit ifade",
  "sense of taste": "sabit ifade",
  "separated by": "sıradan",
  "separated from": "sıradan",
  "serve up": "deyimsel fiil",
  "services in": "sıradan",
  "set about": "deyimsel fiil",
  "set apart": "deyimsel fiil",
  "set aside": "deyimsel fiil",
  "set in": "deyimsel fiil",
  "set in motion": "sabit ifade",
  "set of": "sabit ifade",
  "set off": "deyimsel fiil",
  "set on": "deyimsel fiil",
  "set out": "deyimsel fiil",
  "set up": "deyimsel fiil",
  "sets out to": "deyimsel fiil",
  "settle down": "deyimsel fiil",
  "settle on": "deyimsel fiil",
  "sewage works": "sabit ifade",
  "shaped by": "sıradan",
  "shed light on": "deyimsel fiil",
  "sheet of paper": "sabit ifade",
  "shelter for": "sıradan",
  "shift from": "edat kalıbı",
  "shock absorber": "sabit ifade",
  "shock to": "sıradan",
  "shock wave": "sabit ifade",
  "shoe shop": "sıradan",
  "shoot up": "deyimsel fiil",
  "shop at": "sıradan",
  "short of": "edat kalıbı",
  "short-term memory": "sabit ifade",
  "show off": "deyimsel fiil",
  "show up": "deyimsel fiil",
  "shown by": "sıradan",
  "shown to": "sıradan",
  "side with": "deyimsel fiil",
  "signals to": "sıradan",
  "significant figure": "sabit ifade",
  "signs of": "sıradan",
  "simple to": "sıradan",
  "sit down": "sıradan",
  "sit in": "deyimsel fiil",
  "skeletal structure": "sıradan",
  "skin cancer": "sabit ifade",
  "slang expression": "sıradan",
  "slang word": "sıradan",
  "sleep in": "deyimsel fiil",
  "slow down": "deyimsel fiil",
  "slow to": "sıradan",
  "smoke out": "deyimsel fiil",
  "so far": "sabit ifade",
  "so long": "sabit ifade",
  "so that": "geçiş ifadesi",
  "social class": "sabit ifade",
  "social group": "sıradan",
  "social media": "sabit ifade",
  "social organization": "sıradan",
  "social phobia": "sabit ifade",
  "social psychology": "sabit ifade",
  "social status": "sabit ifade",
  "soft drink": "sabit ifade",
  "software system": "sıradan",
  "solar radiation": "sabit ifade",
  "solar system": "sabit ifade",
  "solar wind": "sabit ifade",
  "sold to": "sıradan",
  "some other": "sıradan",
  "sore throat": "sabit ifade",
  "sort of": "sabit ifade",
  "sounds in": "sıradan",
  "space agency": "sabit ifade",
  "space probe": "sabit ifade",
  "space shuttle": "sabit ifade",
  "space station": "sabit ifade",
  "space travel": "sabit ifade",
  "spare time": "sabit ifade",
  "speaking in": "sıradan",
  "special education": "sabit ifade",
  "special relativity": "sabit ifade",
  "speed limit": "sabit ifade",
  "speed of light": "sabit ifade",
  "speed up": "deyimsel fiil",
  "spending money": "sabit ifade",
  "spent to": "sıradan",
  "split up": "deyimsel fiil",
  "spoken language": "sıradan",
  "sponge cake": "sabit ifade",
  "spread across": "sıradan",
  "spread by": "sıradan",
  "spread from": "sıradan",
  "spread out": "deyimsel fiil",
  "spread over": "deyimsel fiil",
  "spread to": "sıradan",
  "spring up": "deyimsel fiil",
  "stainless steel": "sabit ifade",
  "stand for": "deyimsel fiil",
  "stand in": "deyimsel fiil",
  "stand out": "deyimsel fiil",
  "stand up": "sıradan",
  "standard deviation": "sabit ifade",
  "standard language": "sabit ifade",
  "standard of living": "sabit ifade",
  "stars in": "edat kalıbı",
  "start out": "deyimsel fiil",
  "start up": "deyimsel fiil",
  "started in": "sıradan",
  "started to": "sıradan",
  "state of affairs": "sabit ifade",
  "state of mind": "sabit ifade",
  "stated about": "sıradan",
  "stated in": "edat kalıbı",
  "stay away": "deyimsel fiil",
  "stay away from": "deyimsel fiil",
  "stay in": "sıradan",
  "stay on": "deyimsel fiil",
  "steam engine": "sabit ifade",
  "stems from": "edat kalıbı",
  "step forward": "deyimsel fiil",
  "step in": "deyimsel fiil",
  "stereoscopic vision": "sabit ifade",
  "stick around": "deyimsel fiil",
  "stick to": "deyimsel fiil",
  "still in": "sıradan",
  "stock market": "sabit ifade",
  "stomach flu": "sabit ifade",
  "street fighter": "sabit ifade",
  "stretching from": "sıradan",
  "stripped of": "edat kalıbı",
  "strive to": "sıradan",
  "strong belief": "sıradan",
  "struggle to": "sıradan",
  "struggling with": "edat kalıbı",
  "student teacher": "sabit ifade",
  "studied for": "sıradan",
  "studied with": "sıradan",
  "study in": "sıradan",
  "study to": "sıradan",
  "style of architecture": "sıradan",
  "subject matter": "sabit ifade",
  "subject to": "edat kalıbı",
  "substance abuse": "sabit ifade",
  "substitute for": "edat kalıbı",
  "succeeded in": "edat kalıbı",
  "suck out": "sıradan",
  "suffer from": "edat kalıbı",
  "sugar cane": "sabit ifade",
  "sulfuric acid": "sabit ifade",
  "sum of money": "sabit ifade",
  "sum up": "deyimsel fiil",
  "summer school": "sabit ifade",
  "supported by": "sıradan",
  "supposed to": "sabit ifade",
  "sure thing": "sabit ifade",
  "surgical procedure": "sıradan",
  "surprised to": "sıradan",
  "surrounded by": "sıradan",
  "survive by": "sıradan",
  "survive for": "sıradan",
  "survive in": "sıradan",
  "sweep away": "deyimsel fiil",
  "sweep over": "deyimsel fiil",
  "switch off": "deyimsel fiil",
  "switch on": "deyimsel fiil",
  "switch to": "edat kalıbı",
  "symphonic poem": "sabit ifade",
  "system of logic": "sıradan",
  "system of rules": "sıradan",
  "take a look": "deyimsel fiil",
  "take account": "sabit ifade",
  "take advantage": "deyimsel fiil",
  "take after": "deyimsel fiil",
  "take apart": "deyimsel fiil",
  "take away": "deyimsel fiil",
  "take back": "deyimsel fiil",
  "take care": "sabit ifade",
  "take control": "deyimsel fiil",
  "take down": "deyimsel fiil",
  "take for": "deyimsel fiil",
  "take for granted": "deyimsel fiil",
  "take heed": "sabit ifade",
  "take in": "deyimsel fiil",
  "take into account": "deyimsel fiil",
  "take notice": "sabit ifade",
  "take off": "deyimsel fiil",
  "take office": "sabit ifade",
  "take on": "deyimsel fiil",
  "take out": "deyimsel fiil",
  "take over": "deyimsel fiil",
  "take part": "sabit ifade",
  "take place": "sabit ifade",
  "take shape": "sabit ifade",
  "take to": "deyimsel fiil",
  "take to be": "deyimsel fiil",
  "take up": "deyimsel fiil",
  "taken against": "edat kalıbı",
  "taken for granted": "sabit ifade",
  "taken from": "sıradan",
  "taken into": "deyimsel fiil",
  "taken up": "deyimsel fiil",
  "taken with": "deyimsel fiil",
  "taking apart": "deyimsel fiil",
  "taking over": "deyimsel fiil",
  "talk about": "edat kalıbı",
  "talk into": "deyimsel fiil",
  "talking to": "sabit ifade",
  "tap water": "sabit ifade",
  "targets at": "edat kalıbı",
  "teaching method": "sıradan",
  "team up": "deyimsel fiil",
  "tear apart": "deyimsel fiil",
  "teeming with": "edat kalıbı",
  "telegraph operator": "sıradan",
  "telephone line": "sıradan",
  "television show": "sıradan",
  "television system": "sıradan",
  "ten thousand": "sıradan",
  "tend to": "edat kalıbı",
  "tended to": "deyimsel fiil",
  "terms of in": "sıradan",
  "terms of on": "sıradan",
  "tested in": "sıradan",
  "tested on": "sıradan",
  "tested to": "sıradan",
  "testing of": "sıradan",
  "tetraethyl lead": "sabit ifade",
  "thank you": "sabit ifade",
  "thanks for": "edat kalıbı",
  "thanks to": "edat kalıbı",
  "thanks to in": "edat kalıbı",
  "the true": "sıradan",
  "theory of relativity": "sabit ifade",
  "thermal conductivity": "sabit ifade",
  "think about": "edat kalıbı",
  "think of": "edat kalıbı",
  "think over": "deyimsel fiil",
  "thought in": "sıradan",
  "thought to": "sıradan",
  "threatened by": "sıradan",
  "threatening to": "sıradan",
  "three hundred": "sıradan",
  "three times": "sabit ifade",
  "through with": "sabit ifade",
  "throw away": "deyimsel fiil",
  "throw off": "deyimsel fiil",
  "throw out": "deyimsel fiil",
  "throw up": "deyimsel fiil",
  "tied to": "edat kalıbı",
  "time being": "sabit ifade",
  "time of year": "sabit ifade",
  "time period": "sıradan",
  "time to come": "sabit ifade",
  "tire out": "deyimsel fiil",
  "to a great extent": "sabit ifade",
  "to a lesser extent": "sabit ifade",
  "to begin with": "geçiş ifadesi",
  "to date": "sabit ifade",
  "to it": "sıradan",
  "to order": "sabit ifade",
  "to that": "sıradan",
  "to the point": "sabit ifade",
  "together with": "sabit ifade",
  "told by": "sıradan",
  "told to": "sıradan",
  "too large": "sıradan",
  "too much": "sabit ifade",
  "tool kit": "sıradan",
  "touch down": "deyimsel fiil",
  "touch on": "deyimsel fiil",
  "tourist attraction": "sabit ifade",
  "traffic cop": "sıradan",
  "trained to": "sıradan",
  "training in": "sıradan",
  "training of": "sıradan",
  "transferred to": "sıradan",
  "transform into": "edat kalıbı",
  "travel around": "sıradan",
  "travel at": "sıradan",
  "travel from": "sıradan",
  "travel into": "sıradan",
  "travel to": "sıradan",
  "travelling through": "sıradan",
  "treated with": "edat kalıbı",
  "tree branch": "sıradan",
  "triggered by": "sıradan",
  "true about": "edat kalıbı",
  "true at": "sıradan",
  "true for": "edat kalıbı",
  "true of": "edat kalıbı",
  "try for": "edat kalıbı",
  "try on": "deyimsel fiil",
  "trying to": "sıradan",
  "tuna fish": "sıradan",
  "turn back": "deyimsel fiil",
  "turn down": "deyimsel fiil",
  "turn in": "deyimsel fiil",
  "turn of the century": "sabit ifade",
  "turn off": "deyimsel fiil",
  "turn on": "deyimsel fiil",
  "turn out": "deyimsel fiil",
  "turn out to": "deyimsel fiil",
  "turn over": "deyimsel fiil",
  "turn to": "deyimsel fiil",
  "turn up": "deyimsel fiil",
  "turned into": "deyimsel fiil",
  "turned out": "deyimsel fiil",
  "turning point": "sabit ifade",
  "two hundred": "sıradan",
  "two weeks": "sıradan",
  "ultraviolet radiation": "sabit ifade",
  "under fire": "sabit ifade",
  "under way": "sabit ifade",
  "understanding of": "sıradan",
  "understood about": "sıradan",
  "understood from": "edat kalıbı",
  "undertaking in": "sıradan",
  "underwater archaeology": "sıradan",
  "until now": "sabit ifade",
  "up on": "sabit ifade",
  "up to": "sabit ifade",
  "up to now": "sabit ifade",
  "urban sprawl": "sabit ifade",
  "use up": "deyimsel fiil",
  "used by": "sıradan",
  "used for": "sıradan",
  "used in": "sıradan",
  "used on": "sıradan",
  "used to": "sabit ifade",
  "used with": "sıradan",
  "usher out": "deyimsel fiil",
  "using up": "deyimsel fiil",
  "utilised to": "sıradan",
  "value judgement": "sabit ifade",
  "value on": "edat kalıbı",
  "values in": "sıradan",
  "varies from": "edat kalıbı",
  "vary in": "edat kalıbı",
  "very fast": "sıradan",
  "very much like": "sabit ifade",
  "very well": "sıradan",
  "vice versa": "sabit ifade",
  "video game": "sıradan",
  "view as": "edat kalıbı",
  "view of": "sabit ifade",
  "viral infection": "sıradan",
  "virtual image": "sabit ifade",
  "visual impairment": "sabit ifade",
  "visual range": "sabit ifade",
  "vital force": "sabit ifade",
  "volcanic rock": "sıradan",
  "volunteered to": "sıradan",
  "waiting for": "edat kalıbı",
  "waiting to": "sıradan",
  "wake-up call": "sabit ifade",
  "walk in": "sıradan",
  "walk of life": "sabit ifade",
  "walk through": "deyimsel fiil",
  "walking at": "sıradan",
  "wall in": "deyimsel fiil",
  "wanders through": "sıradan",
  "want to": "sıradan",
  "ward off": "deyimsel fiil",
  "warm to": "deyimsel fiil",
  "warm up": "deyimsel fiil",
  "wash away": "deyimsel fiil",
  "waste of time": "sabit ifade",
  "watch out": "deyimsel fiil",
  "water pollution": "sıradan",
  "water supply": "sabit ifade",
  "water vapour": "sabit ifade",
  "way of life": "sabit ifade",
  "way out": "sabit ifade",
  "wear down": "deyimsel fiil",
  "wear out": "deyimsel fiil",
  "welfare state": "sabit ifade",
  "well up": "deyimsel fiil",
  "western hemisphere": "sabit ifade",
  "whale oil": "sıradan",
  "what is more": "geçiş ifadesi",
  "white shark": "sıradan",
  "white wine": "sıradan",
  "willing to": "edat kalıbı",
  "window dressing": "sabit ifade",
  "winter solstice": "sabit ifade",
  "wishing to": "sıradan",
  "without doubt": "sabit ifade",
  "word meaning": "sıradan",
  "word of mouth": "sabit ifade",
  "work at": "edat kalıbı",
  "work in": "sıradan",
  "work of art": "sabit ifade",
  "work on": "edat kalıbı",
  "work out": "deyimsel fiil",
  "work through": "deyimsel fiil",
  "work to": "sıradan",
  "worked for": "sıradan",
  "working class": "sabit ifade",
  "working memory": "sabit ifade",
  "working principle": "sabit ifade",
  "working with": "sıradan",
  "works of": "sıradan",
  "world power": "sabit ifade",
  "world record": "sıradan",
  "world war": "sabit ifade",
  "world-wide web": "sabit ifade",
  "worry about": "edat kalıbı",
  "write about": "sıradan",
  "write down": "deyimsel fiil",
  "write in": "deyimsel fiil",
  "write of": "edat kalıbı",
  "write on": "edat kalıbı",
  "written by": "sıradan",
  "written language": "sıradan",
  "written to": "sıradan",
  "yellow fever": "sabit ifade",
  "you bet": "sabit ifade",
  "young blood": "sabit ifade",
  "young girl": "sıradan",
  "youth culture": "sıradan"
};
